<a href="https://colab.research.google.com/github/markajbell/BH/blob/main/dikstra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
from IPython.display import clear_output
# prompt: create a data folder under content and import all the files from the data folder in github (https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data)
if os.path.exists("/content/data"):
  print("/content/data exists")
else:
  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/bh.zip
  #!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/bh-2.json
  #!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/bh-3.json
  #!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/bh-4.json
  #!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/bh-5-6016-5981.json
  #!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/bh-6-all_tier_0.json
  #!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/data/tier0.json
  !mkdir /content/data
  !unzip bh.zip -d data


  #!mv bh-1.json /content/data
  #!mv bh-2.json /content/data
  #!mv bh-3.json /content/data
  #!mv bh-4.json /content/data
  #!mv bh-5-6016-5981.json /content/data
  #!mv tier0.json /content/data
  #!mv bh-6-all_tier_0.json /content/data

  clear_output()
  print("Downloading lab files...Done")

Downloading lab files...Done

In [3]:
# prompt: import bh.json and load into a pandas dataframe df

!pip install pandas

import pandas as pd
import json

# Assuming 'bh.json' is in the current working directory
with open('data/bh-6-all_tier_0.json', 'r') as f:
    data_all = json.load(f)

df_all = pd.DataFrame(data_all)

# Display the first few rows of the DataFrame to verify
print(df_all.head())

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
                                                    data
nodes  {'5': {'label': 'DOMAIN ADMINS@MYLAB.LOCAL', '...
edges  [{'source': '5176', 'target': '5', 'label': 'W...

In [4]:
pd.set_option("display.max_colwidth", None)

nodes_all = df_all['data']['nodes']
edges_all = df_all['data']['edges']
print(nodes_all)
print(edges_all)

{'5': {'label': 'DOMAIN ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-512', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.512Z'}, '5087': {'label': 'OGCWWKS1000000.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4105', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.295Z'}, '5092': {'label': 'GOOWSECS1000001.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4111', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.363Z'}, '5128': {'label': 'ITSWWKS1000001.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4146', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.181237651Z'}, '5173': {'label': 'DCTEST.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1000', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.609Z'}, '5174': {'label': 'ACCOUNT OPERATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-548', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.766Z'}, '5175': {'label': 'DA-EST-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3782', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5176': {'label': 'ENTERPRISE ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-519', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.416Z'}, '5177': {'label': 'DE-DAS-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5178': {'label': 'MA-VACACIONE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5179': {'label': 'RO-ARJ-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5180': {'label': 'JE-SIE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3769', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5181': {'label': 'DE-OMAR3BETE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3686', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5182': {'label': 'BE-240-ADMINGROUP1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4066', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '5183': {'label': 'NO-FOR-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3862', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5184': {'label': 'TA-24D-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4033', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '5187': {'label': 'AL-CET-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3654', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5194': {'label': 'DW-ROY-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4085', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '5196': {'label': 'PA-COM-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3962', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5415': {'label': 'LATOYA_LEBLANC@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1308', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5520': {'label': 'MATTIE_PERRY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1413', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5547': {'label': 'MACK_KIRK@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1440', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5554': {'label': 'JENNA_HARDING@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1447', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, '5570': {'label': 'KARL_LITTLE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1463', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5578': {'label': 'GALEN_HARRELL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, '5599': {'label': 'RACHAEL_ARNOLD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1492', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, '5625': {'label': 'MARCIA_TRUJILLO@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1518', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5646': {'label': 'FRANCESCA_ARNOLD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5712': {'label': 'ADRIAN_RUIZ@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1605', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5739': {'label': 'ANGIE_EDWARDS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1632', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, '5830': {'label': 'BRETT_FRANKS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5864': {'label': 'SPENCER_BURKE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1757', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, '5874': {'label': 'CHRISTA_LEVY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1767', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5949': {'label': 'JUANITA_WILKINSON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5950': {'label': 'TIMOTHY_ESTRADA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5951': {'label': '6103350899SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3310', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5953': {'label': 'ARRON_MCCALL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1963', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5954': {'label': 'TODD_VEGA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2605', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5956': {'label': 'RANDALL_NOEL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3393', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5957': {'label': 'LUIS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-500', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5958': {'label': 'WILFORD_MOSS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2830', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, '5959': {'label': '8664140472SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2849', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5974': {'label': 'LOUIS_TYLER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3276', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5978': {'label': 'ANDREA_TYLER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2378', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5981': {'label': 'BEVERLEY_LINDSEY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2549', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5982': {'label': 'RICO_VANCE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3186', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5983': {'label': 'KEITH_CHANEY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3426', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5986': {'label': 'JERRI_LITTLE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1879', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5987': {'label': 'HOLLIS_MIDDLETON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1940', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5988': {'label': 'MAYRA_ODOM@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2622', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5993': {'label': '5308751552SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1858', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6010': {'label': '2900142017SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2978', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6017': {'label': 'ADMINISTRATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-544', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.512Z'}, '6021': {'label': 'BACKUP OPERATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-551', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.766Z'}, '6038': {'label': 'ENTERPRISE DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.997Z'}, '6053': {'label': 'TIER 2@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '10F36C55-9B2C-4789-B41A-120921C3B895', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6054': {'label': 'DEVICES@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '071DB1CF-543B-40CB-A863-BFE2AF55DF1C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6071': {'label': 'ADMIN@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '90CFC892-BAC1-415D-9184-162AF19259DB', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6081': {'label': 'STAGE@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '7C8E5870-E574-4ECA-8166-0D9C8B7F61B6', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6084': {'label': 'TST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '5C343204-573C-4BA3-A62B-E1D2C514FE1C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6093': {'label': 'T2-ACCOUNTS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'C6DFEDDA-0A5C-4371-B715-A3CD516E78E8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6094': {'label': 'TEST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'D4CC2378-3B22-4F65-BA4F-294C9189EBD3', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6097': {'label': 'TIER 2@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'A7310FCB-FB29-4BD4-AF56-E792F305870E', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6098': {'label': 'SERVICEACCOUNTS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '8552338D-C4A8-4EED-B685-FBE20B3AD9E2', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6102': {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '1CF11C6B-7227-4042-ADEE-E4C49893FFF8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6107': {'label': 'GOO@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'A6658770-F882-4DD1-9847-5AE1B6891D4F', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6123': {'label': 'DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '1AFCEA60-7A76-4602-BC16-0386AB6D5A2C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6132': {'label': 'FIN@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'F3CB3F78-6D16-48AD-BC92-2F033E8216CB', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6135': {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'AB9369C5-555D-4851-BE4B-2CE08BE7C9E8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6143': {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '431D0A16-9168-4E2C-AAE3-E451F074ABA3', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6145': {'label': 'T1-ROLES@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '035576AD-6698-4566-8FC1-1876D1AD0FA9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6155': {'label': 'SEC@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '00E70616-0654-42F3-BE4A-F3BA263017A1', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6171': {'label': 'TEST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '22A78F7F-4C8C-4C5D-9DE6-ED1A1063B72B', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6192': {'label': 'AWS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '71F5250E-4324-4BC6-A76B-5F7DDC0AFE2A', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6201': {'label': 'FSR@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'BABC1750-A16A-4D60-B31F-30B1ECBC244F', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6215': {'label': 'GROUPER-GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '81305F83-FADE-4B1E-9D8D-16DC11C81080', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6221': {'label': 'BDE@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '83EEC3DB-0B8C-4622-A97B-C69D604A741D', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6235': {'label': 'TIER 1@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '2231E7DC-FF3B-4F4B-9082-E59ACBEC84A9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6252': {'label': 'T2-SERVERS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '65B3ED59-89A6-40D9-ABE3-2D8C8CF294FC', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6253': {'label': 'TIER 1@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '7FF03EC4-A978-4BAD-8154-615DD496B3DC', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6257': {'label': 'MARIA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1103', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6258': {'label': 'MYLAB.LOCAL', 'kind': 'Domain', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6265': {'label': 'DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-516', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.364Z'}, '6270': {'label': 'TESTING@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'BBC3297B-BF92-45EB-A2DF-8B6A1C799C70', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6271': {'label': 'USERS@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '643CE9DD-6D50-4B82-8DA1-994C82A16D6C', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.297Z'}, '6272': {'label': 'KEY ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-526', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.323Z'}, '6273': {'label': 'ENTERPRISE KEY ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-527', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.323Z'}, '6274': {'label': 'THERESA_RIVERS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2337', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6275': {'label': 'JOSEPHINE_COTE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1859', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, '6277': {'label': 'HALLIE_BRENNAN@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2640', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6279': {'label': 'RAY_DECKER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2944', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, '6733': {'label': 'FERN_MCPHERSON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2310', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.684105763Z'}, '7204': {'label': 'DORTHY_ROWE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2800', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, '7373': {'label': 'LENARD_MACDONALD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2976', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '7545': {'label': 'TOBY_ROBBINS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3156', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '7968': {'label': 'SCHEMA ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-518', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.181Z'}, '8364': {'label': 'SYSTEM@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '7E6DDFDC-07BE-4295-A9EB-1D993D877C48', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.931Z'}, '8376': {'label': 'ADMINSDHOLDER@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '738F5127-0264-4DF8-8444-2C792EA2A637', 'isT

In [ ]:
# prompt: expand the columns of df

import pandas as pd
pd.set_option('display.max_columns', None)
df_all.index

Index(['nodes', 'edges'], dtype='object')

In [11]:
df_all.index

Index(['nodes', 'edges'], dtype='object')

In [18]:
print(df_all['data']['nodes'])

{'5': {'label': 'DOMAIN ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-512', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.512Z'}, '5087': {'label': 'OGCWWKS1000000.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4105', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.295Z'}, '5092': {'label': 'GOOWSECS1000001.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4111', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.363Z'}, '5128': {'label': 'ITSWWKS1000001.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4146', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.181237651Z'}, '5173': {'label': 'DCTEST.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1000', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.609Z'}, '5174': {'label': 'ACCOUNT OPERATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-548', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.766Z'}, '5175': {'label': 'DA-EST-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3782', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5176': {'label': 'ENTERPRISE ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-519', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.416Z'}, '5177': {'label': 'DE-DAS-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5178': {'label': 'MA-VACACIONE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5179': {'label': 'RO-ARJ-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5180': {'label': 'JE-SIE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3769', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5181': {'label': 'DE-OMAR3BETE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3686', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5182': {'label': 'BE-240-ADMINGROUP1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4066', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '5183': {'label': 'NO-FOR-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3862', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, '5184': {'label': 'TA-24D-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4033', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '5187': {'label': 'AL-CET-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3654', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5194': {'label': 'DW-ROY-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4085', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '5196': {'label': 'PA-COM-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3962', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, '5415': {'label': 'LATOYA_LEBLANC@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1308', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5520': {'label': 'MATTIE_PERRY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1413', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5547': {'label': 'MACK_KIRK@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1440', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5554': {'label': 'JENNA_HARDING@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1447', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, '5570': {'label': 'KARL_LITTLE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1463', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5578': {'label': 'GALEN_HARRELL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, '5599': {'label': 'RACHAEL_ARNOLD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1492', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, '5625': {'label': 'MARCIA_TRUJILLO@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1518', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5646': {'label': 'FRANCESCA_ARNOLD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5712': {'label': 'ADRIAN_RUIZ@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1605', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5739': {'label': 'ANGIE_EDWARDS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1632', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, '5830': {'label': 'BRETT_FRANKS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5864': {'label': 'SPENCER_BURKE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1757', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, '5874': {'label': 'CHRISTA_LEVY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1767', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5949': {'label': 'JUANITA_WILKINSON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5950': {'label': 'TIMOTHY_ESTRADA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5951': {'label': '6103350899SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3310', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5953': {'label': 'ARRON_MCCALL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1963', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '5954': {'label': 'TODD_VEGA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2605', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5956': {'label': 'RANDALL_NOEL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3393', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5957': {'label': 'LUIS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-500', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5958': {'label': 'WILFORD_MOSS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2830', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, '5959': {'label': '8664140472SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2849', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, '5974': {'label': 'LOUIS_TYLER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3276', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5978': {'label': 'ANDREA_TYLER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2378', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5981': {'label': 'BEVERLEY_LINDSEY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2549', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5982': {'label': 'RICO_VANCE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3186', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5983': {'label': 'KEITH_CHANEY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3426', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5986': {'label': 'JERRI_LITTLE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1879', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5987': {'label': 'HOLLIS_MIDDLETON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1940', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5988': {'label': 'MAYRA_ODOM@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2622', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '5993': {'label': '5308751552SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1858', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6010': {'label': '2900142017SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2978', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6017': {'label': 'ADMINISTRATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-544', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.512Z'}, '6021': {'label': 'BACKUP OPERATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-551', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.766Z'}, '6038': {'label': 'ENTERPRISE DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.997Z'}, '6053': {'label': 'TIER 2@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '10F36C55-9B2C-4789-B41A-120921C3B895', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6054': {'label': 'DEVICES@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '071DB1CF-543B-40CB-A863-BFE2AF55DF1C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6071': {'label': 'ADMIN@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '90CFC892-BAC1-415D-9184-162AF19259DB', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6081': {'label': 'STAGE@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '7C8E5870-E574-4ECA-8166-0D9C8B7F61B6', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6084': {'label': 'TST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '5C343204-573C-4BA3-A62B-E1D2C514FE1C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6093': {'label': 'T2-ACCOUNTS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'C6DFEDDA-0A5C-4371-B715-A3CD516E78E8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6094': {'label': 'TEST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'D4CC2378-3B22-4F65-BA4F-294C9189EBD3', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6097': {'label': 'TIER 2@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'A7310FCB-FB29-4BD4-AF56-E792F305870E', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6098': {'label': 'SERVICEACCOUNTS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '8552338D-C4A8-4EED-B685-FBE20B3AD9E2', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6102': {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '1CF11C6B-7227-4042-ADEE-E4C49893FFF8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6107': {'label': 'GOO@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'A6658770-F882-4DD1-9847-5AE1B6891D4F', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6123': {'label': 'DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '1AFCEA60-7A76-4602-BC16-0386AB6D5A2C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6132': {'label': 'FIN@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'F3CB3F78-6D16-48AD-BC92-2F033E8216CB', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6135': {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'AB9369C5-555D-4851-BE4B-2CE08BE7C9E8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6143': {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '431D0A16-9168-4E2C-AAE3-E451F074ABA3', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6145': {'label': 'T1-ROLES@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '035576AD-6698-4566-8FC1-1876D1AD0FA9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6155': {'label': 'SEC@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '00E70616-0654-42F3-BE4A-F3BA263017A1', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, '6171': {'label': 'TEST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '22A78F7F-4C8C-4C5D-9DE6-ED1A1063B72B', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6192': {'label': 'AWS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '71F5250E-4324-4BC6-A76B-5F7DDC0AFE2A', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6201': {'label': 'FSR@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'BABC1750-A16A-4D60-B31F-30B1ECBC244F', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6215': {'label': 'GROUPER-GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '81305F83-FADE-4B1E-9D8D-16DC11C81080', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6221': {'label': 'BDE@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '83EEC3DB-0B8C-4622-A97B-C69D604A741D', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6235': {'label': 'TIER 1@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '2231E7DC-FF3B-4F4B-9082-E59ACBEC84A9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6252': {'label': 'T2-SERVERS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '65B3ED59-89A6-40D9-ABE3-2D8C8CF294FC', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, '6253': {'label': 'TIER 1@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '7FF03EC4-A978-4BAD-8154-615DD496B3DC', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6257': {'label': 'MARIA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1103', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6258': {'label': 'MYLAB.LOCAL', 'kind': 'Domain', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6265': {'label': 'DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-516', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.364Z'}, '6270': {'label': 'TESTING@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'BBC3297B-BF92-45EB-A2DF-8B6A1C799C70', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, '6271': {'label': 'USERS@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '643CE9DD-6D50-4B82-8DA1-994C82A16D6C', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.297Z'}, '6272': {'label': 'KEY ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-526', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.323Z'}, '6273': {'label': 'ENTERPRISE KEY ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-527', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.323Z'}, '6274': {'label': 'THERESA_RIVERS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2337', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6275': {'label': 'JOSEPHINE_COTE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1859', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, '6277': {'label': 'HALLIE_BRENNAN@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2640', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '6279': {'label': 'RAY_DECKER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2944', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, '6733': {'label': 'FERN_MCPHERSON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2310', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.684105763Z'}, '7204': {'label': 'DORTHY_ROWE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2800', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, '7373': {'label': 'LENARD_MACDONALD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2976', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '7545': {'label': 'TOBY_ROBBINS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3156', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, '7968': {'label': 'SCHEMA ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-518', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.181Z'}, '8364': {'label': 'SYSTEM@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '7E6DDFDC-07BE-4295-A9EB-1D993D877C48', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.931Z'}, '8376': {'label': 'ADMINSDHOLDER@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '738F5127-0264-4DF8-8444-2C792EA2A637', 'isT

In [63]:
# prompt: show me the columns of the dict df_all['data']

import pandas as pd
#print(pd.DataFrame(df_all['data']['nodes']).columns)
#print(pd.DataFrame(df_all['data']['edges']).columns)
NodeListAll = pd.DataFrame(df_all['data']['nodes']).columns.tolist()
#EdgeListAll = pd.DataFrame(df_all['data']['edges']).columns.tolist()
pd_node_list = pd.DataFrame({'node_id': NodeListAll})
pd_node_list
#NodeListAll

   node_id
0        5
1     5087
2     5092
3     5128
4     5173
..     ...
95    7968
96    8364
97    8376
98    8569
99    8570

[100 rows x 1 columns]

In [13]:
# prompt: get the 1st value from df['data']['nodes']

# Access the list associated with the 'nodes' key within the 'data' column
nodes_list = df_all['data']['nodes']

# Access the first element (at index 0) of the nodes_list
#print(nodes_list[0])
nodes_list.values()

dict_values([{'label': 'DOMAIN ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-512', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.512Z'}, {'label': 'OGCWWKS1000000.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4105', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.295Z'}, {'label': 'GOOWSECS1000001.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4111', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.363Z'}, {'label': 'ITSWWKS1000001.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4146', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.181237651Z'}, {'label': 'DCTEST.MYLAB.LOCAL', 'kind': 'Computer', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1000', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.609Z'}, {'label': 'ACCOUNT OPERATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-548', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.766Z'}, {'label': 'DA-EST-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3782', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, {'label': 'ENTERPRISE ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-519', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.416Z'}, {'label': 'DE-DAS-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, {'label': 'MA-VACACIONE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, {'label': 'RO-ARJ-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, {'label': 'JE-SIE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3769', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, {'label': 'DE-OMAR3BETE-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3686', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, {'label': 'BE-240-ADMINGROUP1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4066', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'NO-FOR-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3862', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.122Z'}, {'label': 'TA-24D-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4033', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'AL-CET-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3654', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, {'label': 'DW-ROY-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-4085', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'PA-COM-DISTLIST1@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3962', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.845Z'}, {'label': 'LATOYA_LEBLANC@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1308', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'MATTIE_PERRY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1413', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'MACK_KIRK@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1440', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'JENNA_HARDING@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1447', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, {'label': 'KARL_LITTLE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1463', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'GALEN_HARRELL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, {'label': 'RACHAEL_ARNOLD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1492', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.83112218Z'}, {'label': 'MARCIA_TRUJILLO@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1518', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'FRANCESCA_ARNOLD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'ADRIAN_RUIZ@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1605', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'ANGIE_EDWARDS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1632', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, {'label': 'BRETT_FRANKS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'SPENCER_BURKE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1757', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, {'label': 'CHRISTA_LEVY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1767', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'JUANITA_WILKINSON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'TIMOTHY_ESTRADA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': '6103350899SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3310', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'ARRON_MCCALL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1963', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'TODD_VEGA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2605', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'RANDALL_NOEL@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3393', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'LUIS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-500', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'WILFORD_MOSS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2830', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, {'label': '8664140472SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2849', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.28Z'}, {'label': 'LOUIS_TYLER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3276', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'ANDREA_TYLER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2378', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'BEVERLEY_LINDSEY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2549', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'RICO_VANCE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3186', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'KEITH_CHANEY@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3426', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'JERRI_LITTLE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1879', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'HOLLIS_MIDDLETON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1940', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'MAYRA_ODOM@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2622', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': '5308751552SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1858', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': '2900142017SA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2978', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'ADMINISTRATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-544', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.512Z'}, {'label': 'BACKUP OPERATORS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-32-551', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.766Z'}, {'label': 'ENTERPRISE DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'MYLAB.LOCAL-S-1-5-9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.997Z'}, {'label': 'TIER 2@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '10F36C55-9B2C-4789-B41A-120921C3B895', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'DEVICES@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '071DB1CF-543B-40CB-A863-BFE2AF55DF1C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'ADMIN@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '90CFC892-BAC1-415D-9184-162AF19259DB', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'STAGE@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '7C8E5870-E574-4ECA-8166-0D9C8B7F61B6', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'TST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '5C343204-573C-4BA3-A62B-E1D2C514FE1C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'T2-ACCOUNTS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'C6DFEDDA-0A5C-4371-B715-A3CD516E78E8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'TEST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'D4CC2378-3B22-4F65-BA4F-294C9189EBD3', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'TIER 2@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'A7310FCB-FB29-4BD4-AF56-E792F305870E', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'SERVICEACCOUNTS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '8552338D-C4A8-4EED-B685-FBE20B3AD9E2', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '1CF11C6B-7227-4042-ADEE-E4C49893FFF8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'GOO@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'A6658770-F882-4DD1-9847-5AE1B6891D4F', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '1AFCEA60-7A76-4602-BC16-0386AB6D5A2C', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'FIN@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'F3CB3F78-6D16-48AD-BC92-2F033E8216CB', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'AB9369C5-555D-4851-BE4B-2CE08BE7C9E8', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '431D0A16-9168-4E2C-AAE3-E451F074ABA3', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'T1-ROLES@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '035576AD-6698-4566-8FC1-1876D1AD0FA9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'SEC@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '00E70616-0654-42F3-BE4A-F3BA263017A1', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.637Z'}, {'label': 'TEST@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '22A78F7F-4C8C-4C5D-9DE6-ED1A1063B72B', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'AWS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '71F5250E-4324-4BC6-A76B-5F7DDC0AFE2A', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'FSR@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'BABC1750-A16A-4D60-B31F-30B1ECBC244F', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'GROUPER-GROUPS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '81305F83-FADE-4B1E-9D8D-16DC11C81080', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'BDE@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '83EEC3DB-0B8C-4622-A97B-C69D604A741D', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'TIER 1@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '2231E7DC-FF3B-4F4B-9082-E59ACBEC84A9', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'T2-SERVERS@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '65B3ED59-89A6-40D9-ABE3-2D8C8CF294FC', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.588Z'}, {'label': 'TIER 1@MYLAB.LOCAL', 'kind': 'OU', 'objectId': '7FF03EC4-A978-4BAD-8154-615DD496B3DC', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'MARIA@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1103', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'MYLAB.LOCAL', 'kind': 'Domain', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'DOMAIN CONTROLLERS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-516', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.364Z'}, {'label': 'TESTING@MYLAB.LOCAL', 'kind': 'OU', 'objectId': 'BBC3297B-BF92-45EB-A2DF-8B6A1C799C70', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.652Z'}, {'label': 'USERS@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '643CE9DD-6D50-4B82-8DA1-994C82A16D6C', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.297Z'}, {'label': 'KEY ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-526', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.323Z'}, {'label': 'ENTERPRISE KEY ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-527', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.323Z'}, {'label': 'THERESA_RIVERS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2337', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'JOSEPHINE_COTE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-1859', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:36.982929044Z'}, {'label': 'HALLIE_BRENNAN@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2640', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'RAY_DECKER@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2944', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, {'label': 'FERN_MCPHERSON@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2310', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.684105763Z'}, {'label': 'DORTHY_ROWE@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2800', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:41.852961635Z'}, {'label': 'LENARD_MACDONALD@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-2976', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'TOBY_ROBBINS@MYLAB.LOCAL', 'kind': 'User', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-3156', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.484Z'}, {'label': 'SCHEMA ADMINS@MYLAB.LOCAL', 'kind': 'Group', 'objectId': 'S-1-5-21-1333368235-828418111-1849936505-518', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:47.181Z'}, {'label': 'SYSTEM@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '7E6DDFDC-07BE-4295-A9EB-1D993D877C48', 'isTierZero': False, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.931Z'}, {'label': 'ADMINSDHOLDER@MYLAB.LOCAL', 'kind': 'Container', 'objectId': '738F5127-0264-4DF8-8444-2C792EA2A637', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:48.931Z'}, {'label': 'DEFAULT DOMAIN POLICY@MYLAB.LOCAL', 'kind': 'GPO', 'objectId': 'CD3A9B14-C932-416E-8E01-1C8C8FAEF125', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.464Z'}, {'label': 'DEFAULT DOMAIN CONTROLLERS POLICY@MYLAB.LOCAL', 'kind': 'GPO', 'objectId': 'F39BE162-0FF0-46B0-B117-39FD979A220A', 'isTierZero': True, 'isOwnedObject': False, 'lastSeen': '2025-05-13T13:28:49.464Z'}])

In [53]:
# prompt: get the 1st value from df['data']['nodes']

# Access the list associated with the 'nodes' key within the 'data' column
edges_list = df_all['data']['edges']

# Convert the dictionary values to a list and access the first element
edges_list

[{'source': '5176',
  'target': '5',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5957',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5974',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6017',
  'target': '5',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6257',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5087',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5176',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5177',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5178',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5179',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5578',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5646',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5712',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5830',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5874',
  'target': '5173',
  'label': 'CanPSRemote',
  'kind': 'CanPSRemote',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5949',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5950',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5957',
  'target': '5173',
  'label': 'AdminTo',
  'kind': 'AdminTo',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5978',
  'target': '5173',
  'label': 'AdminTo',
  'kind': 'AdminTo',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5986',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5987',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5988',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5993',
  'target': '5173',
  'label': 'ExecuteDCOM',
  'kind': 'ExecuteDCOM',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '6010',
  'target': '5173',
  'label': 'CanPSRemote',
  'kind': 'CanPSRemote',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '6017',
  'target': '5173',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '6123',
  'target': '5173',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '6272',
  'target': '5173',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '6273',
  'target': '5173',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5',
  'target': '5176',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5957',
  'target': '5176',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6017',
  'target': '5176',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6271',
  'target': '5176',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5092',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5174',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5177',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5178',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5179',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5415',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5739',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5864',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5950',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5554',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6093',
  'target': '5554',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6272',
  'target': '5554',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6273',
  'target': '5554',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6274',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5092',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5174',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5175',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5177',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5178',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5179',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5739',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5864',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5950',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5570',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6215',
  'target': '5570',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6272',
  'target': '5570',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6273',
  'target': '5570',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6274',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5092',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5174',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5175',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5177',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5178',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5179',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5187',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5739',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5864',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5950',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5951',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5599',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6171',
  'target': '5599',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6272',
  'target': '5599',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6273',
  'target': '5599',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6274',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6279',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6271',
  'target': '5957',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5092',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5174',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5175',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5176',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5177',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5178',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5179',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5184',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5739',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5864',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5950',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6017',
  'target': '5974',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6098',
  'target': '5974',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6272',
  'target': '5974',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6273',
  'target': '5974',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6274',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5092',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5128',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5174',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5175',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5176',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5177',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5178',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5179',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5196',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5739',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5864',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5950',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5953',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5959',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6017',
  'target': '5978',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6102',
  'target': '5978',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6272',
  'target': '5978',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6273',
  'target': '5978',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6274',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6275',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5092',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5174',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5175',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5176',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5177',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5178',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5179',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5547',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5739',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5864',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5950',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6017',
  'target': '5981',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6145',
  'target': '5981',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6272',
  'target': '5981',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6273',

In [54]:
# prompt: show unique edges_list label

edge_labels = []
for edge in edges_list:
  if 'label' in edge:
    edge_labels.append(edge['label'])

unique_edge_labels = set(edge_labels)
unique_edge_labels

{'AddKeyCredentialLink',
 'AdminTo',
 'CanPSRemote',
 'CanRDP',
 'Contains',
 'DCFor',
 'ExecuteDCOM',
 'GPLink',
 'GenericAll',
 'MemberOf',
 'WriteDacl'}

In [56]:
edges_all

[{'source': '5176',
  'target': '5',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5957',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5974',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6017',
  'target': '5',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6257',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5087',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5176',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5177',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5178',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5179',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5578',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5646',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5712',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5830',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5874',
  'target': '5173',
  'label': 'CanPSRemote',
  'kind': 'CanPSRemote',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5949',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5950',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5957',
  'target': '5173',
  'label': 'AdminTo',
  'kind': 'AdminTo',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5978',
  'target': '5173',
  'label': 'AdminTo',
  'kind': 'AdminTo',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5986',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5987',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5988',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '5993',
  'target': '5173',
  'label': 'ExecuteDCOM',
  'kind': 'ExecuteDCOM',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '6010',
  'target': '5173',
  'label': 'CanPSRemote',
  'kind': 'CanPSRemote',
  'lastSeen': '2025-05-15T09:47:56.580159608Z'},
 {'source': '6017',
  'target': '5173',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '6123',
  'target': '5173',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '6272',
  'target': '5173',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '6273',
  'target': '5173',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5',
  'target': '5176',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5957',
  'target': '5176',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6017',
  'target': '5176',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6271',
  'target': '5176',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5092',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5174',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5177',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5178',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5179',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5415',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5739',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5864',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5950',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5554',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6093',
  'target': '5554',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6272',
  'target': '5554',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6273',
  'target': '5554',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6274',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5092',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5174',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5175',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5177',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5178',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5179',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5739',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5864',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5950',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5570',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6215',
  'target': '5570',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6272',
  'target': '5570',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6273',
  'target': '5570',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6274',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5092',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5174',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5175',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5177',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5178',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5179',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5187',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5739',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5864',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5950',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5951',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5599',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6171',
  'target': '5599',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6272',
  'target': '5599',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6273',
  'target': '5599',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6274',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6279',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5176',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6017',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '6271',
  'target': '5957',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5092',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5174',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5175',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5176',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5177',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5178',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5179',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5184',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5739',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5864',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5950',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6017',
  'target': '5974',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6098',
  'target': '5974',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6272',
  'target': '5974',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6273',
  'target': '5974',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '6274',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5092',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5128',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5174',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5175',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5176',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5177',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5178',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5179',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5196',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5739',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5864',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5950',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5953',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5959',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6017',
  'target': '5978',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6102',
  'target': '5978',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6272',
  'target': '5978',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6273',
  'target': '5978',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6274',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6275',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5092',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5174',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5175',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5176',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5177',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5178',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5179',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5547',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5739',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5864',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '5950',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6017',
  'target': '5981',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6145',
  'target': '5981',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6272',
  'target': '5981',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6273',

In [59]:
# prompt: add a Weight = 10 column to df['data']['edges']

# Access the list of edges within the 'data' column and 'edges' key
#edges = df['data']['edges']

# Iterate through each edge dictionary in the list
for edge in edges_all:
    # Add the 'Weight' key with a value of 10 to the current edge dictionary
    # Add the 'Weight' key with a value based on the 'label'
  if 'label' in edge:  # Check if 'label' key exists
      label = edge['label']
      if label == "GenericAll":
          edge['Weight'] = 9
      elif label == "Owns":
          edge['Weight'] = 10
      elif label == "GenericWrite":
          edge['Weight'] = 2
      elif label == "AllExtendedRights":
          edge['Weight'] = 6
      elif label == "CanRDP":
          edge['Weight'] = 2
      elif label == "Contains":
          edge['Weight'] = 2
      elif label == "DCSync":
          edge['Weight'] = 8
      elif label == "WriteDacl":
          edge['Weight'] = 5
      elif label == "WriteOwner":
          edge['Weight'] = 7
      elif label == "AddKeyCredentialLink":
          edge['Weight'] = 6
      elif label == "AdminTo":
          edge['Weight'] = 8
      elif label == "MemberOf":
          edge['Weight'] = 1
      elif label == "CanPSRemote":
          edge['Weight'] = 2
      elif label == "ExecuteDCOM":
          edge['Weight'] = 2
      elif label == "GPLink":
          edge['Weight'] = 3
      else:
          # Assign a default weight if the label exists but doesn't match any specific case
          edge['Weight'] = 0 # Or any other suitable default value
  else:
      # Assign a default weight if the 'label' key does not exist
      edge['Weight'] = 0 # Or any other suitable default value



# Display the updated list of edges
print(edges_all)
#print(df['data']['edges'])

[{'source': '5176', 'target': '5', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 5}, {'source': '5554', 'target': '5', 'label': 'MemberOf', 'kind': 'MemberOf', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 1}, {'source': '5957', 'target': '5', 'label': 'MemberOf', 'kind': 'MemberOf', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 1}, {'source': '5974', 'target': '5', 'label': 'MemberOf', 'kind': 'MemberOf', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 1}, {'source': '6017', 'target': '5', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 5}, {'source': '6257', 'target': '5', 'label': 'MemberOf', 'kind': 'MemberOf', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 1}, {'source': '6271', 'target': '5', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 2}, {'source': '5', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5087', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5176', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5177', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5178', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5179', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5578', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5646', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5712', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5830', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5874', 'target': '5173', 'label': 'CanPSRemote', 'kind': 'CanPSRemote', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 2}, {'source': '5949', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5950', 'target': '5173', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 9}, {'source': '5957', 'target': '5173', 'label': 'AdminTo', 'kind': 'AdminTo', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 8}, {'source': '5978', 'target': '5173', 'label': 'AdminTo', 'kind': 'AdminTo', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 8}, {'source': '5986', 'target': '5173', 'label': 'CanRDP', 'kind': 'CanRDP', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 2}, {'source': '5987', 'target': '5173', 'label': 'CanRDP', 'kind': 'CanRDP', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 2}, {'source': '5988', 'target': '5173', 'label': 'CanRDP', 'kind': 'CanRDP', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 2}, {'source': '5993', 'target': '5173', 'label': 'ExecuteDCOM', 'kind': 'ExecuteDCOM', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 2}, {'source': '6010', 'target': '5173', 'label': 'CanPSRemote', 'kind': 'CanPSRemote', 'lastSeen': '2025-05-15T09:47:56.580159608Z', 'Weight': 2}, {'source': '6017', 'target': '5173', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 5}, {'source': '6123', 'target': '5173', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 2}, {'source': '6272', 'target': '5173', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 6}, {'source': '6273', 'target': '5173', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.181502638Z', 'Weight': 6}, {'source': '5', 'target': '5176', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 5}, {'source': '5957', 'target': '5176', 'label': 'MemberOf', 'kind': 'MemberOf', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 1}, {'source': '6017', 'target': '5176', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 5}, {'source': '6271', 'target': '5176', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:44.995877259Z', 'Weight': 2}, {'source': '5', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5092', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5174', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5175', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5176', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5177', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5178', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5179', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5415', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5739', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5864', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5950', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '6017', 'target': '5554', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 5}, {'source': '6093', 'target': '5554', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 2}, {'source': '6272', 'target': '5554', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 6}, {'source': '6273', 'target': '5554', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 6}, {'source': '6274', 'target': '5554', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5092', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5174', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5175', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5176', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5177', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5178', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5179', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5739', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5864', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5950', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '6017', 'target': '5570', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 5}, {'source': '6215', 'target': '5570', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 2}, {'source': '6272', 'target': '5570', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 6}, {'source': '6273', 'target': '5570', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 6}, {'source': '6274', 'target': '5570', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5092', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5174', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5175', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5176', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5177', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5178', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5179', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5187', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5739', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5864', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5950', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5951', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '6017', 'target': '5599', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 5}, {'source': '6171', 'target': '5599', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 2}, {'source': '6272', 'target': '5599', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 6}, {'source': '6273', 'target': '5599', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 6}, {'source': '6274', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '6279', 'target': '5599', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 9}, {'source': '5', 'target': '5957', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 5}, {'source': '5176', 'target': '5957', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 5}, {'source': '6017', 'target': '5957', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 5}, {'source': '6271', 'target': '5957', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:36.832245798Z', 'Weight': 2}, {'source': '5', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5092', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5174', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5175', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5176', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5177', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5178', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5179', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5184', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5739', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5864', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5950', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '6017', 'target': '5974', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 5}, {'source': '6098', 'target': '5974', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 2}, {'source': '6272', 'target': '5974', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 6}, {'source': '6273', 'target': '5974', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 6}, {'source': '6274', 'target': '5974', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:43.548154584Z', 'Weight': 9}, {'source': '5', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5092', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5128', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5174', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5175', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5176', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5177', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5178', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5179', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5196', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5739', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5864', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5950', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5953', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5959', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '6017', 'target': '5978', 'label': 'WriteDacl', 'kind': 'WriteDacl', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 5}, {'source': '6102', 'target': '5978', 'label': 'Contains', 'kind': 'Contains', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 2}, {'source': '6272', 'target': '5978', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 6}, {'source': '6273', 'target': '5978', 'label': 'AddKeyCredentialLink', 'kind': 'AddKeyCredentialLink', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 6}, {'source': '6274', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '6275', 'target': '5978', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5092', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5174', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5175', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5176', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5177', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5178', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5179', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5547', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5739', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5864', 'target': '5981', 'label': 'GenericAll', 'kind': 'GenericAll', 'lastSeen': '2025-05-13T13:28:41.684963398Z', 'Weight': 9}, {'source': '5950', 'target': '5981', 'l

In [65]:
# prompt: count the number of nodes in df['data']['nodes']

node_count = len(pd_node_list)
print(f"Number of nodes: {node_count}")

Number of nodes: 100

In [77]:
edges_len = len(edges_all)
#node_edges_len = len(df['data']['edges'])
#node_edges = df['data']['edges']
print(f"Number of nodes: {edges_len}")

Number of nodes: 543

In [ ]:
edges_all

In [126]:
# prompt: import bh.json and load into a pandas dataframe df

!pip install pandas

import pandas as pd
import json

# Assuming 'bh.json' is in the current working directory
with open('data/bh-7.json', 'r') as f:
    data_tier0 = json.load(f)

df_tier0 = pd.DataFrame(data_tier0)

# Display the first few rows of the DataFrame to verify
print(df_tier0.head())

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [127]:
# prompt: find column names in a dictionary df_tier0['data']['nodes']

if len(df_tier0['data']['nodes']) > 0:
  # If the dictionary of nodes is not empty, print the keys of the first node
  # Access the first dictionary in the values of the nodes dictionary
  first_node = next(iter(df_tier0['data']['nodes'].values()))
  print(first_node.keys())
else:
  # If the dictionary of nodes is empty, print a message
  print("The dictionary of nodes is empty.")

dict_keys(['label', 'kind', 'objectId', 'isTierZero', 'isOwnedObject', 'lastSeen'])

In [128]:
import pandas as pd
pd.set_option('display.max_columns', None)
#edge.keys()
edges_all

[{'source': '5176',
  'target': '5',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 5},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 1},
 {'source': '5957',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 1},
 {'source': '5974',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 1},
 {'source': '6017',
  'target': '5',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 5},
 {'source': '6257',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 1},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 2},
 {'source': '5',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5087',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5176',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5177',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5178',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5179',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5578',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5646',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5712',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5830',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5874',
  'target': '5173',
  'label': 'CanPSRemote',
  'kind': 'CanPSRemote',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 2},
 {'source': '5949',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5950',
  'target': '5173',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 9},
 {'source': '5957',
  'target': '5173',
  'label': 'AdminTo',
  'kind': 'AdminTo',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 8},
 {'source': '5978',
  'target': '5173',
  'label': 'AdminTo',
  'kind': 'AdminTo',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 8},
 {'source': '5986',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 2},
 {'source': '5987',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 2},
 {'source': '5988',
  'target': '5173',
  'label': 'CanRDP',
  'kind': 'CanRDP',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 2},
 {'source': '5993',
  'target': '5173',
  'label': 'ExecuteDCOM',
  'kind': 'ExecuteDCOM',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 2},
 {'source': '6010',
  'target': '5173',
  'label': 'CanPSRemote',
  'kind': 'CanPSRemote',
  'lastSeen': '2025-05-15T09:47:56.580159608Z',
  'Weight': 2},
 {'source': '6017',
  'target': '5173',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 5},
 {'source': '6123',
  'target': '5173',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 2},
 {'source': '6272',
  'target': '5173',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 6},
 {'source': '6273',
  'target': '5173',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.181502638Z',
  'Weight': 6},
 {'source': '5',
  'target': '5176',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 5},
 {'source': '5957',
  'target': '5176',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 1},
 {'source': '6017',
  'target': '5176',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 5},
 {'source': '6271',
  'target': '5176',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z',
  'Weight': 2},
 {'source': '5',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5092',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5174',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5176',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5177',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5178',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5179',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5415',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5739',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5864',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5950',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '6017',
  'target': '5554',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 5},
 {'source': '6093',
  'target': '5554',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 2},
 {'source': '6272',
  'target': '5554',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 6},
 {'source': '6273',
  'target': '5554',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 6},
 {'source': '6274',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5092',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5174',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5175',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5176',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5177',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5178',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5179',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5739',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5864',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5950',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '6017',
  'target': '5570',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 5},
 {'source': '6215',
  'target': '5570',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 2},
 {'source': '6272',
  'target': '5570',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 6},
 {'source': '6273',
  'target': '5570',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 6},
 {'source': '6274',
  'target': '5570',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5092',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5174',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5175',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5176',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5177',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5178',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5179',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5187',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5739',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5864',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5950',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5951',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '6017',
  'target': '5599',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 5},
 {'source': '6171',
  'target': '5599',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 2},
 {'source': '6272',
  'target': '5599',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 6},
 {'source': '6273',
  'target': '5599',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 6},
 {'source': '6274',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '6279',
  'target': '5599',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 9},
 {'source': '5',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 5},
 {'source': '5176',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 5},
 {'source': '6017',
  'target': '5957',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 5},
 {'source': '6271',
  'target': '5957',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:36.832245798Z',
  'Weight': 2},
 {'source': '5',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5092',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5174',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5175',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5176',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5177',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5178',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5179',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5184',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5739',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5864',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5950',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '6017',
  'target': '5974',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 5},
 {'source': '6098',
  'target': '5974',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 2},
 {'source': '6272',
  'target': '5974',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 6},
 {'source': '6273',
  'target': '5974',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 6},
 {'source': '6274',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z',
  'Weight': 9},
 {'source': '5',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5092',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5128',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5174',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5175',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5176',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5177',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5178',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5179',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5196',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5739',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5864',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5950',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5953',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5959',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '6017',
  'target': '5978',
  'label': 'WriteDacl',
  'kind': 'WriteDacl',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 5},
 {'source': '6102',
  'target': '5978',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 2},
 {'source': '6272',
  'target': '5978',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 6},
 {'source': '6273',
  'target': '5978',
  'label': 'AddKeyCredentialLink',
  'kind': 'AddKeyCredentialLink',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 6},
 {'source': '6274',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '6275',
  'target': '5978',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5',
  'target': '5981',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z',
  'Weight': 9},
 {'source': '5092',

In [129]:
# prompt: get unique value from edges['source']

source_values = [edge['source'] for edge in edges_all]
unique_source_values = set(source_values)
unique_source_values

{'5',
 '5087',
 '5092',
 '5128',
 '5173',
 '5174',
 '5175',
 '5176',
 '5177',
 '5178',
 '5179',
 '5180',
 '5181',
 '5182',
 '5183',
 '5184',
 '5187',
 '5194',
 '5196',
 '5415',
 '5520',
 '5547',
 '5554',
 '5570',
 '5578',
 '5599',
 '5625',
 '5646',
 '5712',
 '5739',
 '5830',
 '5864',
 '5874',
 '5949',
 '5950',
 '5951',
 '5953',
 '5954',
 '5956',
 '5957',
 '5958',
 '5959',
 '5974',
 '5978',
 '5981',
 '5982',
 '5983',
 '5986',
 '5987',
 '5988',
 '5993',
 '6010',
 '6017',
 '6053',
 '6054',
 '6071',
 '6081',
 '6084',
 '6093',
 '6094',
 '6097',
 '6098',
 '6102',
 '6107',
 '6123',
 '6132',
 '6135',
 '6143',
 '6145',
 '6155',
 '6171',
 '6192',
 '6201',
 '6215',
 '6221',
 '6235',
 '6252',
 '6253',
 '6257',
 '6258',
 '6270',
 '6271',
 '6272',
 '6273',
 '6274',
 '6275',
 '6277',
 '6279',
 '6733',
 '7204',
 '7373',
 '7545',
 '8364',
 '8569',
 '8570'}

In [130]:
# prompt: print df['data']['edges']['source'], df['data']['edges']['target'] and df['data']['edges']['Weight']. I just want the values not the labels and assign these to Source, Target and Weight

Source = [edge['source'] for edge in df_all['data']['edges']]
Target = [edge['target'] for edge in df_all['data']['edges']]
Weight = [edge['Weight'] for edge in df_all['data']['edges']]

print("Source:", Source)
print("Target:", Target)
print("Weight:", Weight)

Source: ['5176', '5554', '5957', '5974', '6017', '6257', '6271', '5', '5087', '5176', '5177', '5178', '5179', '5578', '5646', '5712', '5830', '5874', '5949', '5950', '5957', '5978', '5986', '5987', '5988', '5993', '6010', '6017', '6123', '6272', '6273', '5', '5957', '6017', '6271', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5415', '5739', '5864', '5950', '6017', '6093', '6272', '6273', '6274', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5739', '5864', '5950', '6017', '6215', '6272', '6273', '6274', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5187', '5739', '5864', '5950', '5951', '6017', '6171', '6272', '6273', '6274', '6279', '5', '5176', '6017', '6271', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5184', '5739', '5864', '5950', '6017', '6098', '6272', '6273', '6274', '5', '5092', '5128', '5174', '5175', '5176', '5177', '5178', '5179', '5196', '5739', '5864', '5950', '5953', '5959', '6017', '6102', '6272', '6273', '6274', '6275', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5547', '5739', '5864', '5950', '6017', '6145', '6272', '6273', '6274', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5520', '5625', '5739', '5864', '5950', '5953', '5959', '6017', '6143', '6272', '6273', '6274', '6275', '6277', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5181', '5415', '5646', '5739', '5864', '5950', '5954', '5958', '6017', '6252', '6272', '6273', '6274', '5', '5176', '5957', '5978', '6258', '5', '5176', '5981', '5982', '5983', '6017', '6258', '5173', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6071', '5', '5176', '5177', '5178', '5179', '5180', '5950', '6017', '6221', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '5', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6081', '5', '5176', '5177', '5178', '5179', '5415', '5950', '6017', '6053', '5', '5176', '5177', '5178', '5179', '5183', '5950', '5953', '6017', '6155', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6192', '5', '5092', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6084', '5', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6081', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '8570', '5', '5176', '5177', '5178', '5179', '5950', '5951', '6017', '6253', '5', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6201', '5', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6107', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6235', '5', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6081', '5', '5176', '5177', '5178', '5179', '5950', '5951', '6017', '6132', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6097', '5', '5176', '5177', '5178', '5179', '5950', '5953', '6017', '6081', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6097', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6071', '5', '5176', '5177', '5178', '5179', '5415', '5950', '6017', '6053', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '5', '5176', '6017', '6271', '5', '5173', '5176', '6017', '8569', '5', '5173', '5176', '5570', '5599', '6017', '6271', '7373', '7545', '5', '5176', '5177', '5178', '5179', '5950', '6017', '6258', '5', '5176', '6017', '6271', '6733', '7204', '5', '5176', '6017', '6271', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5183', '5194', '5547', '5739', '5864', '5950', '5953', '5956', '5959', '6017', '6094', '6272', '6273', '6274', '6275', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5180', '5739', '5864', '5950', '6017', '6054', '6272', '6273', '6274', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5739', '5864', '5950', '6017', '6270', '6272', '6273', '6274', '5', '5092', '5174', '5175', '5176', '5177', '5178', '5179', '5182', '5739', '5864', '5950', '5953', '5959', '6017', '6135', '6272', '6273', '6274', '6275', '5', '5176', '5957', '6017', '6271', '5', '5176', '6017', '8364', '5', '5176', '5', '5176']
Target: ['5', '5', '5', '5', '5', '5', '5', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5173', '5176', '5176', '5176', '5176', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5554', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5570', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5599', '5957', '5957', '5957', '5957', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5974', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5978', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5981', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5982', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '5983', '6017', '6017', '6017', '6017', '6017', '6021', '6021', '6021', '6021', '6021', '6021', '6021', '6038', '6053', '6053', '6053', '6053', '6053', '6053', '6053', '6053', '6054', '6054', '6054', '6054', '6054', '6054', '6054', '6054', '6054', '6071', '6071', '6071', '6071', '6071', '6071', '6071', '6071', '6081', '6081', '6081', '6081', '6081', '6081', '6081', '6081', '6084', '6084', '6084', '6084', '6084', '6084', '6084', '6084', '6084', '6093', '6093', '6093', '6093', '6093', '6093', '6093', '6093', '6093', '6094', '6094', '6094', '6094', '6094', '6094', '6094', '6094', '6094', '6094', '6097', '6097', '6097', '6097', '6097', '6097', '6097', '6097', '6098', '6098', '6098', '6098', '6098', '6098', '6098', '6098', '6102', '6102', '6102', '6102', '6102', '6102', '6102', '6102', '6102', '6102', '6107', '6107', '6107', '6107', '6107', '6107', '6107', '6107', '6107', '6123', '6123', '6123', '6123', '6123', '6123', '6123', '6123', '6123', '6132', '6132', '6132', '6132', '6132', '6132', '6132', '6132', '6132', '6135', '6135', '6135', '6135', '6135', '6135', '6135', '6135', '6135', '6143', '6143', '6143', '6143', '6143', '6143', '6143', '6143', '6143', '6145', '6145', '6145', '6145', '6145', '6145', '6145', '6145', '6155', '6155', '6155', '6155', '6155', '6155', '6155', '6155', '6155', '6171', '6171', '6171', '6171', '6171', '6171', '6171', '6171', '6171', '6192', '6192', '6192', '6192', '6192', '6192', '6192', '6192', '6201', '6201', '6201', '6201', '6201', '6201', '6201', '6201', '6201', '6215', '6215', '6215', '6215', '6215', '6215', '6215', '6215', '6221', '6221', '6221', '6221', '6221', '6221', '6221', '6221', '6235', '6235', '6235', '6235', '6235', '6235', '6235', '6235', '6252', '6252', '6252', '6252', '6252', '6252', '6252', '6252', '6252', '6253', '6253', '6253', '6253', '6253', '6253', '6253', '6253', '6257', '6257', '6257', '6257', '6258', '6258', '6258', '6258', '6258', '6265', '6265', '6265', '6265', '6265', '6265', '6265', '6265', '6265', '6270', '6270', '6270', '6270', '6270', '6270', '6270', '6270', '6272', '6272', '6272', '6272', '6272', '6272', '6273', '6273', '6273', '6273', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '6733', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7204', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7373', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7545', '7968', '7968', '7968', '7968', '7968', '8376', '8376', '8376', '8376', '8569', '8569', '8570', '8570']
Weight: [5, 1, 1, 1, 5, 1, 2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 2, 9, 9, 8, 8, 2, 2, 2, 2, 2, 5, 2, 6, 6, 5, 1, 5, 2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 5, 5, 5, 2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 5, 5, 1, 1, 2, 5, 5, 1, 1, 1, 5, 2, 1, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 5, 9, 9, 9, 9, 9, 5, 2, 3, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 9, 5, 2, 9, 9, 9, 9, 9, 9, 5, 2, 5, 5, 5, 2, 5, 0, 9, 5, 3, 5, 1, 5, 1, 1, 5, 2, 1, 1, 9, 9, 9, 9, 9, 9, 5, 2, 5, 5, 5, 2, 1, 1, 5, 5, 5, 2, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 2, 6, 6, 9, 9, 5, 5, 1, 5, 2, 5, 5, 5, 2, 5, 5, 5, 5]

In [131]:
if Weight == 0:
  print([Weight])

In [132]:
# prompt: i want to iterate over the sources and pick the 1st value, then the 2nd , then the 3rd etc, but just want the values without the labels
i = 0
for i in range(len(Source)):
    source_value = Source[i]
    target_value = Target[i]
    weight_value = Weight[i]
    print(f"{source_value}, {target_value},{weight_value}")

5176, 5,5
5554, 5,1
5957, 5,1
5974, 5,1
6017, 5,5
6257, 5,1
6271, 5,2
5, 5173,9
5087, 5173,9
5176, 5173,9
5177, 5173,9
5178, 5173,9
5179, 5173,9
5578, 5173,9
5646, 5173,9
5712, 5173,9
5830, 5173,9
5874, 5173,2
5949, 5173,9
5950, 5173,9
5957, 5173,8
5978, 5173,8
5986, 5173,2
5987, 5173,2
5988, 5173,2
5993, 5173,2
6010, 5173,2
6017, 5173,5
6123, 5173,2
6272, 5173,6
6273, 5173,6
5, 5176,5
5957, 5176,1
6017, 5176,5
6271, 5176,2
5, 5554,9
5092, 5554,9
5174, 5554,9
5175, 5554,9
5176, 5554,9
5177, 5554,9
5178, 5554,9
5179, 5554,9
5415, 5554,9
5739, 5554,9
5864, 5554,9
5950, 5554,9
6017, 5554,5
6093, 5554,2
6272, 5554,6
6273, 5554,6
6274, 5554,9
5, 5570,9
5092, 5570,9
5174, 5570,9
5175, 5570,9
5176, 5570,9
5177, 5570,9
5178, 5570,9
5179, 5570,9
5739, 5570,9
5864, 5570,9
5950, 5570,9
6017, 5570,5
6215, 5570,2
6272, 5570,6
6273, 5570,6
6274, 5570,9
5, 5599,9
5092, 5599,9
5174, 5599,9
5175, 5599,9
5176, 5599,9
5177, 5599,9
5178, 5599,9
5179, 5599,9
5187, 5599,9
5739, 5599,9
5864, 5599,9
5950, 5599,9
5951, 5599,9
6017, 5599,5
6171, 5599,2
6272, 5599,6
6273, 5599,6
6274, 5599,9
6279, 5599,9
5, 5957,5
5176, 5957,5
6017, 5957,5
6271, 5957,2
5, 5974,9
5092, 5974,9
5174, 5974,9
5175, 5974,9
5176, 5974,9
5177, 5974,9
5178, 5974,9
5179, 5974,9
5184, 5974,9
5739, 5974,9
5864, 5974,9
5950, 5974,9
6017, 5974,5
6098, 5974,2
6272, 5974,6
6273, 5974,6
6274, 5974,9
5, 5978,9
5092, 5978,9
5128, 5978,9
5174, 5978,9
5175, 5978,9
5176, 5978,9
5177, 5978,9
5178, 5978,9
5179, 5978,9
5196, 5978,9
5739, 5978,9
5864, 5978,9
5950, 5978,9
5953, 5978,9
5959, 5978,9
6017, 5978,5
6102, 5978,2
6272, 5978,6
6273, 5978,6
6274, 5978,9
6275, 5978,9
5, 5981,9
5092, 5981,9
5174, 5981,9
5175, 5981,9
5176, 5981,9
5177, 5981,9
5178, 5981,9
5179, 5981,9
5547, 5981,9
5739, 5981,9
5864, 5981,9
5950, 5981,9
6017, 5981,5
6145, 5981,2
6272, 5981,6
6273, 5981,6
6274, 5981,9
5, 5982,9
5092, 5982,9
5174, 5982,9
5175, 5982,9
5176, 5982,9
5177, 5982,9
5178, 5982,9
5179, 5982,9
5520, 5982,9
5625, 5982,9
5739, 5982,9
5864, 5982,9
5950, 5982,9
5953, 5982,9
5959, 5982,9
6017, 5982,5
6143, 5982,2
6272, 5982,6
6273, 5982,6
6274, 5982,9
6275, 5982,9
6277, 5982,9
5, 5983,9
5092, 5983,9
5174, 5983,9
5175, 5983,9
5176, 5983,9
5177, 5983,9
5178, 5983,9
5179, 5983,9
5181, 5983,9
5415, 5983,9
5646, 5983,9
5739, 5983,9
5864, 5983,9
5950, 5983,9
5954, 5983,9
5958, 5983,9
6017, 5983,5
6252, 5983,2
6272, 5983,6
6273, 5983,6
6274, 5983,9
5, 6017,5
5176, 6017,5
5957, 6017,1
5978, 6017,1
6258, 6017,2
5, 6021,5
5176, 6021,5
5981, 6021,1
5982, 6021,1
5983, 6021,1
6017, 6021,5
6258, 6021,2
5173, 6038,1
5, 6053,9
5176, 6053,9
5177, 6053,9
5178, 6053,9
5179, 6053,9
5950, 6053,9
6017, 6053,5
6071, 6053,2
5, 6054,9
5176, 6054,9
5177, 6054,9
5178, 6054,9
5179, 6054,9
5180, 6054,9
5950, 6054,9
6017, 6054,5
6221, 6054,2
5, 6071,9
5176, 6071,9
5177, 6071,9
5178, 6071,9
5179, 6071,9
5950, 6071,9
6017, 6071,5
6258, 6071,2
5, 6081,9
5176, 6081,9
5177, 6081,9
5178, 6081,9
5179, 6081,9
5950, 6081,9
6017, 6081,5
6258, 6081,2
5, 6084,9
5176, 6084,9
5177, 6084,9
5178, 6084,9
5179, 6084,9
5950, 6084,9
5953, 6084,9
6017, 6084,5
6081, 6084,2
5, 6093,9
5176, 6093,9
5177, 6093,9
5178, 6093,9
5179, 6093,9
5415, 6093,9
5950, 6093,9
6017, 6093,5
6053, 6093,2
5, 6094,9
5176, 6094,9
5177, 6094,9
5178, 6094,9
5179, 6094,9
5183, 6094,9
5950, 6094,9
5953, 6094,9
6017, 6094,5
6155, 6094,2
5, 6097,9
5176, 6097,9
5177, 6097,9
5178, 6097,9
5179, 6097,9
5950, 6097,9
6017, 6097,5
6258, 6097,2
5, 6098,9
5176, 6098,9
5177, 6098,9
5178, 6098,9
5179, 6098,9
5950, 6098,9
6017, 6098,5
6192, 6098,2
5, 6102,9
5092, 6102,9
5176, 6102,9
5177, 6102,9
5178, 6102,9
5179, 6102,9
5950, 6102,9
5953, 6102,9
6017, 6102,5
6084, 6102,2
5, 6107,9
5176, 6107,9
5177, 6107,9
5178, 6107,9
5179, 6107,9
5950, 6107,9
5953, 6107,9
6017, 6107,5
6081, 6107,2
5, 6123,5
5176, 6123,9
5177, 6123,9
5178, 6123,9
5179, 6123,9
5950, 6123,9
6017, 6123,5
6258, 6123,2
8570, 6123,3
5, 6132,9
5176, 6132,9
5177, 6132,9
5178, 6132,9
5179, 6132,9
5950, 6132,9
5951, 6132,9
6017, 6132,5
6253, 6132,2
5, 6135,9
5176, 6135,9
5177, 6135,9
5178, 6135,9
5179, 6135,9
5950, 6135,9
5953, 6135,9
6017, 6135,5
6201, 6135,2
5, 6143,9
5176, 6143,9
5177, 6143,9
5178, 6143,9
5179, 6143,9
5950, 6143,9
5953, 6143,9
6017, 6143,5
6107, 6143,2
5, 6145,9
5176, 6145,9
5177, 6145,9
5178, 6145,9
5179, 6145,9
5950, 6145,9
6017, 6145,5
6235, 6145,2
5, 6155,9
5176, 6155,9
5177, 6155,9
5178, 6155,9
5179, 6155,9
5950, 6155,9
5953, 6155,9
6017, 6155,5
6081, 6155,2
5, 6171,9
5176, 6171,9
5177, 6171,9
5178, 6171,9
5179, 6171,9
5950, 6171,9
5951, 6171,9
6017, 6171,5
6132, 6171,2
5, 6192,9
5176, 6192,9
5177, 6192,9
5178, 6192,9
5179, 6192,9
5950, 6192,9
6017, 6192,5
6097, 6192,2
5, 6201,9
5176, 6201,9
5177, 6201,9
5178, 6201,9
5179, 6201,9
5950, 6201,9
5953, 6201,9
6017, 6201,5
6081, 6201,2
5, 6215,9
5176, 6215,9
5177, 6215,9
5178, 6215,9
5179, 6215,9
5950, 6215,9
6017, 6215,5
6258, 6215,2
5, 6221,9
5176, 6221,9
5177, 6221,9
5178, 6221,9
5179, 6221,9
5950, 6221,9
6017, 6221,5
6097, 6221,2
5, 6235,9
5176, 6235,9
5177, 6235,9
5178, 6235,9
5179, 6235,9
5950, 6235,9
6017, 6235,5
6071, 6235,2
5, 6252,9
5176, 6252,9
5177, 6252,9
5178, 6252,9
5179, 6252,9
5415, 6252,9
5950, 6252,9
6017, 6252,5
6053, 6252,2
5, 6253,9
5176, 6253,9
5177, 6253,9
5178, 6253,9
5179, 6253,9
5950, 6253,9
6017, 6253,5
6258, 6253,2
5, 6257,5
5176, 6257,5
6017, 6257,5
6271, 6257,2
5, 6258,5
5173, 6258,0
5176, 6258,9
6017, 6258,5
8569, 6258,3
5, 6265,5
5173, 6265,1
5176, 6265,5
5570, 6265,1
5599, 6265,1
6017, 6265,5
6271, 6265,2
7373, 6265,1
7545, 6265,1
5, 6270,9
5176, 6270,9
5177, 6270,9
5178, 6270,9
5179, 6270,9
5950, 6270,9
6017, 6270,5
6258, 6270,2
5, 6272,5
5176, 6272,5
6017, 6272,5
6271, 6272,2
6733, 6272,1
7204, 6272,1
5, 6273,5
5176, 6273,5
6017, 6273,5
6271, 6273,2
5, 6733,9
5092, 6733,9
5174, 6733,9
5175, 6733,9
5176, 6733,9
5177, 6733,9
5178, 6733,9
5179, 6733,9
5183, 6733,9
5194, 6733,9
5547, 6733,9
5739, 6733,9
5864, 6733,9
5950, 6733,9
5953, 6733,9
5956, 6733,9
5959, 6733,9
6017, 6733,5
6094, 6733,2
6272, 6733,6
6273, 6733,6
6274, 6733,9
6275, 6733,9
5, 7204,9
5092, 7204,9
5174, 7204,9
5175, 7204,9
5176, 7204,9
5177, 7204,9
5178, 7204,9
5179, 7204,9
5180, 7204,9
5739, 7204,9
5864, 7204,9
5950, 7204,9
6017, 7204,5
6054, 7204,2
6272, 7204,6
6273, 7204,6
6274, 7204,9
5, 7373,9
5092, 7373,9
5174, 7373,9
5175, 7373,9
5176, 7373,9
5177, 7373,9
5178, 7373,9
5179, 7373,9
5739, 7373,9
5864, 7373,9
5950, 7373,9
6017, 7373,5
6270, 7373,2
6272, 7373,6
6273, 7373,6
6274, 7373,9
5, 7545,9
5092, 7545,9
5174, 7545,9
5175, 7545,9
5176, 7545,9
5177, 7545,9
5178, 7545,9
5179, 7545,9
5182, 7545,9
5739, 7545,9
5864, 7545,9
5950, 7545,9
5953, 7545,9
5959, 7545,9
6017, 7545,5
6135, 7545,2
6272, 7545,6
6273, 7545,6
6274, 7545,9
6275, 7545,9
5, 7968,5
5176, 7968,5
5957, 7968,1
6017, 7968,5
6271, 7968,2
5, 8376,5
5176, 8376,5
6017, 8376,5
8364, 8376,2
5, 8569,5
5176, 8569,5
5, 8570,5
5176, 8570,5

In [133]:
#df_tier0.columns
#df_tier0_nodes=df_tier0['data']['nodes']
#df_tier0_nodes=df_tier0['data']['nodes'].keys()

df_tier0_edges=df_tier0['data']['edges']
#df_tier0_edges=df_tier0['data']['edges']
df_tier0_edges=df_tier0['data']['edges']
df_tier0_edges

[{'source': '5210',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5211',
  'target': '8246',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8246',
  'target': '8205',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8205',
  'target': '8361',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8361',
  'target': '5196',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5196',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5212',
  'target': '8153',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8153',
  'target': '5186',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5186',
  'target': '7522',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7522',
  'target': '5175',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5213',
  'target': '5180',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5180',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5222',
  'target': '8129',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8129',
  'target': '5206',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5206',
  'target': '7721',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7721',
  'target': '5180',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5180',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5223',
  'target': '5184',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5184',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5974',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5224',
  'target': '8250',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8250',
  'target': '5188',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5188',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5225',
  'target': '8351',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8351',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5230',
  'target': '5200',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5200',
  'target': '5785',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '5785',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5237',
  'target': '8326',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8326',
  'target': '5192',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5192',
  'target': '5400',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5400',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5238',
  'target': '5188',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5188',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5239',
  'target': '8111',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8111',
  'target': '5198',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5198',
  'target': '5175',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5240',
  'target': '5209',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5209',
  'target': '5175',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5241',
  'target': '5194',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:46.669671706Z'},
 {'source': '5194',
  'target': '6998',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6998',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5243',
  'target': '8270',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8270',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5244',
  'target': '8126',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8126',
  'target': '8158',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8158',
  'target': '5200',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5200',
  'target': '5785',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '5785',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5248',
  'target': '5183',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5183',
  'target': '6275',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6275',
  'target': '5950',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5950',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5249',
  'target': '8346',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8346',
  'target': '5190',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5190',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5250',
  'target': '6264',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6264',
  'target': '5186',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5186',
  'target': '5483',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5483',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5251',
  'target': '8157',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8157',
  'target': '5175',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5252',
  'target': '7995',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '7995',
  'target': '5202',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5202',
  'target': '6280',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6280',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5253',
  'target': '8355',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8355',
  'target': '6259',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6259',
  'target': '5168',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5168',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5255',
  'target': '8361',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8361',
  'target': '5196',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5196',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5258',
  'target': '7995',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '7995',
  'target': '5202',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5202',
  'target': '6280',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6280',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5261',
  'target': '5185',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5185',
  'target': '7108',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.853681099Z'},
 {'source': '7108',
  'target': '8351',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8351',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5262',
  'target': '5195',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5195',
  'target': '5399',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5399',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5263',
  'target': '5207',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5207',
  'target': '5593',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5593',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5264',
  'target': '5092',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5092',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5265',
  'target': '5182',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5182',
  'target': '7927',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7927',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},

In [134]:
# prompt: create a new dataframe that iterates over the df_tier0_nodes with a label of source

import pandas as pd
df_source_nodes = pd.DataFrame({'source': [edge['source'] for edge in df_tier0_edges]})
df_source_nodes['target'] = 9999
df_source_nodes['label'] = "tier_0"
df_source_nodes['kind'] = "tier_0"
df_source_nodes['lastSeen'] = "2025-05-13T13:28:46.75975446Z"
df_source_nodes['Weight'] = 20

#df_source_nodes
edges_tier0 = df_source_nodes
edges_tier0

     source  target   label    kind                       lastSeen  Weight
0      5210    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
1      5179    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
2      6271    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
3      5211    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
4      8246    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
...     ...     ...     ...     ...                            ...     ...
4972   5177    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
4973   6271    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
4974   7470    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
4975   5177    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
4976   6271    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20

[4977 rows x 6 columns]

In [115]:
edges_tier0

    source  target   label    kind                       lastSeen  Weight
0     6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
1     6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
2     6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
3     6081    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
4     6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
..     ...     ...     ...     ...                            ...     ...
116   6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
117   6271    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
118   6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
119   6271    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20
120   6258    9999  tier_0  tier_0  2025-05-13T13:28:46.75975446Z      20

[121 rows x 6 columns]

In [135]:
# prompt: please append edges_tier0 to the df_tier0_edges and call it new_edges

new_edges =  df_tier0_edges + edges_tier0.to_dict(orient='records')

In [136]:
new_edges

[{'source': '5210',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5211',
  'target': '8246',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8246',
  'target': '8205',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8205',
  'target': '8361',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8361',
  'target': '5196',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5196',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5212',
  'target': '8153',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8153',
  'target': '5186',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5186',
  'target': '7522',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7522',
  'target': '5175',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5213',
  'target': '5180',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5180',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5222',
  'target': '8129',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8129',
  'target': '5206',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5206',
  'target': '7721',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7721',
  'target': '5180',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5180',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5223',
  'target': '5184',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5184',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5974',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5224',
  'target': '8250',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8250',
  'target': '5188',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5188',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5225',
  'target': '8351',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8351',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5230',
  'target': '5200',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5200',
  'target': '5785',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '5785',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5237',
  'target': '8326',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8326',
  'target': '5192',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5192',
  'target': '5400',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5400',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5238',
  'target': '5188',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5188',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5239',
  'target': '8111',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8111',
  'target': '5198',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5198',
  'target': '5175',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5240',
  'target': '5209',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5209',
  'target': '5175',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5241',
  'target': '5194',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:46.669671706Z'},
 {'source': '5194',
  'target': '6998',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6998',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5243',
  'target': '8270',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8270',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5244',
  'target': '8126',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8126',
  'target': '8158',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8158',
  'target': '5200',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5200',
  'target': '5785',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '5785',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5248',
  'target': '5183',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5183',
  'target': '6275',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6275',
  'target': '5950',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5950',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5249',
  'target': '8346',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8346',
  'target': '5190',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5190',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5250',
  'target': '6264',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6264',
  'target': '5186',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5186',
  'target': '5483',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5483',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5251',
  'target': '8157',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8157',
  'target': '5175',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5252',
  'target': '7995',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '7995',
  'target': '5202',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5202',
  'target': '6280',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6280',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5253',
  'target': '8355',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8355',
  'target': '6259',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6259',
  'target': '5168',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5168',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5255',
  'target': '8361',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8361',
  'target': '5196',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5196',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5258',
  'target': '7995',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '7995',
  'target': '5202',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5202',
  'target': '6280',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6280',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5261',
  'target': '5185',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5185',
  'target': '7108',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.853681099Z'},
 {'source': '7108',
  'target': '8351',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8351',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5262',
  'target': '5195',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5195',
  'target': '5399',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5399',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5263',
  'target': '5207',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5207',
  'target': '5593',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5593',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5264',
  'target': '5092',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5092',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5265',
  'target': '5182',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5182',
  'target': '7927',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7927',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},

In [142]:
new_edges_len = len(new_edges)
new_edges_len

9954

In [141]:
# prompt: append the values of df_source_nodes to edges

# Assuming df_source_nodes is a DataFrame with 'source', 'target', and 'Weight' columns
# and edges is a list of tuples (source, target, weight)

# Convert df_source_nodes DataFrame into a list of tuples
new_edges_list = [(row['source'], row['target'], row['Weight']) for index, row in df_source_nodes.iterrows()]

# Append the new edges from df_source_nodes to the existing edges list
edges_tier0.extend(new_edges_list)

print("Updated edges list after appending df_source_nodes:")
#edges
new_edges_list

AttributeError: 'DataFrame' object has no attribute 'extend'

In [ ]:
   node_count = len(df_all['data']['nodes'])
   node_count

100

In [140]:
edges

NameError: name 'edges' is not defined

In [143]:
new_edges

[{'source': '5210',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5211',
  'target': '8246',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8246',
  'target': '8205',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8205',
  'target': '8361',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8361',
  'target': '5196',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5196',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5212',
  'target': '8153',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8153',
  'target': '5186',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5186',
  'target': '7522',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7522',
  'target': '5175',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5213',
  'target': '5180',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5180',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5222',
  'target': '8129',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8129',
  'target': '5206',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5206',
  'target': '7721',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7721',
  'target': '5180',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5180',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5223',
  'target': '5184',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5184',
  'target': '5974',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5974',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5224',
  'target': '8250',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8250',
  'target': '5188',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5188',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5225',
  'target': '8351',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8351',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5230',
  'target': '5200',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5200',
  'target': '5785',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '5785',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5237',
  'target': '8326',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8326',
  'target': '5192',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5192',
  'target': '5400',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5400',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5238',
  'target': '5188',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5188',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5239',
  'target': '8111',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8111',
  'target': '5198',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5198',
  'target': '5175',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5240',
  'target': '5209',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5209',
  'target': '5175',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5241',
  'target': '5194',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:46.669671706Z'},
 {'source': '5194',
  'target': '6998',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6998',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5243',
  'target': '8270',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8270',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5244',
  'target': '8126',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8126',
  'target': '8158',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8158',
  'target': '5200',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5200',
  'target': '5785',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '5785',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5248',
  'target': '5183',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5183',
  'target': '6275',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6275',
  'target': '5950',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '5950',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5249',
  'target': '8346',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8346',
  'target': '5190',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5190',
  'target': '6889',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.684963398Z'},
 {'source': '6889',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5250',
  'target': '6264',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6264',
  'target': '5186',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5186',
  'target': '5483',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5483',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5251',
  'target': '8157',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8157',
  'target': '5175',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5175',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5252',
  'target': '7995',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '7995',
  'target': '5202',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5202',
  'target': '6280',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6280',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5253',
  'target': '8355',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8355',
  'target': '6259',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '6259',
  'target': '5168',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5168',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5255',
  'target': '8361',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8361',
  'target': '5196',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5196',
  'target': '5177',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5258',
  'target': '7995',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '7995',
  'target': '5202',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5202',
  'target': '6280',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.983754394Z'},
 {'source': '6280',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5261',
  'target': '5185',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5185',
  'target': '7108',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:41.853681099Z'},
 {'source': '7108',
  'target': '8351',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '8351',
  'target': '5179',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5179',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5262',
  'target': '5195',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5195',
  'target': '5399',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5399',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5263',
  'target': '5207',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5207',
  'target': '5593',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5593',
  'target': '5178',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5178',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},
 {'source': '6271',
  'target': '5',
  'label': 'Contains',
  'kind': 'Contains',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5264',
  'target': '5092',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.181502638Z'},
 {'source': '5092',
  'target': '5554',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:36.832245798Z'},
 {'source': '5554',
  'target': '5',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5265',
  'target': '5182',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5182',
  'target': '7927',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:43.548154584Z'},
 {'source': '7927',
  'target': '5177',
  'label': 'MemberOf',
  'kind': 'MemberOf',
  'lastSeen': '2025-05-13T13:28:44.995877259Z'},
 {'source': '5177',
  'target': '6271',
  'label': 'GenericAll',
  'kind': 'GenericAll',
  'lastSeen': '2025-05-13T13:28:46.711604812Z'},

In [144]:
# prompt: convert new_edge into a dataframe

import pandas as pd
new_edges_df = pd.DataFrame(new_edges)

In [145]:
new_edges_df

,source,target,label,kind,lastSeen,Weight
0,5210,5179,MemberOf,MemberOf,2025-05-13T13:28:44.995877259Z,NaN
1,5179,6271,GenericAll,GenericAll,2025-05-13T13:28:46.711604812Z,NaN
2,6271,5,Contains,Contains,2025-05-13T13:28:44.995877259Z,NaN
3,5211,8246,MemberOf,MemberOf,2025-05-13T13:28:44.995877259Z,NaN
4,8246,8205,MemberOf,MemberOf,2025-05-13T13:28:44.995877259Z,NaN
...,...,...,...,...,...,...
9949,5177,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9950,6271,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9951,7470,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9952,5177,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9953,6271,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0

In [146]:
#convert new_edges_df['source'] and new_edges_df['target'] to int
new_edges_df['source'] = new_edges_df['source'].astype(int)
new_edges_df['target'] = new_edges_df['target'].astype(int)

In [172]:
# prompt: set the df_all['data']['nodes] to int

# Access the dictionary of nodes
nodes_dict = df_all['data']['nodes']

# Convert the dictionary of nodes to a pandas Series (where keys become index)
# or to a DataFrame if the inner structure of each node is consistent
# Let's assume you want to work with the keys (node IDs) as integers

# Convert the dictionary of nodes into a pandas Series where keys are the index
nodes_series = pd.Series(nodes_dict)

# If you intended to convert the index (node IDs) to integer type:
# nodes_series.index = nodes_series.index.astype(int)

# If you intended to convert the dictionary values (node attributes) within the Series
# to a DataFrame and then convert columns, you'd do something like:
# nodes_df = pd.DataFrame(nodes_series.tolist(), index=nodes_series.index)
# nodes_df['some_column'] = nodes_df['some_column'].astype(int) # Example

# However, it seems from your prompt history you might just want the node IDs as a list of integers:
node_ids_list = [int(node_id) for node_id in nodes_dict.keys()]

# If you want to update the 'nodes' entry in the df_all DataFrame's 'data' column,
# you would need to decide what format you want it in after conversion.
# Simply assigning the list of integer IDs back might not be what you want
# if you were previously accessing it as a dictionary.

# If your goal was to work with the nodes dictionary but ensure its keys are treated as integers
# in operations later on (like merging with edge data), converting the dictionary to a Series
# or DataFrame at the point of use is more appropriate than trying to change the type of the keys
# within the original dictionary cell in the DataFrame.

# Let's stick to the likely intention based on the error: you want to use the nodes data
# in a way that allows integer operations. The most direct way to handle this
# for subsequent merging or indexing is to convert the node IDs (keys) to integers
# when you extract them or convert the dictionary to a DataFrame.

# For example, if you need a list of integer node IDs:
df_all_node_ids_int = [int(node_id) for node_id in df_all['data']['nodes'].keys()]

# Or if you want a DataFrame of nodes with integer index:
# Assuming the values of the nodes dictionary are dictionaries themselves
try:
    nodes_list_of_dicts = [value for value in df_all['data']['nodes'].values()]
    nodes_df_converted = pd.DataFrame(nodes_list_of_dicts, index=[int(key) for key in df_all['data']['nodes'].keys()])
    # Now nodes_df_converted has an integer index (the node IDs) and you can work with it
    print("Converted nodes dictionary to DataFrame with integer index:")
    print(nodes_df_converted.head())
except Exception as e:
    print(f"Could not convert node values to DataFrame: {e}")
    print("Proceeding with extracting integer node IDs.")
    print(f"List of integer node IDs: {df_all_node_ids_int[:10]}...") # Print first 10 for preview

# The original line caused an error because you can't call .astype(int) on a dictionary.
# Remove or comment out the erroneous line:
# df_all['data']['nodes'] = df_all['data']['nodes'].astype(int)

# The variable df_all remains unchanged in its 'data' column's structure by this code,
# but you now have `df_all_node_ids_int` or `nodes_df_converted` which you can use
# for operations requiring integer node IDs.

Converted nodes dictionary to DataFrame with integer index:
                            label      kind  \
5       DOMAIN ADMINS@MYLAB.LOCAL     Group
5087   OGCWWKS1000000.MYLAB.LOCAL  Computer
5092  GOOWSECS1000001.MYLAB.LOCAL  Computer
5128   ITSWWKS1000001.MYLAB.LOCAL  Computer
5173           DCTEST.MYLAB.LOCAL  Computer

                                           objectId  isTierZero  \
5      S-1-5-21-1333368235-828418111-1849936505-512        True
5087  S-1-5-21-1333368235-828418111-1849936505-4105       False
5092  S-1-5-21-1333368235-828418111-1849936505-4111       False
5128  S-1-5-21-1333368235-828418111-1849936505-4146       False
5173  S-1-5-21-1333368235-828418111-1849936505-1000        True

      isOwnedObject                        lastSeen
5             False        2025-05-13T13:28:49.512Z
5087          False        2025-05-13T13:28:47.295Z
5092          False        2025-05-13T13:28:48.363Z
5128          False  2025-05-13T13:28:36.181237651Z
5173          False        2025-05-13T13:28:48.609Z

In [173]:
nodes_df_converted

,label,kind,objectId,isTierZero,isOwnedObject,lastSeen
5,DOMAIN ADMINS@MYLAB.LOCAL,Group,S-1-5-21-1333368235-828418111-1849936505-512,True,False,2025-05-13T13:28:49.512Z
5087,OGCWWKS1000000.MYLAB.LOCAL,Computer,S-1-5-21-1333368235-828418111-1849936505-4105,False,False,2025-05-13T13:28:47.295Z
5092,GOOWSECS1000001.MYLAB.LOCAL,Computer,S-1-5-21-1333368235-828418111-1849936505-4111,False,False,2025-05-13T13:28:48.363Z
5128,ITSWWKS1000001.MYLAB.LOCAL,Computer,S-1-5-21-1333368235-828418111-1849936505-4146,False,False,2025-05-13T13:28:36.181237651Z
5173,DCTEST.MYLAB.LOCAL,Computer,S-1-5-21-1333368235-828418111-1849936505-1000,True,False,2025-05-13T13:28:48.609Z
...,...,...,...,...,...,...
7968,SCHEMA ADMINS@MYLAB.LOCAL,Group,S-1-5-21-1333368235-828418111-1849936505-518,True,False,2025-05-13T13:28:47.181Z
8364,SYSTEM@MYLAB.LOCAL,Container,7E6DDFDC-07BE-4295-A9EB-1D993D877C48,False,False,2025-05-13T13:28:48.931Z
8376,ADMINSDHOLDER@MYLAB.LOCAL,Container,738F5127-0264-4DF8-8444-2C792EA2A637,True,False,2025-05-13T13:28:48.931Z
8569,DEFAULT DOMAIN POLICY@MYLAB.LOCAL,GPO,CD3A9B14-C932-416E-8E01-1C8C8FAEF125,True,False,2025-05-13T13:28:49.464Z
8570,DEFAULT DOMAIN CONTROLLERS POLICY@MYLAB.LOCAL,GPO,F39BE162-0FF0-46B0-B117-39FD979A220A,True,False,2025-05-13T13:28:49.464Z

In [177]:
# prompt: add another row to nodes_df_converted with a key of 9999, label = "tier 0", kind = "tier 0", objectId = "S-1-5-21-1333368235-828418111-1849936505-9999", isTierZero = "True", isOwnedObject = "False", lastSeen = "2025-05-13T13:28:46.75975446Z"

import pandas as pd
new_row_data = {
    'label': "tier 0",
    'kind': "tier 0",
    'objectId': "S-1-5-21-1333368235-828418111-1849936505-9999",
    'isTierZero': "True",
    'isOwnedObject': "False",
    'lastSeen': "2025-05-13T13:28:46.75975446Z"
}

# Create a new DataFrame for the row with the specified index
new_row_df = pd.DataFrame([new_row_data], index=[9999])

# Concatenate the original DataFrame with the new row
nodes_df_converted = pd.concat([nodes_df_converted, new_row_df])

print("DataFrame after adding the new row:")
print(nodes_df_converted.tail())

DataFrame after adding the new row:
                                              label       kind  \
8364                             SYSTEM@MYLAB.LOCAL  Container
8376                      ADMINSDHOLDER@MYLAB.LOCAL  Container
8569              DEFAULT DOMAIN POLICY@MYLAB.LOCAL        GPO
8570  DEFAULT DOMAIN CONTROLLERS POLICY@MYLAB.LOCAL        GPO
9999                                         tier 0     tier 0

                                           objectId isTierZero isOwnedObject  \
8364           7E6DDFDC-07BE-4295-A9EB-1D993D877C48      False         False
8376           738F5127-0264-4DF8-8444-2C792EA2A637       True         False
8569           CD3A9B14-C932-416E-8E01-1C8C8FAEF125       True         False
8570           F39BE162-0FF0-46B0-B117-39FD979A220A       True         False
9999  S-1-5-21-1333368235-828418111-1849936505-9999       True         False

                           lastSeen
8364       2025-05-13T13:28:48.931Z
8376       2025-05-13T13:28:48.931Z
8569       2025-05-13T13:28:49.464Z
8570       2025-05-13T13:28:49.464Z
9999  2025-05-13T13:28:46.75975446Z

In [178]:
# prompt: show me all target from new_edeges_df that are not included in nodes_df_converted and sort them ascendingly

# Find targets in new_edges_df that are not in the index of nodes_df_converted
targets_not_in_nodes = new_edges_df[~new_edges_df['target'].isin(nodes_df_converted.index)]['target']

# Get unique target values and sort them ascendingly
unique_targets_not_in_nodes = sorted(targets_not_in_nodes.unique())

# Print the results
print("Targets in new_edges_df not included in nodes_df_converted (sorted ascendingly):")
unique_targets_not_in_nodes

Targets in new_edges_df not included in nodes_df_converted (sorted ascendingly):

[np.int64(5094),
 np.int64(5116),
 np.int64(5132),
 np.int64(5147),
 np.int64(5150),
 np.int64(5161),
 np.int64(5164),
 np.int64(5168),
 np.int64(5185),
 np.int64(5186),
 np.int64(5188),
 np.int64(5189),
 np.int64(5190),
 np.int64(5191),
 np.int64(5192),
 np.int64(5195),
 np.int64(5197),
 np.int64(5198),
 np.int64(5199),
 np.int64(5200),
 np.int64(5201),
 np.int64(5202),
 np.int64(5203),
 np.int64(5205),
 np.int64(5206),
 np.int64(5207),
 np.int64(5208),
 np.int64(5209),
 np.int64(5325),
 np.int64(5399),
 np.int64(5400),
 np.int64(5483),
 np.int64(5516),
 np.int64(5593),
 np.int64(5726),
 np.int64(5785),
 np.int64(5828),
 np.int64(5883),
 np.int64(5900),
 np.int64(6259),
 np.int64(6260),
 np.int64(6261),
 np.int64(6262),
 np.int64(6263),
 np.int64(6264),
 np.int64(6280),
 np.int64(6396),
 np.int64(6456),
 np.int64(6734),
 np.int64(6823),
 np.int64(6824),
 np.int64(6868),
 np.int64(6889),
 np.int64(6900),
 np.int64(6998),
 np.int64(7108),
 np.int64(7191),
 np.int64(7227),
 np.int64(7407),
 np.int64(7522),
 np.int64(7583),
 np.int64(7721),
 np.int64(7757),
 np.int64(7894),
 np.int64(7927),
 np.int64(7995),
 np.int64(8017),
 np.int64(8032),
 np.int64(8108),
 np.int64(8111),
 np.int64(8115),
 np.int64(8126),
 np.int64(8129),
 np.int64(8153),
 np.int64(8154),
 np.int64(8157),
 np.int64(8158),
 np.int64(8180),
 np.int64(8189),
 np.int64(8202),
 np.int64(8205),
 np.int64(8219),
 np.int64(8226),
 np.int64(8227),
 np.int64(8246),
 np.int64(8250),
 np.int64(8263),
 np.int64(8270),
 np.int64(8276),
 np.int64(8280),
 np.int64(8287),
 np.int64(8326),
 np.int64(8346),
 np.int64(8348),
 np.int64(8351),
 np.int64(8355),
 np.int64(8358),
 np.int64(8361)]

In [179]:
new_edges_df

,source,target,label,kind,lastSeen,Weight
0,5210,5179,MemberOf,MemberOf,2025-05-13T13:28:44.995877259Z,1.0
1,5179,6271,GenericAll,GenericAll,2025-05-13T13:28:46.711604812Z,1.0
2,6271,5,Contains,Contains,2025-05-13T13:28:44.995877259Z,1.0
3,5211,8246,MemberOf,MemberOf,2025-05-13T13:28:44.995877259Z,1.0
4,8246,8205,MemberOf,MemberOf,2025-05-13T13:28:44.995877259Z,1.0
...,...,...,...,...,...,...
9949,5177,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9950,6271,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9951,7470,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9952,5177,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0
9953,6271,9999,tier_0,tier_0,2025-05-13T13:28:46.75975446Z,20.0

In [148]:
# prompt: if new_edges_df.Weight = "NaN" then set Weight == 1

new_edges_df.loc[new_edges_df['Weight'].isna(), 'Weight'] = 1

In [149]:
new_edges_df['Weight']

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ...
9949    20.0
9950    20.0
9951    20.0
9952    20.0
9953    20.0
Name: Weight, Length: 9954, dtype: float64

In [150]:
source = new_edges_df['source']
source = source.tolist()
source
target = new_edges_df['target']
target = target.tolist()
#target
Weight = new_edges_df['Weight']
Weight = Weight.tolist()
#Weight
#source = int(source)
#source.keys

In [159]:
import heapq
import sys

def dijkstra(graph, start_node):
  """
  Implements Dijkstra's algorithm to find the shortest paths from a start node.

  Args:
    graph: A dictionary representing the graph. Keys are nodes, and values are
           dictionaries where keys are neighboring nodes and values are edge weights.
    start_node: The node to start the algorithm from.

  Returns:
    A dictionary where keys are nodes and values are the shortest distance
    from the start_node to that node. Returns float('inf') if a node is unreachable.
  """
  # Initialize distances with infinity for all nodes except the start node
  distances = {node: float('inf') for node in graph}
  distances[start_node] = 0

  # Use a priority queue (min-heap) to store nodes to visit
  # The heap will store tuples of (distance, node)
  priority_queue = [(0, start_node)]

  while priority_queue:
    # Get the node with the smallest distance from the priority queue
    # Corrected: Remove [1] as heappop returns the tuple directly
    current_distance, current_node = heapq.heappop(priority_queue)

    # If the current distance is greater than the recorded distance,
    # we've found a shorter path already, so skip
    if current_distance > distances[current_node]:
      continue

    # Explore neighbors of the current node
    if current_node in graph:
      for neighbor, weight in graph[current_node].items():
        distance = current_distance + weight

        # If a shorter path to the neighbor is found, update the distance
        if distance < distances[neighbor]:
          distances[neighbor] = distance
          heapq.heappush(priority_queue, (distance, neighbor))

  return distances

# Example usage with the loaded data
# First, let's build the graph representation from the edges
graph = {}

# Populate the graph dictionary from the new_edges_df DataFrame
# Use iterrows() to iterate through the rows of the DataFrame
for index, row in new_edges_df.iterrows():
  source_node = row['source']
  target_node = row['target']
  # Access the 'Weight' column from the row, defaulting to 1 if not present (though you've already handled NaNs)
  weight = row['Weight'] if 'Weight' in row else 1

  # Ensure the nodes exist in the graph dictionary
  if source_node not in graph:
    graph[source_node] = {}
  if target_node not in graph:
    graph[target_node] = {}

  # Add the edge to the graph (assuming undirected for simplicity, adjust if directed)
  # For a directed graph, only add graph[source_node][target_node] = weight
  graph[source_node][target_node] = weight
  graph[target_node][source_node] = weight


# Let's pick a random node as the starting point for Dijkstra's
# You might want to choose a more meaningful starting node based on your data
if graph:
  # Ensure start_node is one of the keys in the graph
  if list(graph.keys()):
    start_node = list(graph.keys())[0] # Get the first node in the graph
    shortest_distances = dijkstra(graph, start_node)

    print(f"\nShortest distances from node '{start_node}':")
    for node, distance in shortest_distances.items():
      # Handle unreachable nodes (distance remains infinity)
      if distance == float('inf'): # Use float('inf') for comparison
          print(f"To node {node}: Unreachable")
      else:
          print(f"To node {node}: {distance}")
  else:
      print("\nGraph is empty. Cannot run Dijkstra's algorithm.")

else:
  print("\nGraph is empty. Cannot run Dijkstra's algorithm.")
  shortest_distances

Shortest distances from node '5210':
To node 5210: 0
To node 5179: 1.0
To node 6271: 2.0
To node 5: 3.0
To node 5211: 8.0
To node 8246: 7.0
To node 8205: 6.0
To node 8361: 5.0
To node 5196: 4.0
To node 5177: 3.0
To node 5212: 5.0
To node 8153: 4.0
To node 5186: 3.0
To node 7522: 4.0
To node 5175: 3.0
To node 5554: 4.0
To node 5213: 5.0
To node 5180: 4.0
To node 5222: 8.0
To node 8129: 7.0
To node 5206: 6.0
To node 7721: 5.0
To node 5223: 4.0
To node 5184: 3.0
To node 5974: 4.0
To node 5224: 7.0
To node 8250: 6.0
To node 5188: 5.0
To node 6889: 4.0
To node 5225: 3.0
To node 8351: 2.0
To node 5230: 6.0
To node 5200: 5.0
To node 5785: 4.0
To node 5237: 7.0
To node 8326: 6.0
To node 5192: 5.0
To node 5400: 4.0
To node 5238: 6.0
To node 5239: 6.0
To node 8111: 5.0
To node 5198: 4.0
To node 5240: 3.0
To node 5209: 2.0
To node 5241: 6.0
To node 5194: 5.0
To node 6998: 4.0
To node 5178: 3.0
To node 5243: 5.0
To node 8270: 4.0
To node 5244: 8.0
To node 8126: 7.0
To node 8158: 6.0
To node 5248: 6.0
To node 5183: 5.0
To node 6275: 4.0
To node 5950: 3.0
To node 5249: 7.0
To node 8346: 6.0
To node 5190: 5.0
To node 5250: 5.0
To node 6264: 4.0
To node 5483: 2.0
To node 5251: 5.0
To node 8157: 4.0
To node 5252: 5.0
To node 7995: 4.0
To node 5202: 3.0
To node 6280: 2.0
To node 5253: 7.0
To node 8355: 6.0
To node 6259: 5.0
To node 5168: 4.0
To node 5255: 6.0
To node 5258: 5.0
To node 5261: 5.0
To node 5185: 4.0
To node 7108: 3.0
To node 5262: 6.0
To node 5195: 5.0
To node 5399: 4.0
To node 5263: 6.0
To node 5207: 5.0
To node 5593: 4.0
To node 5264: 6.0
To node 5092: 5.0
To node 5265: 6.0
To node 5182: 5.0
To node 7927: 4.0
To node 5266: 8.0
To node 8280: 7.0
To node 5325: 4.0
To node 5267: 6.0
To node 5268: 6.0
To node 5270: 5.0
To node 5271: 6.0
To node 5273: 5.0
To node 5274: 6.0
To node 5275: 6.0
To node 8017: 5.0
To node 5276: 7.0
To node 8180: 6.0
To node 5278: 7.0
To node 5279: 5.0
To node 5283: 4.0
To node 5284: 6.0
To node 5287: 6.0
To node 5289: 8.0
To node 8227: 7.0
To node 5295: 6.0
To node 5181: 5.0
To node 5299: 6.0
To node 5301: 5.0
To node 5302: 5.0
To node 5304: 7.0
To node 5307: 4.0
To node 5308: 7.0
To node 6261: 6.0
To node 5164: 5.0
To node 5311: 4.0
To node 5314: 6.0
To node 5315: 6.0
To node 5317: 5.0
To node 5318: 5.0
To node 5320: 4.0
To node 5322: 5.0
To node 5323: 5.0
To node 5324: 4.0
To node 5327: 6.0
To node 8154: 5.0
To node 5205: 4.0
To node 5330: 6.0
To node 5335: 7.0
To node 6262: 6.0
To node 5147: 5.0
To node 5336: 3.0
To node 5338: 4.0
To node 5340: 3.0
To node 5341: 8.0
To node 5343: 8.0
To node 5344: 7.0
To node 8202: 6.0
To node 5348: 7.0
To node 5128: 6.0
To node 5978: 5.0
To node 6017: 4.0
To node 5349: 8.0
To node 5351: 5.0
To node 5358: 6.0
To node 5360: 5.0
To node 5361: 8.0
To node 5364: 6.0
To node 5365: 7.0
To node 8219: 6.0
To node 5367: 6.0
To node 5191: 5.0
To node 6396: 4.0
To node 5368: 8.0
To node 8263: 7.0
To node 5371: 6.0
To node 8115: 5.0
To node 5372: 4.0
To node 5373: 6.0
To node 5197: 5.0
To node 7227: 4.0
To node 5374: 6.0
To node 5375: 4.0
To node 5376: 4.0
To node 5377: 6.0
To node 5378: 4.0
To node 5380: 8.0
To node 5381: 6.0
To node 5382: 7.0
To node 8189: 6.0
To node 5383: 5.0
To node 5384: 3.0
To node 5385: 6.0
To node 5386: 6.0
To node 5389: 5.0
To node 5390: 7.0
To node 5391: 6.0
To node 5394: 6.0
To node 5201: 5.0
To node 7191: 4.0
To node 5402: 3.0
To node 5406: 8.0
To node 8287: 7.0
To node 5407: 6.0
To node 5408: 6.0
To node 5413: 6.0
To node 5415: 5.0
To node 5416: 6.0
To node 5417: 3.0
To node 5421: 6.0
To node 5424: 3.0
To node 5427: 5.0
To node 5430: 8.0
To node 5432: 7.0
To node 5434: 7.0
To node 5436: 6.0
To node 5440: 4.0
To node 5441: 6.0
To node 5444: 6.0
To node 5189: 5.0
To node 5445: 6.0
To node 5446: 6.0
To node 5447: 4.0
To node 5448: 6.0
To node 6734: 4.0
To node 5449: 8.0
To node 5451: 7.0
To node 5830: 6.0
To node 5454: 5.0
To node 5456: 6.0
To node 5457: 6.0
To node 5458: 6.0
To node 5459: 5.0
To node 5463: 7.0
To node 5464: 5.0
To node 5465: 3.0
To node 5466: 6.0
To node 5469: 8.0
To node 5470: 6.0
To node 5472: 6.0
To node 5473: 5.0
To node 5474: 6.0
To node 5476: 6.0
To node 5478: 6.0
To node 5481: 5.0
To node 5482: 7.0
To node 5484: 7.0
To node 5486: 8.0
To node 5487: 2.0
To node 5488: 4.0
To node 5492: 7.0
To node 5495: 8.0
To node 5497: 3.0
To node 5500: 6.0
To node 7583: 4.0
To node 5504: 3.0
To node 5505: 5.0
To node 6260: 4.0
To node 5510: 6.0
To node 5512: 4.0
To node 5515: 5.0
To node 5516: 6.0
To node 5864: 5.0
To node 5517: 7.0
To node 8358: 6.0
To node 5520: 5.0
To node 6868: 4.0
To node 5524: 6.0
To node 5529: 3.0
To node 5531: 2.0
To node 5532: 5.0
To node 5537: 4.0
To node 5539: 6.0
To node 5540: 7.0
To node 5542: 5.0
To node 5545: 6.0
To node 5546: 6.0
To node 5547: 5.0
To node 5549: 3.0
To node 5550: 7.0
To node 5552: 6.0
To node 5553: 7.0
To node 5555: 4.0
To node 5557: 6.0
To node 5559: 6.0
To node 5561: 4.0
To node 5562: 6.0
To node 5563: 5.0
To node 5565: 6.0
To node 5566: 4.0
To node 5569: 3.0
To node 5570: 5.0
To node 5572: 6.0
To node 8276: 5.0
To node 5573: 7.0
To node 5576: 7.0
To node 5199: 6.0
To node 5739: 5.0
To node 5577: 5.0
To node 6456: 4.0
To node 5578: 6.0
To node 5579: 6.0
To node 5580: 7.0
To node 5581: 5.0
To node 5584: 7.0
To node 5586: 7.0
To node 5588: 6.0
To node 5590: 6.0
To node 5591: 6.0
To node 5594: 6.0
To node 5595: 5.0
To node 5598: 4.0
To node 5602: 6.0
To node 5607: 5.0
To node 5609: 8.0
To node 5612: 6.0
To node 5613: 5.0
To node 5615: 5.0
To node 5616: 3.0
To node 5618: 4.0
To node 5622: 8.0
To node 5624: 6.0
To node 5625: 4.0
To node 5628: 6.0
To node 5630: 8.0
To node 5632: 6.0
To node 5633: 7.0
To node 5636: 6.0
To node 5637: 7.0
To node 5639: 8.0
To node 8108: 7.0
To node 5640: 8.0
To node 5641: 7.0
To node 5644: 5.0
To node 5645: 6.0
To node 5646: 4.0
To node 5647: 5.0
To node 5648: 5.0
To node 5649: 5.0
To node 5651: 7.0
To node 5656: 6.0
To node 5132: 5.0
To node 5658: 8.0
To node 5659: 5.0
To node 5660: 6.0
To node 5664: 6.0
To node 5665: 4.0
To node 5666: 3.0
To node 5668: 2.0
To node 5669: 6.0
To node 5672: 6.0
To node 5674: 3.0
To node 5675: 8.0
To node 5679: 5.0
To node 5684: 6.0
To node 5685: 7.0
To node 5686: 4.0
To node 5691: 5.0
To node 5692: 8.0
To node 8032: 7.0
To node 5694: 7.0
To node 5695: 7.0
To node 5696: 2.0
To node 5698: 4.0
To node 5699: 5.0
To node 5700: 7.0
To node 5701: 4.0
To node 5702: 8.0
To node 5704: 6.0
To node 5707: 6.0
To node 5710: 5.0
To node 5712: 5.0
To node 5173: 4.0
To node 6258: 3.0
To node 5713: 4.0
To node 5714: 5.0
To node 5715: 4.0
To node 5720: 4.0
To node 5726: 4.0
To node 5727: 5.0
To node 5728: 6.0
To node 5730: 4.0
To node 5731: 7.0
To node 5732: 6.0
To node 5733: 6.0
To node 5735: 5.0
To node 5736: 4.0
To node 5737: 7.0
To node 5208: 6.0
To node 7894: 5.0
To node 5742: 7.0
To node 5743: 5.0
To node 5744: 8.0
To node 5746: 5.0
To node 5747: 4.0
To node 5750: 5.0
To node 5755: 6.0
To node 5761: 6.0
To node 5763: 5.0
To node 5765: 6.0
To node 5766: 8.0
To node 8348: 7.0
To node 5768: 6.0
To node 5769: 6.0
To node 5772: 7.0
To node 6263: 6.0
To node 5150: 5.0
To node 5775: 6.0
To node 5777: 6.0
To node 5779: 3.0
To node 5784: 4.0
To node 5786: 8.0
To node 5792: 6.0
To node 5793: 6.0
To node 5795: 7.0
To node 5796: 6.0
To node 5799: 8.0
To node 5800: 4.0
To node 5801: 4.0
To node 5802: 7.0
To node 5809: 7.0
To node 5813: 4.0
To node 5814: 4.0
To node 5819: 8.0
To node 5823: 6.0
To node 5825: 5.0
To node 5094: 4.0
To node 5828: 4.0
To node 5831: 6.0
To node 5832: 7.0
To node 5833: 6.0
To node 5834: 6.0
To node 5836: 5.0
To node 5840: 6.0
To node 5844: 7.0
To node 5848: 3.0
To node 5849: 7.0
To node 5850: 6.0
To node 5853: 5.0
To node 5856: 5.0
To node 5857: 7.0
To node 5862: 6.0
To node 5866: 6.0
To node 5868: 8.0
To node 5870: 6.0
To node 5871: 7.0
To node 5874: 5.0
To node 5878: 4.0
To node 5880: 6.0
To node 5881: 4.0
To node 5882: 6.0
To node 5883: 4.0
To node 5887: 6.0
To node 5890: 6.0
To node 5891: 7.0
To node 5895: 7.0
To node 5897: 8.0
To node 5898: 5.0
To node 5900: 4.0
To node 5901: 6.0
To node 5902: 6.0
To node 5905: 7.0
To node 5906: 7.0
To node 5907: 4.0
To node 5909: 4.0
To node 5912: 4.0
To node 5913: 7.0
To node 5914: 6.0
To node 5915: 7.0
To node 5919: 6.0
To node 5920: 4.0
To node 5921: 7.0
To node 5926: 5.0
To node 5927: 7.0
To node 5929: 6.0
To node 5930: 5.0
To node 5934: 4.0
To node 5936: 8.0
To node 5940: 5.0
To node 5941: 6.0
To node 5942: 8.0
To node 5945: 6.0
To node 5946: 7.0
To node 5947: 7.0
To node 5948: 6.0
To node 5949: 2.0
To node 5951: 6.0
To node 5952: 4.0
To node 5953: 4.0
To node 5954: 5.0
To node 6823: 4.0
To node 5955: 2.0
To node 5956: 5.0
To node 5957: 4.0
To node 5958: 5.0
To node 5959: 4.0
To node 5960: 5.0
To node 5961: 7.0
To node 5161: 6.0
To node 5962: 6.0
To node 5963: 6.0
To node 5964: 6.0
To node 5116: 5.0
To node 5965: 5.0
To node 7757: 4.0
To node 5966: 5.0
To node 5967: 5.0
To node 5968: 4.0
To node 5969: 5.0
To node 5970: 5.0
To node 5972: 6.0
To node 5973: 6.0
To node 5174: 5.0
To node 5979: 8.0
To node 8226: 7.0
To node 5980: 6.0
To node 5986: 5.0
To node 5987: 5.0
To node 5988: 5.0
To node 5989: 7.0
To node 5992: 4.0
To node 5993: 5.0
To node 5996: 6.0
To node 5999: 8.0
To node 6000: 4.0
To node 5203: 3.0
To node 6824: 2.0
To node 6001: 4.0
To node 6002: 7.0
To node 6003: 6.0
To node 6006: 7.0
To node 6007: 8.0
To node 6008: 5.0
To node 6009: 7.0
To node 6010: 5.0
To node 6011: 7.0
To node 6257: 4.0
To node 6274: 5.0
To node 6276: 5.0
To node 6277: 5.0
To node 6900: 4.0
To node 6278: 5.0
To node 6279: 5.0
To node 6284: 6.0
To node 6285: 6.0
To node 6286: 7.0
To node 6288: 6.0
To node 6289: 2.0
To node 6291: 2.0
To node 6293: 5.0
To node 6295: 5.0
To node 6296: 5.0
To node 6298: 6.0
To node 6299: 8.0
To node 6301: 5.0
To node 6309: 6.0
To node 6311: 8.0
To node 6318: 5.0
To node 6319: 8.0
To node 6320: 5.0
To node 6322: 4.0
To node 6323: 6.0
To node 6327: 6.0
To node 6328: 5.0
To node 6329: 2.0
To node 6330: 5.0
To node 6331: 5.0
To node 6333: 8.0
To node 6334: 4.0
To node 6335: 8.0
To node 6337: 6.0
To node 6339: 5.0
To node 6341: 6.0
To node 6342: 4.0
To node 6346: 7.0
To node 6348: 5.0
To node 6349: 7.0
To node 6350: 8.0
To node 6353: 6.0
To node 6359: 6.0
To node 6360: 5.0
To node 6363: 7.0
To node 6364: 4.0
To node 6366: 4.0
To node 6367: 7.0
To node 6368: 7.0
To node 6369: 7.0
To node 6371: 8.0
To node 6372: 6.0
To node 6373: 6.0
To node 6375: 8.0
To node 6381: 5.0
To node 6383: 8.0
To node 6384: 8.0
To node 6385: 5.0
To node 6387: 7.0
To node 6391: 6.0
To node 6392: 5.0
To node 6397: 8.0
To node 6399: 2.0
To node 6400: 6.0
To node 6401: 8.0
To node 6404: 7.0
To node 6406: 8.0
To node 6407: 6.0
To node 6412: 4.0
To node 6413: 6.0
To node 6415: 7.0
To node 6419: 7.0
To node 6420: 6.0
To node 6422: 8.0
To node 6423: 7.0
To node 6424: 5.0
To node 6425: 5.0
To node 6426: 5.0
To node 6427: 6.0
To node 6428: 3.0
To node 6429: 7.0
To node 6430: 4.0
To node 6432: 7.0
To node 6433: 6.0
To node 6435: 5.0
To node 6436: 6.0
To node 6442: 5.0
To node 6443: 7.0
To node 6445: 7.0
To node 6448: 7.0
To node 6449: 6.0
To node 6451: 6.0
To node 6452: 5.0
To node 6457: 7.0
To node 6459: 6.0
To node 6461: 5.0
To node 6463: 5.0
To node 6464: 6.0
To node 6465: 7.0
To node 5187: 6.0
To node 7407: 5.0
To node 6468: 4.0
To node 6471: 6.0
To node 6473: 6.0
To node 6474: 4.0
To node 6475: 8.0
To node 6476: 5.0
To node 6480: 5.0
To node 6484: 7.0
To node 6485: 7.0
To node 6486: 4.0
To node 6490: 8.0
To node 6493: 8.0
To node 6494: 7.0
To node 6495: 6.0
To node 6497: 7.0
To node 6498: 7.0
To node 6499: 6.0
To node 6503: 5.0
To node 6505: 5.0
To node 6506: 5.0
To node 6507: 6.0
To node 6508: 6.0
To node 6509: 7.0
To node 6511: 6.0
To node 6512: 5.0
To node 6513: 6.0
To node 6517: 7.0
To node 6518: 7.0
To node 6519: 7.0
To node 6520: 3.0
To node 6521: 5.0
To node 6522: 6.0
To node 6527: 6.0
To node 6528: 7.0
To node 6529: 7.0
To node 6532: 6.0
To node 6534: 7.0
To node 6535: 6.0
To node 6536: 8.0
To node 6538: 8.0
To node 6539: 8.0
To node 6540: 4.0
To node 6543: 6.0
To node 6544: 7.0
To node 6545: 6.0
To node 6551: 5.0
To node 6552: 5.0
To node 6554: 7.0
To node 6555: 6.0
To node 6556: 7.0
To node 6557: 6.0
To node 6558: 6.0
To node 6560: 7.0
To node 6561: 7.0
To node 6564: 6.0
To node 6565: 4.0
To node 6566: 6.0
To node 6568: 5.0
To node 6571: 8.0
To node 6572: 5.0
To node 6578: 6.0
To node 6582: 6.0
To node 6586: 7.0
To node 6589: 5.0
To node 6590: 7.0
To node 6591: 3.0
To node 6593: 6.0
To node 6595: 5.0
To node 6596: 4.0
To node 6597: 7.0
To node 6601: 7.0
To node 6603: 6.0
To node 6605: 5.0
To node 6607: 5.0
To node 6609: 6.0
To node 6612: 6.0
To node 6613: 5.0
To node 6614: 5.0
To node 6615: 6.0
To node 6617: 6.0
To node 6623: 7.0
To node 6625: 6.0
To node 6626: 6.0
To node 6627: 6.0
To node 6628: 5.0
To node 6629: 6.0
To node 6630: 8.0
To node 6631: 6.0
To node 6633: 6.0
To node 6635: 3.0
To node 6637: 5.0
To node 6638: 2.0
To node 6639: 7.0
To node 6646: 3.0
To node 6653: 4.0
To node 6655: 5.0
To node 6657: 4.0
To node 6658: 7.0
To node 6659: 7.0
To node 6661: 3.0
To node 6662: 7.0
To node 6663: 6.0
To node 6667: 7.0
To node 6669: 7.0
To node 6670: 2.0
To node 6673: 4.0
To node 6674: 6.0
To node 6675: 3.0
To node 6679: 7.0
To node 6682: 5.0
To node 6683: 6.0
To node 6684: 5.0
To node 6686: 3.0
To node 6687: 7.0
To node 6689: 6.0
To node 6690: 5.0
To node 6692: 5.0
To node 6693: 6.0
To node 6702: 6.0
To node 6704: 6.0
To node 6708: 6.0
To node 6709: 6.0
To node 6710: 4.0
To node 6711: 3.0
To node 6715: 6.0
To node 6717: 6.0
To node 6718: 8.0
To node 6722: 6.0
To node 6723: 5.0
To node 6729: 5.0
To node 6733: 6.0
To node 6272: 5.0
To node 6736: 6.0
To node 6738: 3.0
To node 6742: 7.0
To node 6743: 6.0
To node 6745: 7.0
To node 6750: 6.0
To node 6751: 7.0
To node 6753: 6.0
To node 6757: 7.0
To node 6764: 3.0
To node 6769: 6.0
To node 6771: 7.0
To node 6772: 6.0
To node 6775: 5.0
To node 6776: 7.0
To node 6779: 6.0
To node 6780: 7.0
To node 6783: 7.0
To node 6785: 6.0
To node 6787: 4.0
To node 6794: 6.0
To node 6795: 5.0
To node 6796: 7.0
To node 6798: 4.0
To node 6799: 6.0
To node 6803: 6.0
To node 6805: 6.0
To node 6809: 6.0
To node 6810: 6.0
To node 6812: 3.0
To node 6815: 8.0
To node 6817: 8.0
To node 6818: 5.0
To node 6819: 5.0
To node 6820: 6.0
To node 6825: 6.0
To node 6826: 7.0
To node 6829: 7.0
To node 6830: 4.0
To node 6833: 3.0
To node 6835: 6.0
To node 6836: 7.0
To node 6843: 7.0
To node 6844: 6.0
To node 6845: 7.0
To node 6847: 8.0
To node 6848: 5.0
To node 6849: 4.0
To node 6850: 6.0
To node 6852: 6.0
To node 6853: 5.0
To node 6854: 6.0
To node 6856: 4.0
To node 6858: 8.0
To node 6859: 5.0
To node 6861: 7.0
To node 6862: 4.0
To node 6867: 7.0
To node 6869: 6.0
To node 6870: 7.0
To node 6871: 6.0
To node 6872: 7.0
To node 6876: 7.0
To node 6879: 7.0
To node 6881: 4.0
To node 6882: 5.0
To node 6883: 5.0
To node 6884: 6.0
To node 6886: 3.0
To node 6888: 7.0
To node 6898: 7.0
To node 6899: 4.0
To node 6901: 7.0
To node 6903: 6.0
To node 6905: 6.0
To node 6911: 6.0
To node 6914: 6.0
To node 6916: 5.0
To node 6918: 7.0
To node 6920: 4.0
To node 6921: 6.0
To node 6923: 7.0
To node 6928: 5.0
To node 6929: 5.0
To node 6930: 7.0
To node 6932: 7.0
To node 6935: 7.0
To node 6936: 5.0
To node 6938: 5.0
To node 6940: 6.0
To node 6942: 4.0
To node 6944: 6.0
To node 6945: 7.0
To node 6949: 6.0
To node 6950: 5.0
To node 6951: 6.0
To node 6952: 5.0
To node 6957: 5.0
To node 6960: 7.0
To node 6961: 7.0
To node 6966: 7.0
To node 6970: 4.0
To node 6971: 2.0
To node 6972: 5.0
To node 6974: 4.0
To node 6975: 7.0
To node 6982: 6.0
To node 6985: 4.0
To node 6988: 6.0
To node 6989: 7.0
To node 6990: 6.0
To node 6992: 5.0
To node 6993: 3.0
To node 6995: 7.0
To node 6999: 7.0
To node 7000: 6.0
To node 7005: 7.0
To node 7010: 6.0
To node 7011: 8.0
To node 7012: 4.0
To node 7013: 6.0
To node 7015: 5.0
To node 7016: 5.0
To node 7017: 8.0
To node 7018: 7.0
To node 7019: 7.0
To node 7020: 6.0
To node 7023: 5.0
To node 7024: 6.0
To node 7025: 7.0
To node 7028: 8.0
To node 7032: 5.0
To node 7036: 3.0
To node 7037: 6.0
To node 7040: 6.0
To node 7041: 5.0
To node 7045: 6.0
To node 7046: 6.0
To node 7050: 7.0
To node 7051: 6.0
To node 7056: 7.0
To node 7060: 5.0
To node 7061: 6.0
To node 7063: 6.0
To node 7064: 2.0
To node 7067: 6.0
To node 7069: 8.0
To node 7073: 5.0
To node 7079: 6.0
To node 7087: 5.0
To node 7091: 6.0
To node 7093: 7.0
To node 7100: 4.0
To node 7101: 6.0
To node 7102: 5.0
To node 7105: 7.0
To node 7106: 6.0
To node 7107: 6.0
To node 7110: 6.0
To node 7112: 5.0
To node 7113: 7.0
To node 7114: 6.0
To node 7115: 4.0
To node 7116: 5.0
To node 7117: 8.0
To node 7119: 6.0
To node 7120: 7.0
To node 7122: 5.0
To node 7123: 6.0
To node 7126: 6.0
To node 7127: 6.0
To node 7128: 6.0
To node 7130: 7.0
To node 7132: 7.0
To node 7135: 4.0
To node 7136: 8.0
To node 7138: 5.0
To node 7139: 6.0
To node 7141: 6.0
To node 7142: 6.0
To node 7143: 6.0
To node 7145: 7.0
To node 7148: 7.0
To node 7150: 6.0
To node 7151: 8.0
To node 7152: 6.0
To node 7153: 8.0
To node 7157: 4.0
To node 7159: 4.0
To node 7163: 6.0
To node 7164: 8.0
To node 7166: 6.0
To node 7168: 5.0
To node 7169: 7.0
To node 7170: 7.0
To node 7172: 6.0
To node 7173: 5.0
To node 7177: 4.0
To node 7178: 6.0
To node 7183: 6.0
To node 7184: 5.0
To node 7185: 5.0
To node 7187: 6.0
To node 7189: 6.0
To node 7190: 6.0
To node 7192: 6.0
To node 7196: 6.0
To node 7197: 4.0
To node 7199: 3.0
To node 7202: 6.0
To node 7204: 6.0
To node 7206: 6.0
To node 7207: 8.0
To node 7209: 7.0
To node 7210: 6.0
To node 7213: 7.0
To node 7216: 7.0
To node 7217: 5.0
To node 7223: 5.0
To node 7225: 5.0
To node 7230: 8.0
To node 7232: 5.0
To node 7236: 5.0
To node 7238: 7.0
To node 7239: 2.0
To node 7242: 5.0
To node 7245: 6.0
To node 7248: 8.0
To node 7254: 6.0
To node 7255: 4.0
To node 7257: 6.0
To node 7259: 7.0
To node 7260: 7.0
To node 7261: 7.0
To node 7262: 5.0
To node 7264: 6.0
To node 7265: 6.0
To node 7268: 4.0
To node 7269: 8.0
To node 7270: 6.0
To node 7274: 6.0
To node 7275: 4.0
To node 7284: 7.0
To node 7285: 6.0
To node 7287: 6.0
To node 7290: 6.0
To node 7291: 7.0
To node 7292: 5.0
To node 7293: 4.0
To node 7295: 8.0
To node 7298: 6.0
To node 7299: 5.0
To node 7300: 3.0
To node 7301: 6.0
To node 7305: 6.0
To node 7308: 5.0
To node 7309: 8.0
To node 7310: 6.0
To node 7311: 6.0
To node 7312: 8.0
To node 7317: 6.0
To node 7318: 7.0
To node 7319: 7.0
To node 7321: 6.0
To node 7323: 8.0
To node 7324: 8.0
To node 7325: 7.0
To node 7327: 5.0
To node 7328: 4.0
To node 7329: 7.0
To node 7332: 7.0
To node 7334: 2.0
To node 7335: 6.0
To node 7339: 4.0
To node 7340: 6.0
To node 7341: 7.0
To node 7342: 7.0
To node 7343: 5.0
To node 7347: 3.0
To node 7350: 6.0
To node 7351: 7.0
To node 7352: 5.0
To node 7361: 6.0
To node 7365: 4.0
To node 7367: 7.0
To node 7368: 8.0
To node 7370: 6.0
To node 7372: 7.0
To node 7373: 3.0
To node 7374: 6.0
To node 7384: 6.0
To node 7386: 8.0
To node 7387: 3.0
To node 7388: 5.0
To node 7391: 5.0
To node 7392: 6.0
To node 7393: 6.0
To node 7394: 4.0
To node 7398: 8.0
To node 7399: 6.0
To node 7402: 6.0
To node 7403: 6.0
To node 7408: 8.0
To node 7409: 5.0
To node 7410: 6.0
To node 7411: 6.0
To node 7413: 6.0
To node 7415: 6.0
To node 7420: 7.0
To node 7421: 6.0
To node 7422: 6.0
To node 7423: 4.0
To node 7424: 7.0
To node 7426: 7.0
To node 7427: 5.0
To node 7434: 7.0
To node 7435: 8.0
To node 7437: 8.0
To node 7438: 6.0
To node 7440: 5.0
To node 7441: 5.0
To node 7442: 4.0
To node 7443: 5.0
To node 7444: 2.0
To node 7447: 6.0
To node 7449: 8.0
To node 7450: 6.0
To node 7451: 6.0
To node 7452: 7.0
To node 7454: 7.0
To node 7455: 5.0
To node 7456: 6.0
To node 7457: 7.0
To node 7459: 7.0
To node 7461: 7.0
To node 7462: 7.0
To node 7463: 4.0
To node 7464: 6.0
To node 7469: 7.0
To node 7470: 4.0
To node 9999: 20.0

In [160]:
shortest_distances

{5210: 0,
 5179: 1.0,
 6271: 2.0,
 5: 3.0,
 5211: 8.0,
 8246: 7.0,
 8205: 6.0,
 8361: 5.0,
 5196: 4.0,
 5177: 3.0,
 5212: 5.0,
 8153: 4.0,
 5186: 3.0,
 7522: 4.0,
 5175: 3.0,
 5554: 4.0,
 5213: 5.0,
 5180: 4.0,
 5222: 8.0,
 8129: 7.0,
 5206: 6.0,
 7721: 5.0,
 5223: 4.0,
 5184: 3.0,
 5974: 4.0,
 5224: 7.0,
 8250: 6.0,
 5188: 5.0,
 6889: 4.0,
 5225: 3.0,
 8351: 2.0,
 5230: 6.0,
 5200: 5.0,
 5785: 4.0,
 5237: 7.0,
 8326: 6.0,
 5192: 5.0,
 5400: 4.0,
 5238: 6.0,
 5239: 6.0,
 8111: 5.0,
 5198: 4.0,
 5240: 3.0,
 5209: 2.0,
 5241: 6.0,
 5194: 5.0,
 6998: 4.0,
 5178: 3.0,
 5243: 5.0,
 8270: 4.0,
 5244: 8.0,
 8126: 7.0,
 8158: 6.0,
 5248: 6.0,
 5183: 5.0,
 6275: 4.0,
 5950: 3.0,
 5249: 7.0,
 8346: 6.0,
 5190: 5.0,
 5250: 5.0,
 6264: 4.0,
 5483: 2.0,
 5251: 5.0,
 8157: 4.0,
 5252: 5.0,
 7995: 4.0,
 5202: 3.0,
 6280: 2.0,
 5253: 7.0,
 8355: 6.0,
 6259: 5.0,
 5168: 4.0,
 5255: 6.0,
 5258: 5.0,
 5261: 5.0,
 5185: 4.0,
 7108: 3.0,
 5262: 6.0,
 5195: 5.0,
 5399: 4.0,
 5263: 6.0,
 5207: 5.0,
 5593: 4.0,
 5264: 6.0,
 5092: 5.0,
 5265: 6.0,
 5182: 5.0,
 7927: 4.0,
 5266: 8.0,
 8280: 7.0,
 5325: 4.0,
 5267: 6.0,
 5268: 6.0,
 5270: 5.0,
 5271: 6.0,
 5273: 5.0,
 5274: 6.0,
 5275: 6.0,
 8017: 5.0,
 5276: 7.0,
 8180: 6.0,
 5278: 7.0,
 5279: 5.0,
 5283: 4.0,
 5284: 6.0,
 5287: 6.0,
 5289: 8.0,
 8227: 7.0,
 5295: 6.0,
 5181: 5.0,
 5299: 6.0,
 5301: 5.0,
 5302: 5.0,
 5304: 7.0,
 5307: 4.0,
 5308: 7.0,
 6261: 6.0,
 5164: 5.0,
 5311: 4.0,
 5314: 6.0,
 5315: 6.0,
 5317: 5.0,
 5318: 5.0,
 5320: 4.0,
 5322: 5.0,
 5323: 5.0,
 5324: 4.0,
 5327: 6.0,
 8154: 5.0,
 5205: 4.0,
 5330: 6.0,
 5335: 7.0,
 6262: 6.0,
 5147: 5.0,
 5336: 3.0,
 5338: 4.0,
 5340: 3.0,
 5341: 8.0,
 5343: 8.0,
 5344: 7.0,
 8202: 6.0,
 5348: 7.0,
 5128: 6.0,
 5978: 5.0,
 6017: 4.0,
 5349: 8.0,
 5351: 5.0,
 5358: 6.0,
 5360: 5.0,
 5361: 8.0,
 5364: 6.0,
 5365: 7.0,
 8219: 6.0,
 5367: 6.0,
 5191: 5.0,
 6396: 4.0,
 5368: 8.0,
 8263: 7.0,
 5371: 6.0,
 8115: 5.0,
 5372: 4.0,
 5373: 6.0,
 5197: 5.0,
 7227: 4.0,
 5374: 6.0,
 5375: 4.0,
 5376: 4.0,
 5377: 6.0,
 5378: 4.0,
 5380: 8.0,
 5381: 6.0,
 5382: 7.0,
 8189: 6.0,
 5383: 5.0,
 5384: 3.0,
 5385: 6.0,
 5386: 6.0,
 5389: 5.0,
 5390: 7.0,
 5391: 6.0,
 5394: 6.0,
 5201: 5.0,
 7191: 4.0,
 5402: 3.0,
 5406: 8.0,
 8287: 7.0,
 5407: 6.0,
 5408: 6.0,
 5413: 6.0,
 5415: 5.0,
 5416: 6.0,
 5417: 3.0,
 5421: 6.0,
 5424: 3.0,
 5427: 5.0,
 5430: 8.0,
 5432: 7.0,
 5434: 7.0,
 5436: 6.0,
 5440: 4.0,
 5441: 6.0,
 5444: 6.0,
 5189: 5.0,
 5445: 6.0,
 5446: 6.0,
 5447: 4.0,
 5448: 6.0,
 6734: 4.0,
 5449: 8.0,
 5451: 7.0,
 5830: 6.0,
 5454: 5.0,
 5456: 6.0,
 5457: 6.0,
 5458: 6.0,
 5459: 5.0,
 5463: 7.0,
 5464: 5.0,
 5465: 3.0,
 5466: 6.0,
 5469: 8.0,
 5470: 6.0,
 5472: 6.0,
 5473: 5.0,
 5474: 6.0,
 5476: 6.0,
 5478: 6.0,
 5481: 5.0,
 5482: 7.0,
 5484: 7.0,
 5486: 8.0,
 5487: 2.0,
 5488: 4.0,
 5492: 7.0,
 5495: 8.0,
 5497: 3.0,
 5500: 6.0,
 7583: 4.0,
 5504: 3.0,
 5505: 5.0,
 6260: 4.0,
 5510: 6.0,
 5512: 4.0,
 5515: 5.0,
 5516: 6.0,
 5864: 5.0,
 5517: 7.0,
 8358: 6.0,
 5520: 5.0,
 6868: 4.0,
 5524: 6.0,
 5529: 3.0,
 5531: 2.0,
 5532: 5.0,
 5537: 4.0,
 5539: 6.0,
 5540: 7.0,
 5542: 5.0,
 5545: 6.0,
 5546: 6.0,
 5547: 5.0,
 5549: 3.0,
 5550: 7.0,
 5552: 6.0,
 5553: 7.0,
 5555: 4.0,
 5557: 6.0,
 5559: 6.0,
 5561: 4.0,
 5562: 6.0,
 5563: 5.0,
 5565: 6.0,
 5566: 4.0,
 5569: 3.0,
 5570: 5.0,
 5572: 6.0,
 8276: 5.0,
 5573: 7.0,
 5576: 7.0,
 5199: 6.0,
 5739: 5.0,
 5577: 5.0,
 6456: 4.0,
 5578: 6.0,
 5579: 6.0,
 5580: 7.0,
 5581: 5.0,
 5584: 7.0,
 5586: 7.0,
 5588: 6.0,
 5590: 6.0,
 5591: 6.0,
 5594: 6.0,
 5595: 5.0,
 5598: 4.0,
 5602: 6.0,
 5607: 5.0,
 5609: 8.0,
 5612: 6.0,
 5613: 5.0,
 5615: 5.0,
 5616: 3.0,
 5618: 4.0,
 5622: 8.0,
 5624: 6.0,
 5625: 4.0,
 5628: 6.0,
 5630: 8.0,
 5632: 6.0,
 5633: 7.0,
 5636: 6.0,
 5637: 7.0,
 5639: 8.0,
 8108: 7.0,
 5640: 8.0,
 5641: 7.0,
 5644: 5.0,
 5645: 6.0,
 5646: 4.0,
 5647: 5.0,
 5648: 5.0,
 5649: 5.0,
 5651: 7.0,
 5656: 6.0,
 5132: 5.0,
 5658: 8.0,
 5659: 5.0,
 5660: 6.0,
 5664: 6.0,
 5665: 4.0,
 5666: 3.0,
 5668: 2.0,
 5669: 6.0,
 5672: 6.0,
 5674: 3.0,
 5675: 8.0,
 5679: 5.0,
 5684: 6.0,
 5685: 7.0,
 5686: 4.0,
 5691: 5.0,
 5692: 8.0,
 8032: 7.0,
 5694: 7.0,
 5695: 7.0,
 5696: 2.0,
 5698: 4.0,
 5699: 5.0,
 5700: 7.0,
 5701: 4.0,
 5702: 8.0,
 5704: 6.0,
 5707: 6.0,
 5710: 5.0,
 5712: 5.0,
 5173: 4.0,
 6258: 3.0,
 5713: 4.0,
 5714: 5.0,
 5715: 4.0,
 5720: 4.0,
 5726: 4.0,
 5727: 5.0,
 5728: 6.0,
 5730: 4.0,
 5731: 7.0,
 5732: 6.0,
 5733: 6.0,
 5735: 5.0,
 5736: 4.0,
 5737: 7.0,
 5208: 6.0,
 7894: 5.0,
 5742: 7.0,
 5743: 5.0,
 5744: 8.0,
 5746: 5.0,
 5747: 4.0,
 5750: 5.0,
 5755: 6.0,
 5761: 6.0,
 5763: 5.0,
 5765: 6.0,
 5766: 8.0,
 8348: 7.0,
 5768: 6.0,
 5769: 6.0,
 5772: 7.0,
 6263: 6.0,
 5150: 5.0,
 5775: 6.0,
 5777: 6.0,
 5779: 3.0,
 5784: 4.0,
 5786: 8.0,
 5792: 6.0,
 5793: 6.0,
 5795: 7.0,
 5796: 6.0,
 5799: 8.0,
 5800: 4.0,
 5801: 4.0,
 5802: 7.0,
 5809: 7.0,
 5813: 4.0,
 5814: 4.0,
 5819: 8.0,
 5823: 6.0,
 5825: 5.0,
 5094: 4.0,
 5828: 4.0,
 5831: 6.0,
 5832: 7.0,
 5833: 6.0,
 5834: 6.0,
 5836: 5.0,
 5840: 6.0,
 5844: 7.0,
 5848: 3.0,
 5849: 7.0,
 5850: 6.0,
 5853: 5.0,
 5856: 5.0,
 5857: 7.0,
 5862: 6.0,
 5866: 6.0,
 5868: 8.0,
 5870: 6.0,
 5871: 7.0,
 5874: 5.0,
 5878: 4.0,
 5880: 6.0,
 5881: 4.0,
 5882: 6.0,
 5883: 4.0,
 5887: 6.0,
 5890: 6.0,
 5891: 7.0,
 5895: 7.0,
 5897: 8.0,
 5898: 5.0,
 5900: 4.0,
 5901: 6.0,
 5902: 6.0,
 5905: 7.0,
 5906: 7.0,
 5907: 4.0,
 5909: 4.0,
 5912: 4.0,
 5913: 7.0,
 5914: 6.0,
 5915: 7.0,
 5919: 6.0,
 5920: 4.0,
 5921: 7.0,
 5926: 5.0,
 5927: 7.0,
 5929: 6.0,
 5930: 5.0,
 5934: 4.0,
 5936: 8.0,
 5940: 5.0,
 5941: 6.0,
 5942: 8.0,
 5945: 6.0,
 5946: 7.0,
 5947: 7.0,
 5948: 6.0,
 5949: 2.0,
 5951: 6.0,
 5952: 4.0,
 5953: 4.0,
 5954: 5.0,
 6823: 4.0,
 5955: 2.0,
 5956: 5.0,
 5957: 4.0,
 5958: 5.0,
 5959: 4.0,
 5960: 5.0,
 5961: 7.0,
 5161: 6.0,
 5962: 6.0,
 5963: 6.0,
 5964: 6.0,
 5116: 5.0,
 5965: 5.0,
 7757: 4.0,
 5966: 5.0,
 5967: 5.0,
 5968: 4.0,
 5969: 5.0,
 5970: 5.0,
 5972: 6.0,
 5973: 6.0,
 5174: 5.0,
 5979: 8.0,
 8226: 7.0,
 5980: 6.0,
 5986: 5.0,
 5987: 5.0,
 5988: 5.0,
 5989: 7.0,
 5992: 4.0,
 5993: 5.0,
 5996: 6.0,
 5999: 8.0,
 6000: 4.0,
 5203: 3.0,
 6824: 2.0,
 6001: 4.0,
 6002: 7.0,
 6003: 6.0,
 6006: 7.0,
 6007: 8.0,
 6008: 5.0,
 6009: 7.0,
 6010: 5.0,
 6011: 7.0,
 6257: 4.0,
 6274: 5.0,
 6276: 5.0,
 6277: 5.0,
 6900: 4.0,
 6278: 5.0,
 6279: 5.0,
 6284: 6.0,
 6285: 6.0,
 6286: 7.0,
 6288: 6.0,
 6289: 2.0,
 6291: 2.0,
 6293: 5.0,
 6295: 5.0,
 6296: 5.0,
 6298: 6.0,
 6299: 8.0,
 6301: 5.0,
 6309: 6.0,
 6311: 8.0,
 6318: 5.0,
 6319: 8.0,
 6320: 5.0,
 6322: 4.0,
 6323: 6.0,
 6327: 6.0,
 6328: 5.0,
 6329: 2.0,
 6330: 5.0,
 6331: 5.0,
 6333: 8.0,
 6334: 4.0,
 6335: 8.0,
 6337: 6.0,
 6339: 5.0,
 6341: 6.0,
 6342: 4.0,
 6346: 7.0,
 6348: 5.0,
 6349: 7.0,
 6350: 8.0,
 6353: 6.0,
 6359: 6.0,
 6360: 5.0,
 6363: 7.0,
 6364: 4.0,
 6366: 4.0,
 6367: 7.0,
 6368: 7.0,
 6369: 7.0,
 6371: 8.0,
 6372: 6.0,
 6373: 6.0,
 6375: 8.0,
 6381: 5.0,
 6383: 8.0,
 6384: 8.0,
 6385: 5.0,
 6387: 7.0,
 6391: 6.0,
 6392: 5.0,
 6397: 8.0,
 6399: 2.0,
 6400: 6.0,
 6401: 8.0,
 6404: 7.0,
 6406: 8.0,
 6407: 6.0,
 6412: 4.0,
 6413: 6.0,
 6415: 7.0,
 6419: 7.0,
 6420: 6.0,
 6422: 8.0,
 6423: 7.0,
 6424: 5.0,
 6425: 5.0,
 6426: 5.0,
 6427: 6.0,
 6428: 3.0,
 6429: 7.0,
 6430: 4.0,
 6432: 7.0,
 6433: 6.0,
 6435: 5.0,
 6436: 6.0,
 6442: 5.0,
 6443: 7.0,
 6445: 7.0,
 6448: 7.0,
 6449: 6.0,
 6451: 6.0,
 6452: 5.0,
 6457: 7.0,
 6459: 6.0,
 6461: 5.0,
 6463: 5.0,
 6464: 6.0,
 6465: 7.0,
 5187: 6.0,
 7407: 5.0,
 6468: 4.0,
 6471: 6.0,
 6473: 6.0,
 6474: 4.0,
 6475: 8.0,
 6476: 5.0,
 6480: 5.0,
 6484: 7.0,
 6485: 7.0,
 6486: 4.0,
 6490: 8.0,
 6493: 8.0,
 6494: 7.0,
 6495: 6.0,
 6497: 7.0,
 6498: 7.0,
 6499: 6.0,
 6503: 5.0,
 6505: 5.0,
 6506: 5.0,
 6507: 6.0,
 6508: 6.0,
 6509: 7.0,
 6511: 6.0,
 6512: 5.0,
 6513: 6.0,
 6517: 7.0,
 6518: 7.0,
 6519: 7.0,
 6520: 3.0,
 6521: 5.0,
 6522: 6.0,
 6527: 6.0,
 6528: 7.0,
 6529: 7.0,
 6532: 6.0,
 6534: 7.0,
 6535: 6.0,
 6536: 8.0,
 6538: 8.0,
 6539: 8.0,
 6540: 4.0,
 6543: 6.0,
 6544: 7.0,
 6545: 6.0,
 6551: 5.0,
 6552: 5.0,
 6554: 7.0,
 6555: 6.0,
 6556: 7.0,
 6557: 6.0,
 6558: 6.0,
 6560: 7.0,
 6561: 7.0,
 6564: 6.0,
 6565: 4.0,
 6566: 6.0,
 6568: 5.0,
 6571: 8.0,
 6572: 5.0,
 6578: 6.0,
 6582: 6.0,
 6586: 7.0,
 6589: 5.0,
 6590: 7.0,
 6591: 3.0,
 6593: 6.0,
 6595: 5.0,
 6596: 4.0,
 6597: 7.0,
 6601: 7.0,
 6603: 6.0,
 6605: 5.0,
 6607: 5.0,
 6609: 6.0,
 6612: 6.0,
 6613: 5.0,
 6614: 5.0,
 6615: 6.0,
 6617: 6.0,
 6623: 7.0,
 6625: 6.0,
 6626: 6.0,
 6627: 6.0,
 6628: 5.0,
 6629: 6.0,
 6630: 8.0,
 6631: 6.0,
 6633: 6.0,
 6635: 3.0,
 6637: 5.0,
 6638: 2.0,
 6639: 7.0,
 6646: 3.0,
 6653: 4.0,
 6655: 5.0,
 6657: 4.0,
 6658: 7.0,
 6659: 7.0,
 6661: 3.0,
 6662: 7.0,
 6663: 6.0,
 6667: 7.0,
 6669: 7.0,
 6670: 2.0,
 6673: 4.0,
 6674: 6.0,
 6675: 3.0,
 6679: 7.0,
 6682: 5.0,
 6683: 6.0,
 6684: 5.0,
 6686: 3.0,
 6687: 7.0,
 6689: 6.0,
 6690: 5.0,
 6692: 5.0,
 6693: 6.0,
 6702: 6.0,
 6704: 6.0,
 6708: 6.0,
 6709: 6.0,
 6710: 4.0,
 6711: 3.0,
 6715: 6.0,
 6717: 6.0,
 6718: 8.0,
 6722: 6.0,
 6723: 5.0,
 6729: 5.0,
 6733: 6.0,
 6272: 5.0,
 6736: 6.0,
 6738: 3.0,
 6742: 7.0,
 6743: 6.0,
 6745: 7.0,
 6750: 6.0,
 6751: 7.0,
 6753: 6.0,
 6757: 7.0,
 6764: 3.0,
 6769: 6.0,
 6771: 7.0,
 6772: 6.0,
 6775: 5.0,
 6776: 7.0,
 6779: 6.0,
 6780: 7.0,
 6783: 7.0,
 6785: 6.0,
 6787: 4.0,
 6794: 6.0,
 6795: 5.0,
 6796: 7.0,
 6798: 4.0,
 6799: 6.0,
 6803: 6.0,
 6805: 6.0,
 6809: 6.0,
 6810: 6.0,
 6812: 3.0,
 6815: 8.0,
 6817: 8.0,
 6818: 5.0,
 6819: 5.0,
 6820: 6.0,
 6825: 6.0,
 6826: 7.0,
 6829: 7.0,
 6830: 4.0,
 6833: 3.0,
 6835: 6.0,
 6836: 7.0,
 6843: 7.0,
 6844: 6.0,
 6845: 7.0,
 6847: 8.0,
 6848: 5.0,
 6849: 4.0,
 6850: 6.0,
 6852: 6.0,
 6853: 5.0,
 6854: 6.0,
 6856: 4.0,
 6858: 8.0,
 6859: 5.0,
 6861: 7.0,
 6862: 4.0,
 6867: 7.0,
 6869: 6.0,
 6870: 7.0,
 6871: 6.0,
 6872: 7.0,
 6876: 7.0,
 6879: 7.0,
 6881: 4.0,
 6882: 5.0,
 6883: 5.0,
 6884: 6.0,
 6886: 3.0,
 6888: 7.0,
 6898: 7.0,
 6899: 4.0,
 6901: 7.0,
 6903: 6.0,
 6905: 6.0,
 6911: 6.0,
 6914: 6.0,
 6916: 5.0,
 6918: 7.0,
 6920: 4.0,
 6921: 6.0,
 6923: 7.0,
 6928: 5.0,
 6929: 5.0,
 6930: 7.0,
 6932: 7.0,
 6935: 7.0,
 6936: 5.0,
 6938: 5.0,
 6940: 6.0,
 6942: 4.0,
 6944: 6.0,
 6945: 7.0,
 6949: 6.0,
 6950: 5.0,
 6951: 6.0,
 6952: 5.0,
 6957: 5.0,
 6960: 7.0,
 6961: 7.0,
 6966: 7.0,
 6970: 4.0,
 6971: 2.0,
 6972: 5.0,
 6974: 4.0,
 6975: 7.0,
 6982: 6.0,
 6985: 4.0,
 6988: 6.0,
 6989: 7.0,
 6990: 6.0,
 6992: 5.0,
 6993: 3.0,
 6995: 7.0,
 6999: 7.0,
 7000: 6.0,
 7005: 7.0,
 7010: 6.0,
 7011: 8.0,
 7012: 4.0,
 7013: 6.0,
 7015: 5.0,
 7016: 5.0,
 7017: 8.0,
 7018: 7.0,
 7019: 7.0,
 7020: 6.0,
 7023: 5.0,
 7024: 6.0,
 7025: 7.0,
 7028: 8.0,
 7032: 5.0,
 7036: 3.0,
 7037: 6.0,
 7040: 6.0,
 7041: 5.0,
 7045: 6.0,
 7046: 6.0,
 7050: 7.0,
 7051: 6.0,
 7056: 7.0,
 7060: 5.0,
 7061: 6.0,
 7063: 6.0,
 7064: 2.0,
 7067: 6.0,
 7069: 8.0,
 7073: 5.0,
 7079: 6.0,
 7087: 5.0,
 7091: 6.0,
 7093: 7.0,
 7100: 4.0,
 7101: 6.0,
 7102: 5.0,
 7105: 7.0,
 7106: 6.0,
 7107: 6.0,
 7110: 6.0,
 7112: 5.0,
 7113: 7.0,
 7114: 6.0,
 7115: 4.0,
 7116: 5.0,
 7117: 8.0,
 7119: 6.0,
 7120: 7.0,
 7122: 5.0,
 7123: 6.0,
 7126: 6.0,
 7127: 6.0,
 7128: 6.0,
 7130: 7.0,
 7132: 7.0,
 7135: 4.0,
 7136: 8.0,
 7138: 5.0,
 7139: 6.0,
 7141: 6.0,
 7142: 6.0,
 7143: 6.0,
 7145: 7.0,
 7148: 7.0,
 7150: 6.0,
 7151: 8.0,
 7152: 6.0,
 7153: 8.0,
 7157: 4.0,
 7159: 4.0,
 7163: 6.0,
 7164: 8.0,
 7166: 6.0,
 7168: 5.0,
 7169: 7.0,
 7170: 7.0,
 7172: 6.0,
 7173: 5.0,
 7177: 4.0,
 7178: 6.0,
 7183: 6.0,
 7184: 5.0,
 7185: 5.0,
 7187: 6.0,
 7189: 6.0,
 7190: 6.0,
 7192: 6.0,
 7196: 6.0,
 7197: 4.0,
 7199: 3.0,
 7202: 6.0,
 7204: 6.0,
 7206: 6.0,
 7207: 8.0,
 7209: 7.0,
 7210: 6.0,
 7213: 7.0,
 7216: 7.0,
 7217: 5.0,
 7223: 5.0,
 7225: 5.0,
 7230: 8.0,
 7232: 5.0,
 7236: 5.0,
 7238: 7.0,
 7239: 2.0,
 7242: 5.0,
 7245: 6.0,
 7248: 8.0,
 7254: 6.0,
 7255: 4.0,
 7257: 6.0,
 7259: 7.0,
 7260: 7.0,
 7261: 7.0,
 7262: 5.0,
 7264: 6.0,
 7265: 6.0,
 7268: 4.0,
 7269: 8.0,
 7270: 6.0,
 7274: 6.0,
 7275: 4.0,
 7284: 7.0,
 7285: 6.0,
 7287: 6.0,
 7290: 6.0,
 ...}

In [162]:
# prompt: find the 2nd highest value  in shortest_distances and print out the source, target and the distance

# Convert the shortest_distances dictionary to a list of (distance, target_node) tuples
distances_list = [(distance, target_node) for target_node, distance in shortest_distances.items() if distance != float('inf')]

# Sort the list in descending order based on distance
distances_list.sort(reverse=True)

# Check if there are at least two distinct distances
if len(distances_list) >= 2:
    # The second highest distance is the second element in the sorted list
    second_highest_distance, second_highest_target_node = distances_list[1]

    # Find the edge(s) in the original DataFrame that have this target node and distance
    # We need to find an edge where the target matches and the distance from the start_node
    # to that target node is the second highest. This might involve looking back at the
    # paths, but for simplicity, we can find an edge *connected* to this target node
    # which was likely part of the path. It's hard to definitively link a single edge
    # to a shortest path distance without tracking predecessors in Dijkstra.

    # A simpler approach is to find an edge connected to the target node.
    # Let's find the edge(s) where the target is the second_highest_target_node.
    # This doesn't guarantee it was the edge used in the shortest path but will give
    # us an edge involving the target node.
    edges_to_second_highest = new_edges_df[new_edges_df['target'] == second_highest_target_node]

    if not edges_to_second_highest.empty:
        # Take the first such edge found
        edge_info = edges_to_second_highest.iloc[0]
        source_of_edge = edge_info['source']
        target_of_edge = edge_info['target']
        weight_of_edge = edge_info['Weight'] # This is the weight of this specific edge, not the shortest path distance

        print(f"\nSecond highest shortest distance:")
        print(f"  Target Node: {second_highest_target_node}")
        print(f"  Shortest Distance from Start Node ({start_node}): {second_highest_distance}")
        # Print information about an edge connected to this target node
        print(f"  Example Edge connected to target node: Source={source_of_edge}, Target={target_of_edge}, Edge Weight={weight_of_edge}")
    else:
        print(f"\nSecond highest shortest distance is to node {second_highest_target_node} with distance {second_highest_distance}, but no edge found in DataFrame with this target node.")

elif len(distances_list) == 1:
    print("\nOnly one reachable node found other than the start node.")
else:
    print("\nNo reachable nodes found other than the start node.")

Second highest shortest distance is to node 7449 with distance 8.0, but no edge found in DataFrame with this target node.