<a href="https://colab.research.google.com/github/markajbell/BH/blob/main/ImportADSynth_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [1]:
import pandas as pd
import json
import os
import glob

Set the Path to the Data location (imported form SharpHound)

# Set the Path
to the Data location (imported from SharpHound) and Read json files in folder and create a dictionary with the entire data.

In [2]:
#@title Download lab files
# from IPython.display import clear_output
# if not os.path.exists("/content/mylab"):
#   print("Downloading lab files...")
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_computers.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_containers.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_domains.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_gpos.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_groups.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_ous.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_users.json
#   !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab.zip
#   !unzip mylab.zip -d mylab
#   clear_output()
#   print("Done")
!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/adsync/secure.json
#!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/adsync/secure10k.json
# else:
#   print("Lab files already downloaded")
!mkdir = "/content/adsync"
!mv secure.json /content/adsync
#!mv secure10k.json /content/adsync

path = "/content/adsync"
data = {}
json_files = glob.glob(os.path.join(path, "*.json"))
for file in json_files:
    filename = os.path.basename(file).replace(".json", "")
    suf = filename.split("_")[-1]

    with open(file, 'r', encoding='utf-8') as f:
        content = json.load(f)

    if "data" in content:
        if suf in data:
            data[f"{suf}"].extend(content["data"])
            #print(f" The key 'data' was found in {f}.")
        else:
            data[f"{suf}"] = content["data"]
            #print(f" The key 'data' was found in {f}.")
    else:
        print(f"Warning: The key 'data' was not found in {f}.")

--2025-06-17 12:29:11--  https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/adsync/secure.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1314149 (1.3M) [text/plain]
Saving to: ‘secure.json’

secure.json         100%[===================>]   1.25M  --.-KB/s    in 0.01s

2025-06-17 12:29:11 (85.9 MB/s) - ‘secure.json’ saved [1314149/1314149]

In [3]:
suf

'secure'

Show the "content"

In [ ]:
content

In [ ]:
# prompt: from data['secure'] get the type column

# try:
#   secure_types = [item['type'] for item in data[suf]]
#   print(secure_types)
# except KeyError:
#   print("The key 'secure' was not found in the data dictionary.")
# except TypeError:
#   print("The value for 'secure' is not a list of dictionaries.")

In [6]:
# prompt: if the type column = "node" save that record into a pandas dataframe called nodes, if the type = "relationship' then save to a pandas dataframe called edges

import pandas as pd
df = pd.DataFrame(data[suf])
nodes = df[df['type'] == 'node'].copy()
edges = df[df['type'] == 'relationship'].copy()

In [8]:
# prompt: convert id in nodes to int

nodes['id'] = nodes['id'].astype(int)
nodes.head()

,id,labels,properties,type,start,end,label
0,0,"[Base, Domain]","{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL',...",node,NaN,NaN,NaN
1,1,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Admin@MARK.L...",node,NaN,NaN,NaN
2,2,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Tier 1 Serve...",node,NaN,NaN,NaN
3,3,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK....",node,NaN,NaN,NaN
4,4,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MAR...",node,NaN,NaN,NaN

In [9]:
nodes['id'].dtype

dtype('int64')

In [10]:
# prompt: show all rows

import pandas as pd
pd.set_option('display.max_rows', None)

In [11]:
# prompt: for every record in "nodes" create a l1, l2 and l3 column for the values in "nodes.labels" eg. for record 1 l1=Base, l2=OU and l3 would be null

import pandas as pd
def extract_labels(labels):
    # Ensure labels is a list
    if not isinstance(labels, list):
        return [None, None, None]

    l1 = labels[0] if len(labels) > 0 else None
    l2 = labels[1] if len(labels) > 1 else None
    l3 = labels[2] if len(labels) > 2 else None
    return [l1, l2, l3]

# Apply the function to create the new columns
nodes[['l1', 'l2', 'l3']] = nodes['labels'].apply(lambda x: pd.Series(extract_labels(x)))

nodes.head()

,id,labels,properties,type,start,end,label,l1,l2,l3
0,0,"[Base, Domain]","{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL',...",node,NaN,NaN,NaN,Base,Domain,None
1,1,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Admin@MARK.L...",node,NaN,NaN,NaN,Base,OU,None
2,2,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Tier 1 Serve...",node,NaN,NaN,NaN,Base,OU,None
3,3,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK....",node,NaN,NaN,NaN,Base,OU,None
4,4,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MAR...",node,NaN,NaN,NaN,Base,OU,None

In [12]:
# prompt: show me records where l3 ne "None"

nodes[nodes['l3'].notna()]

,id,labels,properties,type,start,end,label,l1,l2,l3
71,71,"[Base, Group, User]","{'domain': 'MARK.LOCAL', 'name': 'DMAPLE00091@...",node,NaN,NaN,NaN,Base,Group,User
83,83,"[Base, Group, User]","{'domain': 'MARK.LOCAL', 'name': 'MHONNETTE000...",node,NaN,NaN,NaN,Base,Group,User
396,396,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised
425,425,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised
428,428,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised
450,450,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised

In [13]:
# prompt: remove the following columns from nodes:
# start, end, label

nodes = nodes.drop(columns=['start', 'end', 'label', 'labels'])
nodes.head()

,id,properties,type,l1,l2,l3
0,0,"{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL',...",node,Base,Domain,None
1,1,"{'domain': 'MARK.LOCAL', 'name': 'Admin@MARK.L...",node,Base,OU,None
2,2,"{'domain': 'MARK.LOCAL', 'name': 'Tier 1 Serve...",node,Base,OU,None
3,3,"{'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK....",node,Base,OU,None
4,4,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MAR...",node,Base,OU,None

In [ ]:
edges.tail()

,id,labels,properties,type,start,end,label
5266,r_3969,NaN,"{'isacl': True, 'isInherited': True, 'inherita...",relationship,"{'id': '65', 'labels': ['Base', 'Group']}","{'id': '3', 'labels': ['Base', 'OU']}",GenericAll
5267,r_3970,NaN,"{'isacl': True, 'isInherited': False, 'inherit...",relationship,"{'id': '66', 'labels': ['Base', 'Group']}","{'id': '1', 'labels': ['Base', 'OU']}",GenericAll
5268,r_3971,NaN,"{'isacl': True, 'isInherited': False, 'inherit...",relationship,"{'id': '66', 'labels': ['Base', 'Group']}","{'id': '3', 'labels': ['Base', 'OU']}",GenericAll
5269,r_3972,NaN,"{'isacl': True, 'isInherited': False, 'inherit...",relationship,"{'id': '60', 'labels': ['Base', 'Group']}","{'id': '101', 'labels': ['Base', 'OU']}",GenericAll
5270,r_3973,NaN,"{'isacl': True, 'isInherited': False, 'inherit...",relationship,"{'id': '66', 'labels': ['Base', 'Group']}","{'id': '101', 'labels': ['Base', 'OU']}",GenericAll

In [14]:
# prompt: remove the "labels" column from edges

edges = edges.drop(columns=['labels'])
edges.head()

,id,properties,type,start,end,label
1297,r_0,{},relationship,"{'id': '0', 'labels': ['Base', 'Domain']}","{'id': '1', 'labels': ['Base', 'OU']}",Contains
1298,r_1,{},relationship,"{'id': '0', 'labels': ['Base', 'Domain']}","{'id': '2', 'labels': ['Base', 'OU']}",Contains
1299,r_2,{},relationship,"{'id': '0', 'labels': ['Base', 'Domain']}","{'id': '3', 'labels': ['Base', 'OU']}",Contains
1300,r_3,{},relationship,"{'id': '1', 'labels': ['Base', 'OU']}","{'id': '4', 'labels': ['Base', 'OU']}",Contains
1301,r_4,{},relationship,"{'id': '1', 'labels': ['Base', 'OU']}","{'id': '5', 'labels': ['Base', 'OU']}",Contains

Expand "Properties" column in new columns.

Convert to Dict

In [ ]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

#nodes

In [17]:
#edges = edges.drop(columns=['id'])
import numpy as np
edges['id'] = np.arange(len(edges)).astype('int64')
edges.head()
edges['id'].dtype

dtype('int64')

In [ ]:
# prompt: save the df_compuers as json to content

import json

# Assuming df_computers is already defined as in your provided code.

# Convert the DataFrame to a JSON string.
nodes_json = nodes.to_json(orient='records')

# Save the JSON string to a file named 'content.json'.
with open('nodes.json', 'w') as f:
  f.write(nodes_json)

In [50]:
# prompt: save the df_compuers as json to content

import json

# Assuming df_computers is already defined as in your provided code.

# Convert the DataFrame to a JSON string.
edges_json = edges.to_json(orient='records')

# Save the JSON string to a file named 'content.json'.
with open('edges.json', 'w') as f:
  f.write(edges_json)

In [19]:
# prompt: create a new column in nodes called weight

nodes['weight'] = 1

In [20]:
# prompt: create a list of all id from nodes where "highvalue" = true

# Before accessing 'Properties', check if the column exists in the DataFrame.
if 'properties' in nodes.columns:
    # Use .loc to avoid SettingWithCopyWarning and access the nested 'highvalue' key
    # We use a lambda function with .apply to safely access nested dictionary keys.
    high_value_node_ids = nodes[nodes['properties'].apply(lambda x: x.get('highvalue', False) == True)]['id'].tolist()
    print(high_value_node_ids)
else:
    print("Error: The 'Properties' column was not found in the nodes DataFrame.")

[0, 36, 38, 40, 59, 60, 65, 66, 72, 75, 90, 91, 92, 93, 94, 95, 96, 97, 98, 288, 289, 291, 293, 294, 295, 296, 297, 299, 301, 302, 303, 304, 305, 306, 307, 308, 309, 311, 312, 313, 314, 315, 318, 319, 320, 321, 322, 323, 324, 491, 501, 507, 508, 509, 511, 512, 514, 521, 523, 527, 530, 531, 532, 533, 534, 539, 544, 548, 550, 553, 557, 561, 562, 563, 564, 565, 567, 573, 575, 577, 585, 590, 597, 599, 600, 603, 607, 609, 610, 620, 623, 624, 625, 626, 631, 632, 637, 638, 639, 640, 645, 648, 649, 650, 651, 653, 654, 655, 656, 660, 661, 663, 665, 666, 668, 672, 673, 676, 677, 681, 684, 692, 693, 694]

In [21]:
len(high_value_node_ids)

124

In [22]:
# prompt: if node[id] = value in high_value_nodes_ids assign a weight of 20

for value in high_value_node_ids:
    nodes.loc[nodes['id'] == value, 'weight'] = 20

In [ ]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
pd.set_option('display.max_colwidth', None)

#nodes.tail(50)

In [ ]:
# prompt: print all nodes where weight==20

#print(nodes[nodes['weight'] == 20])

In [ ]:
len(nodes)

1297

In [ ]:
# prompt: show me records where nodes['properties']['distinguishedname']  does not contain "T2", "T1" or "T0"

# Filter nodes where 'distinguishedname' in 'properties' does not contain "T2", "T1", or "T0"
filtered_nodes = nodes[
    nodes['properties'].apply(
        lambda x: 'distinguishedname' in x and
                  'T2' not in x['distinguishedname'] and
                  'T1' not in x['distinguishedname'] and
                  'T0' not in x['distinguishedname'] and
                  'Tier 0' not in x['distinguishedname'] and
                  'Tier 1' not in x['distinguishedname'] and
                  'Tier 2' not in x['distinguishedname'] and
                  'TIER 0' not in x['distinguishedname'] and
                  'TIER 1' not in x['distinguishedname'] and
                  'TIER 2' not in x['distinguishedname']
    )
]

filtered_nodes

,id,labels,properties,type,l1,l2,l3,weight
0,0,"[Base, Domain]","{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL', 'highvalue': True, 'objectid': 'S-1-5-21-883232822-274137685-4173207997', 'distinguishedname': 'DC=MARK,DC=LOCAL', 'functionallevel': '2012', 'owned': False}",node,Base,Domain,None,20
1,1,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-cdca22b1-d164-4ec1-8233-45c0ea9044ac', 'distinguishedname': 'OU=ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
19,19,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Application@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c8fbc840-cc56-4337-aa2c-31984398cf7f', 'distinguishedname': 'OU=APPLICATION,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
20,20,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Print@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-70355ec3-a132-4ec7-b4c7-f7cdfb011b59', 'distinguishedname': 'OU=PRINT,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
21,21,"[Base, OU]","{'domain': 'MARK.LOCAL', 'name': 'Database@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-bee8279d-bcc2-427c-827c-510159969430', 'distinguishedname': 'OU=DATABASE,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
36,36,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-544', 'highvalue': True, 'distinguishedname': 'CN=Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Administrators have complete and unrestricted access to the computer/domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
37,37,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'REMOTE DESKTOP USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-555', 'highvalue': False, 'distinguishedname': 'CN=Remote Desktop Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members in this group are granted the right to logon remotely', 'admincount': False, 'owned': False}",node,Base,Group,None,1
38,38,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'PRINT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-550', 'highvalue': True, 'distinguishedname': 'CN=Print Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer printers installed on domain controllers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
39,39,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'IIS_IUSRS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-568', 'highvalue': False, 'distinguishedname': 'CN=IIS_IUSRS,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Built-in group used by Internet Information Services.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
40,40,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'BACKUP OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-551', 'highvalue': True, 'distinguishedname': 'CN=Backup Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Backup Operators can override security restrictions for the sole purpose of backing up or restoring files', 'admincount': True, 'owned': False}",node,Base,Group,None,20
41,41,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'NETWORK CONFIGURATION OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-556', 'highvalue': False, 'distinguishedname': 'CN=Network Configuration Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members in this group can have some administrative privileges to manage configuration of networking features', 'admincount': False, 'owned': False}",node,Base,Group,None,1
42,42,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'PERFORMANCE MONITOR USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-558', 'highvalue': False, 'distinguishedname': 'CN=Performance Monitor Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can access performance counter data locally and remotely', 'admincount': False, 'owned': False}",node,Base,Group,None,1
43,43,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'REPLICATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-552', 'highvalue': False, 'distinguishedname': 'CN=Replicator,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Supports file replication in a domain', 'admincount': True, 'owned': False}",node,Base,Group,None,1
44,44,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DISTRIBUTED COM USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-562', 'highvalue': False, 'distinguishedname': 'CN=Distributed COM Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members are allowed to launch, activate and use Distributed COM objects on this machine.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
45,45,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'PERFORMANCE LOG USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-559', 'highvalue': False, 'distinguishedname': 'CN=Performance Log Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group may schedule logging of performance counters, enable trace providers, and collect event traces both locally and via remote access to this computer', 'admincount': False, 'owned': False}",node,Base,Group,None,1
46,46,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'CRYPTOGRAPHIC OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-569', 'highvalue': False, 'distinguishedname': 'CN=Cryptographic Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members are authorized to perform cryptographic operations.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
47,47,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'EVENT LOG READERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-573', 'highvalue': False, 'distinguishedname': 'CN=Event Log Readers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can read event logs from local machine', 'admincount': False, 'owned': False}",node,Base,Group,None,1
48,48,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'GUESTS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-546', 'highvalue': False, 'distinguishedname': 'CN=Guests,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Guests have the same access as members of the Users group by default, except for the Guest account which is further restricted', 'admincount': False, 'owned': False}",node,Base,Group,None,1
49,49,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'SYSTEM MANAGED ACCOUNTS GROUP@MARK.LOCAL', 'objectid': 'S-1-5-32-581', 'highvalue': False, 'distinguishedname': 'CN=System Managed Accounts Group,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group are managed by the system.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
50,50,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-545', 'highvalue': 'null', 'distinguishedname': 'null', 'description': 'null', 'admincount': 'null', 'owned': False}",node,Base,Group,None,1
51,51,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'CERTIFICATE SERVICE DCOM ACCESS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-574', 'highvalue': False, 'distinguishedname': 'CN=Certificate Service DCOM Access,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group are allowed to connect to Certification Authorities in the enterprise', 'admincount': False, 'owned': False}",node,Base,Group,None,1
52,52,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'RDS REMOTE ACCESS SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-575', 'highvalue': False, 'distinguishedname': 'CN=RDS Remote Access Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Servers in this group enable users of RemoteApp programs and personal virtual desktops access to these resources. In Internet-facing deployments, these servers are typically deployed in an edge network. This group needs to be populated on servers running RD Connection Broker. RD Gateway servers and RD Web Access servers used in the deployment need to be in this group.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
53,53,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'RDS ENDPOINT SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-576', 'highvalue': False, 'distinguishedname': 'CN=RDS Endpoint Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Servers in this group run virtual machines and host sessions where users RemoteApp programs and personal virtual desktops run. This group needs to be populated on servers running RD Connection Broker. RD Session Host servers and RD Virtualization Host servers used in the deployment need to be in this group.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
54,54,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'RDS MANAGEMENT SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-577', 'highvalue': False, 'distinguishedname': 'CN=RDS Management Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Servers in this group can perform routine administrative actions on servers running Remote Desktop Services. This group needs to be populated on all servers in a Remote Desktop Services deployment. The servers running the RDS Central Management service must be included in this group.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
55,55,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'HYPER-V ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-578', 'highvalue': False, 'distinguishedname': 'CN=Hyper-V Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group have complete and unrestricted access to all features of Hyper-V.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
56,56,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'ACCESS CONTROL ASSISTANCE OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-579', 'highvalue': False, 'distinguishedname': 'CN=Access Control Assistance Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can remotely query authorization attributes and permissions for resources on this computer.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
57,57,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'REMOTE MANAGEMENT USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-580', 'highvalue': False, 'distinguishedname': 'CN=Remote Management Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can access WMI resources over management protocols (such as WS-Management via the Windows Remote Management service). This applies only to WMI namespaces that grant access to the user.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
58,58,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'CERT PUBLISHERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-517', 'highvalue': False, 'distinguishedname': 'CN=Cert Publishers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are permitted to publish certificates to the directory', 'admincount': False, 'owned': False}",node,Base,Group,None,1
59,59,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'SERVER OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-549', 'highvalue': True, 'distinguishedname': 'CN=Server Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain servers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
60,60,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'ACCOUNT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-548', 'highvalue': True, 'distinguishedname': 'CN=Account Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain user and group accounts', 'admincount': True, 'owned': False}",node,Base,Group,None,20
61,61,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'PRE-WINDOWS 2000 COMPATIBLE ACCESS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-554', 'highvalue': False, 'distinguishedname': 'CN=Pre-Windows 2000 Compatible Access,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'A backward compatibility group which allows read access on all users and groups in the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
62,62,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'WINDOWS AUTHORIZATION ACCESS GROUP@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-560', 'highvalue': False, 'distinguishedname': 'CN=Windows Authorization Access Group,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group have access to the computed tokenGroupsGlobalAndUniversal attribute on User objects', 'admincount': False, 'owned': False}",node,Base,Group,None,1
63,63,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DENIED RODC PASSWORD REPLICATION GROUP@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-572', 'highvalue': False, 'distinguishedname': 'CN=Denied RODC Password Replication Group,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group cannot have their passwords replicated to any read-only domain controllers in the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
64,64,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'SCHEMA ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-518', 'highvalue': False, 'distinguishedname': 'CN=Schema Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the schema', 'admincount': True, 'owned': False}",node,Base,Group,None,1
65,65,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-519', 'highvalue': True, 'distinguishedname': 'CN=Enterprise Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the enterprise', 'admincount': True, 'owned': False}",node,Base,Group,None,20
66,66,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DOMAIN ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-512', 'highvalue': True, 'distinguishedname': 'CN=Domain Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
67,67,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'RAS AND IAS SERVERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-553', 'highvalue': False, 'distinguishedname': 'CN=RAS and IAS Servers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Servers in this group can access remote access properties of users', 'admincount': False, 'owned': False}",node,Base,Group,None,1
68,68,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'INCOMING FOREST TRUST BUILDERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-557', 'highvalue': False, 'distinguishedname': 'CN=Incoming Forest Trust Builders,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can create incoming, one-way trusts to this forest', 'admincount': False, 'owned': False}",node,Base,Group,None,1
69,69,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'TERMINAL SERVER LICENSE SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-561', 'highvalue': False, 'distinguishedname': 'CN=Terminal Server License Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can update user accounts in Active Directory with information about license issuance, for the purpose of tracking and reporting TS Per User CAL usage', 'admincount': False, 'owned': False}",node,Base,Group,None,1
70,70,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'ALLOWED RODC PASSWORD REPLICATION GROUP@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-571', 'highvalue': False, 'distinguishedname': 'CN=Allowed RODC Password Replication Group,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group can have their passwords replicated to all read-only domain controllers in the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
72,72,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-516', 'highvalue': True, 'distinguishedname': 'CN=Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain controllers in the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
73,73,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DOMAIN COMPUTERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-515', 'highvalue': False, 'distinguishedname': 'CN=Domain Computers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All workstations and servers joined to the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
74,74,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DOMAIN USERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-513', 'highvalue': False, 'distinguishedname': 'CN=Domain Users,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain users', 'admincount': False, 'owned': False}",node,Base,Group,None,1
75,75,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'GROUP POLICY CREATOR OWNERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-520', 'highvalue': True, 'distinguishedname': 'CN=Group Policy Creator Owners,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group can modify group policy for the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,20
76,76,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'DOMAIN GUESTS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-514', 'highvalue': False, 'distinguishedname': 'CN=Domain Guests,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain guests', 'admincount': False, 'owned': False}",node,Base,Group,None,1
77,77,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'READ-ONLY DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-521', 'highvalue': False, 'distinguishedname': 'CN=Read-only Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are Read-Only Domain Controllers in the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,1
78,78,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE READ-ONLY DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-498', 'highvalue': False, 'distinguishedname': 'CN=Enterprise Read-only Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are Read-Only Domain Controllers in the enterprise', 'admincount': False, 'owned': False}",node,Base,Group,None,1
79,79,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'CLONEABLE DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-522', 'highvalue': False, 'distinguishedname': 'CN=Cloneable Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group that are domain controllers may be cloned.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
80,80,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'PROTECTED USERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-525', 'highvalue': False, 'distinguishedname': 'CN=Protected Users,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are afforded additional protections against authentication security threats. See http://go.microsoft.com/fwlink/?LinkId=298939 for more information.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
81,81,"[Base, Group]","{'domain': 'MARK.LOCAL', 'name': 'KEY ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-526', 'highvalue': False, 'distinguishedname': 'CN=Key Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group can perform administrative actions on key objects within the domain.', 'admincount': False, 'owned': False}",node,Base,Group,None,1

In [ ]:
len(filtered_nodes)

68

In [ ]:
# prompt: show all column contents for nodes do not truncate columns

import pandas as pd
pd.set_option('display.max_colwidth', None)
#nodes

In [25]:
# prompt: compile a list of all id's from nodes where distinguishedname contains 'Tier 0' or T0. distinguishedname is a key within the properties column

tier_0_t0_ids = []
for index, row in nodes.iterrows():
    properties = row.get('properties')
    if properties and isinstance(properties, dict):
        distinguishedname = properties.get('distinguishedname')
        if distinguishedname and ('Tier 0' in distinguishedname or 'T0' in distinguishedname or 'TIER 0' in distinguishedname):
            tier_0_t0_ids.append(row['id'])

print("tier 0: ", tier_0_t0_ids)
len_tier0=len(tier_0_t0_ids)
print(len_tier0)

tier_1_t0_ids = []
for index, row in nodes.iterrows():
    properties = row.get('properties')
    if properties and isinstance(properties, dict):
        distinguishedname = properties.get('distinguishedname')
        if distinguishedname and ('Tier 1' in distinguishedname or 'T1' in distinguishedname or 'TIER 1' in distinguishedname):
            tier_1_t0_ids.append(row['id'])

print("tier 1: ",tier_1_t0_ids)
len_tier1=len(tier_1_t0_ids)
print(len_tier1)

tier_2_t0_ids = []
for index, row in nodes.iterrows():
    properties = row.get('properties')
    if properties and isinstance(properties, dict):
        distinguishedname = properties.get('distinguishedname')
        if distinguishedname and ('Tier 2' in distinguishedname or 'T2' in distinguishedname or 'TIER 2' in distinguishedname):
            tier_2_t0_ids.append(row['id'])

print("tier 2: ",tier_2_t0_ids)
len_tier2= len(tier_2_t0_ids)
print(len_tier2)
total = len_tier0 + len_tier1 + len_tier2
print("total: ",total)

tier 0:  [4, 7, 8, 9, 10, 295, 296, 301, 303, 305, 306, 307, 318, 324, 331, 341, 357, 392, 405, 444, 448, 457, 458, 467, 469, 481, 527, 530, 531, 532, 553, 607, 610, 625, 631, 632, 640, 645, 653, 663, 686, 692]
42
tier 1:  [5, 11, 12, 13, 14, 90, 91, 92, 93, 288, 291, 297, 302, 309, 315, 319, 323, 459, 460, 461, 467, 491, 508, 512, 514, 523, 534, 544, 550, 561, 563, 564, 575, 577, 585, 590, 597, 599, 600, 620, 623, 624, 626, 639, 648, 650, 651, 654, 665, 677, 681, 684, 687, 689, 690, 691, 693]
57
tier 2:  [6, 15, 16, 17, 18, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 71, 83, 94, 95, 96, 97, 289, 290, 292, 293, 294, 298, 299, 300, 301, 304, 308, 310, 311, 312, 313, 314, 316, 317, 318, 320, 321, 322, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 462, 463, 464, 465, 466, 468, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 509, 510, 511, 513, 515, 516, 517, 518, 519, 520, 521, 522, 524, 525, 526, 528, 529, 533, 535, 536, 537, 538, 539, 540, 541, 542, 543, 545, 546, 547, 548, 549, 551, 552, 554, 555, 556, 557, 558, 559, 560, 562, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 576, 578, 579, 580, 581, 582, 583, 584, 586, 587, 588, 589, 591, 592, 593, 594, 595, 596, 598, 601, 602, 603, 604, 605, 606, 608, 609, 611, 612, 613, 614, 615, 616, 617, 618, 619, 621, 622, 627, 628, 629, 630, 633, 634, 635, 636, 637, 638, 641, 642, 643, 644, 646, 647, 649, 652, 655, 656, 657, 658, 659, 660, 661, 662, 664, 666, 668, 672, 673, 676, 688, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066, 1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077, 1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088, 1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1108, 1109, 1110, 1111, 1112, 1113, 1114, 1115, 1116, 1117, 1118, 1119, 1120, 1121, 1122, 1123, 1124, 1125, 1126, 1127, 1128, 1129, 1130, 1131, 1132, 1133, 1134, 1135, 1136, 1137, 1138, 1139, 1140, 1141, 1142, 1143, 1144, 1145, 1146, 1147, 1148, 1149, 1150, 1151, 1152, 1153, 1154, 1155, 1156, 1157, 1158, 1159, 1160, 1161, 1162, 1163, 1164, 1165, 1166, 1167, 1168, 1169, 1170, 1171, 1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, 1296]
948
total:  1047

In [26]:
# prompt: if tier_0_t0_ids isnot high_value_node_ids then append nodeid in a new dataframe called total_tier0

total_tier0 = []
for nodeid in tier_0_t0_ids:
  if nodeid not in high_value_node_ids:
    total_tier0.append(nodeid)

print("Nodes in tier_0_t0_ids that are not in high_value_node_ids:", total_tier0)

Nodes in tier_0_t0_ids that are not in high_value_node_ids: [4, 7, 8, 9, 10, 331, 341, 357, 392, 405, 444, 448, 457, 458, 467, 469, 481, 686]

In [27]:
# prompt: total_tier0 = total_tier0 and appended high_value_node_ids

total_tier0.extend(high_value_node_ids)
print("total_tier0:", total_tier0)

total_tier0: [4, 7, 8, 9, 10, 331, 341, 357, 392, 405, 444, 448, 457, 458, 467, 469, 481, 686, 0, 36, 38, 40, 59, 60, 65, 66, 72, 75, 90, 91, 92, 93, 94, 95, 96, 97, 98, 288, 289, 291, 293, 294, 295, 296, 297, 299, 301, 302, 303, 304, 305, 306, 307, 308, 309, 311, 312, 313, 314, 315, 318, 319, 320, 321, 322, 323, 324, 491, 501, 507, 508, 509, 511, 512, 514, 521, 523, 527, 530, 531, 532, 533, 534, 539, 544, 548, 550, 553, 557, 561, 562, 563, 564, 565, 567, 573, 575, 577, 585, 590, 597, 599, 600, 603, 607, 609, 610, 620, 623, 624, 625, 626, 631, 632, 637, 638, 639, 640, 645, 648, 649, 650, 651, 653, 654, 655, 656, 660, 661, 663, 665, 666, 668, 672, 673, 676, 677, 681, 684, 692, 693, 694]

In [28]:
len(total_tier0)

142

In [ ]:
len(nodes)

1297

In [ ]:
# prompt: how do i rewrite the following code to check for "TIER 0", "Tier 0" and "T0":
# tier0_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 0' in x.get('distinguishedname', ''))]['id'].tolist()

tier0_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 0', 'Tier 0', 'T0']
        )
    )
]['id'].tolist()

In [ ]:

tier0_node_ids

[4,
 7,
 8,
 9,
 10,
 295,
 296,
 301,
 303,
 305,
 306,
 307,
 318,
 324,
 331,
 341,
 357,
 392,
 405,
 444,
 448,
 457,
 458,
 467,
 469,
 481,
 527,
 530,
 531,
 532,
 553,
 607,
 610,
 625,
 631,
 632,
 640,
 645,
 653,
 663,
 686,
 692]

In [29]:
# 1/0
# tier0_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 0' in x.get('distinguishedname', ''))]['id'].tolist()
# tier0_node_ids

tier0_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 0', 'Tier 0', 'T0']
        )
    )
]['id'].tolist()


tier1_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 1', 'Tier 1', 'T1']
        )
    )
]['id'].tolist()

tier2_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 2', 'Tier 2', 'T2']
        )
    )
]['id'].tolist()

print(f"tier 0 ",len(tier0_node_ids))
# tier1_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 1' in x.get('distinguishedname', ''))]['id'].tolist()
print(f"tier 1 ",len(tier1_node_ids))

# tier2_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 2' in x.get('distinguishedname', ''))]['id'].tolist()
print(f"tier 2 ",len(tier2_node_ids))

tier 0  42
tier 1  58
tier 2  949

In [ ]:
len(nodes)

1297

In [ ]:
# T0="T0"
# T1="T1"
# T2="T2"

In [ ]:
# # prompt: produce a list of id's from nodes when nodes[properties][name] contains T0

# ids_with_T0 = nodes[nodes['properties'].apply(lambda x: T0 in x.get('name', ''))]['id'].tolist()
# #ids_with_T0
# ids_with_T1 = nodes[nodes['properties'].apply(lambda x: T1 in x.get('name', ''))]['id'].tolist()
# #ids_with_T1
# ids_with_T2 = nodes[nodes['properties'].apply(lambda x: T2 in x.get('name', ''))]['id'].tolist()
# #ids_with_T2

In [ ]:
# print(ids_with_T0)
# print(ids_with_T1)
# print(ids_with_T2)

# print(len(ids_with_T0))
# print(len(ids_with_T1))
# print(len(ids_with_T2))

In [ ]:

for value in ids_with_T0:
    nodes.loc[nodes['id'] == value, 'weight'] = 20

for value in ids_with_T1:
    nodes.loc[nodes['id'] == value, 'weight'] = 10

for value in ids_with_T2:
    nodes.loc[nodes['id'] == value, 'weight'] = 5

nodes.head(50)

,id,labels,properties,type,weight
0,6221,"[Base, Domain]","{'domain': 'TESTLAB.LOCALE', 'name': 'TESTLAB....",node,20
1,6222,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'Admin@TE...",node,1
2,6223,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'Tier 1 S...",node,1
3,6224,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'Tier 2@T...",node,1
4,6225,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T0 Admin...",node,20
5,6226,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T1 Admin...",node,10
6,6227,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Admin...",node,5
7,6228,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T0 Admin...",node,20
8,6229,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T0 Admin...",node,20
9,6230,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T0 Admin...",node,20
10,6231,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T0 Admin...",node,20
11,6232,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T1 Admin...",node,10
12,6233,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T1 Admin...",node,10
13,6234,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T1 Admin...",node,10
14,6235,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T1 Admin...",node,10
15,6236,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Admin...",node,5
16,6237,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Admin...",node,5
17,6238,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Admin...",node,5
18,6239,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Admin...",node,5
19,6240,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'Applicat...",node,1
20,6241,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'Print@TE...",node,1
21,6242,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'Database...",node,1
22,6243,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Group...",node,5
23,6244,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Works...",node,5
24,6245,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 User ...",node,5
25,6246,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Serve...",node,5
26,6247,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Enabl...",node,5
27,6248,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Disab...",node,5
28,6249,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Works...",node,5
29,6250,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Works...",node,5
30,6251,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Works...",node,5
31,6252,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Works...",node,5
32,6253,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Works...",node,5
33,6254,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Distr...",node,5
34,6255,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Secur...",node,5
35,6256,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Serve...",node,5
36,6257,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Serve...",node,5
37,6258,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Serve...",node,5
38,6259,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Serve...",node,5
39,6260,"[Base, OU]","{'domain': 'TESTLAB.LOCALE', 'name': 'T2 Serve...",node,5
40,6261,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'ADMINIST...",node,20
41,6262,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'REMOTE D...",node,1
42,6263,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'PRINT OP...",node,20
43,6264,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'IIS_IUSR...",node,1
44,6265,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'BACKUP O...",node,20
45,6266,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'NETWORK ...",node,1
46,6267,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'PERFORMA...",node,1
47,6268,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'REPLICAT...",node,1
48,6269,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'DISTRIBU...",node,1
49,6270,"[Base, Group]","{'domain': 'TESTLAB.LOCALE', 'name': 'PERFORMA...",node,1

In [ ]:
# prompt: get a unique list of label from edges and save it to list called edges_labels

edges_labels = edges['label'].unique().tolist()
edges_labels

['Contains',
 'GpLink',
 'GenericAll',
 'MemberOf',
 'GenericWrite',
 'WriteDacl',
 'Owns',
 'WriteOwner',
 'GetChanges',
 'GetChangesAll',
 'AllExtendedRights',
 'AdminTo',
 'HasSession',
 'AllowedToDelegate',
 'ReadLAPSPassword',
 'CanRDP',
 'ExecuteDCOM',
 'AllowedToAct',
 'CanPSRemote',
 'ForceChangePassword',
 'AddMember',
 'AddSelf']

In [ ]:
# Apply the weights based on the 'label' column

def assign_weight(label):
    if label == "GenericAll":
        return 9
    elif label == "Owns":
        return 10
    elif label == "GenericWrite":
        return 2
    elif label == "AllExtendedRights":
        return 6
    elif label == "CanRDP":
        return 2
    elif label == "Contains":
        return 2
    elif label == "DCSync":
        return 8
    elif label == "WriteDacl":
        return 5
    elif label == "WriteOwner":
        return 7
    elif label == "AddKeyCredentialLink":
        return 6
    elif label == "AdminTo":
        return 8
    elif label == "MemberOf":
        return 1
    elif label == "CanPSRemote":
        return 2
    elif label == "ExecuteDCOM":
        return 2
    elif label == "GPLink":
        return 3
    elif label == "HasSession":
        return 9
    elif label == "ReadLAPSPassword":
        return 2
    elif label == "GetChanges":
        return 3
    elif label == "GetChangesAll":
        return 3
    elif label == "AddSelf":
        return 3
    elif label == "ForceChangePassword":
        return 3
    elif label == "AddMember":
        return 5
    elif label == "tier0":
        return 20
    else:
        return 1 # Default weight for other labels

edges['weight'] = edges['label'].apply(assign_weight)

# Display the updated edges_all DataFrame with the 'weight' column
print("\nEdges_all DataFrame with weight column:")
edges.head(50)
#clear_output()

In [31]:
# prompt: from edges['start'] get 'id' and from edges['end] get 'id'
# replace start with edges['start'][id'] and  end with edges['end']['id']

edges['start'] = edges['start'].apply(lambda x: x.get('id') if isinstance(x, dict) else x)
edges['end'] = edges['end'].apply(lambda x: x.get('id') if isinstance(x, dict) else x)
edges.head(30)

      id properties          type start end     label  weight
1297   0         {}  relationship     0   1  Contains       2
1298   1         {}  relationship     0   2  Contains       2
1299   2         {}  relationship     0   3  Contains       2
1300   3         {}  relationship     1   4  Contains       2
1301   4         {}  relationship     1   5  Contains       2
1302   5         {}  relationship     1   6  Contains       2
1303   6         {}  relationship     4   7  Contains       2
1304   7         {}  relationship     4   8  Contains       2
1305   8         {}  relationship     4   9  Contains       2
1306   9         {}  relationship     4  10  Contains       2
1307  10         {}  relationship     5  11  Contains       2
1308  11         {}  relationship     5  12  Contains       2
1309  12         {}  relationship     5  13  Contains       2
1310  13         {}  relationship     5  14  Contains       2
1311  14         {}  relationship     6  15  Contains       2
1312  15         {}  relationship     6  16  Contains       2
1313  16         {}  relationship     6  17  Contains       2
1314  17         {}  relationship     6  18  Contains       2
1315  18         {}  relationship     2  19  Contains       2
1316  19         {}  relationship     2  20  Contains       2
1317  20         {}  relationship     2  21  Contains       2
1318  21         {}  relationship     3  22  Contains       2
1319  22         {}  relationship     3  23  Contains       2
1320  23         {}  relationship     3  24  Contains       2
1321  24         {}  relationship     3  25  Contains       2
1322  25         {}  relationship    24  26  Contains       2
1323  26         {}  relationship    24  27  Contains       2
1324  27         {}  relationship    23  28  Contains       2
1325  28         {}  relationship    23  29  Contains       2
1326  29         {}  relationship    23  30  Contains       2

In [32]:
len(edges)

3974

In [34]:
print("\nEdges_all DataFrame with weight column:")
edges.tail(50)

Edges_all DataFrame with weight column:

,id,properties,type,start,end,label,weight
5221,3924,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,36,11,WriteOwner,7
5222,3925,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,36,15,WriteOwner,7
5223,3926,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,36,14,WriteOwner,7
5224,3927,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,36,18,WriteOwner,7
5225,3928,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,36,24,WriteOwner,7
5226,3929,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,98,WriteOwner,7
5227,3930,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,65,98,WriteOwner,7
5228,3931,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,8,GenericAll,9
5229,3932,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,12,GenericAll,9
5230,3933,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,16,GenericAll,9
5231,3934,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,2,GenericAll,9
5232,3935,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,25,GenericAll,9
5233,3936,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,23,GenericAll,9
5234,3937,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,22,GenericAll,9
5235,3938,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,11,GenericAll,9
5236,3939,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,15,GenericAll,9
5237,3940,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,14,GenericAll,9
5238,3941,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,18,GenericAll,9
5239,3942,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,24,GenericAll,9
5240,3943,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,8,GenericAll,9
5241,3944,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,12,GenericAll,9
5242,3945,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,16,GenericAll,9
5243,3946,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,2,GenericAll,9
5244,3947,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,25,GenericAll,9
5245,3948,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,23,GenericAll,9
5246,3949,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,22,GenericAll,9
5247,3950,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,11,GenericAll,9
5248,3951,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,15,GenericAll,9
5249,3952,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,14,GenericAll,9
5250,3953,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,18,GenericAll,9
5251,3954,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,24,GenericAll,9
5252,3955,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,8,GenericAll,9
5253,3956,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,12,GenericAll,9
5254,3957,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,16,GenericAll,9
5255,3958,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,2,GenericAll,9
5256,3959,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,25,GenericAll,9
5257,3960,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,23,GenericAll,9
5258,3961,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,22,GenericAll,9
5259,3962,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,11,GenericAll,9
5260,3963,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,15,GenericAll,9
5261,3964,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,14,GenericAll,9
5262,3965,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,18,GenericAll,9
5263,3966,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,24,GenericAll,9
5264,3967,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,101,GenericAll,9
5265,3968,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,1,GenericAll,9
5266,3969,"{'isacl': True, 'isInherited': True, 'inheritanceType': 'All'}",relationship,65,3,GenericAll,9
5267,3970,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,1,GenericAll,9
5268,3971,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,3,GenericAll,9
5269,3972,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,60,101,GenericAll,9
5270,3973,"{'isacl': True, 'isInherited': False, 'inheritanceType': 'All'}",relationship,66,101,GenericAll,9

In [ ]:
# prompt: create a new dataframe called adj with the values of start['id'] and end['id'] from each record

# adj = edges[['start', 'end']].copy()
# adj['start'] = adj['start'].apply(lambda x: x['id']).astype(int)
# adj['end'] = adj['end'].apply(lambda x: x['id']).astype(int)
# adj.head()

In [ ]:
len(edges)
edges.head(20)

     properties          type start end     label  id  weight
1297         {}  relationship     0   1  Contains   0       2
1298         {}  relationship     0   2  Contains   1       2
1299         {}  relationship     0   3  Contains   2       2
1300         {}  relationship     1   4  Contains   3       2
1301         {}  relationship     1   5  Contains   4       2
1302         {}  relationship     1   6  Contains   5       2
1303         {}  relationship     4   7  Contains   6       2
1304         {}  relationship     4   8  Contains   7       2
1305         {}  relationship     4   9  Contains   8       2
1306         {}  relationship     4  10  Contains   9       2
1307         {}  relationship     5  11  Contains  10       2
1308         {}  relationship     5  12  Contains  11       2
1309         {}  relationship     5  13  Contains  12       2
1310         {}  relationship     5  14  Contains  13       2
1311         {}  relationship     6  15  Contains  14       2
1312         {}  relationship     6  16  Contains  15       2
1313         {}  relationship     6  17  Contains  16       2
1314         {}  relationship     6  18  Contains  17       2
1315         {}  relationship     2  19  Contains  18       2
1316         {}  relationship     2  20  Contains  19       2

In [ ]:
# prompt: from edges, convert start[id] into an integer

# edges['start'] = edges['start'].apply(lambda x: x['id']).astype(int)

In [ ]:
# edges['end'] = edges['end'].apply(lambda x: x['id']).astype(int)
# edges['start'] = edges['start'].apply(lambda x: x['id']).astype(int)

In [35]:

edges = edges.drop(columns=['properties', 'id'])

In [38]:
# prompt: create a unique id for each row, make sure it is of type int64
#edges = edges.drop(columns=['id'])
import numpy as np
edges['id'] = np.arange(len(edges)).astype('int64')
edges.head()
edges['id'].dtype

dtype('int64')

In [39]:

edges.keys()

Index(['type', 'start', 'end', 'label', 'weight', 'id'], dtype='object')

In [40]:
# prompt: filter where edges['id'] = tier2_node_ids and call the dataframe selected_ddges

selected_edges = edges[edges['id'].isin(tier2_node_ids)]

In [71]:
selected_nodes = nodes[nodes['id'].isin(tier2_node_ids)]

In [42]:
# prompt: set weight to 20 in selected_nodes

for value in selected_nodes['id']:
    selected_nodes.loc[selected_nodes['id'] == value, 'weight'] = 20

In [80]:
selected_nodes

        id  \
3        3
6        6
15      15
16      16
17      17
18      18
22      22
23      23
24      24
25      25
26      26
27      27
28      28
29      29
30      30
31      31
32      32
33      33
34      34
35      35
71      71
83      83
94      94
95      95
96      96
97      97
289    289
290    290
292    292
293    293
294    294
298    298
299    299
300    300
301    301
304    304
308    308
310    310
311    311
312    312
313    313
314    314
316    316
317    317
318    318
320    320
321    321
322    322
325    325
326    326
327    327
328    328
329    329
330    330
331    331
332    332
333    333
334    334
335    335
336    336
337    337
338    338
339    339
340    340
341    341
342    342
343    343
344    344
345    345
346    346
347    347
348    348
349    349
350    350
351    351
352    352
353    353
354    354
355    355
356    356
357    357
358    358
359    359
360    360
361    361
362    362
363    363
364    364
365    365
366    366
367    367
368    368
369    369
370    370
371    371
372    372
373    373
374    374
375    375
376    376
377    377
378    378
379    379
380    380
381    381
382    382
383    383
384    384
385    385
386    386
387    387
388    388
389    389
390    390
391    391
392    392
393    393
394    394
395    395
396    396
397    397
398    398
399    399
400    400
401    401
402    402
403    403
404    404
405    405
406    406
407    407
408    408
409    409
410    410
411    411
412    412
413    413
414    414
415    415
416    416
417    417
418    418
419    419
420    420
421    421
422    422
423    423
424    424
425    425
426    426
427    427
428    428
429    429
430    430
431    431
432    432
433    433
434    434
435    435
436    436
437    437
438    438
439    439
440    440
441    441
442    442
443    443
444    444
445    445
446    446
447    447
448    448
449    449
450    450
451    451
452    452
453    453
454    454
455    455
456    456
462    462
463    463
464    464
465    465
466    466
468    468
470    470
471    471
472    472
473    473
474    474
475    475
476    476
477    477
478    478
479    479
480    480
481    481
482    482
483    483
484    484
485    485
486    486
487    487
488    488
489    489
490    490
492    492
493    493
494    494
495    495
496    496
497    497
498    498
499    499
500    500
501    501
502    502
503    503
504    504
505    505
506    506
507    507
509    509
510    510
511    511
513    513
515    515
516    516
517    517
518    518
519    519
520    520
521    521
522    522
524    524
525    525
526    526
528    528
529    529
533    533
535    535
536    536
537    537
538    538
539    539
540    540
541    541
542    542
543    543
545    545
546    546
547    547
548    548
549    549
551    551
552    552
554    554
555    555
556    556
557    557
558    558
559    559
560    560
562    562
565    565
566    566
567    567
568    568
569    569
570    570
571    571
572    572
573    573
574    574
576    576
578    578
579    579
580    580
581    581
582    582
583    583
584    584
586    586
587    587
588    588
589    589
591    591
592    592
593    593
594    594
595    595
596    596
598    598
601    601
602    602
603    603
604    604
605    605
606    606
608    608
609    609
611    611
612    612
613    613
614    614
615    615
616    616
617    617
618    618
619    619
621    621
622    622
627    627
628    628
629    629
630    630
633    633
634    634
635    635
636    636
637    637
638    638
641    641
642    642
643    643
644    644
646    646
647    647
649    649
652    652
655    655
656    656
657    657
658    658
659    659
660    660
661    661
662    662
664    664
666    666
668    668
672    672
673    673
676    676
688    688
694    694
695    695
696    696
697    697
698    698
699    699
700    700
701    701
702    702
703    703
704    704
705    705
706    706
707    707
708    708
709    709
710    710
711    711
712    712
713    713
714    714
715    715
716    716
717    717
718    718
719    719
720    720
721    721
722    722
723    723
724    724
725    725
726    726
727    727
728    728
729    729
730    730
731    731
732    732
733    733
734    734
735    735
736    736
737    737
738    738
739    739
740    740
741    741
742    742
743    743
744    744
745    745
746    746
747    747
748    748
749    749
750    750
751    751
752    752
753    753
754    754
755    755
756    756
757    757
758    758
759    759
760    760
761    761
762    762
763    763
764    764
765    765
766    766
767    767
768    768
769    769
770    770
771    771
772    772
773    773
774    774
775    775
776    776
777    777
778    778
779    779
780    780
781    781
782    782
783    783
784    784
785    785
786    786
787    787
788    788
789    789
790    790
791    791
792    792
793    793
794    794
795    795
796    796
797    797
798    798
799    799
800    800
801    801
802    802
803    803
804    804
805    805
806    806
807    807
808    808
809    809
810    810
811    811
812    812
813    813
814    814
815    815
816    816
817    817
818    818
819    819
820    820
821    821
822    822
823    823
824    824
825    825
826    826
827    827
828    828
829    829
830    830
831    831
832    832
833    833
834    834
835    835
836    836
837    837
838    838
839    839
840    840
841    841
842    842
843    843
844    844
845    845
846    846
847    847
848    848
849    849
850    850
851    851
852    852
853    853
854    854
855    855
856    856
857    857
858    858
859    859
860    860
861    861
862    862
863    863
864    864
865    865
866    866
867    867
868    868
869    869
870    870
871    871
872    872
873    873
874    874
875    875
876    876
877    877
878    878
879    879
880    880
881    881
882    882
883    883
884    884
885    885
886    886
887    887
888    888
889    889
890    890
891    891
892    892
893    893
894    894
895    895
896    896
897    897
898    898
899    899
900    900
901    901
902    902
903    903
904    904
905    905
906    906
907    907
908    908
909    909
910    910
911    911
912    912
913    913
914    914
915    915
916    916
917    917
918    918
919    919
920    920
921    921
922    922
923    923
924    924
925    925
926    926
927    927
928    928
929    929
930    930
931    931
932    932
933    933
934    934
935    935
936    936
937    937
938    938
939    939
940    940
941    941
942    942
943    943
944    944
945    945
946    946
947    947
948    948
949    949
950    950
951    951
952    952
953    953
954    954
955    955
956    956
957    957
958    958
959    959
960    960
961    961
962    962
963    963
964    964
965    965
966    966
967    967
968    968
969    969
970    970
971    971
972    972
973    973
974    974
975    975
976    976
977    977
978    978
979    979
980    980
981    981
982    982
983    983
984    984
985    985
986    986
987    987
988    988
989    989
990    990
991    991
992    992
993    993
994    994
995    995
996    996
997    997
998    998
999    999
1000  1000
1001  1001
1002  1002
1003  1003
1004  1004
1005  1005
1006  1006
1007  1007
1008  1008
1009  1009
1010  1010
1011  1011
1012  1012
1013  1013
1014  1014
1015  1015
1016  1016
1017  1017
1018  1018
1019  1019
1020  1020
1021  1021
1022  1022
1023  1023
1024  1024
1025  1025
1026  1026
1027  1027
1028  1028
1029  1029
1030  1030
1031  1031
1032  1032
1033  1033
1034  1034
1035  1035
1036  1036
1037  1037
1038  1038
1039  1039
1040  1040
1041  1041
1042  1042
1043  1043
1044  1044
1045  1045
1046  1046
1047  1047
1048  1048
1049  1049
1050  1050
1051  1051
1052  1052
1053  1053
1054  1054
1055  1055
1056  1056
1057  1057
1058  1058
1059  1059
1060  1060
1061  1061
1062  1062
1063  1063
1064  1064
1065  1065
1066  1066
1067  1067
1068  1068
1069  1069
1070  1070
1071  1071
1072  1072
1073  1073
1074  1074
1075  1075
1076  1076
1077  1077
1078  1078
1079  1079
1080  1080
1081  1081
1082  1082
1083  1083
1084  1084
1085  1085
1086  1086
1087  1087
1088  1088
1089  1089
1090  1090
1091  1091
1092  1092
1093  1093
1094  1094
1095  1095
1096  1096
1097  1097
1098  1098
1099  1099
1100  1100
1101  1101
1102  1102
1103  1103
1104  1104
1105  1105
1106  1106
1107  1107
1108  1108
1109  1109
1110  1110
1111  1111
1112  1112
1113  1113
1114  1114
1115  1115
1116  1116
1117  1117
1118  1118
1119  1119
1120  1120
1121  1121
1122  1122
1123  1123
1124  1124
1125  1125
1126  1126
1127  1127
1128  1128
1129  1129
1130  1130
1131  1131
1132  1132
1133  1133
1134  1134
1135  1135
1136  1136
1137  1137
1138  1138
1139  1139
1140  1140
1141  1141
1142  1142
1143  1143
1144  1144
1145  1145
1146  1146
1147  1147
1148  1148
1149  1149
1150  1150
1151  1151
1152  1152
1153  1153
1154  1154
1155  1155
1156  1156
1157  1157
1158  1158
1159  1159
1160  1160
1161  1161
1162  1162
1163  1163
1164  1164
1165  1165
1166  1166
1167  1167
1168  1168
1169  1169
1170  1170
1171  1171
1172  1172
1173  1173
1174  1174
1175  1175
1176  1176
1177  1177
1178  1178
1179  1179
1180  1180
1181  1181
1182  1182
1183  1183
1184  1184
1185  1185
1186  1186
1187  1187
1188  1188
1189  1189
1190  1190
1191  1191
1192  1192
1193  1193
1194  1194
1195  1195
1196  1196
1197  1197
1198  1198
1199  1199
1200  1200
1201  1201
1202  1202
1203  1203
1204  1204
1205  1205
1206  1206
1207  1207
1208  1208
1209  1209
1210  1210
1211  1211
1212  1212
1213  1213
1214  1214
1215  1215
1216  1216
1217  1217
1218  1218
1219  1219
1220  1220
1221  1221
1222  1222
1223  1223
1224  1224
1225  1225
1226  1226
1227  1227
1228  1228
1229  1229
1230  1230
1231  1231
1232  1232
1233  1233
1234  1234
1235  1235
1236  1236
1237  1237
1238  1238
1239  1239
1240  1240
1241  1241
1242  1242
1243  1243
1244  1244
1245  1245
1246  1246
1247  1247
1248  1248
1249  1249
1250  1250
1251  1251
1252  1252
1253  1253
1254  1254
1255  1255
1256  1256
1257  1257
1258  1258
1259  1259
1260  1260
1261  1261
1262  1262
1263  1263
1264  1264
1265  1265
1266  1266
1267  1267
1268  1268
1269  1269
1270  1270
1271  1271
1272  1272
1273  1273
1274  1274
1275  1275
1276  1276
1277  1277
1278  1278
1279  1279
1280  1280
1281  1281
1282  1282
1283  1283
1284  1284
1285  1285
1286  1286
1287  1287
1288  1288
1289  1289
1290  1290
1291  1291
1292  1292
1293  1293
1294  1294
1295  1295
1296  1296

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               properties  \
3                                                                                                                                                                                                                                                                                                                                                                                                                                                               {'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5de20ac8-e7ff-4f05-b597-268af392400e', 'distinguishedname': 'OU=TIER 2,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
6                                                                                                                                                                                                                                                                                                                                                                                                                                                           {'domain': 'MARK.LOCAL', 'name': 'T2 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e4602f9d-12bf-4f9e-b667-f6ccd27fae90', 'distinguishedname': 'OU=T2 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
15                                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-61c17d81-4eb2-4829-94e7-c7ddd6ecd193', 'distinguishedname': 'OU=T2 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
16                                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5305b84a-5f72-4ee8-9726-81485bc11905', 'distinguishedname': 'OU=T2 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
17                                                                                                                                                                                                                                                                                                                                                                                                                                            {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-508809b7-63d4-4f53-8376-b31aa66c0af6', 'distinguishedname': 'OU=T2 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
18                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e7679546-c753-4556-889a-67fd84f9d165', 'distinguishedname': 'OU=T2 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
22                                                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d13355-d2f9-45cf-9ee6-fdc8230ae4e5', 'distinguishedname': 'OU=T2 GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
23                                                                                                                                                                                                                                                                                                                                                                                                                                            {'domain': 'MARK.LOCAL', 'name': 'T2 Workstations@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-66aadca5-ccbc-46d4-91e7-f74f2527bdb5', 'distinguishedname': 'OU=T2 WORKSTATIONS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
24                                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-d4c0667d-16e8-4afd-8cf3-5f6a900f6913', 'distinguishedname': 'OU=T2 USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
25                                                                                                                                                                                                                                                                                                                                                                                                                                                      {'domain': 'MARK.LOCAL', 'name': 'T2 Servers@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-3f1588f2-5124-4111-8d63-caf4b57a87ca', 'distinguishedname': 'OU=T2 SERVERS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
26                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 Enabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-dd1b08e8-140d-49e3-ab56-1551c008827a', 'distinguishedname': 'OU=T2 ENABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
27                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Disabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-9c9959e1-1718-4648-9aa1-e0eb9920d50c', 'distinguishedname': 'OU=T2 DISABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}

In [ ]:
len(selected_edges)

949

In [ ]:
# import networkx as nx

# # Create a directed graph
# G = nx.DiGraph()

# # Add nodes with their weights
# for index, row in nodes.iterrows():
#     # Ensure node IDs are integers when adding to the graph
#     G.add_node(int(row['id']), weight=row['weight'])

# # Add edges with their weights
# for index, row in edges.iterrows():
#     # Ensure edge endpoints are integers when adding to the graph
#     G.add_edge(int(row['start']), int(row['end']), weight=row['weight'])

# # Compute shortest paths from each source node to all reachable nodes
# shortest_paths = {}
# for source in G.nodes():
#     # Use single_source_dijkstra_path to find paths from one source to all others
#     shortest_paths[source] = nx.single_source_dijkstra_path(G, source)

# # Filter out paths from a node to itself and store in a new dictionary
# shortest_paths_filtered = {
#     source: {
#         target: path
#         for target, path in paths.items()
#         if source != target
#     }
#     for source, paths in shortest_paths.items()
# }

# # Print the shortest paths (optional)
# # for source, paths in shortest_paths_filtered.items():
# #     print(f"Shortest paths from node {source}:")
# #     for target, path in paths.items():
# #         print(f"  To node {target}: {path}")

In [ ]:
tier2_node_ids

In [ ]:
# selected_edges['end'] = selected_edges['end'].apply(lambda x: x['id']).astype(int)
# selected_edges['start'] = selected_edges['start'].apply(lambda x: x['id']).astype(int)

In [47]:
selected_edges

              type start  end              label  weight    id
1300  relationship     1    4           Contains       2     3
1303  relationship     4    7           Contains       2     6
1312  relationship     6   16           Contains       2    15
1313  relationship     6   17           Contains       2    16
1314  relationship     6   18           Contains       2    17
1315  relationship     2   19           Contains       2    18
1319  relationship     3   23           Contains       2    22
1320  relationship     3   24           Contains       2    23
1321  relationship     3   25           Contains       2    24
1322  relationship    24   26           Contains       2    25
1323  relationship    24   27           Contains       2    26
1324  relationship    23   28           Contains       2    27
1325  relationship    23   29           Contains       2    28
1326  relationship    23   30           Contains       2    29
1327  relationship    22   31           Contains       2    30
1328  relationship    22   32           Contains       2    31
1329  relationship    25   33           Contains       2    32
1330  relationship    25   34           Contains       2    33
1331  relationship    25   35           Contains       2    34
1332  relationship     9   65           Contains       2    35
1368  relationship    36    0         GetChanges       3    71
1380  relationship    66    0  AllExtendedRights       6    83
1391  relationship   102   72           MemberOf       1    94
1392  relationship   101  102           Contains       2    95
1393  relationship   102   85           MemberOf       1    96
1394  relationship    66  102            AdminTo       8    97
1586  relationship    98  106           Contains       2   289
1587  relationship    98  107           Contains       2   290
1589  relationship    98  109           Contains       2   292
1590  relationship    98  110           Contains       2   293
1591  relationship    98  111           Contains       2   294
1595  relationship    98  115           Contains       2   298
1596  relationship    98  116           Contains       2   299
1597  relationship    98  117           Contains       2   300
1598  relationship    98  118           Contains       2   301
1601  relationship    98  121           Contains       2   304
1605  relationship    98  125           Contains       2   308
1607  relationship    98  127           Contains       2   310
1608  relationship    98  128           Contains       2   311
1609  relationship    98  129           Contains       2   312
1610  relationship    98  130           Contains       2   313
1611  relationship    98  131           Contains       2   314
1613  relationship    98  133           Contains       2   316
1614  relationship    98  134           Contains       2   317
1615  relationship    98  135           Contains       2   318
1617  relationship    98  137           Contains       2   320
1618  relationship    98  138           Contains       2   321
1619  relationship    98  139           Contains       2   322
1622  relationship    98  142           Contains       2   325
1623  relationship    98  143           Contains       2   326
1624  relationship    98  144           Contains       2   327
1625  relationship    98  145           Contains       2   328
1626  relationship    98  146           Contains       2   329
1627  relationship    98  147           Contains       2   330
1628  relationship    98  148           Contains       2   331
1629  relationship    98  149           Contains       2   332
1630  relationship    98  150           Contains       2   333
1631  relationship    98  151           Contains       2   334
1632  relationship    98  152           Contains       2   335
1633  relationship    98  153           Contains       2   336
1634  relationship    98  154           Contains       2   337
1635  relationship    98  155           Contains       2   338
1636  relationship    98  156           Contains       2   339
1637  relationship    98  157           Contains       2   340
1638  relationship    98  158           Contains       2   341
1639  relationship    98  159           Contains       2   342
1640  relationship    98  160           Contains       2   343
1641  relationship    98  161           Contains       2   344
1642  relationship    98  162           Contains       2   345
1643  relationship    98  163           Contains       2   346
1644  relationship    98  164           Contains       2   347
1645  relationship    98  165           Contains       2   348
1646  relationship    98  166           Contains       2   349
1647  relationship    98  167           Contains       2   350
1648  relationship    98  168           Contains       2   351
1649  relationship    98  169           Contains       2   352
1650  relationship    98  170           Contains       2   353
1651  relationship    98  171           Contains       2   354
1652  relationship    98  172           Contains       2   355
1653  relationship    98  173           Contains       2   356
1654  relationship    98  174           Contains       2   357
1655  relationship    98  175           Contains       2   358
1656  relationship    98  176           Contains       2   359
1657  relationship    98  177           Contains       2   360
1658  relationship    98  178           Contains       2   361
1659  relationship    98  179           Contains       2   362
1660  relationship    98  180           Contains       2   363
1661  relationship    98  181           Contains       2   364
1662  relationship    98  182           Contains       2   365
1663  relationship    98  183           Contains       2   366
1664  relationship    98  184           Contains       2   367
1665  relationship    98  185           Contains       2   368
1666  relationship    98  186           Contains       2   369
1667  relationship    98  187           Contains       2   370
1668  relationship    98  188           Contains       2   371
1669  relationship    98  189           Contains       2   372
1670  relationship    98  190           Contains       2   373
1671  relationship    98  191           Contains       2   374
1672  relationship    98  192           Contains       2   375
1673  relationship    98  193           Contains       2   376
1674  relationship    98  194           Contains       2   377
1675  relationship    98  195           Contains       2   378
1676  relationship    98  196           Contains       2   379
1677  relationship    98  197           Contains       2   380
1678  relationship    98  198           Contains       2   381
1679  relationship    98  199           Contains       2   382
1680  relationship    98  200           Contains       2   383
1681  relationship    98  201           Contains       2   384
1682  relationship    98  202           Contains       2   385
1683  relationship    98  203           Contains       2   386
1684  relationship    98  204           Contains       2   387
1685  relationship    98  205           Contains       2   388
1686  relationship    98  206           Contains       2   389
1687  relationship    98  207           Contains       2   390
1688  relationship    98  208           Contains       2   391
1689  relationship    98  209           Contains       2   392
1690  relationship    98  210           Contains       2   393
1691  relationship    98  211           Contains       2   394
1692  relationship    98  212           Contains       2   395
1693  relationship    98  213           Contains       2   396
1694  relationship    98  214           Contains       2   397
1695  relationship    98  215           Contains       2   398
1696  relationship    98  216           Contains       2   399
1697  relationship    98  217           Contains       2   400
1698  relationship    98  218           Contains       2   401
1699  relationship    98  219           Contains       2   402
1700  relationship    98  220           Contains       2   403
1701  relationship    98  221           Contains       2   404
1702  relationship    98  222           Contains       2   405
1703  relationship    98  223           Contains       2   406
1704  relationship    98  224           Contains       2   407
1705  relationship    98  225           Contains       2   408
1706  relationship    98  226           Contains       2   409
1707  relationship    98  227           Contains       2   410
1708  relationship    98  228           Contains       2   411
1709  relationship    98  229           Contains       2   412
1710  relationship    98  230           Contains       2   413
1711  relationship    98  231           Contains       2   414
1712  relationship    98  232           Contains       2   415
1713  relationship    98  233           Contains       2   416
1714  relationship    98  234           Contains       2   417
1715  relationship    98  235           Contains       2   418
1716  relationship    98  236           Contains       2   419
1717  relationship    98  237           Contains       2   420
1718  relationship    98  238           Contains       2   421
1719  relationship    98  239           Contains       2   422
1720  relationship    98  240           Contains       2   423
1721  relationship    98  241           Contains       2   424
1722  relationship    98  242           Contains       2   425
1723  relationship    98  243           Contains       2   426
1724  relationship    98  244           Contains       2   427
1725  relationship    98  245           Contains       2   428
1726  relationship    98  246           Contains       2   429
1727  relationship    98  247           Contains       2   430
1728  relationship    98  248           Contains       2   431
1729  relationship    98  249           Contains       2   432
1730  relationship    98  250           Contains       2   433
1731  relationship    98  251           Contains       2   434
1732  relationship    98  252           Contains       2   435
1733  relationship    98  253           Contains       2   436
1734  relationship    98  254           Contains       2   437
1735  relationship    98  255           Contains       2   438
1736  relationship    98  256           Contains       2   439
1737  relationship    98  257           Contains       2   440
1738  relationship    98  258           Contains       2   441
1739  relationship    98  259           Contains       2   442
1740  relationship    98  260           Contains       2   443
1741  relationship    98  261           Contains       2   444
1742  relationship    98  262           Contains       2   445
1743  relationship    98  263           Contains       2   446
1744  relationship    98  264           Contains       2   447
1745  relationship    98  265           Contains       2   448
1746  relationship    98  266           Contains       2   449
1747  relationship    98  267           Contains       2   450
1748  relationship    98  268           Contains       2   451
1749  relationship    98  269           Contains       2   452
1750  relationship    98  270           Contains       2   453
1751  relationship    98  271           Contains       2   454
1752  relationship    98  272           Contains       2   455
1753  relationship    98  273           Contains       2   456
1759  relationship    98  279           Contains       2   462
1760  relationship    98  280           Contains       2   463
1761  relationship    98  281           Contains       2   464
1762  relationship    98  282           Contains       2   465
1763  relationship    98  283           Contains       2   466
1765  relationship     0  285           Contains       2   468
1767  relationship     0  287           Contains       2   470
1768  relationship    36  284               Owns      10   471
1769  relationship    60  284         GenericAll       9   472
1770  relationship    66  284         GenericAll       9   473
1771  relationship    65  284         GenericAll       9   474
1772  relationship    36  284          WriteDacl       5   475
1773  relationship    36  284         WriteOwner       7   476
1774  relationship    36  284  AllExtendedRights       6   477
1775  relationship    36  284       GenericWrite       2   478
1776  relationship    36  285               Owns      10   479
1777  relationship    60  285         GenericAll       9   480
1778  relationship    66  285         GenericAll       9   481
1779  relationship    65  285         GenericAll       9   482
1780  relationship    36  285          WriteDacl       5   483
1781  relationship    36  285         WriteOwner       7   484
1782  relationship    36  285  AllExtendedRights       6   485
1783  relationship    36  285       GenericWrite       2   486
1784  relationship    66  286               Owns      10   487
1785  relationship    36  286          WriteDacl       5   488
1786  relationship    36  286         WriteOwner       7   489
1787  relationship    36  286  AllExtendedRights       6   490
1789  relationship    66  286          WriteDacl       5   492
1790  relationship    66  286         WriteOwner       7   493
1791  relationship    66  286  AllExtendedRights       6   494
1792  relationship    66  286       GenericWrite       2   495
1793  relationship    65  286          WriteDacl       5   496
1794  relationship    65  286         WriteOwner       7   497
1795  relationship    65  286  AllExtendedRights       6   498
1796  relationship    65  286       GenericWrite       2   499
1797  relationship    66  287               Owns      10   500
1798  relationship    36  287          WriteDacl       5   501
1799  relationship    36  287         WriteOwner       7   502
1800  relationship    36  287  AllExtendedRights       6   503
1801  relationship    36  287       GenericWrite       2   504
1802  relationship    66  287          WriteDacl       5   505
1803  relationship    66  287         WriteOwner       7   506
1804  relationship    66  287  AllExtendedRights       6   507
1806  relationship    65  287          WriteDacl       5   509
1807  relationship    65  287         WriteOwner       7   510
1808  relationship    65  287  AllExtendedRights       6   511
1810  relationship   286   38           MemberOf       1   513
1812  relationship   286   59           MemberOf       1   515
1813  relationship   286   60           MemberOf       1   516
1814  relationship   286   65           MemberOf       1   517
1815  relationship   286   66           MemberOf       1   518
1816  relationship   286   72           MemberOf       1   519
1817  relationship   286   75           MemberOf       1   520
1818  relationship    66   36           MemberOf       1   521
1819  relationship   286   36           MemberOf       1   522
1821  relationship    76   48           MemberOf       1   524
1822  relationship   284   48           MemberOf       1   525
1823  relationship   285   49           MemberOf       1   526
1825  relationship    87   50           MemberOf       1   528
1826  relationship    89   50           MemberOf       1   529
1830  relationship    75   63           MemberOf       1   533
1832  relationship    58   63           MemberOf       1   535
1833  relationship    65   63           MemberOf       1   536
1834  relationship    64   63           MemberOf       1   537
1835  relationship    72   63           MemberOf       1   538
1836  relationship   287   63           MemberOf       1   539
1837  relationship   286   64           MemberOf       1   540
1838  relationship   285   74           MemberOf       1   541
1839  relationship   286   74           MemberOf       1   542
1840  relationship   287   74           MemberOf       1   543
1842  relationship    90   85           MemberOf       1   545
1843  relationship    73   86           MemberOf       1   546
1844  relationship    74   86           MemberOf       1   547
1845  relationship    73   87           MemberOf       1   548
1846  relationship    74   87           MemberOf       1   549
1848  relationship    66   36         WriteOwner       7   551
1849  relationship    66   36       GenericWrite       2   552
1851  relationship    65   36       GenericWrite       2   554
1852  relationship    36   37               Owns      10   555
1853  relationship    60   37         GenericAll       9   556
1854  relationship    66   37         GenericAll       9   557
1855  relationship    65   37         GenericAll       9   558
1856  relationship    36   37          WriteDacl       5   559
1857  relationship    36   37         WriteOwner       7   560
1859  relationship    66   38               Owns      10   562
1862  relationship    66   38          WriteDacl       5   565
1863  relationship    66   38         WriteOwner       7   566
1864  relationship    65   38          WriteDacl       5   567
1865  relationship    65   38         WriteOwner       7   568
1866  relationship    36   39               Owns      10   569
1867  relationship    60   39         GenericAll       9   570
1868  relationship    66   39         GenericAll       9   571
1869  relationship    65   39         GenericAll       9   572
1870  relationship    36   39          WriteDacl       5   573
1871  relationship    36   39         WriteOwner       7   574
1873  relationship    66   40               Owns      10   576
1875  relationship    36   40         WriteOwner       7   578
1876  relationship    66   40          WriteDacl       5   579
1877  relationship    66   40         WriteOwner       7   580
1878  relationship    65   40          WriteDacl       5   581
1879  relationship    65   40         WriteOwner       7   582
1880  relationship    36   41               Owns      10   583
1881  relationship    60   41         GenericAll       9   584
1883  relationship    65   41         GenericAll       9   586
1884  relationship    36   41          WriteDacl       5   587
1885  relationship    36   41         WriteOwner       7   588
1886  relationship    36   41       GenericWrite       2   589
1888  relationship    60   42         GenericAll       9   591
1889  relationship    66   42         GenericAll       9   592
1890  relationship    65   42         GenericAll       9   593
1891  relationship    36   42          WriteDacl       5   594
1892  relationship    36   42         WriteOwner       7   595
1893  relationship    36   42       GenericWrite       2   596
1895  relationship    36   43          WriteDacl       5   598
1898  relationship    66   43          WriteDacl       5   601
1899  relationship    66   43         WriteOwner       7   602
1900  relationship    66   43       GenericWrite       2   603
1901  relationship    65   43          WriteDacl       5   604
1902  relationship    65   43         WriteOwner       7   605
1903  relationship    65   43       GenericWrite       2   606
1905  relationship    60   44         GenericAll       9   608
1906  relationship    66   44         GenericAll       9   609
1908  relationship    36   44          WriteDacl       5   611
1909  relationship    36   44         WriteOwner       7   612
1910  relationship    36   44       GenericWrite       2   613
1911  relationship    36   45               Owns      10   614
1912  relationship    60   45         GenericAll       9   615
1913  relationship    66   45         GenericAll       9   616
1914  relationship    65   45         GenericAll       9   617
1915  relationship    36   45          WriteDacl       5   618
1916  relationship    36   45         WriteOwner       7   619
1918  relationship    36   46               Owns      10   621
1919  relationship    60   46         GenericAll       9   622
1924  relationship    36   46       GenericWrite       2   627
1925  relationship    36   47               Owns      10   628
1926  relationship    60   47         GenericAll       9   629

In [74]:
import networkx as nx

# Create a directed graph
G = nx.DiGraph()

# Add nodes with their weights
for index, row in selected_nodes.iterrows():
    # Ensure node IDs are integers when adding to the graph
    G.add_node(int(row['id']), weight=row['weight'])

# Add edges with their weights
for index, row in edges.iterrows():
    # Ensure edge endpoints are integers when adding to the graph
    G.add_edge(row['start'], row['end'], weight=row['weight'])

# Compute shortest paths from each source node to all reachable nodes
shortest_paths = {}
for source in G.nodes():
    # Use single_source_dijkstra_path to find paths from one source to all others
    shortest_paths[source] = nx.single_source_dijkstra_path(G, source)

# Filter out paths from a node to itself and store in a new dictionary
shortest_paths_filtered = {
    source: {
        target: path
        for target, path in paths.items()
        if source != target
    }
    for source, paths in shortest_paths.items()
}

# Print the shortest paths (optional)
for source, paths in shortest_paths_filtered.items():
    print(f"Shortest paths from node {source}:")
    for target, path in paths.items():
        print(f"  To node {target}: {path}")

Streaming output truncated to the last 5000 lines.
  To node 831: ['870', '30', '569', '362', '780', '92', '711', '831']
  To node 832: ['870', '30', '569', '362', '780', '92', '711', '832']
  To node 833: ['870', '30', '569', '362', '780', '92', '711', '833']
  To node 835: ['870', '30', '569', '362', '780', '92', '711', '835']
  To node 847: ['870', '30', '569', '362', '780', '92', '711', '847']
  To node 848: ['870', '30', '569', '362', '780', '92', '711', '848']
  To node 851: ['870', '30', '569', '362', '780', '92', '711', '851']
  To node 857: ['870', '30', '569', '362', '780', '92', '711', '857']
  To node 864: ['870', '30', '569', '362', '780', '92', '711', '864']
  To node 868: ['870', '30', '569', '362', '780', '92', '711', '868']
  To node 869: ['870', '30', '569', '362', '780', '92', '711', '869']
  To node 871: ['870', '30', '569', '362', '780', '92', '711', '871']
  To node 872: ['870', '30', '569', '362', '780', '92', '711', '872']
  To node 873: ['870', '30', '569', '362', '780', '92', '711', '873']
  To node 19: ['870', '30', '486', '371', '700', '66', '286', '59', '19']
  To node 323: ['870', '30', '486', '371', '700', '66', '14', '323']
  To node 288: ['870', '30', '486', '371', '700', '66', '11', '288']
  To node 302: ['870', '30', '486', '371', '700', '66', '11', '302']
  To node 693: ['870', '30', '486', '371', '700', '66', '11', '693']
  To node 1200: ['870', '30', '495', '377', '705', '60', '26', '336', '1200']
  To node 1139: ['870', '30', '495', '377', '705', '60', '26', '345', '1139']
  To node 1242: ['870', '30', '495', '377', '705', '60', '26', '345', '1242']
  To node 1218: ['870', '30', '495', '377', '705', '60', '26', '348', '1218']
  To node 1143: ['870', '30', '495', '377', '705', '60', '26', '348', '1143']
  To node 1167: ['870', '30', '495', '377', '705', '60', '26', '356', '1167']
  To node 1150: ['870', '30', '495', '377', '705', '60', '26', '364', '1150']
  To node 1163: ['870', '30', '495', '377', '705', '60', '26', '393', '1163']
  To node 1145: ['870', '30', '495', '377', '705', '60', '26', '424', '1145']
  To node 1268: ['870', '30', '495', '377', '705', '60', '26', '425', '1268']
  To node 1174: ['870', '30', '495', '377', '705', '60', '26', '425', '1174']
  To node 1264: ['870', '30', '495', '377', '705', '60', '26', '440', '1264']
  To node 1188: ['870', '30', '495', '377', '705', '60', '26', '440', '1188']
  To node 1158: ['870', '30', '495', '377', '705', '60', '26', '449', '1158']
  To node 290: ['870', '30', '494', '387', '710', '91', '27', '290']
  To node 292: ['870', '30', '494', '387', '710', '91', '27', '292']
  To node 298: ['870', '30', '494', '387', '710', '91', '27', '298']
  To node 300: ['870', '30', '494', '387', '710', '91', '27', '300']
  To node 310: ['870', '30', '494', '387', '710', '91', '27', '310']
  To node 316: ['870', '30', '494', '387', '710', '91', '27', '316']
  To node 317: ['870', '30', '494', '387', '710', '91', '27', '317']
  To node 342: ['870', '30', '494', '387', '710', '91', '27', '342']
  To node 351: ['870', '30', '494', '387', '710', '91', '27', '351']
  To node 354: ['870', '30', '494', '387', '710', '91', '27', '354']
  To node 355: ['870', '30', '494', '387', '710', '91', '27', '355']
  To node 358: ['870', '30', '494', '387', '710', '91', '27', '358']
  To node 359: ['870', '30', '494', '387', '710', '91', '27', '359']
  To node 366: ['870', '30', '494', '387', '710', '91', '27', '366']
  To node 368: ['870', '30', '494', '387', '710', '91', '27', '368']
  To node 370: ['870', '30', '494', '387', '710', '91', '27', '370']
  To node 374: ['870', '30', '494', '387', '710', '91', '27', '374']
  To node 376: ['870', '30', '494', '387', '710', '91', '27', '376']
  To node 379: ['870', '30', '494', '387', '710', '91', '27', '379']
  To node 380: ['870', '30', '494', '387', '710', '91', '27', '380']
  To node 390: ['870', '30', '494', '387', '710', '91', '27', '390']
  To node 392: ['870', '30', '494', '387', '710', '91', '27', '392']
  To node 394: ['870', '30', '494', '387', '710', '91', '27', '394']
  To node 398: ['870', '30', '494', '387', '710', '91', '27', '398']
  To node 417: ['870', '30', '494', '387', '710', '91', '27', '417']
  To node 419: ['870', '30', '494', '387', '710', '91', '27', '419']
  To node 420: ['870', '30', '494', '387', '710', '91', '27', '420']
  To node 427: ['870', '30', '494', '387', '710', '91', '27', '427']
  To node 430: ['870', '30', '494', '387', '710', '91', '27', '430']
  To node 432: ['870', '30', '494', '387', '710', '91', '27', '432']
  To node 434: ['870', '30', '494', '387', '710', '91', '27', '434']
  To node 451: ['870', '30', '494', '387', '710', '91', '27', '451']
  To node 453: ['870', '30', '494', '387', '710', '91', '27', '453']
  To node 465: ['870', '30', '494', '387', '710', '91', '27', '465']
  To node 472: ['870', '30', '494', '387', '710', '91', '27', '472']
  To node 474: ['870', '30', '494', '387', '710', '91', '27', '474']
  To node 480: ['870', '30', '494', '387', '710', '91', '27', '480']
  To node 511: ['870', '30', '495', '377', '705', '60', '34', '511']
  To node 521: ['870', '30', '495', '377', '705', '60', '34', '521']
  To node 533: ['870', '30', '495', '377', '705', '60', '34', '533']
  To node 562: ['870', '30', '495', '377', '705', '60', '34', '562']
  To node 603: ['870', '30', '495', '377', '705', '60', '34', '603']
  To node 649: ['870', '30', '495', '377', '705', '60', '34', '649']
  To node 666: ['870', '30', '495', '377', '705', '60', '34', '666']
  To node 673: ['870', '30', '495', '377', '705', '60', '34', '673']
  To node 461: ['870', '30', '486', '371', '700', '66', '11', '461']
  To node 459: ['870', '30', '486', '371', '700', '66', '11', '459']
  To node 469: ['870', '30', '486', '371', '700', '66', '7', '469']
  To node 309: ['870', '30', '486', '371', '700', '66', '11', '309']
  To node 1249: ['870', '30', '495', '377', '705', '60', '26', '336', '1200', '1249']
  To node 1290: ['870', '30', '495', '377', '705', '60', '26', '393', '1163', '1290']
  To node 692: ['870', '30', '486', '371', '700', '66', '7', '692']
  To node 295: ['870', '30', '486', '371', '700', '66', '7', '295']
  To node 303: ['870', '30', '486', '371', '700', '66', '7', '303']
  To node 306: ['870', '30', '486', '371', '700', '66', '7', '306']
  To node 307: ['870', '30', '486', '371', '700', '66', '7', '307']
  To node 324: ['870', '30', '486', '371', '700', '66', '7', '324']
  To node 457: ['870', '30', '486', '371', '700', '66', '7', '457']
  To node 458: ['870', '30', '486', '371', '700', '66', '7', '458']
  To node 296: ['870', '30', '486', '371', '700', '66', '10', '296']
  To node 305: ['870', '30', '486', '371', '700', '66', '10', '305']
  To node 507: ['870', '30', '569', '362', '780', '92', '35', '507']
  To node 557: ['870', '30', '569', '362', '780', '92', '35', '557']
  To node 565: ['870', '30', '569', '362', '780', '92', '35', '565']
  To node 573: ['870', '30', '569', '362', '780', '92', '35', '573']
  To node 638: ['870', '30', '569', '362', '780', '92', '35', '638']
  To node 668: ['870', '30', '569', '362', '780', '92', '35', '668']
  To node 99: ['870', '30', '486', '371', '700', '66', '98', '99']
  To node 100: ['870', '30', '486', '371', '700', '66', '98', '100']
  To node 105: ['870', '30', '486', '371', '700', '66', '98', '105']
  To node 106: ['870', '30', '486', '371', '700', '66', '98', '106']
  To node 107: ['870', '30', '486', '371', '700', '66', '98', '107']
  To node 108: ['870', '30', '486', '371', '700', '66', '98', '108']
  To node 109: ['870', '30', '486', '371', '700', '66', '98', '109']
  To node 110: ['870', '30', '486', '371', '700', '66', '98', '110']
  To node 111: ['870', '30', '486', '371', '700', '66', '98', '111']
  To node 112: ['870', '30', '486', '371', '700', '66', '98', '112']
  To node 113: ['870', '30', '486', '371', '700', '66', '98', '113']
  To node 114: ['870', '30', '486', '371', '700', '66', '98', '114']
  To node 115: ['870', '30', '486', '371', '700', '66', '98', '115']
  To node 116: ['870', '30', '486', '371', '700', '66', '98', '116']
  To node 117: ['870', '30', '486', '371', '700', '66', '98', '117']
  To node 118: ['870', '30', '486', '371', '700', '66', '98', '118']
  To node 119: ['870', '30', '486', '371', '700', '66', '98', '119']
  To node 120: ['870', '30', '486', '371', '700', '66', '98', '120']
  To node 121: ['870', '30', '486', '371', '700', '66', '98', '121']
  To node 122: ['870', '30', '486', '371', '700', '66', '98', '122']
  To node 123: ['870', '30', '486', '371', '700', '66', '98', '123']
  To node 124: ['870', '30', '486', '371', '700', '66', '98', '124']
  To node 125: ['870', '30', '486', '371', '700', '66', '98', '125']
  To node 126: ['870', '30', '486', '371', '700', '66', '98', '126']
  To node 127: ['870', '30', '486', '371', '700', '66', '98', '127']
  To node 128: ['870', '30', '486', '371', '700', '66', '98', '128']
  To node 129: ['870', '30', '486', '371', '700', '66', '98', '129']
  To node 130: ['870', '30', '486', '371', '700', '66', '98', '130']
  To node 131: ['870', '30', '486', '371', '700', '66', '98', '131']
  To node 132: ['870', '30', '486', '371', '700', '66', '98', '132']
  To node 133: ['870', '30', '486', '371', '700', '66', '98', '133']
  To node 134: ['870', '30', '486', '371', '700', '66', '98', '134']
  To node 135: ['870', '30', '486', '371', '700', '66', '98', '135']
  To node 136: ['870', '30', '486', '371', '700', '66', '98', '136']
  To node 137: ['870', '30', '486', '371', '700', '66', '98', '137']
  To node 138: ['870', '30', '486', '371', '700', '66', '98', '138']
  To node 139: ['870', '30', '486', '371', '700', '66', '98', '139']
  To node 140: ['870', '30', '486', '371', '700', '66', '98', '140']
  To node 141: ['870', '30', '486', '371', '700', '66', '98', '141']
  To node 142: ['870', '30', '486', '371', '700', '66', '98', '142']
  To node 143: ['870', '30', '486', '371', '700', '66', '98', '143']
  To node 144: ['870', '30', '486', '371', '700', '66', '98', '144']
  To node 145: ['870', '30', '486', '371', '700', '66', '98', '145']
  To node 146: ['870', '30', '486', '371', '700', '66', '98', '146']
  To node 147: ['870', '30', '486', '371', '700', '66', '98', '147']
  To node 148: ['870', '30', '486', '371', '700', '66', '98', '148']
  To node 149: ['870', '30', '486', '371', '700', '66', '98', '149']
  To node 150: ['870', '30', '486', '371', '700', '66', '98', '150']
  To node 151: ['870', '30', '486', '371', '700', '66', '98', '151']
  To node 152: ['870', '30', '486', '371', '700', '66', '98', '152']
  To node 153: ['870', '30', '486', '371', '700', '66', '98', '153']
  To node 154: ['870', '30', '486', '371', '700', '66', '98', '154']
  To node 155: ['870', '30', '486', '371', '700', '66', '98', '155']
  To node 156: ['870', '30', '486', '371', '700', '66', '98', '156']
  To node 157: ['870', '30', '486', '371', '700', '66', '98', '157']
  To node 158: ['870', '30', '486', '371', '700', '66', '98', '158']
  To node 159: ['870', '30', '486', '371', '700', '66', '98', '159']
  To node 160: ['870', '30', '486', '371', '700', '66', '98', '160']
  To node 161: ['870', '30', '486', '371', '700', '66', '98', '161']
  To node 162: ['870', '30', '486', '371', '700', '66', '98', '162']
  To node 163: ['870', '30', '486', '371', '700', '66', '98', '163']
  To node 164: ['870', '30', '486', '371', '700', '66', '98', '164']
  To node 165: ['870', '30', '486', '371', '700', '66', '98', '165']
  To node 166: ['870', '30', '486', '371', '700', '66', '98', '166']
  To node 167: ['870', '30', '486', '371', '700', '66', '98', '167']
  To node 168: ['870', '30', '486', '371', '700', '66', '98', '168']
  To node 169: ['870', '30', '486', '371', '700', '66', '98', '169']
  To node 170: ['870', '30', '486', '371', '700', '66', '98', '170']
  To node 171: ['870', '30', '486', '371', '700', '66', '98', '171']
  To node 172: ['870', '30', '486', '371', '700', '66', '98', '172']
  To node 173: ['870', '30', '486', '371', '700', '66', '98', '173']
  To node 174: ['870', '30', '486', '371', '700', '66', '98', '174']
  To node 175: ['870', '30', '486', '371', '700', '66', '98', '175']
  To node 176: ['870', '30', '486', '371', '700', '66', '98', '176']
  To node 177: ['870', '30', '486', '371', '700', '66', '98', '177']
  To node 178: ['870', '30', '486', '371', '700', '66', '98', '178']
  To node 179: ['870', '30', '486', '371', '700', '66', '98', '179']
  To node 180: ['870', '30', '486', '371', '700', '66', '98', '180']
  To node 181: ['870', '30', '486', '371', '700', '66', '98', '181']
  To node 182: ['870', '30', '486', '371', '700', '66', '98', '182']
  To node 183: ['870', '30', '486', '371', '700', '66', '98', '183']
  To node 184: ['870', '30', '486', '371', '700', '66', '98', '184']
  To node 185: ['870', '30', '486', '371', '700', '66', '98', '185']
  To node 186: ['870', '30', '486', '371', '700', '66', '98', '186']
  To node 187: ['870', '30', '486', '371', '700', '66', '98', '187']
  To node 188: ['870', '30', '486', '371', '700', '66', '98', '188']
  To node 189: ['870', '30', '486', '371', '700', '66', '98', '189']
  To node 190: ['870', '30', '486', '371', '700', '66', '98', '190']
  To node 191: ['870', '30', '486', '371', '700', '66', '98', '191']
  To node 192: ['870', '30', '486', '371', '700', '66', '98', '192']
  To node 193: ['870', '30', '486', '371', '700', '66', '98', '193']
  To node 194: ['870', '30', '486', '371', '700', '66', '98', '194']
  To node 195: ['870', '30', '486', '371', '700', '66', '98', '195']
  To node 196: ['870', '30', '486', '371', '700', '66', '98', '196']
  To node 197: ['870', '30', '486', '371', '700', '66', '98', '197']
  To node 198: ['870', '30', '486', '371', '700', '66', '98', '198']
  To node 199: ['870', '30', '486', '371', '700', '66', '98', '199']
  To node 200: ['870', '30', '486', '371', '700', '66', '98', '200']
  To node 201: ['870', '30', '486', '371', '700', '66', '98', '201']
  To node 202: ['870', '30', '486', '371', '700', '66', '98', '202']
  To node 203: ['870', '30', '486', '371', '700', '66', '98', '203']
  To node 204: ['870', '30', '486', '371', '700', '66', '98', '204']
  To node 205: ['870', '30', '486', '371', '700', '66', '98', '205']
  To node 206: ['870', '30', '486', '371', '700', '66', '98', '206']
  To node 207: ['870', '30', '486', '371', '700', '66', '98', '207']
  To node 208: ['870', '30', '486', '371', '700', '66', '98', '208']
  To node 209: ['870', '30', '486', '371', '700', '66', '98', '209']
  To node 210: ['870', '30', '486', '371', '700', '66', '98', '210']
  To node 211: ['870', '30', '486', '371', '700', '66', '98', '211']
  To node 212: ['870', '30', '486', '371', '700', '66', '98', '212']
  To node 213: ['870', '30', '486', '371', '700', '66', '98', '213']
  To node 214: ['870', '30', '486', '371', '700', '66', '98', '214']
  To node 215: ['870', '30', '486', '371', '700', '66', '98', '215']
  To node 216: ['870', '30', '486', '371', '700', '66', '98', '216']
  To node 217: ['870', '30', '486', '371', '700', '66', '98', '217']
  To node 218: ['870', '30', '486', '371', '700', '66', '98', '218']
  To node 219: ['870', '30', '486', '371', '700', '66', '98', '219']
  To node 220: ['870', '30', '486', '371', '700', '66', '98', '220']
  To node 221: ['870', '30', '486', '371', '700', '66', '98', '221']
  To node 222: ['870', '30', '486', '371', '700', '66', '98', '222']
  To node 223: ['870', '30', '486', '371', '700', '66', '98', '223']
  To node 224: ['870', '30', '486', '371', '700', '66', '98', '224']
  To node 225: ['870', '30', '486', '371', '700', '66', '98', '225']
  To node 226: ['870', '30', '486', '371', '700', '66', '98', '226']
  To node 227: ['870', '30', '486', '371', '700', '66', '98', '227']
  To node 228: ['870', '30', '486', '371', '700', '66', '98', '228']
  To node 229: ['870', '30', '486', '371', '700', '66', '98', '229']
  To node 230: ['870', '30', '486', '371', '700', '66', '98', '230']
  To node 231: ['870', '30', '486', '371', '700', '66', '98', '231']
  To node 232: ['870', '30', '486', '371', '700', '66', '98', '232']
  To node 233: ['870', '30', '486', '371', '700', '66', '98', '233']
  To node 234: ['870', '30', '486', '371', '700', '66', '98', '234']
  To node 235: ['870', '30', '486', '371', '700', '66', '98', '235']
  To node 236: ['870', '30', '486', '371', '700', '66', '98', '236']
  To node 237: ['870', '30', '486', '371', '700', '66', '98', '237']
  To node 238: ['870', '30', '486', '371', '700', '66', '98', '238']
  To node 239: ['870', '30', '486', '371', '700', '66', '98', '239']
  To node 240: ['870', '30', '486', '371', '700', '66', '98', '240']
  To node 241: ['870', '30', '486', '371', '700', '66', '98', '241']
  To node 242: ['870', '30', '486', '371', '700', '66', '98', '242']
  To node 243: ['870', '30', '486', '371', '700', '66', '98', '243']
  To node 244: ['870', '30', '486', '371', '700', '66', '98', '244']
  To node 245: ['870', '30', '486', '371', '700', '66', '98', '245']
  To node 246: ['870', '30', '486', '371', '700', '66', '98', '246']
  To node 247: ['870', '30', '486', '371', '700', '66', '98', '247']
  To node 248: ['870', '30', '486', '371', '700', '66', '98', '248']
  To node 249: ['870', '30', '486', '371', '700', '66', '98', '249']
  To node 250: ['870', '30', '486', '371', '700', '66', '98', '250']
  To node 251: ['870', '30', '486', '371', '700', '66', '98', '251']
  To node 252: ['870', '30', '486', '371', '700', '66', '98', '252']
  To node 253: ['870', '30', '486', '371', '700', '66', '98', '253']
  To node 254: ['870', '30', '486', '371', '700', '66', '98', '254']
  To node 255: ['870', '30', '486', '371', '700', '66', '98', '255']
  To node 256: ['870', '30', '486', '371', '700', '66', '98', '256']
  To node 257: ['870', '30', '486', '371', '700', '66', '98', '257']
  To node 258: ['870', '30', '486', '371', '700', '66', '98', '258']
  To node 259: ['870', '30', '486', '371', '700', '66', '98', '259']
  To node 260: ['870', '30', '486', '371', '700', '66', '98', '260']
  To node 261: ['870', '30', '486', '371', '700', '66', '98', '261']
  To node 262: ['870', '30', '486', '371', '700', '66', '98', '262']
  To node 263: ['870', '30', '486', '371', '700', '66', '98', '263']
  To node 264: ['870', '30', '486', '371', '700', '66', '98', '264']
  To node 265: ['870', '30', '486', '371', '700', '66', '98', '265']
  To node 266: ['870', '30', '486', '371', '700', '66', '98', '266']
  To node 267: ['870', '30', '486', '371', '700', '66', '98', '267']
  To node 268: ['870', '30', '486', '371', '700', '66', '98', '268']
  To node 269: ['870', '30', '486', '371', '700', '66', '98', '269']
  To node 270: ['870', '30', '486', '371', '700', '66', '98', '270']
  To node 271: ['870', '30', '486', '371', '700', '66', '98', '271']
  To node 272: ['870', '30', '486', '371', '700', '66', '98', '272']
  To node 273: ['870', '30', '486', '371', '700', '66', '98', '273']
  To node 274: ['870', '30', '486', '371', '700', '66', '98', '274']
  To node 275: ['870', '30', '486', '371', '700', '66', '98', '275']
  To node 276: ['870', '30', '486', '371', '700', '66', '98', '276']
  To node 277: ['870', '30', '486', '371', '700', '66', '98', '277']
  To node 278: ['870', '30', '486', '371', '700', '66', '98', '278']
  To node 279: ['870', '30', '486', '371', '700', '66', '98', '279']
  To node 280: ['870', '30', '486', '371', '700', '66', '98', '280']
  To node 281: ['870', '30', '486', '371', '700', '66', '98', '281']
  To node 282: ['870', '30', '486', '371', '700', '66', '98', '282']
  To node 283: ['870', '30', '486', '371', '700', '66', '98', '283']
  To node 686: ['870', '30', '569', '362', '780', '92', '711', '869', '8', '686']
  To node 527: ['870', '30', '569', '362', '780', '92', '711', '869', '8', '527']
  To node 530: ['870', '30', '569', '362', '780', '92', '711', '869', '8', '530']
  To node 531: ['870', '30', '569', '362', '780', '92', '711', '869', '8', '531']

In [51]:
# prompt: save the df_compuers as json to content

import json

# Assuming df_computers is already defined as in your provided code.

# Convert the DataFrame to a JSON string.
selected_edges_json = selected_edges.to_json(orient='records')

# Save the JSON string to a file named 'content.json'.
with open('selected_edges.json', 'w') as f:
  f.write(selected_edges_json)

In [52]:
# prompt: save the df_compuers as json to content

import json

# Assuming df_computers is already defined as in your provided code.

# Convert the DataFrame to a JSON string.
selected_nodes_json = selected_nodes.to_json(orient='records')

# Save the JSON string to a file named 'content.json'.
with open('selected_nodes.json', 'w') as f:
  f.write(selected_nodes_json)

In [55]:
# prompt: export shortest_paths_filtered to json and save as shortest_paths_filtered_json

shortest_paths_filtered_json = json.dumps(shortest_paths_filtered, indent=2)

# Optionally, save the JSON string to a file
with open('shortest_paths_filtered.json', 'w') as f:
  f.write(shortest_paths_filtered_json)

In [86]:
# prompt: for each record in "shortest_paths_filtered" add up the weights and find the smallest and largest combined weights and the path for the largest weight

# Function to calculate the total weight of a path
def calculate_path_weight(graph, path):
    total_weight = 0
    for i in range(len(path) - 1):
        # Add node weight
        total_weight += graph.nodes[path[i]].get('weight', 0)
        # Add edge weight
        total_weight += graph[path[i]][path[i+1]].get('weight', 0)
    # Add the weight of the last node in the path
    if path:
        total_weight += graph.nodes[path[-1]].get('weight', 0)
    return total_weight

all_path_weights = {}

# Iterate through each source and its paths in shortest_paths_filtered
for source, paths_from_source in shortest_paths_filtered.items():
    all_path_weights[source] = {}
    # Iterate through each target and its path
    for target, path in paths_from_source.items():
        # Calculate the weight of the path using the original graph G
        weight = calculate_path_weight(G, path)
        all_path_weights[source][target] = weight

# Find the smallest and largest combined weights
min_weight = float('inf')
max_weight = float('-inf')
largest_weight_path = None
largest_weight_source = None
largest_weight_target = None

for source, paths_from_source in all_path_weights.items():
    for target, weight in paths_from_source.items():
        if weight < min_weight:
            min_weight_source = source
            min_weight_target = target
            min_weight_path = shortest_paths_filtered[source][target]
            min_weight = weight
        if weight > max_weight:
            max_weight = weight
            largest_weight_source = source
            largest_weight_target = target
            largest_weight_path = shortest_paths_filtered[source][target]

print(f"Smallest combined weight: {min_weight}")
print(f"Path for the smallest weight: {min_weight_path}")
print(f"Source for the smallest weight path: {min_weight_source}")
print(f"Target for the smallest weight path: {min_weight_target}")
print(f"Largest combined weight: {max_weight}")
print(f"Path for the largest weight: {largest_weight_path}")
print(f"Source for the largest weight path: {largest_weight_source}")
print(f"Target for the largest weight path: {largest_weight_target}")

Smallest combined weight: 1
Path for the smallest weight: ['64', '63']
Source for the smallest weight path: 64
Target for the smallest weight path: 63
Largest combined weight: 43
Path for the largest weight: ['660', '313', '94', '698', '710', '91', '26', '329', '700', '66', '286', '59', '19', '689']
Source for the largest weight path: 660
Target for the largest weight path: 689

In [91]:

print(nodes[nodes['id'] == 660])
print(nodes[nodes['id'] == 313])
print(nodes[nodes['id'] == 94])
print(nodes[nodes['id'] == 698])
print(nodes[nodes['id'] == 710])
print(nodes[nodes['id'] == 91])

      id  \
660  660

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  properties  \
660  {'name': 'PAW-00023@MARK.LOCAL', 'operatingsystem': 'Windows 10 Enterprise', 'enabled': True, 'haslaps': False, 'highvalue': True, 'lastlogontimestamp': -1, 'pwdlastset': 0, 'serviceprincipalnames': 'TERMSRV/PAW-00023@MARK.LOCAL,TERMSRV/PAW-00023@MARK.LOCAL,RestrictedKrbHost/PAW-00023@MARK,HOST/PAW-00023@MARK,RestrictedKrbHost/PAW-00023@MARK.LOCAL,HOST/PAW-00023@MARK.LOCAL', 'unconstraineddelegation': False, 'privesc': True, 'creddump': True, 'exploitable': False, 'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1385', 'owned': False, 'distinguishedname': 'CN=PAW-00023,OU=T2 Admin Devices,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}

     type    l1        l2    l3  weight
660  node  Base  Computer  None      20
      id  \
313  313

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       properties  \
313  {'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1036', 'displayname': 'Yuri Dubow', 'name': 'YDUBOW00026@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 1742809157, 'lastlogontimestamp': 1742809157, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=YDUBOW00026,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}

     type    l1    l2    l3  weight
313  node  Base  User  None      20
    id  \
94  94

                                                                                                                                                                                                                                                                                                  properties  \
94  {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1004', 'distinguishedname': 'CN=T2 ADMIN ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}

    type    l1     l2    l3  weight
94  node  Base  Group  None      20
      id  \
698  698

                                                                                                                                                                                                                                                                                                            properties  \
698  {'domain': 'MARK.LOCAL', 'name': 'T2 Distribution HR@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-d3c1cf84-4d4f-473b-9b16-09f539d4d39a', 'distinguishedname': 'OU=T2 DISTRIBUTION HR,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}

     type    l1  l2    l3  weight
698  node  Base  OU  None       1
      id  \
710  710

                                                                                                                                                                                                                                                                                                                                                                            properties  \
710  {'domain': 'MARK.LOCAL', 'name': 'T2 Distribution HR_AZ@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1431', 'distinguishedname': 'CN=T2 DISTRIBUTION HR_AZ,OU=T2 Distribution HR,OU=T2 Distribution Groups,OU=T2 Groups,OU=Tier 2,DC=MARK,DC=LOCAL', 'description': 'This is a distribution group', 'highvalue': False, 'admincount': False, 'owned': False}

     type    l1     l2    l3  weight
710  node  Base  Group  None       1
    id  \
91  91

                                                                                                                                                                                                                                                                                        properties  \
91  {'domain': 'MARK.LOCAL', 'name': 'T1 PAW Maintenance@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1001', 'distinguishedname': 'CN=T1 PAW MAINTENANCE,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}

    type    l1     l2    l3  weight
91  node  Base  Group  None      20

In [78]:
selected_nodes

        id  \
3        3
6        6
15      15
16      16
17      17
18      18
22      22
23      23
24      24
25      25
26      26
27      27
28      28
29      29
30      30
31      31
32      32
33      33
34      34
35      35
71      71
83      83
94      94
95      95
96      96
97      97
289    289
290    290
292    292
293    293
294    294
298    298
299    299
300    300
301    301
304    304
308    308
310    310
311    311
312    312
313    313
314    314
316    316
317    317
318    318
320    320
321    321
322    322
325    325
326    326
327    327
328    328
329    329
330    330
331    331
332    332
333    333
334    334
335    335
336    336
337    337
338    338
339    339
340    340
341    341
342    342
343    343
344    344
345    345
346    346
347    347
348    348
349    349
350    350
351    351
352    352
353    353
354    354
355    355
356    356
357    357
358    358
359    359
360    360
361    361
362    362
363    363
364    364
365    365
366    366
367    367
368    368
369    369
370    370
371    371
372    372
373    373
374    374
375    375
376    376
377    377
378    378
379    379
380    380
381    381
382    382
383    383
384    384
385    385
386    386
387    387
388    388
389    389
390    390
391    391
392    392
393    393
394    394
395    395
396    396
397    397
398    398
399    399
400    400
401    401
402    402
403    403
404    404
405    405
406    406
407    407
408    408
409    409
410    410
411    411
412    412
413    413
414    414
415    415
416    416
417    417
418    418
419    419
420    420
421    421
422    422
423    423
424    424
425    425
426    426
427    427
428    428
429    429
430    430
431    431
432    432
433    433
434    434
435    435
436    436
437    437
438    438
439    439
440    440
441    441
442    442
443    443
444    444
445    445
446    446
447    447
448    448
449    449
450    450
451    451
452    452
453    453
454    454
455    455
456    456
462    462
463    463
464    464
465    465
466    466
468    468
470    470
471    471
472    472
473    473
474    474
475    475
476    476
477    477
478    478
479    479
480    480
481    481
482    482
483    483
484    484
485    485
486    486
487    487
488    488
489    489
490    490
492    492
493    493
494    494
495    495
496    496
497    497
498    498
499    499
500    500
501    501
502    502
503    503
504    504
505    505
506    506
507    507
509    509
510    510
511    511
513    513
515    515
516    516
517    517
518    518
519    519
520    520
521    521
522    522
524    524
525    525
526    526
528    528
529    529
533    533
535    535
536    536
537    537
538    538
539    539
540    540
541    541
542    542
543    543
545    545
546    546
547    547
548    548
549    549
551    551
552    552
554    554
555    555
556    556
557    557
558    558
559    559
560    560
562    562
565    565
566    566
567    567
568    568
569    569
570    570
571    571
572    572
573    573
574    574
576    576
578    578
579    579
580    580
581    581
582    582
583    583
584    584
586    586
587    587
588    588
589    589
591    591
592    592
593    593
594    594
595    595
596    596
598    598
601    601
602    602
603    603
604    604
605    605
606    606
608    608
609    609
611    611
612    612
613    613
614    614
615    615
616    616
617    617
618    618
619    619
621    621
622    622
627    627
628    628
629    629
630    630
633    633
634    634
635    635
636    636
637    637
638    638
641    641
642    642
643    643
644    644
646    646
647    647
649    649
652    652
655    655
656    656
657    657
658    658
659    659
660    660
661    661
662    662
664    664
666    666
668    668
672    672
673    673
676    676
688    688
694    694
695    695
696    696
697    697
698    698
699    699
700    700
701    701
702    702
703    703
704    704
705    705
706    706
707    707
708    708
709    709
710    710
711    711
712    712
713    713
714    714
715    715
716    716
717    717
718    718
719    719
720    720
721    721
722    722
723    723
724    724
725    725
726    726
727    727
728    728
729    729
730    730
731    731
732    732
733    733
734    734
735    735
736    736
737    737
738    738
739    739
740    740
741    741
742    742
743    743
744    744
745    745
746    746
747    747
748    748
749    749
750    750
751    751
752    752
753    753
754    754
755    755
756    756
757    757
758    758
759    759
760    760
761    761
762    762
763    763
764    764
765    765
766    766
767    767
768    768
769    769
770    770
771    771
772    772
773    773
774    774
775    775
776    776
777    777
778    778
779    779
780    780
781    781
782    782
783    783
784    784
785    785
786    786
787    787
788    788
789    789
790    790
791    791
792    792
793    793
794    794
795    795
796    796
797    797
798    798
799    799
800    800
801    801
802    802
803    803
804    804
805    805
806    806
807    807
808    808
809    809
810    810
811    811
812    812
813    813
814    814
815    815
816    816
817    817
818    818
819    819
820    820
821    821
822    822
823    823
824    824
825    825
826    826
827    827
828    828
829    829
830    830
831    831
832    832
833    833
834    834
835    835
836    836
837    837
838    838
839    839
840    840
841    841
842    842
843    843
844    844
845    845
846    846
847    847
848    848
849    849
850    850
851    851
852    852
853    853
854    854
855    855
856    856
857    857
858    858
859    859
860    860
861    861
862    862
863    863
864    864
865    865
866    866
867    867
868    868
869    869
870    870
871    871
872    872
873    873
874    874
875    875
876    876
877    877
878    878
879    879
880    880
881    881
882    882
883    883
884    884
885    885
886    886
887    887
888    888
889    889
890    890
891    891
892    892
893    893
894    894
895    895
896    896
897    897
898    898
899    899
900    900
901    901
902    902
903    903
904    904
905    905
906    906
907    907
908    908
909    909
910    910
911    911
912    912
913    913
914    914
915    915
916    916
917    917
918    918
919    919
920    920
921    921
922    922
923    923
924    924
925    925
926    926
927    927
928    928
929    929
930    930
931    931
932    932
933    933
934    934
935    935
936    936
937    937
938    938
939    939
940    940
941    941
942    942
943    943
944    944
945    945
946    946
947    947
948    948
949    949
950    950
951    951
952    952
953    953
954    954
955    955
956    956
957    957
958    958
959    959
960    960
961    961
962    962
963    963
964    964
965    965
966    966
967    967
968    968
969    969
970    970
971    971
972    972
973    973
974    974
975    975
976    976
977    977
978    978
979    979
980    980
981    981
982    982
983    983
984    984
985    985
986    986
987    987
988    988
989    989
990    990
991    991
992    992
993    993
994    994
995    995
996    996
997    997
998    998
999    999
1000  1000
1001  1001
1002  1002
1003  1003
1004  1004
1005  1005
1006  1006
1007  1007
1008  1008
1009  1009
1010  1010
1011  1011
1012  1012
1013  1013
1014  1014
1015  1015
1016  1016
1017  1017
1018  1018
1019  1019
1020  1020
1021  1021
1022  1022
1023  1023
1024  1024
1025  1025
1026  1026
1027  1027
1028  1028
1029  1029
1030  1030
1031  1031
1032  1032
1033  1033
1034  1034
1035  1035
1036  1036
1037  1037
1038  1038
1039  1039
1040  1040
1041  1041
1042  1042
1043  1043
1044  1044
1045  1045
1046  1046
1047  1047
1048  1048
1049  1049
1050  1050
1051  1051
1052  1052
1053  1053
1054  1054
1055  1055
1056  1056
1057  1057
1058  1058
1059  1059
1060  1060
1061  1061
1062  1062
1063  1063
1064  1064
1065  1065
1066  1066
1067  1067
1068  1068
1069  1069
1070  1070
1071  1071
1072  1072
1073  1073
1074  1074
1075  1075
1076  1076
1077  1077
1078  1078
1079  1079
1080  1080
1081  1081
1082  1082
1083  1083
1084  1084
1085  1085
1086  1086
1087  1087
1088  1088
1089  1089
1090  1090
1091  1091
1092  1092
1093  1093
1094  1094
1095  1095
1096  1096
1097  1097
1098  1098
1099  1099
1100  1100
1101  1101
1102  1102
1103  1103
1104  1104
1105  1105
1106  1106
1107  1107
1108  1108
1109  1109
1110  1110
1111  1111
1112  1112
1113  1113
1114  1114
1115  1115
1116  1116
1117  1117
1118  1118
1119  1119
1120  1120
1121  1121
1122  1122
1123  1123
1124  1124
1125  1125
1126  1126
1127  1127
1128  1128
1129  1129
1130  1130
1131  1131
1132  1132
1133  1133
1134  1134
1135  1135
1136  1136
1137  1137
1138  1138
1139  1139
1140  1140
1141  1141
1142  1142
1143  1143
1144  1144
1145  1145
1146  1146
1147  1147
1148  1148
1149  1149
1150  1150
1151  1151
1152  1152
1153  1153
1154  1154
1155  1155
1156  1156
1157  1157
1158  1158
1159  1159
1160  1160
1161  1161
1162  1162
1163  1163
1164  1164
1165  1165
1166  1166
1167  1167
1168  1168
1169  1169
1170  1170
1171  1171
1172  1172
1173  1173
1174  1174
1175  1175
1176  1176
1177  1177
1178  1178
1179  1179
1180  1180
1181  1181
1182  1182
1183  1183
1184  1184
1185  1185
1186  1186
1187  1187
1188  1188
1189  1189
1190  1190
1191  1191
1192  1192
1193  1193
1194  1194
1195  1195
1196  1196
1197  1197
1198  1198
1199  1199
1200  1200
1201  1201
1202  1202
1203  1203
1204  1204
1205  1205
1206  1206
1207  1207
1208  1208
1209  1209
1210  1210
1211  1211
1212  1212
1213  1213
1214  1214
1215  1215
1216  1216
1217  1217
1218  1218
1219  1219
1220  1220
1221  1221
1222  1222
1223  1223
1224  1224
1225  1225
1226  1226
1227  1227
1228  1228
1229  1229
1230  1230
1231  1231
1232  1232
1233  1233
1234  1234
1235  1235
1236  1236
1237  1237
1238  1238
1239  1239
1240  1240
1241  1241
1242  1242
1243  1243
1244  1244
1245  1245
1246  1246
1247  1247
1248  1248
1249  1249
1250  1250
1251  1251
1252  1252
1253  1253
1254  1254
1255  1255
1256  1256
1257  1257
1258  1258
1259  1259
1260  1260
1261  1261
1262  1262
1263  1263
1264  1264
1265  1265
1266  1266
1267  1267
1268  1268
1269  1269
1270  1270
1271  1271
1272  1272
1273  1273
1274  1274
1275  1275
1276  1276
1277  1277
1278  1278
1279  1279
1280  1280
1281  1281
1282  1282
1283  1283
1284  1284
1285  1285
1286  1286
1287  1287
1288  1288
1289  1289
1290  1290
1291  1291
1292  1292
1293  1293
1294  1294
1295  1295
1296  1296

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               properties  \
3                                                                                                                                                                                                                                                                                                                                                                                                                                                               {'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5de20ac8-e7ff-4f05-b597-268af392400e', 'distinguishedname': 'OU=TIER 2,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
6                                                                                                                                                                                                                                                                                                                                                                                                                                                           {'domain': 'MARK.LOCAL', 'name': 'T2 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e4602f9d-12bf-4f9e-b667-f6ccd27fae90', 'distinguishedname': 'OU=T2 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
15                                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-61c17d81-4eb2-4829-94e7-c7ddd6ecd193', 'distinguishedname': 'OU=T2 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
16                                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5305b84a-5f72-4ee8-9726-81485bc11905', 'distinguishedname': 'OU=T2 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
17                                                                                                                                                                                                                                                                                                                                                                                                                                            {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-508809b7-63d4-4f53-8376-b31aa66c0af6', 'distinguishedname': 'OU=T2 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
18                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e7679546-c753-4556-889a-67fd84f9d165', 'distinguishedname': 'OU=T2 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
22                                                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d13355-d2f9-45cf-9ee6-fdc8230ae4e5', 'distinguishedname': 'OU=T2 GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
23                                                                                                                                                                                                                                                                                                                                                                                                                                            {'domain': 'MARK.LOCAL', 'name': 'T2 Workstations@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-66aadca5-ccbc-46d4-91e7-f74f2527bdb5', 'distinguishedname': 'OU=T2 WORKSTATIONS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
24                                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-d4c0667d-16e8-4afd-8cf3-5f6a900f6913', 'distinguishedname': 'OU=T2 USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
25                                                                                                                                                                                                                                                                                                                                                                                                                                                      {'domain': 'MARK.LOCAL', 'name': 'T2 Servers@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-3f1588f2-5124-4111-8d63-caf4b57a87ca', 'distinguishedname': 'OU=T2 SERVERS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
26                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 Enabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-dd1b08e8-140d-49e3-ab56-1551c008827a', 'distinguishedname': 'OU=T2 ENABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
27                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Disabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-9c9959e1-1718-4648-9aa1-e0eb9920d50c', 'distinguishedname': 'OU=T2 DISABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}

In [49]:
selected_nodes

,id,properties,type,l1,l2,l3,weight
0,0,"{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL', 'highvalue': True, 'objectid': 'S-1-5-21-883232822-274137685-4173207997', 'distinguishedname': 'DC=MARK,DC=LOCAL', 'functionallevel': '2012', 'owned': False}",node,Base,Domain,None,20
4,4,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f249f685-d5e0-4dad-b5b5-7f723c41ca1e', 'distinguishedname': 'OU=T0 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
7,7,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c0fb853d-9b96-449b-b25c-4d20a1c02e5f', 'distinguishedname': 'OU=T0 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
8,8,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-b9fd1aed-b3e6-4d53-9242-b85ff389822f', 'distinguishedname': 'OU=T0 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
9,9,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-cd13b9d6-76ca-4b5c-82bd-2d86bef8a375', 'distinguishedname': 'OU=T0 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
10,10,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-58cd5b4f-82db-4cd1-a3f4-08661c9c53d2', 'distinguishedname': 'OU=T0 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
36,36,"{'domain': 'MARK.LOCAL', 'name': 'ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-544', 'highvalue': True, 'distinguishedname': 'CN=Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Administrators have complete and unrestricted access to the computer/domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
38,38,"{'domain': 'MARK.LOCAL', 'name': 'PRINT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-550', 'highvalue': True, 'distinguishedname': 'CN=Print Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer printers installed on domain controllers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
40,40,"{'domain': 'MARK.LOCAL', 'name': 'BACKUP OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-551', 'highvalue': True, 'distinguishedname': 'CN=Backup Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Backup Operators can override security restrictions for the sole purpose of backing up or restoring files', 'admincount': True, 'owned': False}",node,Base,Group,None,20
59,59,"{'domain': 'MARK.LOCAL', 'name': 'SERVER OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-549', 'highvalue': True, 'distinguishedname': 'CN=Server Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain servers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
60,60,"{'domain': 'MARK.LOCAL', 'name': 'ACCOUNT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-548', 'highvalue': True, 'distinguishedname': 'CN=Account Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain user and group accounts', 'admincount': True, 'owned': False}",node,Base,Group,None,20
65,65,"{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-519', 'highvalue': True, 'distinguishedname': 'CN=Enterprise Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the enterprise', 'admincount': True, 'owned': False}",node,Base,Group,None,20
66,66,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-512', 'highvalue': True, 'distinguishedname': 'CN=Domain Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
72,72,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-516', 'highvalue': True, 'distinguishedname': 'CN=Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain controllers in the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
75,75,"{'domain': 'MARK.LOCAL', 'name': 'GROUP POLICY CREATOR OWNERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-520', 'highvalue': True, 'distinguishedname': 'CN=Group Policy Creator Owners,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group can modify group policy for the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,20
90,90,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1000', 'distinguishedname': 'CN=T1 ADMIN ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
91,91,"{'domain': 'MARK.LOCAL', 'name': 'T1 PAW Maintenance@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1001', 'distinguishedname': 'CN=T1 PAW MAINTENANCE,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
92,92,"{'domain': 'MARK.LOCAL', 'name': 'T1 Server Management@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1002', 'distinguishedname': 'CN=T1 SERVER MANAGEMENT,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
93,93,"{'domain': 'MARK.LOCAL', 'name': 'T1 Service Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1003', 'distinguishedname': 'CN=T1 SERVICE ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
94,94,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1004', 'distinguishedname': 'CN=T2 ADMIN ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
95,95,"{'domain': 'MARK.LOCAL', 'name': 'T2 PAW Maintenance@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1005', 'distinguishedname': 'CN=T2 PAW MAINTENANCE,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
96,96,"{'domain': 'MARK.LOCAL', 'name': 'T2 Server Management@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1006', 'distinguishedname': 'CN=T2 SERVER MANAGEMENT,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
97,97,"{'domain': 'MARK.LOCAL', 'name': 'T2 Service Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1007', 'distinguishedname': 'CN=T2 SERVICE ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
98,98,"{'domain': 'MARK.LOCAL', 'name': 'Group Policy Objects Container@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-167D14BB-ED5C-438D-89A0-8E2173C713FB', 'highvalue': True, 'distinguishedname': 'CN=Policies,CN=System,DC=MARK,DC=LOCAL', 'owned': False}",node,Base,Container,None,20
288,288,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1011', 'displayname': 'Lore Domebo', 'name': 'LDOMEBO00001@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1735793646, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=LDOMEBO00001,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
289,289,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1012', 'displayname': 'Ora Swinney', 'name': 'OSWINNEY00002@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=OSWINNEY00002,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
291,291,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1014', 'displayname': 'Leandra Marucci', 'name': 'LMARUCCI00004@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 1744872398, 'lastlogontimestamp': 1744872398, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=LMARUCCI00004,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
293,293,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1016', 'displayname': 'Lynette Nette', 'name': 'LNETTE00006@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=LNETTE00006,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
294,294,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1017', 'displayname': 'Venessa Schaumberg', 'name': 'VSCHAUMBERG00007@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1729493472, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=VSCHAUMBERG00007,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
295,295,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1018', 'displayname': 'Shanel Nori', 'name': 'SNORI00008@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': True, 'hasspn': True, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=SNORI00008,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
296,296,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1019', 'displayname': 'Devon Scotti', 'name': 'DSCOTTI00009@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=DSCOTTI00009,OU=T0 ADMIN SERVICE ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
297,297,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1020', 'displayname': 'Leta Radoslovich', 'name': 'LRADOSLOVICH00010@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=LRADOSLOVICH00010,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
299,299,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1022', 'displayname': 'Deane Broaddus', 'name': 'DBROADDUS00012@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 1737401792, 'lastlogontimestamp': 1737401792, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=DBROADDUS00012,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
301,301,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1024', 'displayname': 'Teisha Ralat', 'name': 'TRALAT00014@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1728191894, 'lastlogon': 1718679255, 'lastlogontimestamp': 1718679255, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': 'S-1-5-21-883822822-279636685-4182209497-1384', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=TRALAT00014,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
302,302,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1025', 'displayname': 'Roxanna Florido', 'name': 'RFLORIDO00015@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1742548203, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=RFLORIDO00015,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
303,303,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1026', 'displayname': 'Shaquita Flanegan', 'name': 'SFLANEGAN00016@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': True, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=SFLANEGAN00016,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
304,304,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1027', 'displayname': 'Tomasa Boyarski', 'name': 'TBOYARSKI00017@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=TBOYARSKI00017,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
305,305,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1028', 'displayname': 'Zoila Dinucci', 'name': 'ZDINUCCI00018@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1747923112, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': 'S-1-5-21-883822822-279636685-4182209497-1934', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=ZDINUCCI00018,OU=T0 ADMIN SERVICE ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
306,306,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1029', 'displayname': 'Maryanne Sedtal', 'name': 'MSEDTAL00019@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1746739983, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=MSEDTAL00019,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
307,307,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1030', 'displayname': 'Chelsea Sullivan', 'name': 'CSULLIVAN00020@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1724431118, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': 'S-1-5-21-883822822-279636685-4182209497-1268', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=CSULLIVAN00020,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
308,308,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1031', 'displayname': 'Chanda Meiggs', 'name': 'CMEIGGS00021@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=CMEIGGS00021,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20

In [ ]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
shortest_paths

{0: {0: [0],
  285: [0, 285],
  287: [0, 287],
  49: [0, 285, 49],
  74: [0, 285, 74],
  63: [0, 287, 63],
  86: [0, 285, 74, 86],
  87: [0, 285, 74, 87],
  50: [0, 285, 74, 87, 50]},
 4: {4: [4], 7: [4, 7]},
 7: {7: [7]},
 8: {8: [8],
  686: [8, 686],
  527: [8, 527],
  530: [8, 530],
  531: [8, 531],
  532: [8, 532],
  553: [8, 553],
  607: [8, 607],
  610: [8, 610],
  625: [8, 625],
  631: [8, 631],
  632: [8, 632],
  640: [8, 640],
  645: [8, 645],
  653: [8, 653],
  663: [8, 663]},
 9: {9: [9],
  65: [9, 65],
  284: [9, 65, 36, 284],
  285: [9, 65, 36, 285],
  286: [9, 65, 286],
  287: [9, 65, 36, 287],
  63: [9, 65, 64, 63],
  36: [9, 65, 36],
  37: [9, 65, 37],
  38: [9, 65, 286, 38],
  39: [9, 65, 39],
  40: [9, 65, 40],
  41: [9, 65, 36, 41],
  42: [9, 65, 36, 42],
  43: [9, 65, 43],
  45: [9, 65, 45],
  48: [9, 65, 36, 48],
  50: [9, 65, 36, 50],
  51: [9, 65, 36, 51],
  52: [9, 65, 52],
  53: [9, 65, 36, 53],
  56: [9, 65, 36, 56],
  57: [9, 65, 36, 57],
  58: [9, 65, 36, 58],
  59: [9, 65, 286, 59],
  60: [9, 65, 60],
  61: [9, 65, 36, 61],
  62: [9, 65, 36, 62],
  64: [9, 65, 64],
  66: [9, 65, 286, 66],
  67: [9, 65, 36, 67],
  68: [9, 65, 36, 68],
  69: [9, 65, 36, 69],
  70: [9, 65, 36, 70],
  71: [9, 65, 36, 71],
  72: [9, 65, 286, 72],
  73: [9, 65, 36, 73],
  74: [9, 65, 286, 74],
  75: [9, 65, 286, 75],
  76: [9, 65, 36, 76],
  77: [9, 65, 77],
  78: [9, 65, 36, 78],
  79: [9, 65, 36, 79],
  80: [9, 65, 36, 80],
  81: [9, 65, 36, 81],
  82: [9, 65, 36, 82],
  83: [9, 65, 36, 83],
  84: [9, 65, 36, 84],
  0: [9, 65, 36, 0],
  44: [9, 65, 36, 44],
  46: [9, 65, 36, 46],
  47: [9, 65, 36, 47],
  49: [9, 65, 36, 285, 49],
  55: [9, 65, 36, 55],
  102: [9, 65, 286, 66, 102],
  86: [9, 65, 286, 74, 86],
  87: [9, 65, 286, 74, 87],
  85: [9, 65, 286, 66, 102, 85]},
 10: {10: [10]},
 36: {36: [36],
  0: [36, 0],
  284: [36, 284],
  285: [36, 285],
  286: [36, 65, 286],
  287: [36, 287],
  37: [36, 37],
  39: [36, 39],
  40: [36, 40],
  41: [36, 41],
  42: [36, 42],
  43: [36, 65, 43],
  44: [36, 44],
  45: [36, 45],
  46: [36, 46],
  47: [36, 47],
  48: [36, 48],
  49: [36, 285, 49],
  50: [36, 50],
  51: [36, 51],
  52: [36, 52],
  53: [36, 53],
  55: [36, 55],
  56: [36, 56],
  57: [36, 57],
  58: [36, 58],
  59: [36, 65, 286, 59],
  60: [36, 60],
  61: [36, 61],
  62: [36, 62],
  63: [36, 63],
  64: [36, 64],
  65: [36, 65],
  66: [36, 66],
  67: [36, 67],
  68: [36, 68],
  69: [36, 69],
  70: [36, 70],
  71: [36, 71],
  72: [36, 65, 286, 72],
  73: [36, 73],
  74: [36, 74],
  75: [36, 75],
  76: [36, 76],
  77: [36, 77],
  78: [36, 78],
  79: [36, 79],
  80: [36, 80],
  81: [36, 81],
  82: [36, 82],
  83: [36, 83],
  84: [36, 84],
  38: [36, 65, 286, 38],
  102: [36, 66, 102],
  86: [36, 73, 86],
  87: [36, 73, 87],
  85: [36, 66, 102, 85]},
 38: {38: [38]},
 40: {40: [40]},
 59: {59: [59]},
 60: {60: [60],
  284: [60, 284],
  285: [60, 285],
  37: [60, 37],
  39: [60, 39],
  41: [60, 41],
  42: [60, 42],
  44: [60, 44],
  45: [60, 45],
  46: [60, 46],
  47: [60, 47],
  48: [60, 48],
  49: [60, 49],
  51: [60, 51],
  52: [60, 52],
  57: [60, 57],
  58: [60, 58],
  61: [60, 61],
  62: [60, 62],
  63: [60, 63],
  67: [60, 67],
  68: [60, 68],
  69: [60, 69],
  70: [60, 70],
  71: [60, 71],
  73: [60, 73],
  74: [60, 74],
  75: [60, 75],
  76: [60, 76],
  78: [60, 78],
  79: [60, 79],
  80: [60, 80],
  81: [60, 81],
  82: [60, 82],
  83: [60, 83],
  84: [60, 84],
  86: [60, 73, 86],
  87: [60, 73, 87],
  50: [60, 73, 87, 50]},
 65: {65: [65],
  284: [65, 36, 284],
  285: [65, 36, 285],
  286: [65, 286],
  287: [65, 36, 287],
  63: [65, 64, 63],
  36: [65, 36],
  37: [65, 37],
  38: [65, 286, 38],
  39: [65, 39],
  40: [65, 40],
  41: [65, 36, 41],
  42: [65, 36, 42],
  43: [65, 43],
  45: [65, 45],
  48: [65, 36, 48],
  50: [65, 36, 50],
  51: [65, 36, 51],
  52: [65, 52],
  53: [65, 36, 53],
  56: [65, 36, 56],
  57: [65, 36, 57],
  58: [65, 36, 58],
  59: [65, 286, 59],
  60: [65, 60],
  61: [65, 36, 61],
  62: [65, 36, 62],
  64: [65, 64],
  66: [65, 286, 66],
  67: [65, 36, 67],
  68: [65, 36, 68],
  69: [65, 36, 69],
  70: [65, 36, 70],
  71: [65, 36, 71],
  72: [65, 286, 72],
  73: [65, 36, 73],
  74: [65, 286, 74],
  75: [65, 286, 75],
  76: [65, 36, 76],
  77: [65, 77],
  78: [65, 36, 78],
  79: [65, 36, 79],
  80: [65, 36, 80],
  81: [65, 36, 81],
  82: [65, 36, 82],
  83: [65, 36, 83],
  84: [65, 36, 84],
  0: [65, 36, 0],
  44: [65, 36, 44],
  46: [65, 36, 46],
  47: [65, 36, 47],
  49: [65, 36, 285, 49],
  55: [65, 36, 55],
  102: [65, 286, 66, 102],
  86: [65, 286, 74, 86],
  87: [65, 286, 74, 87],
  85: [65, 286, 66, 102, 85]},
 66: {66: [66],
  0: [66, 36, 0],
  102: [66, 102],
  284: [66, 36, 284],
  285: [66, 36, 285],
  286: [66, 286],
  287: [66, 36, 287],
  36: [66, 36],
  37: [66, 37],
  38: [66, 286, 38],
  39: [66, 39],
  40: [66, 40],
  42: [66, 36, 42],
  43: [66, 43],
  44: [66, 36, 44],
  45: [66, 45],
  47: [66, 36, 47],
  48: [66, 36, 48],
  49: [66, 36, 285, 49],
  51: [66, 36, 51],
  53: [66, 36, 53],
  57: [66, 36, 57],
  58: [66, 36, 58],
  59: [66, 286, 59],
  60: [66, 60],
  61: [66, 36, 61],
  62: [66, 36, 62],
  63: [66, 64, 63],
  64: [66, 64],
  65: [66, 65],
  67: [66, 36, 67],
  68: [66, 36, 68],
  69: [66, 36, 69],
  70: [66, 36, 70],
  71: [66, 36, 71],
  72: [66, 286, 72],
  73: [66, 36, 73],
  74: [66, 286, 74],
  75: [66, 286, 75],
  76: [66, 36, 76],
  77: [66, 77],
  78: [66, 36, 78],
  79: [66, 36, 79],
  80: [66, 36, 80],
  81: [66, 36, 81],
  82: [66, 36, 82],
  83: [66, 36, 83],
  84: [66, 36, 84],
  41: [66, 36, 41],
  46: [66, 36, 46],
  50: [66, 36, 50],
  52: [66, 36, 52],
  55: [66, 36, 55],
  56: [66, 36, 56],
  86: [66, 286, 74, 86],
  87: [66, 286, 74, 87],
  85: [66, 102, 85]},
 72: {72: [72], 63: [72, 63]},
 75: {75: [75], 63: [75, 63]},
 90: {90: [90], 85: [90, 85]},
 91: {91: [91]},
 92: {92: [92]},
 93: {93: [93]},
 94: {94: [94]},
 95: {95: [95]},
 96: {96: [96]},
 97: {97: [97]},
 98: {98: [98],
  106: [98, 106],
  107: [98, 107],
  109: [98, 109],
  110: [98, 110],
  111: [98, 111],
  115: [98, 115],
  116: [98, 116],
  117: [98, 117],
  118: [98, 118],
  121: [98, 121],
  125: [98, 125],
  127: [98, 127],
  128: [98, 128],
  129: [98, 129],
  130: [98, 130],
  131: [98, 131],
  133: [98, 133],
  134: [98, 134],
  135: [98, 135],
  137: [98, 137],
  138: [98, 138],
  139: [98, 139],
  142: [98, 142],
  143: [98, 143],
  144: [98, 144],
  145: [98, 145],
  146: [98, 146],
  147: [98, 147],
  148: [98, 148],
  149: [98, 149],
  150: [98, 150],
  151: [98, 151],
  152: [98, 152],
  153: [98, 153],
  154: [98, 154],
  155: [98, 155],
  156: [98, 156],
  157: [98, 157],
  158: [98, 158],
  159: [98, 159],
  160: [98, 160],
  161: [98, 161],
  162: [98, 162],
  163: [98, 163],
  164: [98, 164],
  165: [98, 165],
  166: [98, 166],
  167: [98, 167],
  168: [98, 168],
  169: [98, 169],
  170: [98, 170],
  171: [98, 171],
  172: [98, 172],
  173: [98, 173],
  174: [98, 174],
  175: [98, 175],
  176: [98, 176],
  177: [98, 177],
  178: [98, 178],
  179: [98, 179],
  180: [98, 180],
  181: [98, 181],
  182: [98, 182],
  183: [98, 183],
  184: [98, 184],
  185: [98, 185],
  186: [98, 186],
  187: [98, 187],
  188: [98, 188],
  189: [98, 189],
  190: [98, 190],
  191: [98, 191],
  192: [98, 192],
  193: [98, 193],
  194: [98, 194],
  195: [98, 195],
  196: [98, 196],
  197: [98, 197],
  198: [98, 198],
  199: [98, 199],
  200: [98, 200],
  201: [98, 201],
  202: [98, 202],
  203: [98, 203],
  204: [98, 204],
  205: [98, 205],
  206: [98, 206],
  207: [98, 207],
  208: [98, 208],
  209: [98, 209],
  210: [98, 210],
  211: [98, 211],
  212: [98, 212],
  213: [98, 213],
  214: [98, 214],
  215: [98, 215],
  216: [98, 216],
  217: [98, 217],
  218: [98, 218],
  219: [98, 219],
  220: [98, 220],
  221: [98, 221],
  222: [98, 222],
  223: [98, 223],
  224: [98, 224],
  225: [98, 225],
  226: [98, 226],
  227: [98, 227],
  228: [98, 228],
  229: [98, 229],
  230: [98, 230],
  231: [98, 231],
  232: [98, 232],
  233: [98, 233],
  234: [98, 234],
  235: [98, 235],
  236: [98, 236],
  237: [98, 237],
  238: [98, 238],
  239: [98, 239],
  240: [98, 240],
  241: [98, 241],
  242: [98, 242],
  243: [98, 243],
  244: [98, 244],
  245: [98, 245],
  246: [98, 246],
  247: [98, 247],
  248: [98, 248],
  249: [98, 249],
  250: [98, 250],
  251: [98, 251],
  252: [98, 252],
  253: [98, 253],
  254: [98, 254],
  255: [98, 255],
  256: [98, 256],
  257: [98, 257],
  258: [98, 258],
  259: [98, 259],
  260: [98, 260],
  261: [98, 261],
  262: [98, 262],
  263: [98, 263],
  264: [98, 264],
  265: [98, 265],
  266: [98, 266],
  267: [98, 267],
  268: [98, 268],
  269: [98, 269],
  270: [98, 270],
  271: [98, 271],
  272: [98, 272],
  273: [98, 273],
  279: [98, 279],
  280: [98, 280],
  281: [98, 281],
  282: [98, 282],
  283: [98, 283]},
 288: {288: [288],
  74: [288, 74],
  86: [288, 74, 86],
  87: [288, 74, 87],
  50: [288, 74, 87, 50]},
 289: {289: [289],
  74: [289, 74],
  86: [289, 74, 86],
  87: [289, 74, 87],
  50: [289, 74, 87, 50]},
 291: {291: [291],
  74: [291, 74],
  86: [291, 74, 86],
  87: [291, 74, 87],
  50: [291, 74, 87, 50]},
 293: {293: [293],
  74: [293, 74],
  86: [293, 74, 86],
  87: [293, 74, 87],
  50: [293, 74, 87, 50]},
 294: {294: [294],
  74: [294, 74],
  86: [294, 74, 86],
  87: [294, 74, 87],
  50: [294, 74, 87, 50]},
 295: {295: [295],
  74: [295, 74],
  86: [295, 74, 86],
  87: [295, 74, 87],
  50: [295, 74, 87, 50]},
 296: {296: [296],
  74: [296, 74],
  86: [296, 74, 86],
  87: [296, 74, 87],
  50: [296, 74, 87, 50]},
 297: {297: [297],
  74: [297, 74],
  86: [297, 74, 86],
  87: [297, 74, 87],
  50: [297, 74, 87, 50]},
 299: {299: [299],
  74: [299, 74],
  86: [299, 74, 86],
  87: [299, 74, 87],
  50: [299, 74, 87, 50]},
 301: {301: [301],
  74: [301, 74],
  86: [301, 74, 86],
  87: [301, 74, 87],
  50: [301, 74, 87, 50]},
 302: {302: [302],
  74: [302, 74],
  86: [302, 74, 86],
  87: [302, 74, 87],
  50: [302, 74, 87, 50]},
 303: {303: [303],
  74: [303, 74],
  86: [303, 74, 86],
  87: [303, 74, 87],
  50: [303, 74, 87, 50]},
 304: {304: [304],
  74: [304, 74],
  86: [304, 74, 86],
  87: [304, 74, 87],
  50: [304, 74, 87, 50]},
 305: {305: [305],
  74: [305, 74],
  86: [305, 74, 86],
  87: [305, 74, 87],
  50: [305, 74, 87, 50]},
 306: {306: [306],
  74: [306, 74],
  86: [306, 74, 86],
  87: [306, 74, 87],
  50: [306, 74, 87, 50]},
 307: {307: [307],
  74: [307, 74],
  86: [307, 74, 86],
  87: [307, 74, 87],
  50: [307, 74, 87, 50]},
 308: {308: [308],
  74: [308, 74],
  86: [308, 74, 86],
  87: [308, 74, 87],
  50: [308, 74, 87, 50]},
 309: {309: [309],
  74: [309, 74],
  86: [309, 74, 86],
  87: [309, 74, 87],
  50: [309, 74, 87, 50]},
 311: {311: [311],
  74: [311, 74],
  86: [311, 74, 86],
  87: [311, 74, 87],
  50: [311, 74, 87, 50]},
 312: {312: [312],
  74: [312, 74],
  86: [312, 74, 86],
  87: [312, 74, 87],
  50: [312, 74, 87, 50]},
 313: {313: [313],
  74: [313, 74],
  86: [313, 74, 86],
  87: [313, 74, 87],
  50: [313, 74, 87, 50]},
 314: {314: [314],
  74: [314, 74],
  86: [314, 74, 86],
  87: [314, 74, 87],
  50: [314, 74, 87, 50]},
 315: {315: [315],
  74: [315, 74],
  86: [315, 74, 86],
  87: [315, 74, 87],
  50: [315, 74, 87, 50]},
 318: {318: [318],
  74: [318, 74],
  86: [318, 74, 86],
  87: [318, 74, 87],
  50: [318, 74, 87, 50]},
 319: {319: [319],
  74: [319, 74],
  86: [319, 74, 86],
  87: [319, 74, 87],
  50: [319, 74, 87, 50]},
 320: {320: [320],
  74: [320, 74],
  86: [320, 74, 86],
  87: [320, 74, 87],
  50: [320, 74, 87, 50]},
 321: {321: [321],
  74: [321, 74],
  86: [321, 74, 86],
  87: [321, 74, 87],
  50: [321, 74, 87, 50]},
 322: {322: [322],
  74: [322, 74],
  86: [322, 74, 86],
  87: [322, 74, 87],
  50: [322, 74, 87, 50]},
 323: {323: [323],
  74: [323, 74],
  86: [323, 74, 86],
  87: [323, 74, 87],
  50: [323, 74, 87, 50]},
 324: {324: [324],
  74: [324, 74],
  86: [324, 74, 86],
  87: [324, 74, 87],
  50: [324, 74, 87, 50]},
 331: {331: [331],
  74: [331, 74],
  86: [331, 74, 86],
  87: [331, 74, 87],
  50: [331, 74, 87, 50]},
 341: {341: [341],
  74: [341, 74],
  86: [341, 74, 86],
  87: [341, 74, 87],
  50: [341, 74, 87, 50]},
 357: {357: [357],
  74: [357, 74],
  86: [357, 74, 86],
  87: [357, 74, 87],
  50: [357, 74, 87, 50]},
 392: {392: [392],
  74: [392, 74],
  86: [392, 74, 86],
  87: [392, 74, 87],
  50: [392, 74, 87, 50]},
 405: {405: [405],
  74: [405, 74],
  86: [405, 74, 86],
  87: [405, 74, 87],
  50: [405, 74, 87, 50]},
 444: {444: [444],
  74: [444, 74],
  86: [444, 74, 86],
  87: [444, 74, 87],
  50: [444, 74, 87, 50]},
 448: {448: [448],
  74: [448, 74],
  86: [448, 74, 86],
  87: [448, 74, 87],
  50: [448, 74, 87, 50]},
 457: {457: [457],
  74: [457, 74],
  86: [457, 74, 86],
  87: [457, 74, 87],
  50: [457, 74, 87, 50]},
 458: {458: [458],
  74: [458, 74],
  86: [458, 74, 86],
  87: [458, 74, 87],
  50: [458, 74, 87, 50]},
 467: {467: [467],
  74: [467, 74],
  86: [467, 74, 86],
  87: [467, 74, 87],
  50: [467, 74, 87, 50]},
 469: {469: [469],
  74: [469, 74],
  86: [469, 74, 86],
  87: [469, 74, 87],
  50: [469, 74, 87, 50]},
 481: {481: [481],
  74: [481, 74],
  86: [481, 74, 86],
  87: [481, 74, 87],
  50: [481, 74, 87, 50]},
 491: {491: [491]},
 501: {501: [501]},
 507: {507: [507]},
 508: {508: [508]},
 509: {509: [509]},
 511: {511: [511]},
 512: {512: [512]},
 514: {514: [514]},
 521: {521: [521]},
 523: {523: [523]},
 527: {527: [527]},
 530: {530: [530]},
 531: {531: [531]},
 532: {532: [532]},
 533: {533: [533]},
 534: {534: [534]},
 539: {539: [539]},
 544: {544: [544]},
 548: {548: [548]},
 550: {550: [550]},
 553: {553: [553]},
 557: {557: [557]},
 561: {561: [561]},
 562: {562: [562]},
 563: {563: [563]},
 564: {564: [564]},
 565: {565: [565]},
 567: {567: [567]},
 573: {573: [573]},
 575: {575: [575]},
 577: {577: [577]},
 585: {585: [585]},
 590: {590: [590]},
 597: {597: [597]},
 599: {599: [599]},
 600: {600: [600]},
 603: {603: [603]},
 607: {607: [607]},
 609: {609: [609]},
 610: {610: [610]},
 620: {620: [620]},
 623: {623: [623]},
 624: {624: [624]},
 625: {625: [625]},
 626: {626: [626]},
 631: {631: [631]},
 632: {632: [632]},
 637: {637: [637]},
 638: {638: [638]},
 639: {639: [639]},
 640: {640: [640]},
 645: {645: [645]},
 648: {648: [648]},
 649: {649: [649]},
 650: {650: [650]},
 651: {651: [651]},
 653: {653: [653]},
 654: {654: [654]},
 655: {655: [655]},
 656: {656: [656]},
 660: {660: [660]},
 661: {661: [661]},
 663: {663: [663]},
 665: {665: [665]},
 666: {666: [666]},
 668: {668: [668]},
 672: {672: [672]},
 673: {673: [673]},
 676: {676: [676]},
 677: {677: [677]},
 681: {681: [681]},
 684: {684: [684]},
 686: {686: [686]},
 692: {692: [692]},
 693: {693: [693]},
 694: {694: [694]},
 1: {1: [1], 4: [1, 4], 7: [1, 4, 7]},
 6: {6: [6],
  16: [6, 16],
  17: [6, 17],
  18: [6, 18],
  688: [6, 16, 688],
  539: [6, 16, 539],
  567: [6, 16, 567],
  609: [6, 16, 609],
  637: [6, 16, 637],
  655: [6, 16, 655],
  660: [6, 16, 660],
  661: [6, 16, 661],
  676: [6, 16, 676]},
 16: {16: [16],
  688: [16, 688],
  539: [16, 539],
  567: [16, 567],
  609: [16, 609],
  637: [16, 637],
  655: [16, 655],
  660: [16, 660],
  661: [16, 661],
  676: [16, 676]},
 17: {17: [17]},
 18: {18: [18]},
 2: {2: [2],
  19: [2, 19],
  689: [2, 19, 689],
  512: [2, 19, 512],
  534: [2, 19, 534],
  575: [2, 19, 575],
  651: [2, 19, 651]},
 19: {19: [19],
  689: [19, 689],
  512: [19, 512],
  534: [19, 534],
  575: [19, 575],
  651: [19, 651]},
 3: {3: [3],
  23: [3, 23],
  24: [3, 24],
  25: [3, 25],
  28: [3, 23, 28],
  29: [3, 23, 29],
  30: [3, 23, 30],
  26: [3, 24, 26],
  27: [3, 24, 27],
  33: [3, 25, 33],
  34: [3, 25, 34],
  35: [3, 25, 35],
  501: [3, 25, 33, 501],
  509: [3, 25, 33, 509],
  548: [3, 25, 33, 548],
  656: [3, 25, 33, 656],
  672: [3, 25, 33, 672],
  511: [3, 25, 34, 511],
  521: [3, 25, 34, 521],
  533: [3, 25, 34, 533],
  562: [3, 25, 34, 562],
  603: [3, 25, 34, 603],
  649: [3, 25, 34, 649],
  666: [3, 25, 34, 666],
  673: [3, 25, 34, 673],
  507: [3, 25, 35, 507],
  557: [3, 25, 35, 557],
  565: [3, 25, 35, 565],
  573: [3, 25, 35, 573],
  638: [3, 25, 35, 638],
  668: [3, 25, 35, 668]},
 23: {23: [23], 28: [23, 28], 29: [23, 29], 30: [23, 30]},
 24: {24: [24], 26: [24, 26], 27: [24, 27]},
 25: {25: [25],
  33: [25, 33],
  34: [25, 34],
  35: [25, 35],
  501: [25, 33, 501],
  509: [25, 33, 509],
  548: [25, 33, 548],
  656: [25, 33, 656],
  672: [25, 33, 672],
  511: [25, 34, 511],
  521: [25, 34, 521],
  533: [25, 34, 533],
  562: [25, 34, 562],
  603: [25, 34, 603],
  649: [25, 34, 649],
  666: [25, 34, 666],
  673: [25, 34, 673],
  507: [25, 35, 507],
  557: [25, 35, 557],
  565: [25, 35, 565],
  573: [25, 35, 573],
  638: [25, 35, 638],
  668: [25, 35, 668]},
 26: {26: [26]},
 27: {27: [27]},
 28: {28: [28]},
 29: {29: [29]},
 30: {30: [30]},
 22: {22: [22], 31: [22, 31], 32: [22, 32]},
 31: {31: [31]},
 32: {32: [32]},
 33: {33: [33],
  501: [33, 501],
  509: [33, 509],
  548: [33, 548],
  656: [33, 656],
  672: [33, 672]},
 34: {34: [34],
  511: [34, 511],
  521: [34, 521],
  533: [34, 533],
  562: [34, 562],
  603: [34, 603],
  649: [34, 649],
  666: [34, 666],
  673: [34, 673]},
 35: {35: [35],
  507: [35, 507],
  557: [35, 557],
  565: [35, 565],
  573: [35, 573],
  638: [35, 638],
  668: [35, 668]},
 102: {102: [102], 72: [102, 72], 85: [102, 85], 63: [102, 72, 63]},
 101: {101: [101],
  102: [101, 102],
  72: [101, 102, 72],
  85: [101, 102, 85],
  63: [101, 102, 72, 63]},
 85: {85: [85]},
 106: {106: [106]},
 107: {107: [107]},
 109: {109: [109]},
 110: {110: [110]},
 111: {111: [111]},
 115: {115: [115]},
 116: {116: [116]},
 117: {117: [117]},
 118: {118: [118]},
 121: {121: [121]},
 125: {125: [125]},
 127: {127: [127]},
 128: {128: [128]},
 129: {129: [129]},
 130: {130: [130]},
 131: {131: [131]},
 133: {133: [133]},
 134: {134: [134]},
 135: {135: [135]},
 137: {137: [137]},
 138: {138: [138]},
 139: {139: [139]},
 142: {142: [142]},
 143: {143: [143]},
 144: {144: [144]},
 145: {145: [145]},
 146: {146: [146]},
 147: {147: [147]},
 148: {148: [148]},
 149: {149: [149]},
 150: {150: [150]},
 151: {151: [151]},
 152: {152: [152]},
 153: {153: [153]},
 154: {154: [154]},
 155: {155: [155]},
 156: {156: [156]},
 157: {157: [157]},
 158: {158: [158]},
 159: {159: [159]},
 160: {160: [160]},
 161: {161: [161]},
 162: {162: [162]},
 163: {163: [163]},
 164: {164: [164]},
 165: {165: [165]},
 166: {166: [166]},
 167: {167: [167]},
 168: {168: [168]},
 169: {169: [169]},
 170: {170: [170]},
 171: {171: [171]},
 172: {172: [172]},
 173: {173: [173]},
 174: {174: [174]},
 175: {175: [175]},
 176: {176: [176]},
 177: {177: [177]},
 178: {178: [178]},
 179: {179: [179]},
 180: {180: [180]},
 181: {181: [181]},
 182: {182: [182]},
 183: {183: [183]},
 184: {184: [184]},
 185: {185: [185]},
 186: {186: [186]},
 187: {187: [187]},
 188: {188: [188]},
 189: {189: [189]},
 190: {190: [190]},
 191: {191: [191]},
 192: {192: [192]},
 193: {193: [193]},
 194: {194: [194]},
 195: {195: [195]},
 196: {196: [196]},
 197: {197: [197]},
 198: {198: [198]},
 199: {199: [199]},
 200: {200: [200]},
 201: {201: [201]},
 202: {202: [202]},
 203: {203: [203]},
 204: {204: [204]},
 205: {205: [205]},
 206: {206: [206]},
 207: {207: [207]},
 208: {208: [208]},
 209: {209: [209]},
 210: {210: [210]},
 211: {211: [211]},
 212: {212: [212]},
 213: {213: [213]},
 214: {214: [214]},
 215: {215: [215]},
 216: {216: [216]},
 217: {217: [217]},
 218: {218: [218]},
 219: {219: [219]},
 220: {220: [220]},
 221: {221: [221]},
 222: {222: [222]},
 223: {223: [223]},
 224: {224: [224]},
 225: {225: [225]},
 226: {226: [226]},
 227: {227: [227]},
 228: {228: [228]},
 229: {229: [229]},
 230: {230: [230]},
 231: {231: [231]},
 232: {232: [232]},
 233: {233: [233]},
 234: {234: [234]},
 235: {235: [235]},
 236: {236: [236]},
 237: {237: [237]},
 238: {238: [238]},
 239: {239: [239]},
 240: {240: [240]},
 241: {241: [241]},
 242: {242: [242]},
 243: {243: [243]},

In [ ]:
shortest_paths_filtered

{0: {285: [0, 285],
  287: [0, 287],
  49: [0, 285, 49],
  74: [0, 285, 74],
  63: [0, 287, 63],
  86: [0, 285, 74, 86],
  87: [0, 285, 74, 87],
  50: [0, 285, 74, 87, 50]},
 4: {7: [4, 7]},
 7: {},
 8: {686: [8, 686],
  527: [8, 527],
  530: [8, 530],
  531: [8, 531],
  532: [8, 532],
  553: [8, 553],
  607: [8, 607],
  610: [8, 610],
  625: [8, 625],
  631: [8, 631],
  632: [8, 632],
  640: [8, 640],
  645: [8, 645],
  653: [8, 653],
  663: [8, 663]},
 9: {65: [9, 65],
  284: [9, 65, 36, 284],
  285: [9, 65, 36, 285],
  286: [9, 65, 286],
  287: [9, 65, 36, 287],
  63: [9, 65, 64, 63],
  36: [9, 65, 36],
  37: [9, 65, 37],
  38: [9, 65, 286, 38],
  39: [9, 65, 39],
  40: [9, 65, 40],
  41: [9, 65, 36, 41],
  42: [9, 65, 36, 42],
  43: [9, 65, 43],
  45: [9, 65, 45],
  48: [9, 65, 36, 48],
  50: [9, 65, 36, 50],
  51: [9, 65, 36, 51],
  52: [9, 65, 52],
  53: [9, 65, 36, 53],
  56: [9, 65, 36, 56],
  57: [9, 65, 36, 57],
  58: [9, 65, 36, 58],
  59: [9, 65, 286, 59],
  60: [9, 65, 60],
  61: [9, 65, 36, 61],
  62: [9, 65, 36, 62],
  64: [9, 65, 64],
  66: [9, 65, 286, 66],
  67: [9, 65, 36, 67],
  68: [9, 65, 36, 68],
  69: [9, 65, 36, 69],
  70: [9, 65, 36, 70],
  71: [9, 65, 36, 71],
  72: [9, 65, 286, 72],
  73: [9, 65, 36, 73],
  74: [9, 65, 286, 74],
  75: [9, 65, 286, 75],
  76: [9, 65, 36, 76],
  77: [9, 65, 77],
  78: [9, 65, 36, 78],
  79: [9, 65, 36, 79],
  80: [9, 65, 36, 80],
  81: [9, 65, 36, 81],
  82: [9, 65, 36, 82],
  83: [9, 65, 36, 83],
  84: [9, 65, 36, 84],
  0: [9, 65, 36, 0],
  44: [9, 65, 36, 44],
  46: [9, 65, 36, 46],
  47: [9, 65, 36, 47],
  49: [9, 65, 36, 285, 49],
  55: [9, 65, 36, 55],
  102: [9, 65, 286, 66, 102],
  86: [9, 65, 286, 74, 86],
  87: [9, 65, 286, 74, 87],
  85: [9, 65, 286, 66, 102, 85]},
 10: {},
 36: {0: [36, 0],
  284: [36, 284],
  285: [36, 285],
  286: [36, 65, 286],
  287: [36, 287],
  37: [36, 37],
  39: [36, 39],
  40: [36, 40],
  41: [36, 41],
  42: [36, 42],
  43: [36, 65, 43],
  44: [36, 44],
  45: [36, 45],
  46: [36, 46],
  47: [36, 47],
  48: [36, 48],
  49: [36, 285, 49],
  50: [36, 50],
  51: [36, 51],
  52: [36, 52],
  53: [36, 53],
  55: [36, 55],
  56: [36, 56],
  57: [36, 57],
  58: [36, 58],
  59: [36, 65, 286, 59],
  60: [36, 60],
  61: [36, 61],
  62: [36, 62],
  63: [36, 63],
  64: [36, 64],
  65: [36, 65],
  66: [36, 66],
  67: [36, 67],
  68: [36, 68],
  69: [36, 69],
  70: [36, 70],
  71: [36, 71],
  72: [36, 65, 286, 72],
  73: [36, 73],
  74: [36, 74],
  75: [36, 75],
  76: [36, 76],
  77: [36, 77],
  78: [36, 78],
  79: [36, 79],
  80: [36, 80],
  81: [36, 81],
  82: [36, 82],
  83: [36, 83],
  84: [36, 84],
  38: [36, 65, 286, 38],
  102: [36, 66, 102],
  86: [36, 73, 86],
  87: [36, 73, 87],
  85: [36, 66, 102, 85]},
 38: {},
 40: {},
 59: {},
 60: {284: [60, 284],
  285: [60, 285],
  37: [60, 37],
  39: [60, 39],
  41: [60, 41],
  42: [60, 42],
  44: [60, 44],
  45: [60, 45],
  46: [60, 46],
  47: [60, 47],
  48: [60, 48],
  49: [60, 49],
  51: [60, 51],
  52: [60, 52],
  57: [60, 57],
  58: [60, 58],
  61: [60, 61],
  62: [60, 62],
  63: [60, 63],
  67: [60, 67],
  68: [60, 68],
  69: [60, 69],
  70: [60, 70],
  71: [60, 71],
  73: [60, 73],
  74: [60, 74],
  75: [60, 75],
  76: [60, 76],
  78: [60, 78],
  79: [60, 79],
  80: [60, 80],
  81: [60, 81],
  82: [60, 82],
  83: [60, 83],
  84: [60, 84],
  86: [60, 73, 86],
  87: [60, 73, 87],
  50: [60, 73, 87, 50]},
 65: {284: [65, 36, 284],
  285: [65, 36, 285],
  286: [65, 286],
  287: [65, 36, 287],
  63: [65, 64, 63],
  36: [65, 36],
  37: [65, 37],
  38: [65, 286, 38],
  39: [65, 39],
  40: [65, 40],
  41: [65, 36, 41],
  42: [65, 36, 42],
  43: [65, 43],
  45: [65, 45],
  48: [65, 36, 48],
  50: [65, 36, 50],
  51: [65, 36, 51],
  52: [65, 52],
  53: [65, 36, 53],
  56: [65, 36, 56],
  57: [65, 36, 57],
  58: [65, 36, 58],
  59: [65, 286, 59],
  60: [65, 60],
  61: [65, 36, 61],
  62: [65, 36, 62],
  64: [65, 64],
  66: [65, 286, 66],
  67: [65, 36, 67],
  68: [65, 36, 68],
  69: [65, 36, 69],
  70: [65, 36, 70],
  71: [65, 36, 71],
  72: [65, 286, 72],
  73: [65, 36, 73],
  74: [65, 286, 74],
  75: [65, 286, 75],
  76: [65, 36, 76],
  77: [65, 77],
  78: [65, 36, 78],
  79: [65, 36, 79],
  80: [65, 36, 80],
  81: [65, 36, 81],
  82: [65, 36, 82],
  83: [65, 36, 83],
  84: [65, 36, 84],
  0: [65, 36, 0],
  44: [65, 36, 44],
  46: [65, 36, 46],
  47: [65, 36, 47],
  49: [65, 36, 285, 49],
  55: [65, 36, 55],
  102: [65, 286, 66, 102],
  86: [65, 286, 74, 86],
  87: [65, 286, 74, 87],
  85: [65, 286, 66, 102, 85]},
 66: {0: [66, 36, 0],
  102: [66, 102],
  284: [66, 36, 284],
  285: [66, 36, 285],
  286: [66, 286],
  287: [66, 36, 287],
  36: [66, 36],
  37: [66, 37],
  38: [66, 286, 38],
  39: [66, 39],
  40: [66, 40],
  42: [66, 36, 42],
  43: [66, 43],
  44: [66, 36, 44],
  45: [66, 45],
  47: [66, 36, 47],
  48: [66, 36, 48],
  49: [66, 36, 285, 49],
  51: [66, 36, 51],
  53: [66, 36, 53],
  57: [66, 36, 57],
  58: [66, 36, 58],
  59: [66, 286, 59],
  60: [66, 60],
  61: [66, 36, 61],
  62: [66, 36, 62],
  63: [66, 64, 63],
  64: [66, 64],
  65: [66, 65],
  67: [66, 36, 67],
  68: [66, 36, 68],
  69: [66, 36, 69],
  70: [66, 36, 70],
  71: [66, 36, 71],
  72: [66, 286, 72],
  73: [66, 36, 73],
  74: [66, 286, 74],
  75: [66, 286, 75],
  76: [66, 36, 76],
  77: [66, 77],
  78: [66, 36, 78],
  79: [66, 36, 79],
  80: [66, 36, 80],
  81: [66, 36, 81],
  82: [66, 36, 82],
  83: [66, 36, 83],
  84: [66, 36, 84],
  41: [66, 36, 41],
  46: [66, 36, 46],
  50: [66, 36, 50],
  52: [66, 36, 52],
  55: [66, 36, 55],
  56: [66, 36, 56],
  86: [66, 286, 74, 86],
  87: [66, 286, 74, 87],
  85: [66, 102, 85]},
 72: {63: [72, 63]},
 75: {63: [75, 63]},
 90: {85: [90, 85]},
 91: {},
 92: {},
 93: {},
 94: {},
 95: {},
 96: {},
 97: {},
 98: {106: [98, 106],
  107: [98, 107],
  109: [98, 109],
  110: [98, 110],
  111: [98, 111],
  115: [98, 115],
  116: [98, 116],
  117: [98, 117],
  118: [98, 118],
  121: [98, 121],
  125: [98, 125],
  127: [98, 127],
  128: [98, 128],
  129: [98, 129],
  130: [98, 130],
  131: [98, 131],
  133: [98, 133],
  134: [98, 134],
  135: [98, 135],
  137: [98, 137],
  138: [98, 138],
  139: [98, 139],
  142: [98, 142],
  143: [98, 143],
  144: [98, 144],
  145: [98, 145],
  146: [98, 146],
  147: [98, 147],
  148: [98, 148],
  149: [98, 149],
  150: [98, 150],
  151: [98, 151],
  152: [98, 152],
  153: [98, 153],
  154: [98, 154],
  155: [98, 155],
  156: [98, 156],
  157: [98, 157],
  158: [98, 158],
  159: [98, 159],
  160: [98, 160],
  161: [98, 161],
  162: [98, 162],
  163: [98, 163],
  164: [98, 164],
  165: [98, 165],
  166: [98, 166],
  167: [98, 167],
  168: [98, 168],
  169: [98, 169],
  170: [98, 170],
  171: [98, 171],
  172: [98, 172],
  173: [98, 173],
  174: [98, 174],
  175: [98, 175],
  176: [98, 176],
  177: [98, 177],
  178: [98, 178],
  179: [98, 179],
  180: [98, 180],
  181: [98, 181],
  182: [98, 182],
  183: [98, 183],
  184: [98, 184],
  185: [98, 185],
  186: [98, 186],
  187: [98, 187],
  188: [98, 188],
  189: [98, 189],
  190: [98, 190],
  191: [98, 191],
  192: [98, 192],
  193: [98, 193],
  194: [98, 194],
  195: [98, 195],
  196: [98, 196],
  197: [98, 197],
  198: [98, 198],
  199: [98, 199],
  200: [98, 200],
  201: [98, 201],
  202: [98, 202],
  203: [98, 203],
  204: [98, 204],
  205: [98, 205],
  206: [98, 206],
  207: [98, 207],
  208: [98, 208],
  209: [98, 209],
  210: [98, 210],
  211: [98, 211],
  212: [98, 212],
  213: [98, 213],
  214: [98, 214],
  215: [98, 215],
  216: [98, 216],
  217: [98, 217],
  218: [98, 218],
  219: [98, 219],
  220: [98, 220],
  221: [98, 221],
  222: [98, 222],
  223: [98, 223],
  224: [98, 224],
  225: [98, 225],
  226: [98, 226],
  227: [98, 227],
  228: [98, 228],
  229: [98, 229],
  230: [98, 230],
  231: [98, 231],
  232: [98, 232],
  233: [98, 233],
  234: [98, 234],
  235: [98, 235],
  236: [98, 236],
  237: [98, 237],
  238: [98, 238],
  239: [98, 239],
  240: [98, 240],
  241: [98, 241],
  242: [98, 242],
  243: [98, 243],
  244: [98, 244],
  245: [98, 245],
  246: [98, 246],
  247: [98, 247],
  248: [98, 248],
  249: [98, 249],
  250: [98, 250],
  251: [98, 251],
  252: [98, 252],
  253: [98, 253],
  254: [98, 254],
  255: [98, 255],
  256: [98, 256],
  257: [98, 257],
  258: [98, 258],
  259: [98, 259],
  260: [98, 260],
  261: [98, 261],
  262: [98, 262],
  263: [98, 263],
  264: [98, 264],
  265: [98, 265],
  266: [98, 266],
  267: [98, 267],
  268: [98, 268],
  269: [98, 269],
  270: [98, 270],
  271: [98, 271],
  272: [98, 272],
  273: [98, 273],
  279: [98, 279],
  280: [98, 280],
  281: [98, 281],
  282: [98, 282],
  283: [98, 283]},
 288: {74: [288, 74],
  86: [288, 74, 86],
  87: [288, 74, 87],
  50: [288, 74, 87, 50]},
 289: {74: [289, 74],
  86: [289, 74, 86],
  87: [289, 74, 87],
  50: [289, 74, 87, 50]},
 291: {74: [291, 74],
  86: [291, 74, 86],
  87: [291, 74, 87],
  50: [291, 74, 87, 50]},
 293: {74: [293, 74],
  86: [293, 74, 86],
  87: [293, 74, 87],
  50: [293, 74, 87, 50]},
 294: {74: [294, 74],
  86: [294, 74, 86],
  87: [294, 74, 87],
  50: [294, 74, 87, 50]},
 295: {74: [295, 74],
  86: [295, 74, 86],
  87: [295, 74, 87],
  50: [295, 74, 87, 50]},
 296: {74: [296, 74],
  86: [296, 74, 86],
  87: [296, 74, 87],
  50: [296, 74, 87, 50]},
 297: {74: [297, 74],
  86: [297, 74, 86],
  87: [297, 74, 87],
  50: [297, 74, 87, 50]},
 299: {74: [299, 74],
  86: [299, 74, 86],
  87: [299, 74, 87],
  50: [299, 74, 87, 50]},
 301: {74: [301, 74],
  86: [301, 74, 86],
  87: [301, 74, 87],
  50: [301, 74, 87, 50]},
 302: {74: [302, 74],
  86: [302, 74, 86],
  87: [302, 74, 87],
  50: [302, 74, 87, 50]},
 303: {74: [303, 74],
  86: [303, 74, 86],
  87: [303, 74, 87],
  50: [303, 74, 87, 50]},
 304: {74: [304, 74],
  86: [304, 74, 86],
  87: [304, 74, 87],
  50: [304, 74, 87, 50]},
 305: {74: [305, 74],
  86: [305, 74, 86],
  87: [305, 74, 87],
  50: [305, 74, 87, 50]},
 306: {74: [306, 74],
  86: [306, 74, 86],
  87: [306, 74, 87],
  50: [306, 74, 87, 50]},
 307: {74: [307, 74],
  86: [307, 74, 86],
  87: [307, 74, 87],
  50: [307, 74, 87, 50]},
 308: {74: [308, 74],
  86: [308, 74, 86],
  87: [308, 74, 87],
  50: [308, 74, 87, 50]},
 309: {74: [309, 74],
  86: [309, 74, 86],
  87: [309, 74, 87],
  50: [309, 74, 87, 50]},
 311: {74: [311, 74],
  86: [311, 74, 86],
  87: [311, 74, 87],
  50: [311, 74, 87, 50]},
 312: {74: [312, 74],
  86: [312, 74, 86],
  87: [312, 74, 87],
  50: [312, 74, 87, 50]},
 313: {74: [313, 74],
  86: [313, 74, 86],
  87: [313, 74, 87],
  50: [313, 74, 87, 50]},
 314: {74: [314, 74],
  86: [314, 74, 86],
  87: [314, 74, 87],
  50: [314, 74, 87, 50]},
 315: {74: [315, 74],
  86: [315, 74, 86],
  87: [315, 74, 87],
  50: [315, 74, 87, 50]},
 318: {74: [318, 74],
  86: [318, 74, 86],
  87: [318, 74, 87],
  50: [318, 74, 87, 50]},
 319: {74: [319, 74],
  86: [319, 74, 86],
  87: [319, 74, 87],
  50: [319, 74, 87, 50]},
 320: {74: [320, 74],
  86: [320, 74, 86],
  87: [320, 74, 87],
  50: [320, 74, 87, 50]},
 321: {74: [321, 74],
  86: [321, 74, 86],
  87: [321, 74, 87],
  50: [321, 74, 87, 50]},
 322: {74: [322, 74],
  86: [322, 74, 86],
  87: [322, 74, 87],
  50: [322, 74, 87, 50]},
 323: {74: [323, 74],
  86: [323, 74, 86],
  87: [323, 74, 87],
  50: [323, 74, 87, 50]},
 324: {74: [324, 74],
  86: [324, 74, 86],
  87: [324, 74, 87],
  50: [324, 74, 87, 50]},
 331: {74: [331, 74],
  86: [331, 74, 86],
  87: [331, 74, 87],
  50: [331, 74, 87, 50]},
 341: {74: [341, 74],
  86: [341, 74, 86],
  87: [341, 74, 87],
  50: [341, 74, 87, 50]},
 357: {74: [357, 74],
  86: [357, 74, 86],
  87: [357, 74, 87],
  50: [357, 74, 87, 50]},
 392: {74: [392, 74],
  86: [392, 74, 86],
  87: [392, 74, 87],
  50: [392, 74, 87, 50]},
 405: {74: [405, 74],
  86: [405, 74, 86],
  87: [405, 74, 87],
  50: [405, 74, 87, 50]},
 444: {74: [444, 74],
  86: [444, 74, 86],
  87: [444, 74, 87],
  50: [444, 74, 87, 50]},
 448: {74: [448, 74],
  86: [448, 74, 86],
  87: [448, 74, 87],
  50: [448, 74, 87, 50]},
 457: {74: [457, 74],
  86: [457, 74, 86],
  87: [457, 74, 87],
  50: [457, 74, 87, 50]},
 458: {74: [458, 74],
  86: [458, 74, 86],
  87: [458, 74, 87],
  50: [458, 74, 87, 50]},
 467: {74: [467, 74],
  86: [467, 74, 86],
  87: [467, 74, 87],
  50: [467, 74, 87, 50]},
 469: {74: [469, 74],
  86: [469, 74, 86],
  87: [469, 74, 87],
  50: [469, 74, 87, 50]},
 481: {74: [481, 74],
  86: [481, 74, 86],
  87: [481, 74, 87],
  50: [481, 74, 87, 50]},
 491: {},
 501: {},
 507: {},
 508: {},
 509: {},
 511: {},
 512: {},
 514: {},
 521: {},
 523: {},
 527: {},
 530: {},
 531: {},
 532: {},
 533: {},
 534: {},
 539: {},
 544: {},
 548: {},
 550: {},
 553: {},
 557: {},
 561: {},
 562: {},
 563: {},
 564: {},
 565: {},
 567: {},
 573: {},
 575: {},
 577: {},
 585: {},
 590: {},
 597: {},
 599: {},
 600: {},
 603: {},
 607: {},
 609: {},
 610: {},
 620: {},
 623: {},
 624: {},
 625: {},
 626: {},
 631: {},
 632: {},
 637: {},
 638: {},
 639: {},
 640: {},
 645: {},
 648: {},
 649: {},
 650: {},
 651: {},
 653: {},
 654: {},
 655: {},
 656: {},
 660: {},
 661: {},
 663: {},
 665: {},
 666: {},
 668: {},
 672: {},
 673: {},
 676: {},
 677: {},
 681: {},
 684: {},
 686: {},
 692: {},
 693: {},
 694: {},
 1: {4: [1, 4], 7: [1, 4, 7]},
 6: {16: [6, 16],
  17: [6, 17],
  18: [6, 18],
  688: [6, 16, 688],
  539: [6, 16, 539],
  567: [6, 16, 567],
  609: [6, 16, 609],
  637: [6, 16, 637],
  655: [6, 16, 655],
  660: [6, 16, 660],
  661: [6, 16, 661],
  676: [6, 16, 676]},
 16: {688: [16, 688],
  539: [16, 539],
  567: [16, 567],
  609: [16, 609],
  637: [16, 637],
  655: [16, 655],
  660: [16, 660],
  661: [16, 661],
  676: [16, 676]},
 17: {},
 18: {},
 2: {19: [2, 19],
  689: [2, 19, 689],
  512: [2, 19, 512],
  534: [2, 19, 534],
  575: [2, 19, 575],
  651: [2, 19, 651]},
 19: {689: [19, 689],
  512: [19, 512],
  534: [19, 534],
  575: [19, 575],
  651: [19, 651]},
 3: {23: [3, 23],
  24: [3, 24],
  25: [3, 25],
  28: [3, 23, 28],
  29: [3, 23, 29],
  30: [3, 23, 30],
  26: [3, 24, 26],
  27: [3, 24, 27],
  33: [3, 25, 33],
  34: [3, 25, 34],
  35: [3, 25, 35],
  501: [3, 25, 33, 501],
  509: [3, 25, 33, 509],
  548: [3, 25, 33, 548],
  656: [3, 25, 33, 656],
  672: [3, 25, 33, 672],
  511: [3, 25, 34, 511],
  521: [3, 25, 34, 521],
  533: [3, 25, 34, 533],
  562: [3, 25, 34, 562],
  603: [3, 25, 34, 603],
  649: [3, 25, 34, 649],
  666: [3, 25, 34, 666],
  673: [3, 25, 34, 673],
  507: [3, 25, 35, 507],
  557: [3, 25, 35, 557],
  565: [3, 25, 35, 565],
  573: [3, 25, 35, 573],
  638: [3, 25, 35, 638],
  668: [3, 25, 35, 668]},
 23: {28: [23, 28], 29: [23, 29], 30: [23, 30]},
 24: {26: [24, 26], 27: [24, 27]},
 25: {33: [25, 33],
  34: [25, 34],
  35: [25, 35],
  501: [25, 33, 501],
  509: [25, 33, 509],
  548: [25, 33, 548],
  656: [25, 33, 656],
  672: [25, 33, 672],
  511: [25, 34, 511],
  521: [25, 34, 521],
  533: [25, 34, 533],
  562: [25, 34, 562],
  603: [25, 34, 603],
  649: [25, 34, 649],
  666: [25, 34, 666],
  673: [25, 34, 673],
  507: [25, 35, 507],
  557: [25, 35, 557],
  565: [25, 35, 565],
  573: [25, 35, 573],
  638: [25, 35, 638],
  668: [25, 35, 668]},
 26: {},
 27: {},
 28: {},
 29: {},
 30: {},
 22: {31: [22, 31], 32: [22, 32]},
 31: {},
 32: {},
 33: {501: [33, 501],
  509: [33, 509],
  548: [33, 548],
  656: [33, 656],
  672: [33, 672]},
 34: {511: [34, 511],
  521: [34, 521],
  533: [34, 533],
  562: [34, 562],
  603: [34, 603],
  649: [34, 649],
  666: [34, 666],
  673: [34, 673]},
 35: {507: [35, 507],
  557: [35, 557],
  565: [35, 565],
  573: [35, 573],
  638: [35, 638],
  668: [35, 668]},
 102: {72: [102, 72], 85: [102, 85], 63: [102, 72, 63]},
 101: {102: [101, 102],
  72: [101, 102, 72],
  85: [101, 102, 85],
  63: [101, 102, 72, 63]},
 85: {},
 106: {},
 107: {},
 109: {},
 110: {},
 111: {},
 115: {},
 116: {},
 117: {},
 118: {},
 121: {},
 125: {},
 127: {},
 128: {},
 129: {},
 130: {},
 131: {},
 133: {},
 134: {},
 135: {},
 137: {},
 138: {},
 139: {},
 142: {},
 143: {},
 144: {},
 145: {},
 146: {},
 147: {},
 148: {},
 149: {},
 150: {},
 151: {},
 152: {},
 153: {},
 154: {},
 155: {},
 156: {},
 157: {},
 158: {},
 159: {},
 160: {},
 161: {},
 162: {},
 163: {},
 164: {},
 165: {},
 166: {},
 167: {},
 168: {},
 169: {},
 170: {},
 171: {},
 172: {},
 173: {},
 174: {},
 175: {},
 176: {},
 177: {},
 178: {},
 179: {},
 180: {},
 181: {},
 182: {},
 183: {},
 184: {},
 185: {},
 186: {},
 187: {},
 188: {},
 189: {},
 190: {},
 191: {},
 192: {},
 193: {},
 194: {},
 195: {},
 196: {},
 197: {},
 198: {},
 199: {},
 200: {},
 201: {},
 202: {},
 203: {},
 204: {},
 205: {},
 206: {},
 207: {},
 208: {},
 209: {},
 210: {},
 211: {},
 212: {},
 213: {},
 214: {},
 215: {},
 216: {},
 217: {},
 218: {},
 219: {},
 220: {},
 221: {},
 222: {},
 223: {},
 224: {},
 225: {},
 226: {},
 227: {},
 228: {},
 229: {},
 230: {},
 231: {},
 232: {},
 233: {},
 234: {},
 235: {},
 236: {},
 237: {},
 238: {},
 239: {},
 240: {},
 241: {},
 242: {},
 243: {},
 244: {},
 245: {},
 246: {},
 247: {},
 248: {},
 249: {},
 250: {},
 251: {},
 252: {},
 253: {},
 254: {},
 255: {},
 256: {},
 257: {},
 258: {},
 259: {},
 260: {},
 261: {},
 262: {},
 263: {},
 264: {},
 265: {},
 266: {},
 267: {},
 268: {},
 269: {},
 270: {},
 271: {},
 272: {},
 273: {},
 279: {},
 280: {},
 281: {},
 282: {},
 283: {},
 285: {49: [285, 49],
  74: [285, 74],
  86: [285, 74, 86],
  87: [285, 74, 87],
  50: [285, 74, 87, 50]},
 287: {63: [287, 63],
  74: [287, 74],
  86: [287, 74, 86],
  87: [287, 74, 87],
  50: [287, 74, 87, 50]},
 284: {48: [284, 48]},
 286: {38: [286, 38],
  59: [286, 59],
  60: [286, 60],
  65: [286, 65],
  66: [286, 66],
  72: [286, 72],
  75: [286, 75],
  36: [286, 36],
  64: [286, 64],
  74: [286, 74],
  284: [286, 36, 284],
  285: [286, 36, 285],
  37: [286, 36, 37],
  39: [286, 36, 39],
  41: [286, 36, 41],
  42: [286, 36, 42],
  44: [286, 36, 44],
  45: [286, 36, 45],
  46: [286, 36, 46],
  47: [286, 36, 47],
  48: [286, 36, 48],
  49: [286, 36, 285, 49],
  51: [286, 36, 51],
  52: [286, 36, 52],
  57: [286, 36, 57],
  58: [286, 36, 58],
  61: [286, 36, 61],
  62: [286, 36, 62],
  63: [286, 72, 63],
  67: [286, 36, 67],
  68: [286, 36, 68],
  69: [286, 36, 69],
  70: [286, 36, 70],
  71: [286, 36, 71],
  73: [286, 36, 73],
  76: [286, 36, 76],
  78: [286, 36, 78],
  79: [286, 36, 79],
  80: [286, 36, 80],
  81: [286, 36, 81],
  82: [286, 36, 82],
  83: [286, 36, 83],
  84: [286, 36, 84],
  287: [286, 36, 287],
  40: [286, 65, 40],
  43: [286, 65, 43],
  50: [286, 36, 50],
  53: [286, 36, 53],
  56: [286, 36, 56],
  77: [286, 65, 77],
  0: [286, 36, 0],
  102: [286, 66, 102],
  55: [286, 36, 55],
  86: [286, 74, 86],
  87: [286, 74, 87],
  85: [286, 66, 102, 85]},
 76: {48: [76, 48]},
 48: {},
 49: {},
 87: {50: [87, 50]},
 50: {},
 89: {50: [89, 50]},
 63: {},
 58: {63: [58, 63]},
 64: {63: [64, 63]},
 74: {86: [74, 86], 87: [74, 87], 50: [74, 87, 50]},
 73: {86: [73, 86], 87: [73, 87], 50: [73, 87, 50]},
 86: {},
 37: {},
 39: {},
 41: {},
 42: {},
 43: {},
 44: {},
 45: {},
 46: {},
 47: {},
 51: {},
 52: {},
 53: {},
 55: {},
 56: {},
 57: {},
 61: {},
 62: {},
 67: {},
 68: {},
 69: {},
 70: {},
 71: {74: [71, 74], 86: [71, 74, 86], 87: [71, 74, 87], 50: [71, 74, 87, 50]},
 77: {},
 78: {},
 79: {},
 80: {},
 81: {},
 82: {},
 83: {74: [83, 74], 86: [83, 74, 86], 87: [83, 74, 87], 50: [83, 74, 87, 50]},
 84: {},
 290: {74: [290, 74],
  86: [290, 74, 86],
  87: [290, 74, 87],
  50: [290, 74, 87, 50]},
 292: {74: [292, 74],
  86: [292, 74, 86],
  87: [292, 74, 87],
  50: [292, 74, 87, 50]},
 298: {74: [298, 74],
  86: [298, 74, 86],
  87: [298, 74, 87],
  50: [298, 74, 87, 50]},
 300: {74: [300, 74],
  86: [300, 74, 86],
  87: [300, 74, 87],
  50: [300, 74, 87, 50]},
 310: {74: [310, 74],
  86: [310, 74, 86],
  87: [310, 74, 87],
  50: [310, 74, 87, 50]},
 316: {74: [316, 74],
  86: [316, 74, 86],
  87: [316, 74, 87],
  50: [316, 74, 87, 50]},
 317: {74: [317, 74],
  86: [317, 74, 86],
  87: [317, 74, 87],
  50: [317, 74, 87, 50]},
 325: {74: [325, 74],

In [ ]:
# prompt: can you display the combined weight from the shortest_paths and display the path with the max weight

# Function to calculate the total weight of a path
def calculate_path_weight(graph, path):
    total_weight = 0
    # Add the weight of the starting node
    if path:
        total_weight += graph.nodes[path[0]].get('weight', 0) # Get node weight
    # Add the weight of the edges and the weights of subsequent nodes
    for i in range(len(path) - 1):
        u, v = path[i], path[i+1]
        # Add edge weight
        total_weight += graph.edges[u, v].get('weight', 0) # Get edge weight
        # Add weight of the next node
        total_weight += graph.nodes[v].get('weight', 0) # Get node weight
    return total_weight

max_weight = -1
max_path = None

# Iterate through the filtered shortest paths and calculate total weights
for source, paths in shortest_paths_filtered.items():
    for target, path in paths.items():
        current_weight = calculate_path_weight(G, path)
#        print(f"Path from {source} to {target}: {path}, Combined Weight: {current_weight}")
        if current_weight > max_weight:
            max_weight = current_weight
            max_path = path

print(f"\nPath with the maximum combined weight: {max_path}")
print(f"Maximum combined weight: {max_weight}")

Path with the maximum combined weight: [9, 65, 36, 0]
Maximum combined weight: 87.0

In [ ]:
max_path
max_path = pd.DataFrame(max_path)
max_path.head()

    0
0   9
1  65
2  36
3   0

In [ ]:
rename = {0: 'id'}
max_path = max_path.rename(columns=rename)
max_path

   id
0   9
1  65
2  36
3   0

In [ ]:
# prompt: get label from nodes where id=max_path['id']

# Assuming max_path is a DataFrame with an 'id' column representing the node IDs in the max path
# and nodes is a DataFrame with 'id' and 'properties' columns.

# Get the list of node IDs from the max_path DataFrame
max_path_node_ids = max_path['id'].tolist()

# Filter the nodes DataFrame to get only the nodes that are in the max_path
nodes_in_max_path = nodes[nodes['id'].isin(max_path_node_ids)].copy()

# Now, extract the 'name' property from the 'properties' column for these nodes
# Use .loc to avoid SettingWithCopyWarning
# We use a lambda function with .apply to safely access nested dictionary keys.
max_path_node_labels = nodes_in_max_path.loc[:, 'properties'].apply(lambda x: x.get('name', ''))

print("Labels of nodes in the max path:")
print(max_path_node_labels.tolist())

Labels of nodes in the max path:
['MARK.LOCAL', 'T0 Admin Groups@MARK.LOCAL', 'ADMINISTRATORS@MARK.LOCAL', 'ENTERPRISE ADMINS@MARK.LOCAL']

In [ ]:
max_path

   id
0   9
1  65
2  36
3   0

ignore from here

In [ ]:
vertices = nodes['id'].tolist()
vertices

[6221,
 6222,
 6223,
 6224,
 6225,
 6226,
 6227,
 6228,
 6229,
 6230,
 6231,
 6232,
 6233,
 6234,
 6235,
 6236,
 6237,
 6238,
 6239,
 6240,
 6241,
 6242,
 6243,
 6244,
 6245,
 6246,
 6247,
 6248,
 6249,
 6250,
 6251,
 6252,
 6253,
 6254,
 6255,
 6256,
 6257,
 6258,
 6259,
 6260,
 6261,
 6262,
 6263,
 6264,
 6265,
 6266,
 6267,
 6268,
 6269,
 6270,
 6271,
 6272,
 6273,
 6274,
 6275,
 6276,
 6277,
 6278,
 6279,
 6280,
 6281,
 6282,
 6283,
 6284,
 6285,
 6286,
 6287,
 6288,
 6289,
 6290,
 6291,
 6292,
 6293,
 6294,
 6295,
 6296,
 6297,
 6298,
 6299,
 6300,
 6301,
 6302,
 6303,
 6304,
 6305,
 6306,
 6307,
 6308,
 6309,
 6310,
 6311,
 6312,
 6313,
 6314,
 6315,
 6316,
 6317,
 6318,
 6319,
 6320,
 6321,
 6322,
 6323,
 6324,
 6325,
 6326,
 6327,
 6328,
 6329,
 6330,
 6331,
 6332,
 6333,
 6334,
 6335,
 6336,
 6337,
 6338,
 6339,
 6340,
 6341,
 6342,
 6343,
 6344,
 6345,
 6346,
 6347,
 6348,
 6349,
 6350,
 6351,
 6352,
 6353,
 6354,
 6355,
 6356,
 6357,
 6358,
 6359,
 6360,
 6361,
 6362,
 6363,
 6364,
 6365,
 6366,
 6367,
 6368,
 6369,
 6370,
 6371,
 6372,
 6373,
 6374,
 6375,
 6376,
 6377,
 6378,
 6379,
 6380,
 6381,
 6382,
 6383,
 6384,
 6385,
 6386,
 6387,
 6388,
 6389,
 6390,
 6391,
 6392,
 6393,
 6394,
 6395,
 6396,
 6397,
 6398,
 6399,
 6400,
 6401,
 6402,
 6403,
 6404,
 6405,
 6406,
 6407,
 6408,
 6409,
 6410,
 6411,
 6412,
 6413,
 6414,
 6415,
 6416,
 6417,
 6418,
 6419,
 6420,
 6421,
 6422,
 6423,
 6424,
 6425,
 6426,
 6427,
 6428,
 6429,
 6430,
 6431,
 6432,
 6433,
 6434,
 6435,
 6436,
 6437,
 6438,
 6439,
 6440,
 6441,
 6442,
 6443,
 6444,
 6445,
 6446,
 6447,
 6448,
 6449,
 6450,
 6451,
 6452,
 6453,
 6454,
 6455,
 6456,
 6457,
 6458,
 6459,
 6460,
 6461,
 6462,
 6463,
 6464,
 6465,
 6466,
 6467,
 6468,
 6469,
 6470,
 6471,
 6472,
 6473,
 6474,
 6475,
 6476,
 6477,
 6478,
 6479,
 6480,
 6481,
 6482,
 6483,
 6484,
 6485,
 6486,
 6487,
 6488,
 6489,
 6490,
 6491,
 6492,
 6493,
 6494,
 6495,
 6496,
 6497,
 6498,
 6499,
 6500,
 6501,
 6502,
 6503,
 6504,
 6505,
 6506,
 6507,
 6508,
 6509,
 6510,
 6511,
 6512,
 6513,
 6514,
 6515,
 6516,
 6517,
 6518,
 6519,
 6520,
 6521,
 6522,
 6523,
 6524,
 6525,
 6526,
 6527,
 6528,
 6529,
 6530,
 6531,
 6532,
 6533,
 6534,
 6535,
 6536,
 6537,
 6538,
 6539,
 6540,
 6541,
 6542,
 6543,
 6544,
 6545,
 6546,
 6547,
 6548,
 6549,
 6550,
 6551,
 6552,
 6553,
 6554,
 6555,
 6556,
 6557,
 6558,
 6559,
 6560,
 6561,
 6562,
 6563,
 6564,
 6565,
 6566,
 6567,
 6568,
 6569,
 6570,
 6571,
 6572,
 6573,
 6574,
 6575,
 6576,
 6577,
 6578,
 6579,
 6580,
 6581,
 6582,
 6583,
 6584,
 6585,
 6586,
 6587,
 6588,
 6589,
 6590,
 6591,
 6592,
 6593,
 6594,
 6595,
 6596,
 6597,
 6598,
 6599,
 6600,
 6601,
 6602,
 6603,
 6604,
 6605,
 6606,
 6607,
 6608,
 6609,
 6610,
 6611,
 6612,
 6613,
 6614,
 6615,
 6616,
 6617,
 6618,
 6619,
 6620,
 6621,
 6622,
 6623,
 6624,
 6625,
 6626,
 6627,
 6628,
 6629,
 6630,
 6631,
 6632,
 6633,
 6634,
 6635,
 6636,
 6637,
 6638,
 6639,
 6640,
 6641,
 6642,
 6643,
 6644,
 6645,
 6646,
 6647,
 6648,
 6649,
 6650,
 6651,
 6652,
 6653,
 6654,
 6655,
 6656,
 6657,
 6658,
 6659,
 6660,
 6661,
 6662,
 6663,
 6664,
 6665,
 6666,
 6667,
 6668,
 6669,
 6670,
 6671,
 6672,
 6673,
 6674,
 6675,
 6676,
 6677,
 6678,
 6679,
 6680,
 6681,
 6682,
 6683,
 6684,
 6685,
 6686,
 6687,
 6688,
 6689,
 6690,
 6691,
 6692,
 6693,
 6694,
 6695,
 6696,
 6697,
 6698,
 6699,
 6700,
 6701,
 6702,
 6703,
 6704,
 6705,
 6706,
 6707,
 6708,
 6709,
 6710,
 6711,
 6712,
 6713,
 6714,
 6715,
 6716,
 6717,
 6718,
 6719,
 6720,
 6721,
 6722,
 6723,
 6724,
 6725,
 6726,
 6727,
 6728,
 6729,
 6730,
 6731,
 6732,
 6733,
 6734,
 6735,
 6736,
 6737,
 6738,
 6739,
 6740,
 6741,
 6742,
 6743,
 6744,
 6745,
 6746,
 6747,
 6748,
 6749,
 6750,
 6751,
 6752,
 6753,
 6754,
 6755,
 6756,
 6757,
 6758,
 6759,
 6760,
 6761,
 6762,
 6763,
 6764,
 6765,
 6766,
 6767,
 6768,
 6769,
 6770,
 6771,
 6772,
 6773,
 6774,
 6775,
 6776,
 6777,
 6778,
 6779,
 6780,
 6781,
 6782,
 6783,
 6784,
 6785,
 6786,
 6787,
 6788,
 6789,
 6790,
 6791,
 6792,
 6793,
 6794,
 6795,
 6796,
 6797,
 6798,
 6799,
 6800,
 6801,
 6802,
 6803,
 6804,
 6805,
 6806,
 6807,
 6808,
 6809,
 6810,
 6811,
 6812,
 6813,
 6814,
 6815,
 6816,
 6817,
 6818,
 6819,
 6820,
 6821,
 6822,
 6823,
 6824,
 6825,
 6826,
 6827,
 6828,
 6829,
 6830,
 6831,
 6832,
 6833,
 6834,
 6835,
 6836,
 6837,
 6838,
 6839,
 6840,
 6841,
 6842,
 6843,
 6844,
 6845,
 6846,
 6847,
 6848,
 6849,
 6850,
 6851,
 6852,
 6853,
 6854,
 6855,
 6856,
 6857,
 6858,
 6859,
 6860,
 6861,
 6862,
 6863,
 6864,
 6865,
 6866,
 6867,
 6868,
 6869,
 6870,
 6871,
 6872,
 6873,
 6874,
 6875,
 6876,
 6877,
 6878,
 6879,
 6880,
 6881,
 6882,
 6883,
 6884,
 6885,
 6886,
 6887,
 6888,
 6889,
 6890,
 6891,
 6892,
 6893,
 6894,
 6895,
 6896,
 6897,
 6898,
 6899,
 6900,
 6901,
 6902,
 6903,
 6904,
 6905,
 6906,
 6907,
 6908,
 6909,
 6910,
 6911,
 6912,
 6913,
 6914,
 6915,
 6916,
 6917,
 6918,
 6919,
 6920,
 6921,
 6922,
 6923,
 6924,
 6925,
 6926,
 6927,
 6928,
 6929,
 6930,
 6931,
 6932,
 6933,
 6934,
 6935,
 6936,
 6937,
 6938,
 6939,
 6940,
 6941,
 6942,
 6943,
 6944,
 6945,
 6946,
 6947,
 6948,
 6949,
 6950,
 6951,
 6952,
 6953,
 6954,
 6955,
 6956,
 6957,
 6958,
 6959,
 6960,
 6961,
 6962,
 6963,
 6964,
 6965,
 6966,
 6967,
 6968,
 6969,
 6970,
 6971,
 6972,
 6973,
 6974,
 6975,
 6976,
 6977,
 6978,
 6979,
 6980,
 6981,
 6982,
 6983,
 6984,
 6985,
 6986,
 6987,
 6988,
 6989,
 6990,
 6991,
 6992,
 6993,
 6994,
 6995,
 6996,
 6997,
 6998,
 6999,
 7000,
 7001,
 7002,
 7003,
 7004,
 7005,
 7006,
 7007,
 7008,
 7009,
 7010,
 7011,
 7012,
 7013,
 7014,
 7015,
 7016,
 7017,
 7018,
 7019,
 7020,
 7021,
 7022,
 7023,
 7024,
 7025,
 7026,
 7027,
 7028,
 7029,
 7030,
 7031,
 7032,
 7033,
 7034,
 7035,
 7036,
 7037,
 7038,
 7039,
 7040,
 7041,
 7042,
 7043,
 7044,
 7045,
 7046,
 7047,
 7048,
 7049,
 7050,
 7051,
 7052,
 7053,
 7054,
 7055,
 7056,
 7057,
 7058,
 7059,
 7060,
 7061,
 7062,
 7063,
 7064,
 7065,
 7066,
 7067,
 7068,
 7069,
 7070,
 7071,
 7072,
 7073,
 7074,
 7075,
 7076,
 7077,
 7078,
 7079,
 7080,
 7081,
 7082,
 7083,
 7084,
 7085,
 7086,
 7087,
 7088,
 7089,
 7090,
 7091,
 7092,
 7093,
 7094,
 7095,
 7096,
 7097,
 7098,
 7099,
 7100,
 7101,
 7102,
 7103,
 7104,
 7105,
 7106,
 7107,
 7108,
 7109,
 7110,
 7111,
 7112,
 7113,
 7114,
 7115,
 7116,
 7117,
 7118,
 7119,
 7120,
 7121,
 7122,
 7123,
 7124,
 7125,
 7126,
 7127,
 7128,
 7129,
 7130,
 7131,
 7132,
 7133,
 7134,
 7135,
 7136,
 7137,
 7138,
 7139,
 7140,
 7141,
 7142,
 7143,
 7144,
 7145,
 7146,
 7147,
 7148,
 7149,
 7150,
 7151,
 7152,
 7153,
 7154,
 7155,
 7156,
 7157,
 7158,
 7159,
 7160,
 7161,
 7162,
 7163,
 7164,
 7165,
 7166,
 7167,
 7168,
 7169,
 7170,
 7171,
 7172,
 7173,
 7174,
 7175,
 7176,
 7177,
 7178,
 7179,
 7180,
 7181,
 7182,
 7183,
 7184,
 7185,
 7186,
 7187,
 7188,
 7189,
 7190,
 7191,
 7192,
 7193,
 7194,
 7195,
 7196,
 7197,
 7198,
 7199,
 7200,
 7201,
 7202,
 7203,
 7204,
 7205,
 7206,
 7207,
 7208,
 7209,
 7210,
 7211,
 7212,
 7213,
 7214,
 7215,
 7216,
 7217,
 7218,
 7219,
 7220,
 ...]

In [ ]:
adj_list=adj.values.tolist()
len(adj_list)

48321

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

def createAdjacencyMatrix(vertices,edges):
  noofvertices=len(vertices)
  adjM=[]
  while(len(adjM)<noofvertices):
    temp=[]
    for i in range(noofvertices):
      temp.append(0)
    adjM.append(temp)
  for edge in edges:
    i=edge[0]
    j=edge[1]
    if i>=noofvertices or j>=noofvertices or i<0 or j<0:
      print(f"Not a Proper Input in Edge {i},{j}")
    else:
      adjM[i][j]=1
      adjM[j][i]=1
#  G=nx.Graph()
#  G.add_edges_from(edges)
#  nx.draw_networkx(G)
#  plt.show()
  return adjM
vertices = vertices
edges = adj_list
adjM=createAdjacencyMatrix(vertices,edges)

Not a Proper Input in Edge 10075,6298
Not a Proper Input in Edge 10077,6298
Not a Proper Input in Edge 10078,6298
Not a Proper Input in Edge 10080,6298
Not a Proper Input in Edge 10081,6298
Not a Proper Input in Edge 10082,6298
Not a Proper Input in Edge 10083,6298
Not a Proper Input in Edge 10085,6298
Not a Proper Input in Edge 10087,6298
Not a Proper Input in Edge 10088,6298
Not a Proper Input in Edge 10089,6298
Not a Proper Input in Edge 10090,6298
Not a Proper Input in Edge 10094,6298
Not a Proper Input in Edge 10100,6298
Not a Proper Input in Edge 10101,6298
Not a Proper Input in Edge 10103,6298
Not a Proper Input in Edge 10104,6298
Not a Proper Input in Edge 10105,6298
Not a Proper Input in Edge 10106,6298
Not a Proper Input in Edge 10107,6298
Not a Proper Input in Edge 10108,6298
Not a Proper Input in Edge 10110,6298
Not a Proper Input in Edge 10111,6298
Not a Proper Input in Edge 10114,6298
Not a Proper Input in Edge 10116,6298
Not a Proper Input in Edge 10117,6298
Not a Proper Input in Edge 10118,6298
Not a Proper Input in Edge 10119,6298
Not a Proper Input in Edge 10120,6298
Not a Proper Input in Edge 10123,6298
Not a Proper Input in Edge 10124,6298
Not a Proper Input in Edge 10125,6298
Not a Proper Input in Edge 10127,6298
Not a Proper Input in Edge 10134,6298
Not a Proper Input in Edge 10136,6298
Not a Proper Input in Edge 10137,6298
Not a Proper Input in Edge 10140,6298
Not a Proper Input in Edge 10141,6298
Not a Proper Input in Edge 10142,6298
Not a Proper Input in Edge 10145,6298
Not a Proper Input in Edge 10148,6298
Not a Proper Input in Edge 10150,6298
Not a Proper Input in Edge 10153,6298
Not a Proper Input in Edge 10156,6298
Not a Proper Input in Edge 10161,6298
Not a Proper Input in Edge 10165,6298
Not a Proper Input in Edge 10166,6298
Not a Proper Input in Edge 10167,6298
Not a Proper Input in Edge 10168,6298
Not a Proper Input in Edge 10170,6298
Not a Proper Input in Edge 10171,6298
Not a Proper Input in Edge 10173,6298
Not a Proper Input in Edge 10174,6298
Not a Proper Input in Edge 10178,6298
Not a Proper Input in Edge 10182,6298
Not a Proper Input in Edge 10185,6298
Not a Proper Input in Edge 10189,6298
Not a Proper Input in Edge 10190,6298
Not a Proper Input in Edge 10191,6298
Not a Proper Input in Edge 10192,6298
Not a Proper Input in Edge 10193,6298
Not a Proper Input in Edge 10194,6298
Not a Proper Input in Edge 10196,6298
Not a Proper Input in Edge 10198,6298
Not a Proper Input in Edge 10199,6298
Not a Proper Input in Edge 10201,6298
Not a Proper Input in Edge 10202,6298
Not a Proper Input in Edge 10203,6298
Not a Proper Input in Edge 10204,6298
Not a Proper Input in Edge 10207,6298
Not a Proper Input in Edge 10209,6298
Not a Proper Input in Edge 10210,6298
Not a Proper Input in Edge 10211,6298
Not a Proper Input in Edge 10212,6298
Not a Proper Input in Edge 10214,6298
Not a Proper Input in Edge 10215,6298
Not a Proper Input in Edge 10216,6298
Not a Proper Input in Edge 10218,6298
Not a Proper Input in Edge 10222,6298
Not a Proper Input in Edge 10224,6298
Not a Proper Input in Edge 10225,6298
Not a Proper Input in Edge 10231,6298
Not a Proper Input in Edge 10232,6298
Not a Proper Input in Edge 10234,6298
Not a Proper Input in Edge 10237,6298
Not a Proper Input in Edge 10239,6298
Not a Proper Input in Edge 10240,6298
Not a Proper Input in Edge 10241,6298
Not a Proper Input in Edge 10242,6298
Not a Proper Input in Edge 10243,6298
Not a Proper Input in Edge 10244,6298
Not a Proper Input in Edge 10246,6298
Not a Proper Input in Edge 10247,6298
Not a Proper Input in Edge 10248,6298
Not a Proper Input in Edge 10251,6298
Not a Proper Input in Edge 10252,6298
Not a Proper Input in Edge 10253,6298
Not a Proper Input in Edge 10254,6298
Not a Proper Input in Edge 10258,6298
Not a Proper Input in Edge 10260,6298
Not a Proper Input in Edge 10261,6298
Not a Proper Input in Edge 10263,6298
Not a Proper Input in Edge 10265,6298
Not a Proper Input in Edge 10266,6298
Not a Proper Input in Edge 10267,6298
Not a Proper Input in Edge 10271,6298
Not a Proper Input in Edge 10272,6298
Not a Proper Input in Edge 10273,6298
Not a Proper Input in Edge 10276,6298
Not a Proper Input in Edge 10277,6298
Not a Proper Input in Edge 10278,6298
Not a Proper Input in Edge 10279,6298
Not a Proper Input in Edge 10284,6298
Not a Proper Input in Edge 10286,6298
Not a Proper Input in Edge 10289,6298
Not a Proper Input in Edge 10292,6298
Not a Proper Input in Edge 10294,6298
Not a Proper Input in Edge 10295,6298
Not a Proper Input in Edge 10296,6298
Not a Proper Input in Edge 10297,6298
Not a Proper Input in Edge 10298,6298
Not a Proper Input in Edge 10300,6298
Not a Proper Input in Edge 10301,6298
Not a Proper Input in Edge 10302,6298
Not a Proper Input in Edge 10304,6298
Not a Proper Input in Edge 10305,6298
Not a Proper Input in Edge 10306,6298
Not a Proper Input in Edge 10307,6298
Not a Proper Input in Edge 10309,6298
Not a Proper Input in Edge 10310,6298
Not a Proper Input in Edge 10311,6298
Not a Proper Input in Edge 10312,6298
Not a Proper Input in Edge 10313,6298
Not a Proper Input in Edge 10315,6298
Not a Proper Input in Edge 10316,6298
Not a Proper Input in Edge 10318,6298
Not a Proper Input in Edge 10319,6298
Not a Proper Input in Edge 10320,6298
Not a Proper Input in Edge 10322,6298
Not a Proper Input in Edge 10323,6298
Not a Proper Input in Edge 10324,6298
Not a Proper Input in Edge 10325,6298
Not a Proper Input in Edge 10326,6298
Not a Proper Input in Edge 10328,6298
Not a Proper Input in Edge 10329,6298
Not a Proper Input in Edge 10331,6298
Not a Proper Input in Edge 10333,6298
Not a Proper Input in Edge 10335,6298
Not a Proper Input in Edge 10341,6298
Not a Proper Input in Edge 10342,6298
Not a Proper Input in Edge 10343,6298
Not a Proper Input in Edge 10345,6298
Not a Proper Input in Edge 10349,6298
Not a Proper Input in Edge 10351,6298
Not a Proper Input in Edge 10352,6298
Not a Proper Input in Edge 10353,6298
Not a Proper Input in Edge 10355,6298
Not a Proper Input in Edge 10358,6298
Not a Proper Input in Edge 10359,6298
Not a Proper Input in Edge 10362,6298
Not a Proper Input in Edge 10364,6298
Not a Proper Input in Edge 10366,6298
Not a Proper Input in Edge 10368,6298
Not a Proper Input in Edge 10369,6298
Not a Proper Input in Edge 10371,6298
Not a Proper Input in Edge 10372,6298
Not a Proper Input in Edge 10375,6298
Not a Proper Input in Edge 10377,6298
Not a Proper Input in Edge 10378,6298
Not a Proper Input in Edge 10380,6298
Not a Proper Input in Edge 10381,6298
Not a Proper Input in Edge 10382,6298
Not a Proper Input in Edge 10383,6298
Not a Proper Input in Edge 10390,6298
Not a Proper Input in Edge 10391,6298
Not a Proper Input in Edge 10395,6298
Not a Proper Input in Edge 10396,6298
Not a Proper Input in Edge 10399,6298
Not a Proper Input in Edge 10400,6298
Not a Proper Input in Edge 10407,6298
Not a Proper Input in Edge 10412,6298
Not a Proper Input in Edge 10413,6298
Not a Proper Input in Edge 10415,6298
Not a Proper Input in Edge 10416,6298
Not a Proper Input in Edge 10421,6298
Not a Proper Input in Edge 10424,6298
Not a Proper Input in Edge 10425,6298
Not a Proper Input in Edge 10427,6298
Not a Proper Input in Edge 10428,6298
Not a Proper Input in Edge 10430,6298
Not a Proper Input in Edge 10431,6298
Not a Proper Input in Edge 10433,6298
Not a Proper Input in Edge 10434,6298
Not a Proper Input in Edge 10435,6298
Not a Proper Input in Edge 10438,6298
Not a Proper Input in Edge 10439,6298
Not a Proper Input in Edge 10440,6298
Not a Proper Input in Edge 10442,6298
Not a Proper Input in Edge 10443,6298
Not a Proper Input in Edge 10444,6298
Not a Proper Input in Edge 10445,6298
Not a Proper Input in Edge 10446,6298
Not a Proper Input in Edge 10449,6298
Not a Proper Input in Edge 10450,6298
Not a Proper Input in Edge 10452,6298
Not a Proper Input in Edge 10453,6298
Not a Proper Input in Edge 10454,6298
Not a Proper Input in Edge 10455,6298
Not a Proper Input in Edge 10458,6298
Not a Proper Input in Edge 10460,6298
Not a Proper Input in Edge 10461,6298
Not a Proper Input in Edge 10462,6298
Not a Proper Input in Edge 10463,6298
Not a Proper Input in Edge 10465,6298
Not a Proper Input in Edge 10470,6298
Not a Proper Input in Edge 10472,6298
Not a Proper Input in Edge 10474,6298
Not a Proper Input in Edge 10475,6298
Not a Proper Input in Edge 10476,6298
Not a Proper Input in Edge 10479,6298
Not a Proper Input in Edge 10481,6298
Not a Proper Input in Edge 10482,6298
Not a Proper Input in Edge 10487,6298
Not a Proper Input in Edge 10489,6298
Not a Proper Input in Edge 10490,6298
Not a Proper Input in Edge 10492,6298
Not a Proper Input in Edge 10494,6298
Not a Proper Input in Edge 10495,6298
Not a Proper Input in Edge 10496,6298
Not a Proper Input in Edge 10497,6298
Not a Proper Input in Edge 10498,6298
Not a Proper Input in Edge 10501,6298
Not a Proper Input in Edge 10503,6298
Not a Proper Input in Edge 10504,6298
Not a Proper Input in Edge 10506,6298
Not a Proper Input in Edge 10509,6298
Not a Proper Input in Edge 10511,6298
Not a Proper Input in Edge 10513,6298
Not a Proper Input in Edge 10517,6298
Not a Proper Input in Edge 10519,6298
Not a Proper Input in Edge 10521,6298
Not a Proper Input in Edge 10522,6298
Not a Proper Input in Edge 10523,6298
Not a Proper Input in Edge 10524,6298
Not a Proper Input in Edge 10526,6298
Not a Proper Input in Edge 10527,6298
Not a Proper Input in Edge 10528,6298
Not a Proper Input in Edge 10529,6298
Not a Proper Input in Edge 10531,6298
Not a Proper Input in Edge 10532,6298
Not a Proper Input in Edge 10533,6298
Not a Proper Input in Edge 10534,6298
Not a Proper Input in Edge 10535,6298
Not a Proper Input in Edge 10536,6298
Not a Proper Input in Edge 10538,6298
Not a Proper Input in Edge 10539,6298
Not a Proper Input in Edge 10540,6298
Not a Proper Input in Edge 10541,6298
Not a Proper Input in Edge 10542,6298
Not a Proper Input in Edge 10543,6298
Not a Proper Input in Edge 10545,6298
Not a Proper Input in Edge 10547,6298
Not a Proper Input in Edge 10548,6298
Not a Proper Input in Edge 10550,6298
Not a Proper Input in Edge 10555,6298
Not a Proper Input in Edge 10556,6298
Not a Proper Input in Edge 10558,6298
Not a Proper Input in Edge 10561,6298
Not a Proper Input in Edge 10563,6298
Not a Proper Input in Edge 10566,6298
Not a Proper Input in Edge 10567,6298
Not a Proper Input in Edge 10569,6298
Not a Proper Input in Edge 10571,6298
Not a Proper Input in Edge 10572,6298
Not a Proper Input in Edge 10574,6298
Not a Proper Input in Edge 10575,6298
Not a Proper Input in Edge 10576,6298
Not a Proper Input in Edge 10577,6298
Not a Proper Input in Edge 10580,6298
Not a Proper Input in Edge 10582,6298
Not a Proper Input in Edge 10583,6298
Not a Proper Input in Edge 10584,6298
Not a Proper Input in Edge 10585,6298
Not a Proper Input in Edge 10586,6298
Not a Proper Input in Edge 10588,6298
Not a Proper Input in Edge 10590,6298
Not a Proper Input in Edge 10591,6298
Not a Proper Input in Edge 10594,6298
Not a Proper Input in Edge 10595,6298
Not a Proper Input in Edge 10596,6298
Not a Proper Input in Edge 10598,6298
Not a Proper Input in Edge 10599,6298
Not a Proper Input in Edge 10601,6298
Not a Proper Input in Edge 10603,6298
Not a Proper Input in Edge 10604,6298
Not a Proper Input in Edge 10607,6298
Not a Proper Input in Edge 10609,6298
Not a Proper Input in Edge 10614,6298
Not a Proper Input in Edge 10615,6298
Not a Proper Input in Edge 10616,6298
Not a Proper Input in Edge 10619,6298
Not a Proper Input in Edge 10622,6298
Not a Proper Input in Edge 10625,6298
Not a Proper Input in Edge 10627,6298
Not a Proper Input in Edge 10629,6298
Not a Proper Input in Edge 10630,6298
Not a Proper Input in Edge 10631,6298
Not a Proper Input in Edge 10632,6298
Not a Proper Input in Edge 10633,6298
Not a Proper Input in Edge 10634,6298
Not a Proper Input in Edge 10635,6298
Not a Proper Input in Edge 10636,6298
Not a Proper Input in Edge 10637,6298
Not a Proper Input in Edge 10638,6298
Not a Proper Input in Edge 10639,6298
Not a Proper Input in Edge 10640,6298
Not a Proper Input in Edge 10641,6298
Not a Proper Input in Edge 10642,6298
Not a Proper Input in Edge 10647,6298
Not a Proper Input in Edge 10648,6298
Not a Proper Input in Edge 10649,6298
Not a Proper Input in Edge 10651,6298
Not a Proper Input in Edge 10652,6298
Not a Proper Input in Edge 10653,6298
Not a Proper Input in Edge 10656,6298
Not a Proper Input in Edge 10657,6298
Not a Proper Input in Edge 10659,6298
Not a Proper Input in Edge 10662,6298
Not a Proper Input in Edge 10667,6298
Not a Proper Input in Edge 10668,6298
Not a Proper Input in Edge 10669,6298
Not a Proper Input in Edge 10675,6298
Not a Proper Input in Edge 10676,6298
Not a Proper Input in Edge 10678,6298
Not a Proper Input in Edge 10681,6298
Not a Proper Input in Edge 10682,6298
Not a Proper Input in Edge 10684,6298
Not a Proper Input in Edge 10685,6298
Not a Proper Input in Edge 10686,6298
Not a Proper Input in Edge 10688,6298
Not a Proper Input in Edge 10694,6298
Not a Proper Input in Edge 10695,6298
Not a Proper Input in Edge 10696,6298
Not a Proper Input in Edge 10698,6298
Not a Proper Input in Edge 10699,6298
Not a Proper Input in Edge 10700,6298
Not a Proper Input in Edge 10706,6298
Not a Proper Input in Edge 10707,6298
Not a Proper Input in Edge 10708,6298
Not a Proper Input in Edge 10709,6298
Not a Proper Input in Edge 10710,6298
Not a Proper Input in Edge 10711,6298
Not a Proper Input in Edge 10712,6298
Not a Proper Input in Edge 10713,6298
Not a Proper Input in Edge 10714,6298
Not a Proper Input in Edge 10715,6298
Not a Proper Input in Edge 10716,6298
Not a Proper Input in Edge 10723,6298
Not a Proper Input in Edge 10726,6298
Not a Proper Input in Edge 10727,6298
Not a Proper Input in Edge 10731,6298
Not a Proper Input in Edge 10732,6298
Not a Proper Input in Edge 10733,6298
Not a Proper Input in Edge 10734,6298
Not a Proper Input in Edge 10735,6298
Not a Proper Input in Edge 10736,6298
Not a Proper Input in Edge 10737,6298
Not a Proper Input in Edge 10739,6298
Not a Proper Input in Edge 10741,6298
Not a Proper Input in Edge 10743,6298
Not a Proper Input in Edge 10744,6298
Not a Proper Input in Edge 10745,6298
Not a Proper Input in Edge 10746,6298
Not a Proper Input in Edge 10751,6298
Not a Proper Input in Edge 10752,6298
Not a Proper Input in Edge 10753,6298
Not a Proper Input in Edge 10755,6298
Not a Proper Input in Edge 10756,6298
Not a Proper Input in Edge 10757,6298
Not a Proper Input in Edge 10758,6298
Not a Proper Input in Edge 10759,6298
Not a Proper Input in Edge 10760,6298
Not a Proper Input in Edge 10762,6298
Not a Proper Input in Edge 10764,6298
Not a Proper Input in Edge 10765,6298
Not a Proper Input in Edge 10766,6298
Not a Proper Input in Edge 10767,6298
Not a Proper Input in Edge 10769,6298
Not a Proper Input in Edge 10770,6298
Not a Proper Input in Edge 10771,6298
Not a Proper Input in Edge 10772,6298
Not a Proper Input in Edge 10775,6298
Not a Proper Input in Edge 10776,6298
Not a Proper Input in Edge 10777,6298
Not a Proper Input in Edge 10778,6298
Not a Proper Input in Edge 10779,6298
Not a Proper Input in Edge 10783,6298
Not a Proper Input in Edge 10784,6298
Not a Proper Input in Edge 10785,6298
Not a Proper Input in Edge 10787,6298
Not a Proper Input in Edge 10789,6298
Not a Proper Input in Edge 10790,6298
Not a Proper Input in Edge 10797,6298
Not a Proper Input in Edge 10798,6298
Not a Proper Input in Edge 10799,6298
Not a Proper Input in Edge 10800,6298
Not a Proper Input in Edge 10801,6298
Not a Proper Input in Edge 10802,6298
Not a Proper Input in Edge 10803,6298
Not a Proper Input in Edge 10804,6298
Not a Proper Input in Edge 10805,6298
Not a Proper Input in Edge 10806,6298
Not a Proper Input in Edge 10808,6298
Not a Proper Input in Edge 10810,6298
Not a Proper Input in Edge 10812,6298
Not a Proper Input in Edge 10815,6298
Not a Proper Input in Edge 10816,6298
Not a Proper Input in Edge 10817,6298
Not a Proper Input in Edge 10818,6298
Not a Proper Input in Edge 10819,6298
Not a Proper Input in Edge 10820,6298
Not a Proper Input in Edge 10822,6298
Not a Proper Input in Edge 10824,6298
Not a Proper Input in Edge 10825,6298
Not a Proper Input in Edge 10826,6298
Not a Proper Input in Edge 10827,6298
Not a Proper Input in Edge 10828,6298
Not a Proper Input in Edge 10829,6298
Not a Proper Input in Edge 10830,6298
Not a Proper Input in Edge 10832,6298
Not a Proper Input in Edge 10834,6298
Not a Proper Input in Edge 10835,6298
Not a Proper Input in Edge 10836,6298
Not a Proper Input in Edge 10838,6298
Not a Proper Input in Edge 10840,6298
Not a Proper Input in Edge 10841,6298
Not a Proper Input in Edge 10842,6298
Not a Proper Input in Edge 10844,6298
Not a Proper Input in Edge 10845,6298
Not a Proper Input in Edge 10847,6298
Not a Proper Input in Edge 10850,6298
Not a Proper Input in Edge 10852,6298
Not a Proper Input in Edge 10853,6298
Not a Proper Input in Edge 10855,6298
Not a Proper Input in Edge 10856,6298
Not a Proper Input in Edge 10857,6298
Not a Proper Input in Edge 10858,6298
Not a Proper Input in Edge 10859,6298
Not a Proper Input in Edge 10861,6298
Not a Proper Input in Edge 10862,6298
Not a Proper Input in Edge 10863,6298
Not a Proper Input in Edge 10864,6298
Not a Proper Input in Edge 10865,6298
Not a Proper Input in Edge 10867,6298
Not a Proper Input in Edge 10868,6298
Not a Proper Input in Edge 10869,6298
Not a Proper Input in Edge 10871,6298
Not a Proper Input in Edge 10874,6298
Not a Proper Input in Edge 10875,6298
Not a Proper Input in Edge 10876,6298
Not a Proper Input in Edge 10877,6298
Not a Proper Input in Edge 10878,6298
Not a Proper Input in Edge 10881,6298
Not a Proper Input in Edge 10882,6298
Not a Proper Input in Edge 10883,6298
Not a Proper Input in Edge 10884,6298
Not a Proper Input in Edge 10885,6298
Not a Proper Input in Edge 10886,6298
Not a Proper Input in Edge 10888,6298
Not a Proper Input in Edge 10889,6298
Not a Proper Input in Edge 10890,6298
Not a Proper Input in Edge 10893,6298
Not a Proper Input in Edge 10894,6298
Not a Proper Input in Edge 10897,6298
Not a Proper Input in Edge 10899,6298
Not a Proper Input in Edge 10900,6298
Not a Proper Input in Edge 10901,6298
Not a Proper Input in Edge 10903,6298
Not a Proper Input in Edge 10904,6298
Not a Proper Input in Edge 10906,6298
Not a Proper Input in Edge 10908,6298
Not a Proper Input in Edge 10909,6298
Not a Proper Input in Edge 10911,6298
Not a Proper Input in Edge 10912,6298
Not a Proper Input in Edge 10914,6298
Not a Proper Input in Edge 10915,6298
Not a Proper Input in Edge 10917,6298
Not a Proper Input in Edge 10918,6298
Not a Proper Input in Edge 10919,6298
Not a Proper Input in Edge 10923,6298
Not a Proper Input in Edge 10924,6298
Not a Proper Input in Edge 10925,6298
Not a Proper Input in Edge 10929,6298
Not a Proper Input in Edge 10933,6298
Not a Proper Input in Edge 10935,6298
Not a Proper Input in Edge 10936,6298
Not a Proper Input in Edge 10940,6298
Not a Proper Input in Edge 10942,6298
Not a Proper Input in Edge 10943,6298
Not a Proper Input in Edge 10944,6298
Not a Proper Input in Edge 10945,6298
Not a Proper Input in Edge 10946,6298
Not a Proper Input in Edge 10947,6298
Not a Proper Input in Edge 10949,6298
Not a Proper Input in Edge 10951,6298
Not a Proper Input in Edge 10952,6298
Not a Proper Input in Edge 10955,6298
Not a Proper Input in Edge 10956,6298
Not a Proper Input in Edge 10958,6298
Not a Proper Input in Edge 10959,6298
Not a Proper Input in Edge 10963,6298
Not a Proper Input in Edge 10965,6298
Not a Proper Input in Edge 10967,6298
Not a Proper Input in Edge 10968,6298
Not a Proper Input in Edge 10970,6298
Not a Proper Input in Edge 10972,6298
Not a Proper Input in Edge 10974,6298
Not a Proper Input in Edge 10976,6298
Not a Proper Input in Edge 10979,6298
Not a Proper Input in Edge 10981,6298
Not a Proper Input in Edge 10983,6298
Not a Proper Input in Edge 10984,6298
Not a Proper Input in Edge 10985,6298
Not a Proper Input in Edge 10988,6298
Not a Proper Input in Edge 10989,6298
Not a Proper Input in Edge 10990,6298

In [ ]:
#adjM.shape
import numpy as np
len(adjM)
arr = np.array(adjM)

newarr = arr.reshape(10075, 10075)

print(newarr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [ ]:
def create_adjacency_matrix(V, edges):
    # Initialize an empty V x V matrix with all zeros
    matrix = [[0] * V for _ in range(V)]

    # Populate the matrix based on the edges
    for edge in edges:
        u, v = edge
        matrix[u][v] = 1
#       matrix[v][u] = 1  # Undirected graph

    return matrix
V1 = len(adj)
edges1 = adj[['start', 'end']].values.tolist()
adj_matrix1 = create_adjacency_matrix(V1, edges1)
for row in adj_matrix1:
    print(row)
print()

In [ ]:
type(adj)

pandas.core.frame.DataFrame