<a href="https://colab.research.google.com/github/markajbell/BH/blob/main/Large_paths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
#Install dependencies

!pip install pandas

import pandas as pd
import json

# Open JSON file
with open('jd.json', 'r') as f:
    data_all = json.load(f)

#Create a dataframe from the uploaded JSON

#df_all = pd.DataFrame(data_all)

# Display the first few rows of the DataFrame to verify
#print(df_all.head())

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [16]:
data_all

{'nodes': {'12': {'label': 'SOM@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '23631FBB-E0CB-47D0-8B72-A3AD167EAEF6',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '13': {'label': 'ADMINSDHOLDER@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'E92F8F06-89FF-4658-9F6D-9611D43790C1',
   'isTierZero': True,
   'isOwnedObject': False,
   'lastSeen': ''},
  '14': {'label': 'WMIGPO@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '2089520C-EA98-4F51-9266-17DB870EB226',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '15': {'label': 'WMIPOLICY@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '16': {'label': 'POLICYTEMPLATE@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '6BC18B1C-3EA1-45BE-B7E1-B001627E90B8',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '17': {'label': 'POLICYTYPE@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '7089E478-DB66-4FAF-B705-917737D4990D',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '18': {'label': 'KEYS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '20A295DB-7AC5-4C38-8A2B-AACA4DC56E68',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '19': {'label': 'RPCSERVICES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'F7C4CB4E-4FF9-418A-A576-F05FFA92E730',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '20': {'label': 'USERS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '06DDAA96-A710-4023-A26A-C522B2A87AB4',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '21': {'label': 'PROGRAM DATA@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '7ECD8E4E-DC0E-49D5-9379-A6E0E1BBBFDE',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '22': {'label': 'MICROSOFT@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '89A59FA1-EBC4-44D1-9F33-F7E033B227ED',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '23': {'label': 'MEETINGS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'C41BB32F-AB5A-4E73-8ECE-F6E65240BF84',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '24': {'label': 'RAS AND IAS SERVERS ACCESS CHECK@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'E87CC94F-2114-4B3B-8899-8964AFCBE6F9',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '25': {'label': 'SYSTEM@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '26': {'label': 'POLICIES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '12B683AA-8B3D-4FE5-B3BF-58326CDC237B',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '27': {'label': 'COMPARTITIONSETS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '69B31891-4A4E-41CC-B007-776E60483A36',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '28': {'label': 'COMPUTERS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '2CADA56A-0451-4431-B0EE-001D47266554',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '29': {'label': 'IP SECURITY@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '8149DB1C-65CF-45AB-BB3D-88339A510982',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '30': {'label': 'WINSOCKSERVICES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '6AC45820-973F-4A59-9430-B442DED41BC4',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '31': {'label': 'FOREIGNSECURITYPRINCIPALS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '1FB9342A-08C0-4F8A-B842-2F6FD0056F0B',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '32': {'label': 'MANAGED SERVICE ACCOUNTS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'AB800822-D421-4264-9E61-87F9EDAA1A92',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '33': {'label': 'WINDOWS NT@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'CF6D738F-12D8-4B8D-894A-94B40F6A27FB',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '34': {'label': 'NETSERVICES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '37E5D66C-A747-4689-B6E5-AD59B456CECE',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '35': {'label': 'RRAS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '6443E8AB-64C9-497D-9737-9974361DADB1',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '36': {'label': 'PUBLIC KEY SERVICES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '9DDA5312-9FD8-44DE-9F45-2C3DB2101286',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '37': {'label': 'CERTIFICATE TEMPLATES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '2E778EA3-7B5F-4D96-800F-F23C95BCBBC0',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '38': {'label': 'ENROLLMENT SERVICES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'EB394777-78ED-412F-92C2-53605DC52D78',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '39': {'label': 'CERTIFICATION AUTHORITIES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'EEF7BFE1-B6CA-4714-9803-91010F65CF02',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '40': {'label': 'AIA@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '8BEE76D9-F2C2-4129-8CC6-296B756714FD',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '41': {'label': 'CDP@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'B1FC6FBD-F5F1-4FC6-B849-A3967E483893',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '42': {'label': 'KRA@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '40549E53-2121-4659-971C-5DFA84BB0685',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '43': {'label': 'CLAIMS CONFIGURATION@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'C2A43304-3EF9-400F-883B-E83CB1DA5186',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '44': {'label': 'VALUE TYPES@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'ED1730EC-DCC9-45F8-92EC-39C21CB8721A',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '45': {'label': 'RESOURCE PROPERTY LISTS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '9F5E387B-71BE-44F6-8D40-1A9ED2F544A2',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '46': {'label': 'MICROSOFT SPP@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'C97552A6-E24E-4AF3-9F7D-3583F42F224F',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '47': {'label': 'GROUP KEY DISTRIBUTION SERVICE@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '06FB948F-2B20-44F8-B322-F97BB8B494F0',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '48': {'label': 'MASTER ROOT KEYS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'C40F0363-1FE6-4E4C-BAA4-B26D0FC2A39E',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '49': {'label': 'SERVER CONFIGURATION@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '53C4CC13-A110-4CCF-BEEB-3FBEE97CB4C7',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '50': {'label': 'AUTHN POLICY CONFIGURATION@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '3467A4DE-1B7E-43F0-A7BC-27289C265D30',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '51': {'label': 'SHADOW PRINCIPAL CONFIGURATION@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'AF30DD41-A578-4F86-9800-68C77C3FE10A',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '52': {'label': '405@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '73E917E8-70BA-4DC7-BE74-6D98686E20FC',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '53': {'label': '406@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'DEC5BD39-D2D0-4CD3-A9C0-5B1A4CBE29AF',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '54': {'label': '407@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '80472F45-089D-434B-8928-A34C5E5CBE40',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '55': {'label': '408@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '7A5E661C-2ED8-49AE-9FCE-3EE32EFAC86A',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '56': {'label': 'C0A@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'E884AAB2-4F03-4AE9-9EBB-512D800E3C5E',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '57': {'label': '40B@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'DCF59437-3CBF-4656-AF63-6EA3201C4570',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '58': {'label': '40C@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'E5C25030-87CA-4C0F-B565-821AB8D2F644',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '59': {'label': '410@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '672F270C-0B58-4342-B4C3-21625B7F6371',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '60': {'label': '40E@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'CC328F3B-14F3-4672-B064-9B558087FD6D',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '61': {'label': '412@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '6A1E7696-D708-4341-9CAF-D4B3709C86EF',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '62': {'label': '411@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'ECE3ACE2-C5FB-45BF-ADCB-5DE45CF5AC01',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '63': {'label': '414@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'E5140161-02BA-41BC-AED3-C00D460FD570',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '64': {'label': '413@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '804172F2-9D60-4F26-9C10-EF9982BF1FCB',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '65': {'label': '415@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '3BA65D36-1BA1-40E8-9572-8FA53EFDA01B',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '66': {'label': '416@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '1DBC20BE-CB9D-402F-BCD9-613D673C8735',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '67': {'label': '816@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'F3DD895C-5460-4025-ABDB-54078B55ABB4',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '68': {'label': '419@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '892D3366-ABCE-4F79-B593-27992F5D4F02',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '69': {'label': '41D@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '2A7F7EE5-F785-4D3E-9AB2-50982AC5D8F8',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '70': {'label': '41F@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '838895CD-0B89-49EC-A9ED-68B3D3D34FC3',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '71': {'label': '804@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '1A0EAE45-D892-46AC-AB35-8E0137DB270F',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '72': {'label': '404@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '891DBFB1-41FB-4958-B003-9F2A337B52B2',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '73': {'label': '409@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '1DE0F54A-AA5A-4EF9-93E7-B1C3F05EF9DD',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '74': {'label': 'OPERATIONS@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '0566BB56-CAA8-430E-8505-6F48CC4845A7',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '75': {'label': '3467DAE5-DEDD-4648-9066-F48AC186B20A@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'FB597C38-91A1-4C9D-B9A8-929B431A06F2',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '76': {'label': '33B7EE33-1386-47CF-BAA1-B03E06473253@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'C4E51409-DC7F-4542-BEF6-9E1D863042DB',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '77': {'label': 'E9EE8D55-C2FB-4723-A333-C80FF4DFBF45@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '3BCD25E3-40EE-47E0-9A3A-F33D3EB5E939',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '78': {'label': 'CCFAE63A-7FB5-454C-83AB-0E8E1214974E@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '33B23EA1-2EB0-4054-9B58-F383BADC16A1',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '79': {'label': 'AD3C7909-B154-4C16-8BF7-2C3A7870BB3D@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'B80D25E6-E120-4D2A-A87F-44DE29FF1F31',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '80': {'label': '26AD2EBF-F8F5-44A4-B97C-A616C8B9D09A@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '59B321D4-923C-4DFC-A9DE-1A6643751C72',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '81': {'label': '4444C516-F43A-4C12-9C4B-B5C064941D61@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '3580BACA-7640-46FB-B2FF-997724BFB34D',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '82': {'label': '436A1A4B-F41A-46E6-AC86-427720EF29F3@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '8BC2AC3D-5C33-4F40-B2FD-E2C366346B45',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '83': {'label': 'B2B7FB45-F50D-41BC-A73B-8F580F3B636A@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '79592503-491E-4DB5-A7F2-AC215BB7C4AB',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '84': {'label': '1BDF6366-C3DB-4D0B-B8CB-F99BA9BCE20F@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'BD08C1E1-6310-4C3A-8D2E-838987E64E7E',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '85': {'label': '63C0F51A-067C-4640-8A4F-044FB33F1049@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'B1229BC0-220F-4722-8950-8D8DA6529443',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '86': {'label': 'DAE441C0-366E-482E-98D9-60A99A1898CC@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '6A666FBD-D97E-4C76-B2E1-8AD775B38169',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '87': {'label': '7DD09CA6-F0D6-43BF-B7F8-EF348F435617@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '40847D4F-EA82-42C0-A112-13A5638FDBEC',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '88': {'label': '6B800A81-AFFE-4A15-8E41-6EA0C7AA89E4@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '38076C67-4FDA-49F2-B0D0-42C4121B8E3F',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '89': {'label': 'DD07182C-3174-4C95-902A-D64FEE285BBF@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '053873C0-E7F8-4249-9AEF-4E2C6AC60523',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '90': {'label': 'FFA5EE3C-1405-476D-B344-7AD37D69CC25@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '6BF0784C-7594-4E17-BA92-B0F6595DF2C1',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '91': {'label': '099F1587-AF70-49C6-AB6C-7B3E82BE0FE2@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '084A7A96-1301-49E7-886C-07DD4BEB5BF8',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '92': {'label': '94FDEBC6-8EEB-4640-80DE-EC52B9CA17FA@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '106E9FF3-7CB1-40F8-99BD-C54BB8E150D3',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '93': {'label': '1A3F6B15-55F2-4752-BA27-3D38A8232C4D@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '74C82502-4DE1-48C7-85F2-238D96EFEA87',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '94': {'label': 'DEE21A17-4E8E-4F40-A58C-C0C009B685A7@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '657F71CE-3527-40A5-B220-DF6FFD23CF9A',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '95': {'label': '9BD98BB4-4047-4DE5-BF4C-7BD1D0F6D21D@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '3CF5C8AE-2B25-4769-AEA9-E77141D95C35',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '96': {'label': '3FE80FBF-BF39-4773-B5BD-3E5767A30D2D@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '7C875678-51D5-4953-8085-94923CCA07AF',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '97': {'label': '39902C52-EF24-4B4B-8033-2C9DFDD173A2@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '782BC8EC-4197-4F0D-AF12-F3CA7C3F1947',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '98': {'label': 'F02915E2-9141-4F73-B8E7-2804662782DA@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '8DB5DF44-E45E-4751-9721-FFFE60C3F243',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '99': {'label': '20BF09B4-6D0B-4CD1-9C09-4231EDF1209B@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '4E71721E-52FD-45A0-9A4B-8D02860696A4',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '100': {'label': '94F238BB-831C-11D6-977B-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'DF7E8C0E-A400-45FD-A862-F7726E35794B',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '101': {'label': '94F238BD-831C-11D6-977B-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'F421CC89-5F03-40DD-86AC-591BF90FD067',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '102': {'label': '94F238BC-831C-11D6-977B-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '8E64474C-52E2-4E7E-B869-E8AD5063E9C3',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '103': {'label': '94F238BF-831C-11D6-977B-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'FDF61127-3601-4468-9484-D702025FC5A9',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '104': {'label': '94F238BE-831C-11D6-977B-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '882EA007-F4A6-40B5-A488-6C3BBA888EF7',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '105': {'label': '94F238C0-831C-11D6-977B-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '93CD89BD-FEBA-4247-9F01-749ABFD54AD2',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '106': {'label': 'EDA27B47-E610-11D6-9793-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'CFE7B03B-4D18-4866-A531-52D07A10DB7A',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '107': {'label': 'EDA27B48-E610-11D6-9793-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '5E75D340-4C35-4908-A5EE-4711D634A464',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '108': {'label': 'EDA27B49-E610-11D6-9793-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': '71FF2722-3398-4650-8052-8928F92B21CA',
   'isTierZero': False,
   'isOwnedObject': False,
   'lastSeen': ''},
  '109': {'label': '26D9C510-E61A-11D6-9793-00C04F613221@PHANTOM.CORP',
   'kind': 'Container',
   'objectId': 'F3CF5452-2DEA-4E1B-912E-ED8FA064A37A',
   'isTierZero': False,

In [17]:
data_all.keys()

dict_keys(['nodes', 'edges'])

In [25]:
nodes_all = data_all['nodes']
edges_all = data_all['edges']

In [31]:
nodes_all=pd.DataFrame(nodes_all).T
edges_all=pd.DataFrame(edges_all)

In [32]:
edges_all

     source target       label        kind lastSeen exploreGraphId data
0      1398   1009   AddMember   AddMember                     NaN  NaN
1      1131    902  GenericAll  GenericAll                     NaN  NaN
2      1034   1195      Enroll      Enroll                     NaN  NaN
3      1034   1196      Enroll      Enroll                     NaN  NaN
4      1003   1238  GenericAll  GenericAll                     NaN  NaN
...     ...    ...         ...         ...      ...            ...  ...
3727   1131   1193  GetChanges  GetChanges                     NaN  NaN
3728    960   1195   WriteDacl   WriteDacl                     NaN  NaN
3729    985   1195   WriteDacl   WriteDacl                     NaN  NaN
3730    960   1196   WriteDacl   WriteDacl                     NaN  NaN
3731    985   1196   WriteDacl   WriteDacl                     NaN  NaN

[3732 rows x 7 columns]

In [28]:
import pandas as pd
#nodes_all = pd.DataFrame(df_all[index])
nodes_all.index = nodes_all.index.astype(int)
nodes_all = nodes_all.reset_index().rename(columns={'index': 'node_id'})
nodes_all

,node_id,label,kind,objectId,isTierZero,isOwnedObject,lastSeen
0,12,SOM@PHANTOM.CORP,Container,23631FBB-E0CB-47D0-8B72-A3AD167EAEF6,False,False,
1,13,ADMINSDHOLDER@PHANTOM.CORP,Container,E92F8F06-89FF-4658-9F6D-9611D43790C1,True,False,
2,14,WMIGPO@PHANTOM.CORP,Container,2089520C-EA98-4F51-9266-17DB870EB226,False,False,
3,15,WMIPOLICY@PHANTOM.CORP,Container,04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0,False,False,
4,16,POLICYTEMPLATE@PHANTOM.CORP,Container,6BC18B1C-3EA1-45BE-B7E1-B001627E90B8,False,False,
...,...,...,...,...,...,...,...
708,1477,SM_6352FF0D1E8A4B359@WRAITH.CORP,Base,S-1-5-21-3702535222-3822678775-2090119576-1148,False,False,
709,1478,TARGETUSERD@WRAITH.CORP,Base,S-1-5-21-3702535222-3822678775-2090119576-1185,False,False,
710,1479,TARGETUSERB@WRAITH.CORP,Base,S-1-5-21-3702535222-3822678775-2090119576-1183,False,False,
711,1480,KRBTGT@WRAITH.CORP,Base,S-1-5-21-3702535222-3822678775-2090119576-502,False,False,
712,1482,JACK@WRAITH.CORP,Base,S-1-5-21-3702535222-3822678775-2090119576-1189,True,False,

In [33]:
edges_all['source'] = edges_all['source'].astype(int)
edges_all['target'] = edges_all['target'].astype(int)
#print(edges_all)
edges_all.dtypes

source             int64
target             int64
label             object
kind              object
lastSeen          object
exploreGraphId    object
data              object
dtype: object

In [34]:
# Apply the weights based on the 'label' column
def assign_weight(label):
    if label == "GenericAll":
        return 9
    elif label == "Owns":
        return 10
    elif label == "GenericWrite":
        return 2
    elif label == "AllExtendedRights":
        return 6
    elif label == "CanRDP":
        return 2
    elif label == "Contains":
        return 2
    elif label == "DCSync":
        return 8
    elif label == "WriteDacl":
        return 5
    elif label == "WriteOwner":
        return 7
    elif label == "AddKeyCredentialLink":
        return 6
    elif label == "AdminTo":
        return 8
    elif label == "MemberOf":
        return 1
    elif label == "CanPSRemote":
        return 2
    elif label == "ExecuteDCOM":
        return 2
    elif label == "GPLink":
        return 3
    elif label == "tier0":
        return 20
    else:
        return 1 # Default weight for other labels

edges_all['weight'] = edges_all['label'].apply(assign_weight)

# Display the updated edges_all DataFrame with the 'weight' column
print("\nEdges_all DataFrame with weight column:")
edges_all
#clear_output()

Edges_all DataFrame with weight column:

,source,target,label,kind,lastSeen,exploreGraphId,data,weight
0,1398,1009,AddMember,AddMember,,NaN,NaN,1
1,1131,902,GenericAll,GenericAll,,NaN,NaN,9
2,1034,1195,Enroll,Enroll,,NaN,NaN,1
3,1034,1196,Enroll,Enroll,,NaN,NaN,1
4,1003,1238,GenericAll,GenericAll,,NaN,NaN,9
...,...,...,...,...,...,...,...,...
3727,1131,1193,GetChanges,GetChanges,,NaN,NaN,1
3728,960,1195,WriteDacl,WriteDacl,,NaN,NaN,5
3729,985,1195,WriteDacl,WriteDacl,,NaN,NaN,5
3730,960,1196,WriteDacl,WriteDacl,,NaN,NaN,5
3731,985,1196,WriteDacl,WriteDacl,,NaN,NaN,5

In [35]:
# prompt: remove columns lastSeen,exploreGraphId, data from edges_all

edges_all = edges_all.drop(columns=['lastSeen', 'exploreGraphId', 'data'])

In [36]:
edges_all

      source  target       label        kind  weight
0       1398    1009   AddMember   AddMember       1
1       1131     902  GenericAll  GenericAll       9
2       1034    1195      Enroll      Enroll       1
3       1034    1196      Enroll      Enroll       1
4       1003    1238  GenericAll  GenericAll       9
...      ...     ...         ...         ...     ...
3727    1131    1193  GetChanges  GetChanges       1
3728     960    1195   WriteDacl   WriteDacl       5
3729     985    1195   WriteDacl   WriteDacl       5
3730     960    1196   WriteDacl   WriteDacl       5
3731     985    1196   WriteDacl   WriteDacl       5

[3732 rows x 5 columns]

In [37]:
# prompt: create a unique list from label in edges_all and create a pd.datadrame with the contents

import pandas as pd
unique_labels = edges_all['label'].unique()
unique_labels_df = pd.DataFrame(unique_labels, columns=['Unique Labels'])
print("\nDataFrame of Unique Labels:")
unique_labels_df

DataFrame of Unique Labels:

              Unique Labels
0                 AddMember
1                GenericAll
2                    Enroll
3        ManageCertificates
4              GenericWrite
5                  MemberOf
6                 WriteDacl
7                  ManageCA
8         AllExtendedRights
9                    DCSync
10         SyncLAPSPassword
11                     Owns
12               WriteOwner
13            GetChangesAll
14   WritePKIEnrollmentFlag
15         WritePKINameFlag
16  GetChangesInFilteredSet
17               GetChanges

In [38]:
# prompt: replace the edges_all[label] with the corresponding index value from unique_labels_df where label=label

edges_all['label'] = edges_all['label'].apply(lambda label: unique_labels_df[unique_labels_df['Unique Labels'] == label].index[0])
edges_all

Edges_all DataFrame with label_index column:

      source  target       label        kind  weight  label_index
0       1398    1009   AddMember   AddMember       1            0
1       1131     902  GenericAll  GenericAll       9            1
2       1034    1195      Enroll      Enroll       1            2
3       1034    1196      Enroll      Enroll       1            2
4       1003    1238  GenericAll  GenericAll       9            1
...      ...     ...         ...         ...     ...          ...
3727    1131    1193  GetChanges  GetChanges       1           17
3728     960    1195   WriteDacl   WriteDacl       5            6
3729     985    1195   WriteDacl   WriteDacl       5            6
3730     960    1196   WriteDacl   WriteDacl       5            6
3731     985    1196   WriteDacl   WriteDacl       5            6

[3732 rows x 6 columns]

In [ ]:
edges_all = edges_all.drop(columns=['label'])

In [41]:
#

import pandas as pd
import heapq

def dijkstra_shortest_path(edges, nodes, start_node_id):
    """
    Finds the shortest paths from a start node to all other nodes
    using Dijkstra's algorithm.

    Args:
        edges (pd.DataFrame): DataFrame with 'source', 'target', and 'weight' columns.
        nodes (pd.DataFrame): DataFrame with 'node_id'.
        start_node_id (int): The ID of the starting node.

    Returns:
        dict: A dictionary where keys are the reachable node IDs and values are their shortest distances.
        dict: A dictionary to reconstruct the shortest paths.
    """
    # Build the graph as an adjacency list
    graph = {}
    for index, row in edges.iterrows():
        source = row['source']
        target = row['target']
        weight = row['weight']
        if source not in graph:
            graph[source] = []
        graph[source].append((target, weight))

    # Initialize distances and predecessors for all nodes in the graph
    all_node_ids = set(nodes['node_id'].tolist()) | set(edges['source'].tolist()) | set(edges['target'].tolist())
    distances = {node_id: float('infinity') for node_id in all_node_ids}
    distances[start_node_id] = 0
    predecessors = {node_id: None for node_id in all_node_ids}

    # Priority queue for Dijkstra
    priority_queue = [(0, start_node_id)]

    while priority_queue:
        current_distance, current_node = heapq.heappop(priority_queue)

        # If the current distance is greater than the known distance, skip
        if current_distance > distances[current_node]:
            continue

        # Explore neighbors
        if current_node in graph:
            for neighbor, weight in graph[current_node]:
                distance = current_distance + weight

                # If a shorter path is found
                if distance < distances[neighbor]:
                    distances[neighbor] = distance
                    predecessors[neighbor] = current_node
                    heapq.heappush(priority_queue, (distance, neighbor))

    # Filter out unreachable nodes
    reachable_distances = {node_id: dist for node_id, dist in distances.items() if dist != float('infinity')}
    reachable_predecessors = {node_id: pred for node_id, pred in predecessors.items() if pred is not None or node_id == start_node_id} # Include start node with None predecessor

    return reachable_distances, reachable_predecessors
start_node = 1398
# Example usage: Find the shortest path from start_node to all reachable nodes
shortest_paths, path_predecessors = dijkstra_shortest_path(edges_all, nodes_all, start_node)

print(f"\nShortest paths from node {start_node} to all reachable nodes:")
if shortest_paths:
    # Sort by distance for better readability
    sorted_paths = sorted(shortest_paths.items(), key=lambda item: item[1])
    for target_node_id, distance in sorted_paths:
        # Reconstruct the path
        path = []
        current = target_node_id
        # Handle the case where the target is the start node itself
        if current == start_node:
            path = [start_node]
        else:
            while current is not None:
                path.append(current)
                current = path_predecessors.get(current)
            path.reverse()
        print(f"  To node {target_node_id}: Distance = {distance}, Path = {path}")
else:
    print(f"  No reachable nodes found from node {start_node}.")

Shortest paths from node 1398 to all reachable nodes:
  To node 1398: Distance = 0, Path = [1398]
  To node 960: Distance = 1, Path = [1398, 960]
  To node 963: Distance = 1, Path = [1398, 963]
  To node 985: Distance = 1, Path = [1398, 985]
  To node 1009: Distance = 1, Path = [1398, 1009]
  To node 1131: Distance = 1, Path = [1398, 1131]
  To node 1003: Distance = 2, Path = [1398, 985, 1003]
  To node 1034: Distance = 2, Path = [1398, 963, 1034]
  To node 1193: Distance = 2, Path = [1398, 1131, 1193]
  To node 1195: Distance = 2, Path = [1398, 960, 1195]
  To node 1196: Distance = 2, Path = [1398, 960, 1196]
  To node 1244: Distance = 2, Path = [1398, 960, 1244]
  To node 1245: Distance = 2, Path = [1398, 960, 1245]
  To node 1246: Distance = 2, Path = [1398, 960, 1246]
  To node 1247: Distance = 2, Path = [1398, 960, 1247]
  To node 1248: Distance = 2, Path = [1398, 960, 1248]
  To node 1249: Distance = 2, Path = [1398, 960, 1249]
  To node 1250: Distance = 2, Path = [1398, 960, 1250]
  To node 1251: Distance = 2, Path = [1398, 960, 1251]
  To node 1252: Distance = 2, Path = [1398, 960, 1252]
  To node 1253: Distance = 2, Path = [1398, 960, 1253]
  To node 1254: Distance = 2, Path = [1398, 960, 1254]
  To node 1255: Distance = 2, Path = [1398, 960, 1255]
  To node 1256: Distance = 2, Path = [1398, 960, 1256]
  To node 1257: Distance = 2, Path = [1398, 960, 1257]
  To node 1258: Distance = 2, Path = [1398, 960, 1258]
  To node 1259: Distance = 2, Path = [1398, 960, 1259]
  To node 1260: Distance = 2, Path = [1398, 960, 1260]
  To node 1261: Distance = 2, Path = [1398, 960, 1261]
  To node 1262: Distance = 2, Path = [1398, 960, 1262]
  To node 1263: Distance = 2, Path = [1398, 960, 1263]
  To node 1264: Distance = 2, Path = [1398, 960, 1264]
  To node 1265: Distance = 2, Path = [1398, 960, 1265]
  To node 1266: Distance = 2, Path = [1398, 960, 1266]
  To node 1267: Distance = 2, Path = [1398, 960, 1267]
  To node 1268: Distance = 2, Path = [1398, 960, 1268]
  To node 1269: Distance = 2, Path = [1398, 960, 1269]
  To node 1271: Distance = 2, Path = [1398, 960, 1271]
  To node 1272: Distance = 2, Path = [1398, 960, 1272]
  To node 1273: Distance = 2, Path = [1398, 960, 1273]
  To node 1274: Distance = 2, Path = [1398, 960, 1274]
  To node 1275: Distance = 2, Path = [1398, 960, 1275]
  To node 1276: Distance = 2, Path = [1398, 960, 1276]
  To node 1277: Distance = 2, Path = [1398, 960, 1277]
  To node 1278: Distance = 2, Path = [1398, 960, 1278]
  To node 1279: Distance = 2, Path = [1398, 960, 1279]
  To node 1280: Distance = 2, Path = [1398, 960, 1280]
  To node 1281: Distance = 2, Path = [1398, 960, 1281]
  To node 1282: Distance = 2, Path = [1398, 960, 1282]
  To node 1283: Distance = 2, Path = [1398, 960, 1283]
  To node 1284: Distance = 2, Path = [1398, 960, 1284]
  To node 1285: Distance = 2, Path = [1398, 960, 1285]
  To node 1286: Distance = 2, Path = [1398, 960, 1286]
  To node 1287: Distance = 2, Path = [1398, 960, 1287]
  To node 1288: Distance = 2, Path = [1398, 960, 1288]
  To node 1289: Distance = 2, Path = [1398, 960, 1289]
  To node 1290: Distance = 2, Path = [1398, 960, 1290]
  To node 1291: Distance = 2, Path = [1398, 960, 1291]
  To node 1293: Distance = 2, Path = [1398, 960, 1293]
  To node 1295: Distance = 2, Path = [1398, 960, 1295]
  To node 1296: Distance = 2, Path = [1398, 960, 1296]
  To node 1297: Distance = 2, Path = [1398, 960, 1297]
  To node 1298: Distance = 2, Path = [1398, 960, 1298]
  To node 1299: Distance = 2, Path = [1398, 960, 1299]
  To node 1300: Distance = 2, Path = [1398, 960, 1300]
  To node 1301: Distance = 2, Path = [1398, 960, 1301]
  To node 1302: Distance = 2, Path = [1398, 960, 1302]
  To node 1303: Distance = 2, Path = [1398, 960, 1303]
  To node 1304: Distance = 2, Path = [1398, 960, 1304]
  To node 1305: Distance = 2, Path = [1398, 960, 1305]
  To node 1306: Distance = 2, Path = [1398, 960, 1306]
  To node 1372: Distance = 2, Path = [1398, 1131, 1372]
  To node 951: Distance = 3, Path = [1398, 960, 951]
  To node 954: Distance = 3, Path = [1398, 960, 954]
  To node 958: Distance = 3, Path = [1398, 960, 958]
  To node 959: Distance = 3, Path = [1398, 960, 959]
  To node 966: Distance = 3, Path = [1398, 960, 966]
  To node 980: Distance = 3, Path = [1398, 960, 980]
  To node 983: Distance = 3, Path = [1398, 960, 983]
  To node 984: Distance = 3, Path = [1398, 960, 984]
  To node 987: Distance = 3, Path = [1398, 960, 987]
  To node 996: Distance = 3, Path = [1398, 960, 996]
  To node 1012: Distance = 3, Path = [1398, 960, 1012]
  To node 1019: Distance = 3, Path = [1398, 960, 1019]
  To node 1023: Distance = 3, Path = [1398, 960, 1023]
  To node 1025: Distance = 3, Path = [1398, 960, 1025]
  To node 1033: Distance = 3, Path = [1398, 963, 1034, 1033]
  To node 1040: Distance = 3, Path = [1398, 960, 1040]
  To node 1043: Distance = 3, Path = [1398, 960, 1043]
  To node 1050: Distance = 3, Path = [1398, 960, 1050]
  To node 1051: Distance = 3, Path = [1398, 960, 1051]
  To node 1066: Distance = 3, Path = [1398, 960, 1066]
  To node 1067: Distance = 3, Path = [1398, 960, 1067]
  To node 1075: Distance = 3, Path = [1398, 960, 1075]
  To node 1078: Distance = 3, Path = [1398, 960, 1078]
  To node 1080: Distance = 3, Path = [1398, 960, 1080]
  To node 1086: Distance = 3, Path = [1398, 1131, 1086]
  To node 1087: Distance = 3, Path = [1398, 1131, 1087]
  To node 1088: Distance = 3, Path = [1398, 1131, 1088]
  To node 1089: Distance = 3, Path = [1398, 1131, 1089]
  To node 1090: Distance = 3, Path = [1398, 1131, 1090]
  To node 1091: Distance = 3, Path = [1398, 1131, 1091]
  To node 1092: Distance = 3, Path = [1398, 1131, 1092]
  To node 1093: Distance = 3, Path = [1398, 1131, 1093]
  To node 1094: Distance = 3, Path = [1398, 1131, 1094]
  To node 1095: Distance = 3, Path = [1398, 1131, 1095]
  To node 1096: Distance = 3, Path = [1398, 1131, 1096]
  To node 1097: Distance = 3, Path = [1398, 1131, 1097]
  To node 1098: Distance = 3, Path = [1398, 1131, 1098]
  To node 1099: Distance = 3, Path = [1398, 1131, 1099]
  To node 1100: Distance = 3, Path = [1398, 1131, 1100]
  To node 1101: Distance = 3, Path = [1398, 1131, 1101]
  To node 1102: Distance = 3, Path = [1398, 1131, 1102]
  To node 1103: Distance = 3, Path = [1398, 1131, 1103]
  To node 1104: Distance = 3, Path = [1398, 1131, 1104]
  To node 1105: Distance = 3, Path = [1398, 1131, 1105]
  To node 1106: Distance = 3, Path = [1398, 1131, 1106]
  To node 1107: Distance = 3, Path = [1398, 1131, 1107]
  To node 1108: Distance = 3, Path = [1398, 1131, 1108]
  To node 1109: Distance = 3, Path = [1398, 1131, 1109]
  To node 1110: Distance = 3, Path = [1398, 1131, 1110]
  To node 1111: Distance = 3, Path = [1398, 1131, 1111]
  To node 1112: Distance = 3, Path = [1398, 1131, 1112]
  To node 1113: Distance = 3, Path = [1398, 1131, 1113]
  To node 1114: Distance = 3, Path = [1398, 1131, 1114]
  To node 1115: Distance = 3, Path = [1398, 1131, 1115]
  To node 1116: Distance = 3, Path = [1398, 1131, 1116]
  To node 1117: Distance = 3, Path = [1398, 1131, 1117]
  To node 1118: Distance = 3, Path = [1398, 1131, 1118]
  To node 1119: Distance = 3, Path = [1398, 1131, 1119]
  To node 1120: Distance = 3, Path = [1398, 1131, 1120]
  To node 1121: Distance = 3, Path = [1398, 1131, 1121]
  To node 1122: Distance = 3, Path = [1398, 1131, 1122]
  To node 1123: Distance = 3, Path = [1398, 1131, 1123]
  To node 1124: Distance = 3, Path = [1398, 1131, 1124]
  To node 1125: Distance = 3, Path = [1398, 1131, 1125]
  To node 1126: Distance = 3, Path = [1398, 1131, 1126]
  To node 1127: Distance = 3, Path = [1398, 1131, 1127]
  To node 1128: Distance = 3, Path = [1398, 1131, 1128]
  To node 1129: Distance = 3, Path = [1398, 1131, 1129]
  To node 1130: Distance = 3, Path = [1398, 1131, 1130]
  To node 1132: Distance = 3, Path = [1398, 1131, 1132]
  To node 1133: Distance = 3, Path = [1398, 1131, 1133]
  To node 1134: Distance = 3, Path = [1398, 1131, 1134]
  To node 1135: Distance = 3, Path = [1398, 1131, 1135]
  To node 1137: Distance = 3, Path = [1398, 1131, 1137]
  To node 1138: Distance = 3, Path = [1398, 1131, 1138]
  To node 1139: Distance = 3, Path = [1398, 1131, 1139]
  To node 1140: Distance = 3, Path = [1398, 1131, 1140]
  To node 1141: Distance = 3, Path = [1398, 1131, 1141]
  To node 1142: Distance = 3, Path = [1398, 1131, 1142]
  To node 1143: Distance = 3, Path = [1398, 1131, 1143]
  To node 1144: Distance = 3, Path = [1398, 1131, 1144]
  To node 1145: Distance = 3, Path = [1398, 1131, 1145]
  To node 1146: Distance = 3, Path = [1398, 1131, 1146]
  To node 1147: Distance = 3, Path = [1398, 1131, 1147]
  To node 1148: Distance = 3, Path = [1398, 1131, 1148]
  To node 1149: Distance = 3, Path = [1398, 1131, 1149]
  To node 1150: Distance = 3, Path = [1398, 1131, 1150]
  To node 1151: Distance = 3, Path = [1398, 1131, 1151]
  To node 1152: Distance = 3, Path = [1398, 1131, 1152]
  To node 1153: Distance = 3, Path = [1398, 1131, 1153]
  To node 1154: Distance = 3, Path = [1398, 1131, 1154]
  To node 1155: Distance = 3, Path = [1398, 1131, 1155]
  To node 1156: Distance = 3, Path = [1398, 1131, 1156]
  To node 1157: Distance = 3, Path = [1398, 1131, 1157]
  To node 1158: Distance = 3, Path = [1398, 1131, 1158]
  To node 1159: Distance = 3, Path = [1398, 1131, 1159]
  To node 1160: Distance = 3, Path = [1398, 1131, 1160]
  To node 1161: Distance = 3, Path = [1398, 1131, 1161]
  To node 1162: Distance = 3, Path = [1398, 1131, 1162]
  To node 1163: Distance = 3, Path = [1398, 1131, 1163]
  To node 1190: Distance = 3, Path = [1398, 985, 1003, 1190]
  To node 1199: Distance = 3, Path = [1398, 960, 1199]
  To node 1200: Distance = 3, Path = [1398, 960, 1200]
  To node 1201: Distance = 3, Path = [1398, 960, 1201]
  To node 1202: Distance = 3, Path = [1398, 960, 1202]
  To node 1203: Distance = 3, Path = [1398, 960, 1203]
  To node 1204: Distance = 3, Path = [1398, 960, 1204]
  To node 1205: Distance = 3, Path = [1398, 960, 1205]
  To node 1206: Distance = 3, Path = [1398, 960, 1206]
  To node 1207: Distance = 3, Path = [1398, 960, 1207]
  To node 1208: Distance = 3, Path = [1398, 960, 1208]
  To node 1209: Distance = 3, Path = [1398, 960, 1209]
  To node 1210: Distance = 3, Path = [1398, 960, 1210]
  To node 1211: Distance = 3, Path = [1398, 960, 1211]
  To node 1212: Distance = 3, Path = [1398, 960, 1212]
  To node 1213: Distance = 3, Path = [1398, 960, 1213]
  To node 1214: Distance = 3, Path = [1398, 960, 1214]
  To node 1215: Distance = 3, Path = [1398, 960, 1215]
  To node 1216: Distance = 3, Path = [1398, 960, 1216]
  To node 1217: Distance = 3, Path = [1398, 960, 1217]
  To node 1218: Distance = 3, Path = [1398, 960, 1218]
  To node 1219: Distance = 3, Path = [1398, 960, 1219]
  To node 1220: Distance = 3, Path = [1398, 960, 1220]
  To node 1221: Distance = 3, Path = [1398, 960, 1221]
  To node 1222: Distance = 3, Path = [1398, 960, 1222]
  To node 1223: Distance = 3, Path = [1398, 960, 1223]
  To node 1367: Distance = 3, Path = [1398, 960, 1367]
  To node 1373: Distance = 3, Path = [1398, 1131, 1373]
  To node 1374: Distance = 3, Path = [1398, 1131, 1374]
  To node 1375: Distance = 3, Path = [1398, 1131, 1375]
  To node 1376: Distance = 3, Path = [1398, 1131, 1376]
  To node 1377: Distance = 3, Path = [1398, 1131, 1377]
  To node 1378: Distance = 3, Path = [1398, 1131, 1378]
  To node 1379: Distance = 3, Path = [1398, 1131, 1379]
  To node 1380: Distance = 3, Path = [1398, 1131, 1380]
  To node 1381: Distance = 3, Path = [1398, 1131, 1381]
  To node 1382: Distance = 3, Path = [1398, 1131, 1382]
  To node 1383: Distance = 3, Path = [1398, 1131, 1383]
  To node 1384: Distance = 3, Path = [1398, 960, 1384]
  To node 1385: Distance = 3, Path = [1398, 960, 1385]
  To node 1387: Distance = 3, Path = [1398, 960, 1387]
  To node 1388: Distance = 3, Path = [1398, 960, 1388]
  To node 1389: Distance = 3, Path = [1398, 960, 1389]
  To node 1390: Distance = 3, Path = [1398, 960, 1390]
  To node 1391: Distance = 3, Path = [1398, 960, 1391]
  To node 1392: Distance = 3, Path = [1398, 960, 1392]
  To node 1393: Distance = 3, Path = [1398, 960, 1393]
  To node 1394: Distance = 3, Path = [1398, 960, 1394]
  To node 1395: Distance = 3, Path = [1398, 960, 1395]
  To node 1396: Distance = 3, Path = [1398, 960, 1396]
  To node 1397: Distance = 3, Path = [1398, 960, 1397]
  To node 1399: Distance = 3, Path = [1398, 960, 1399]
  To node 1400: Distance = 3, Path = [1398, 960, 1400]
  To node 1401: Distance = 3, Path = [1398, 960, 1401]
  To node 1402: Distance = 3, Path = [1398, 960, 1402]
  To node 1403: Distance = 3, Path = [1398, 960, 1403]
  To node 1404: Distance = 3, Path = [1398, 960, 1404]
  To node 1405: Distance = 3, Path = [1398, 960, 1405]
  To node 1406: Distance = 3, Path = [1398, 960, 1406]
  To node 1407: Distance = 3, Path = [1398, 960, 1407]
  To node 1408: Distance = 3, Path = [1398, 960, 1408]
  To node 1409: Distance = 3, Path = [1398, 960, 1409]
  To node 1410: Distance = 3, Path = [1398, 960, 1410]
  To node 1411: Distance = 3, Path = [1398, 960, 1411]
  To node 1413: Distance = 3, Path = [1398, 960, 1413]
  To node 1433: Distance = 3, Path = [1398, 960, 1433]
  To node 1434: Distance = 3, Path = [1398, 960, 1434]
  To node 1436: Distance = 3, Path = [1398, 960, 1436]
  To node 1437: Distance = 3, Path = [1398, 960, 1437]
  To node 1438: Distance = 3, Path = [1398, 960, 1438]
  To node 1441: Distance = 3, Path = [1398, 960, 1441]
  To node 1442: Distance = 3, Path = [1398, 960, 1442]
  To node 1443: Distance = 3, Path = [1398, 1131, 1443]
  To node 1444: Distance = 3, Path = [1398, 1131, 1444]
  To node 1445: Distance = 3, Path = [1398, 1131, 1445]
  To node 1446: Distance = 3, Path = [1398, 1131, 1446]
  To node 1447: Distance = 3, Path = [1398, 1131, 1447]
  To node 1448: Distance = 3, Path = [1398, 1131, 1448]
  To node 1449: Distance = 3, Path = [1398, 1131, 1449]
  To node 1450: Distance = 3, Path = [1398, 1131, 1450]
  To node 1451: Distance = 3, Path = [1398, 1131, 1451]
  To node 1452: Distance = 3, Path = [1398, 1131, 1452]
  To node 1453: Distance = 3, Path = [1398, 1131, 1453]
  To node 1454: Distance = 3, Path = [1398, 1131, 1454]
  To node 1455: Distance = 3, Path = [1398, 1131, 1455]
  To node 1456: Distance = 3, Path = [1398, 1131, 1456]
  To node 1457: Distance = 3, Path = [1398, 1131, 1457]
  To node 1458: Distance = 3, Path = [1398, 1131, 1458]
  To node 1459: Distance = 3, Path = [1398, 1131, 1459]
  To node 1460: Distance = 3, Path = [1398, 1131, 1460]
  To node 1461: Distance = 3, Path = [1398, 1131, 1461]
  To node 1462: Distance = 3, Path = [1398, 1131, 1462]
  To node 1463: Distance = 3, Path = [1398, 1131, 1463]
  To node 1464: Distance = 3, Path = [1398, 1131, 1464]
  To node 1465: Distance = 3, Path = [1398, 1131, 1465]
  To node 1466: Distance = 3, Path = [1398, 1131, 1466]
  To node 1467: Distance = 3, Path = [1398, 1131, 1467]
  To node 1468: Distance = 3, Path = [1398, 1131, 1468]
  To node 1469: Distance = 3, Path = [1398, 1131, 1469]
  To node 1470: Distance = 3, Path = [1398, 1131, 1470]
  To node 1471: Distance = 3, Path = [1398, 1131, 1471]
  To node 1472: Distance = 3, Path = [1398, 1131, 1472]
  To node 1473: Distance = 3, Path = [1398, 1131, 1473]
  To node 1474: Distance = 3, Path = [1398, 1131, 1474]
  To node 1475: Distance = 3, Path = [1398, 1131, 1475]
  To node 1476: Distance = 3, Path = [1398, 1131, 1476]
  To node 1477: Distance = 3, Path = [1398, 1131, 1477]
  To node 1478: Distance = 3, Path = [1398, 1131, 1478]
  To node 1479: Distance = 3, Path = [1398, 1131, 1479]
  To node 1480: Distance = 3, Path = [1398, 1131, 1480]
  To node 1482: Distance = 3, Path = [1398, 1131, 1482]
  To node 952: Distance = 4, Path = [1398, 985, 1003, 952]
  To node 953: Distance = 4, Path = [1398, 985, 1003, 953]
  To node 955: Distance = 4, Path = [1398, 985, 1003, 955]
  To node 956: Distance = 4, Path = [1398, 985, 1003, 956]
  To node 957: Distance = 4, Path = [1398, 985, 1003, 957]
  To node 961: Distance = 4, Path = [1398, 985, 1003, 961]
  To node 962: Distance = 4, Path = [1398, 985, 1003, 962]
  To node 964: Distance = 4, Path = [1398, 985, 1003, 964]
  To node 965: Distance = 4, Path = [1398, 985, 1003, 965]
  To node 967: Distance = 4, Path = [1398, 985, 1003, 967]
  To node 968: Distance = 4, Path = [1398, 985, 1003, 968]
  To node 969: Distance = 4, Path = [1398, 985, 1003, 969]
  To node 970: Distance = 4, Path = [1398, 985, 1003, 970]
  To node 971: Distance = 4, Path = [1398, 985, 1003, 971]
  To node 972: Distance = 4, Path = [1398, 985, 1003, 972]
  To node 973: Distance = 4, Path = [1398, 985, 1003, 973]
  To node 974: Distance = 4, Path = [1398, 985, 1003, 974]
  To node 975: Distance = 4, Path = [1398, 985, 1003, 975]
  To node 976: Distance = 4, Path = [1398, 985, 1003, 976]
  To node 977: Distance = 4, Path = [1398, 985, 1003, 977]
  To node 978: Distance = 4, Path = [1398, 985, 1003, 978]
  To node 979: Distance = 4, Path = [1398, 985, 1003, 979]
  To node 981: Distance = 4, Path = [1398, 985, 1003, 981]
  To node 982: Distance = 4, Path = [1398, 985, 1003, 982]
  To node 986: Distance = 4, Path = [1398, 985, 1003, 986]
  To node 988: Distance = 4, Path = [1398, 985, 1003, 988]
  To node 989: Distance = 4, Path = [1398, 985, 1003, 989]
  To node 990: Distance = 4, Path = [1398, 985, 1003, 990]
  To node 991: Distance = 4, Path = [1398, 985, 1003, 991]
  To node 992: Distance = 4, Path = [1398, 985, 1003, 992]
  To node 993: Distance = 4, Path = [1398, 985, 1003, 993]
  To node 994: Distance = 4, Path = [1398, 985, 1003, 994]
  To node 995: Distance = 4, Path = [1398, 985, 1003, 995]
  To node 997: Distance = 4, Path = [1398, 985, 1003, 997]
  To node 998: Distance = 4, Path = [1398, 985, 1003, 998]
  To node 999: Distance = 4, Path = [1398, 985, 1003, 999]
  To node 1000: Distance = 4, Path = [1398, 985, 1003, 1000]
  To node 1001: Distance = 4, Path = [1398, 985, 1003, 1001]
  To node 1002: Distance = 4, Path = [1398, 985, 1003, 1002]
  To node 1004: Distance = 4, Path = [1398, 985, 1003, 1004]
  To node 1005: Distance = 4, Path = [1398, 985, 1003, 1005]
  To node 1006: Distance = 4, Path = [1398, 985, 1003, 1006]
  To node 1007: Distance = 4, Path = [1398, 985, 1003, 1007]
  To node 1008: Distance = 4, Path = [1398, 985, 1003, 1008]
  To node 1010: Distance = 4, Path = [1398, 985, 1003, 1010]
  To node 1011: Distance = 4, Path = [1398, 985, 1003, 1011]
  To node 1013: Distance = 4, Path = [1398, 985, 1003, 1013]
  To node 1014: Distance = 4, Path = [1398, 985, 1003, 1014]
  To node 1015: Distance = 4, Path = [1398, 985, 1003, 1015]
  To node 1016: Distance = 4, Path = [1398, 985, 1003, 1016]
  To node 1017: Distance = 4, Path = [1398, 985, 1003, 1017]
  To node 1018: Distance = 4, Path = [1398, 985, 1003, 1018]
  To node 1020: Distance = 4, Path = [1398, 985, 1003, 1020]
  To node 1021: Distance = 4, Path = [1398, 985, 1003, 1021]
  To node 1022: Distance = 4, Path = [1398, 985, 1003, 1022]
  To node 1024: Distance = 4, Path = [1398, 985, 1003, 1024]
  To node 1026: Distance = 4, Path = [1398, 985, 1003, 1026]
  To node 1027: Distance = 4, Path = [1398, 985, 1003, 1027]
  To node 1028: Distance = 4, Path = [1398, 985, 1003, 1028]
  To node 1029: Distance = 4, Path = [1398, 985, 1003, 1029]
  To node 1030: Distance = 4, Path = [1398, 985, 1003, 1030]
  To node 1036: Distance = 4, Path = [1398, 985, 1003, 1036]
  To node 1037: Distance = 4, Path = [1398, 985, 1003, 1037]
  To node 1350: Distance = 4, Path = [1398, 985, 1003, 1350]
  To node 1351: Distance = 4, Path = [1398, 985, 1003, 1351]
  To node 1352: Distance = 4, Path = [1398, 985, 1003, 1352]
  To node 1353: Distance = 4, Path = [1398, 985, 1003, 1353]
  To node 1354: Distance = 4, Path = [1398, 985, 1003, 1354]
  To node 1355: Distance = 4, Path = [1398, 985, 1003, 1355]
  To node 1356: Distance = 4, Path = [1398, 985, 1003, 1356]
  To node 1357: Distance = 4, Path = [1398, 985, 1003, 1357]

In [43]:
# prompt: from shortest_path find the path with the highest total weight

# Build the graph as an adjacency list to get edge weights easily
graph_with_weights = {}
for index, row in edges_all.iterrows():
    source = row['source']
    target = row['target']
    weight = row['weight']
    if source not in graph_with_weights:
        graph_with_weights[source] = []
    graph_with_weights[source].append((target, weight))

def calculate_path_weight(path, graph):
    """
    Calculates the total weight of a given path.

    Args:
        path (list): A list of node IDs representing the path.
        graph (dict): Adjacency list representation of the graph with edge weights.

    Returns:
        int or float: The total weight of the path, or 0 if the path is empty or invalid.
    """
    total_weight = 0
    for i in range(len(path) - 1):
        u = path[i]
        v = path[i+1]
        found_edge = False
        if u in graph:
            for neighbor, weight in graph[u]:
                if neighbor == v:
                    total_weight += weight
                    found_edge = True
                    break # Assuming only one edge between two nodes in the given direction
        if not found_edge:
             # This might happen if the path was constructed incorrectly or if there's a disconnect
             print(f"Warning: Edge not found between {u} and {v} in the graph.")
             return -1 # Indicate an invalid path or issue
    return total_weight

# Find the path with the highest total weight among the shortest paths found
highest_weight_path = None
highest_weight = -1 # Initialize with a value lower than any possible path weight

print("\nAnalyzing shortest paths for highest total weight:")
if shortest_paths:
    for target_node_id, distance in sorted_paths:
        path = []
        current = target_node_id
        # Reconstruct the path using the predecessors dictionary
        # Need to handle the start node case specifically as its predecessor is None
        if current == start_node:
            path = [start_node]
        else:
            while current is not None and current in path_predecessors:
                path.append(current)
                current = path_predecessors.get(current)
            path.reverse()

        # Calculate the total weight of the reconstructed path
        current_path_weight = calculate_path_weight(path, graph_with_weights)

        print(f"  Path to node {target_node_id}: {path}, Calculated Weight = {current_path_weight}")

        # Update the highest weight path if the current one is greater
        if current_path_weight > highest_weight:
            highest_weight = current_path_weight
            highest_weight_path = path

    print(f"\nPath with the highest total weight among shortest paths from node {start_node}:")
    print(f"  Path: {highest_weight_path}")
    print(f"  Total Weight: {highest_weight}")
else:
    print(f"  No shortest paths found from node {start_node} to analyze.")

Analyzing shortest paths for highest total weight:
  Path to node 1398: [1398], Calculated Weight = 0
  Path to node 960: [1398, 960], Calculated Weight = 1
  Path to node 963: [1398, 963], Calculated Weight = 1
  Path to node 985: [1398, 985], Calculated Weight = 1
  Path to node 1009: [1398, 1009], Calculated Weight = 1
  Path to node 1131: [1398, 1131], Calculated Weight = 1
  Path to node 1003: [1398, 985, 1003], Calculated Weight = 3
  Path to node 1034: [1398, 963, 1034], Calculated Weight = 2
  Path to node 1193: [1398, 1131, 1193], Calculated Weight = 9
  Path to node 1195: [1398, 960, 1195], Calculated Weight = 2
  Path to node 1196: [1398, 960, 1196], Calculated Weight = 2
  Path to node 1244: [1398, 960, 1244], Calculated Weight = 11
  Path to node 1245: [1398, 960, 1245], Calculated Weight = 11
  Path to node 1246: [1398, 960, 1246], Calculated Weight = 11
  Path to node 1247: [1398, 960, 1247], Calculated Weight = 11
  Path to node 1248: [1398, 960, 1248], Calculated Weight = 11
  Path to node 1249: [1398, 960, 1249], Calculated Weight = 11
  Path to node 1250: [1398, 960, 1250], Calculated Weight = 11
  Path to node 1251: [1398, 960, 1251], Calculated Weight = 11
  Path to node 1252: [1398, 960, 1252], Calculated Weight = 11
  Path to node 1253: [1398, 960, 1253], Calculated Weight = 11
  Path to node 1254: [1398, 960, 1254], Calculated Weight = 11
  Path to node 1255: [1398, 960, 1255], Calculated Weight = 11
  Path to node 1256: [1398, 960, 1256], Calculated Weight = 11
  Path to node 1257: [1398, 960, 1257], Calculated Weight = 11
  Path to node 1258: [1398, 960, 1258], Calculated Weight = 11
  Path to node 1259: [1398, 960, 1259], Calculated Weight = 11
  Path to node 1260: [1398, 960, 1260], Calculated Weight = 11
  Path to node 1261: [1398, 960, 1261], Calculated Weight = 11
  Path to node 1262: [1398, 960, 1262], Calculated Weight = 11
  Path to node 1263: [1398, 960, 1263], Calculated Weight = 11
  Path to node 1264: [1398, 960, 1264], Calculated Weight = 11
  Path to node 1265: [1398, 960, 1265], Calculated Weight = 11
  Path to node 1266: [1398, 960, 1266], Calculated Weight = 11
  Path to node 1267: [1398, 960, 1267], Calculated Weight = 11
  Path to node 1268: [1398, 960, 1268], Calculated Weight = 11
  Path to node 1269: [1398, 960, 1269], Calculated Weight = 11
  Path to node 1271: [1398, 960, 1271], Calculated Weight = 8
  Path to node 1272: [1398, 960, 1272], Calculated Weight = 8
  Path to node 1273: [1398, 960, 1273], Calculated Weight = 8
  Path to node 1274: [1398, 960, 1274], Calculated Weight = 8
  Path to node 1275: [1398, 960, 1275], Calculated Weight = 8
  Path to node 1276: [1398, 960, 1276], Calculated Weight = 8
  Path to node 1277: [1398, 960, 1277], Calculated Weight = 8
  Path to node 1278: [1398, 960, 1278], Calculated Weight = 11
  Path to node 1279: [1398, 960, 1279], Calculated Weight = 8
  Path to node 1280: [1398, 960, 1280], Calculated Weight = 11
  Path to node 1281: [1398, 960, 1281], Calculated Weight = 8
  Path to node 1282: [1398, 960, 1282], Calculated Weight = 8
  Path to node 1283: [1398, 960, 1283], Calculated Weight = 8
  Path to node 1284: [1398, 960, 1284], Calculated Weight = 8
  Path to node 1285: [1398, 960, 1285], Calculated Weight = 8
  Path to node 1286: [1398, 960, 1286], Calculated Weight = 8
  Path to node 1287: [1398, 960, 1287], Calculated Weight = 8
  Path to node 1288: [1398, 960, 1288], Calculated Weight = 8
  Path to node 1289: [1398, 960, 1289], Calculated Weight = 11
  Path to node 1290: [1398, 960, 1290], Calculated Weight = 8
  Path to node 1291: [1398, 960, 1291], Calculated Weight = 8
  Path to node 1293: [1398, 960, 1293], Calculated Weight = 8
  Path to node 1295: [1398, 960, 1295], Calculated Weight = 8
  Path to node 1296: [1398, 960, 1296], Calculated Weight = 8
  Path to node 1297: [1398, 960, 1297], Calculated Weight = 8
  Path to node 1298: [1398, 960, 1298], Calculated Weight = 8
  Path to node 1299: [1398, 960, 1299], Calculated Weight = 8
  Path to node 1300: [1398, 960, 1300], Calculated Weight = 11
  Path to node 1301: [1398, 960, 1301], Calculated Weight = 8
  Path to node 1302: [1398, 960, 1302], Calculated Weight = 11
  Path to node 1303: [1398, 960, 1303], Calculated Weight = 8
  Path to node 1304: [1398, 960, 1304], Calculated Weight = 11
  Path to node 1305: [1398, 960, 1305], Calculated Weight = 11
  Path to node 1306: [1398, 960, 1306], Calculated Weight = 8
  Path to node 1372: [1398, 1131, 1372], Calculated Weight = 2
  Path to node 951: [1398, 960, 951], Calculated Weight = 3
  Path to node 954: [1398, 960, 954], Calculated Weight = 3
  Path to node 958: [1398, 960, 958], Calculated Weight = 3
  Path to node 959: [1398, 960, 959], Calculated Weight = 3
  Path to node 966: [1398, 960, 966], Calculated Weight = 3
  Path to node 980: [1398, 960, 980], Calculated Weight = 3
  Path to node 983: [1398, 960, 983], Calculated Weight = 3
  Path to node 984: [1398, 960, 984], Calculated Weight = 3
  Path to node 987: [1398, 960, 987], Calculated Weight = 3
  Path to node 996: [1398, 960, 996], Calculated Weight = 3
  Path to node 1012: [1398, 960, 1012], Calculated Weight = 3
  Path to node 1019: [1398, 960, 1019], Calculated Weight = 3
  Path to node 1023: [1398, 960, 1023], Calculated Weight = 3
  Path to node 1025: [1398, 960, 1025], Calculated Weight = 3
  Path to node 1033: [1398, 963, 1034, 1033], Calculated Weight = 3
  Path to node 1040: [1398, 960, 1040], Calculated Weight = 3
  Path to node 1043: [1398, 960, 1043], Calculated Weight = 3
  Path to node 1050: [1398, 960, 1050], Calculated Weight = 3
  Path to node 1051: [1398, 960, 1051], Calculated Weight = 3
  Path to node 1066: [1398, 960, 1066], Calculated Weight = 3
  Path to node 1067: [1398, 960, 1067], Calculated Weight = 3
  Path to node 1075: [1398, 960, 1075], Calculated Weight = 3
  Path to node 1078: [1398, 960, 1078], Calculated Weight = 3
  Path to node 1080: [1398, 960, 1080], Calculated Weight = 3
  Path to node 1086: [1398, 1131, 1086], Calculated Weight = 3
  Path to node 1087: [1398, 1131, 1087], Calculated Weight = 3
  Path to node 1088: [1398, 1131, 1088], Calculated Weight = 3
  Path to node 1089: [1398, 1131, 1089], Calculated Weight = 3
  Path to node 1090: [1398, 1131, 1090], Calculated Weight = 3
  Path to node 1091: [1398, 1131, 1091], Calculated Weight = 3
  Path to node 1092: [1398, 1131, 1092], Calculated Weight = 3
  Path to node 1093: [1398, 1131, 1093], Calculated Weight = 3
  Path to node 1094: [1398, 1131, 1094], Calculated Weight = 3
  Path to node 1095: [1398, 1131, 1095], Calculated Weight = 3
  Path to node 1096: [1398, 1131, 1096], Calculated Weight = 3
  Path to node 1097: [1398, 1131, 1097], Calculated Weight = 3
  Path to node 1098: [1398, 1131, 1098], Calculated Weight = 3
  Path to node 1099: [1398, 1131, 1099], Calculated Weight = 3
  Path to node 1100: [1398, 1131, 1100], Calculated Weight = 3
  Path to node 1101: [1398, 1131, 1101], Calculated Weight = 3
  Path to node 1102: [1398, 1131, 1102], Calculated Weight = 3
  Path to node 1103: [1398, 1131, 1103], Calculated Weight = 3
  Path to node 1104: [1398, 1131, 1104], Calculated Weight = 3
  Path to node 1105: [1398, 1131, 1105], Calculated Weight = 3
  Path to node 1106: [1398, 1131, 1106], Calculated Weight = 3
  Path to node 1107: [1398, 1131, 1107], Calculated Weight = 3
  Path to node 1108: [1398, 1131, 1108], Calculated Weight = 3
  Path to node 1109: [1398, 1131, 1109], Calculated Weight = 3
  Path to node 1110: [1398, 1131, 1110], Calculated Weight = 3
  Path to node 1111: [1398, 1131, 1111], Calculated Weight = 3
  Path to node 1112: [1398, 1131, 1112], Calculated Weight = 3
  Path to node 1113: [1398, 1131, 1113], Calculated Weight = 3
  Path to node 1114: [1398, 1131, 1114], Calculated Weight = 3
  Path to node 1115: [1398, 1131, 1115], Calculated Weight = 3
  Path to node 1116: [1398, 1131, 1116], Calculated Weight = 3
  Path to node 1117: [1398, 1131, 1117], Calculated Weight = 3
  Path to node 1118: [1398, 1131, 1118], Calculated Weight = 3
  Path to node 1119: [1398, 1131, 1119], Calculated Weight = 3
  Path to node 1120: [1398, 1131, 1120], Calculated Weight = 3
  Path to node 1121: [1398, 1131, 1121], Calculated Weight = 3
  Path to node 1122: [1398, 1131, 1122], Calculated Weight = 3
  Path to node 1123: [1398, 1131, 1123], Calculated Weight = 3
  Path to node 1124: [1398, 1131, 1124], Calculated Weight = 3
  Path to node 1125: [1398, 1131, 1125], Calculated Weight = 3
  Path to node 1126: [1398, 1131, 1126], Calculated Weight = 3
  Path to node 1127: [1398, 1131, 1127], Calculated Weight = 3
  Path to node 1128: [1398, 1131, 1128], Calculated Weight = 3
  Path to node 1129: [1398, 1131, 1129], Calculated Weight = 3
  Path to node 1130: [1398, 1131, 1130], Calculated Weight = 3
  Path to node 1132: [1398, 1131, 1132], Calculated Weight = 3
  Path to node 1133: [1398, 1131, 1133], Calculated Weight = 3
  Path to node 1134: [1398, 1131, 1134], Calculated Weight = 3
  Path to node 1135: [1398, 1131, 1135], Calculated Weight = 3
  Path to node 1137: [1398, 1131, 1137], Calculated Weight = 3
  Path to node 1138: [1398, 1131, 1138], Calculated Weight = 3
  Path to node 1139: [1398, 1131, 1139], Calculated Weight = 3
  Path to node 1140: [1398, 1131, 1140], Calculated Weight = 3
  Path to node 1141: [1398, 1131, 1141], Calculated Weight = 3
  Path to node 1142: [1398, 1131, 1142], Calculated Weight = 3
  Path to node 1143: [1398, 1131, 1143], Calculated Weight = 3
  Path to node 1144: [1398, 1131, 1144], Calculated Weight = 3
  Path to node 1145: [1398, 1131, 1145], Calculated Weight = 3
  Path to node 1146: [1398, 1131, 1146], Calculated Weight = 3
  Path to node 1147: [1398, 1131, 1147], Calculated Weight = 3
  Path to node 1148: [1398, 1131, 1148], Calculated Weight = 3
  Path to node 1149: [1398, 1131, 1149], Calculated Weight = 3
  Path to node 1150: [1398, 1131, 1150], Calculated Weight = 3
  Path to node 1151: [1398, 1131, 1151], Calculated Weight = 3
  Path to node 1152: [1398, 1131, 1152], Calculated Weight = 3
  Path to node 1153: [1398, 1131, 1153], Calculated Weight = 3
  Path to node 1154: [1398, 1131, 1154], Calculated Weight = 3
  Path to node 1155: [1398, 1131, 1155], Calculated Weight = 3
  Path to node 1156: [1398, 1131, 1156], Calculated Weight = 3
  Path to node 1157: [1398, 1131, 1157], Calculated Weight = 3
  Path to node 1158: [1398, 1131, 1158], Calculated Weight = 3
  Path to node 1159: [1398, 1131, 1159], Calculated Weight = 3
  Path to node 1160: [1398, 1131, 1160], Calculated Weight = 3
  Path to node 1161: [1398, 1131, 1161], Calculated Weight = 3
  Path to node 1162: [1398, 1131, 1162], Calculated Weight = 3
  Path to node 1163: [1398, 1131, 1163], Calculated Weight = 3
  Path to node 1190: [1398, 985, 1003, 1190], Calculated Weight = 11
  Path to node 1199: [1398, 960, 1199], Calculated Weight = 8
  Path to node 1200: [1398, 960, 1200], Calculated Weight = 8
  Path to node 1201: [1398, 960, 1201], Calculated Weight = 8
  Path to node 1202: [1398, 960, 1202], Calculated Weight = 8
  Path to node 1203: [1398, 960, 1203], Calculated Weight = 8
  Path to node 1204: [1398, 960, 1204], Calculated Weight = 8
  Path to node 1205: [1398, 960, 1205], Calculated Weight = 8
  Path to node 1206: [1398, 960, 1206], Calculated Weight = 8
  Path to node 1207: [1398, 960, 1207], Calculated Weight = 8
  Path to node 1208: [1398, 960, 1208], Calculated Weight = 8
  Path to node 1209: [1398, 960, 1209], Calculated Weight = 8
  Path to node 1210: [1398, 960, 1210], Calculated Weight = 8
  Path to node 1211: [1398, 960, 1211], Calculated Weight = 8
  Path to node 1212: [1398, 960, 1212], Calculated Weight = 8
  Path to node 1213: [1398, 960, 1213], Calculated Weight = 8
  Path to node 1214: [1398, 960, 1214], Calculated Weight = 8
  Path to node 1215: [1398, 960, 1215], Calculated Weight = 8
  Path to node 1216: [1398, 960, 1216], Calculated Weight = 8
  Path to node 1217: [1398, 960, 1217], Calculated Weight = 8
  Path to node 1218: [1398, 960, 1218], Calculated Weight = 8
  Path to node 1219: [1398, 960, 1219], Calculated Weight = 8
  Path to node 1220: [1398, 960, 1220], Calculated Weight = 8
  Path to node 1221: [1398, 960, 1221], Calculated Weight = 8
  Path to node 1222: [1398, 960, 1222], Calculated Weight = 8
  Path to node 1223: [1398, 960, 1223], Calculated Weight = 8
  Path to node 1367: [1398, 960, 1367], Calculated Weight = 8
  Path to node 1373: [1398, 1131, 1373], Calculated Weight = 8
  Path to node 1374: [1398, 1131, 1374], Calculated Weight = 8
  Path to node 1375: [1398, 1131, 1375], Calculated Weight = 8
  Path to node 1376: [1398, 1131, 1376], Calculated Weight = 8
  Path to node 1377: [1398, 1131, 1377], Calculated Weight = 8
  Path to node 1378: [1398, 1131, 1378], Calculated Weight = 8
  Path to node 1379: [1398, 1131, 1379], Calculated Weight = 8
  Path to node 1380: [1398, 1131, 1380], Calculated Weight = 8
  Path to node 1381: [1398, 1131, 1381], Calculated Weight = 8
  Path to node 1382: [1398, 1131, 1382], Calculated Weight = 8
  Path to node 1383: [1398, 1131, 1383], Calculated Weight = 8
  Path to node 1384: [1398, 960, 1384], Calculated Weight = 8
  Path to node 1385: [1398, 960, 1385], Calculated Weight = 8
  Path to node 1387: [1398, 960, 1387], Calculated Weight = 8
  Path to node 1388: [1398, 960, 1388], Calculated Weight = 8
  Path to node 1389: [1398, 960, 1389], Calculated Weight = 8
  Path to node 1390: [1398, 960, 1390], Calculated Weight = 8
  Path to node 1391: [1398, 960, 1391], Calculated Weight = 8
  Path to node 1392: [1398, 960, 1392], Calculated Weight = 8
  Path to node 1393: [1398, 960, 1393], Calculated Weight = 8
  Path to node 1394: [1398, 960, 1394], Calculated Weight = 8
  Path to node 1395: [1398, 960, 1395], Calculated Weight = 8
  Path to node 1396: [1398, 960, 1396], Calculated Weight = 8
  Path to node 1397: [1398, 960, 1397], Calculated Weight = 8
  Path to node 1399: [1398, 960, 1399], Calculated Weight = 8
  Path to node 1400: [1398, 960, 1400], Calculated Weight = 8
  Path to node 1401: [1398, 960, 1401], Calculated Weight = 8
  Path to node 1402: [1398, 960, 1402], Calculated Weight = 8
  Path to node 1403: [1398, 960, 1403], Calculated Weight = 8
  Path to node 1404: [1398, 960, 1404], Calculated Weight = 8
  Path to node 1405: [1398, 960, 1405], Calculated Weight = 8
  Path to node 1406: [1398, 960, 1406], Calculated Weight = 8
  Path to node 1407: [1398, 960, 1407], Calculated Weight = 8
  Path to node 1408: [1398, 960, 1408], Calculated Weight = 8
  Path to node 1409: [1398, 960, 1409], Calculated Weight = 8
  Path to node 1410: [1398, 960, 1410], Calculated Weight = 8
  Path to node 1411: [1398, 960, 1411], Calculated Weight = 8
  Path to node 1413: [1398, 960, 1413], Calculated Weight = 8
  Path to node 1433: [1398, 960, 1433], Calculated Weight = 8
  Path to node 1434: [1398, 960, 1434], Calculated Weight = 8
  Path to node 1436: [1398, 960, 1436], Calculated Weight = 8
  Path to node 1437: [1398, 960, 1437], Calculated Weight = 8
  Path to node 1438: [1398, 960, 1438], Calculated Weight = 8
  Path to node 1441: [1398, 960, 1441], Calculated Weight = 8
  Path to node 1442: [1398, 960, 1442], Calculated Weight = 8
  Path to node 1443: [1398, 1131, 1443], Calculated Weight = 8
  Path to node 1444: [1398, 1131, 1444], Calculated Weight = 8
  Path to node 1445: [1398, 1131, 1445], Calculated Weight = 8
  Path to node 1446: [1398, 1131, 1446], Calculated Weight = 8
  Path to node 1447: [1398, 1131, 1447], Calculated Weight = 8
  Path to node 1448: [1398, 1131, 1448], Calculated Weight = 8
  Path to node 1449: [1398, 1131, 1449], Calculated Weight = 8
  Path to node 1450: [1398, 1131, 1450], Calculated Weight = 8
  Path to node 1451: [1398, 1131, 1451], Calculated Weight = 8
  Path to node 1452: [1398, 1131, 1452], Calculated Weight = 8
  Path to node 1453: [1398, 1131, 1453], Calculated Weight = 8
  Path to node 1454: [1398, 1131, 1454], Calculated Weight = 8
  Path to node 1455: [1398, 1131, 1455], Calculated Weight = 8
  Path to node 1456: [1398, 1131, 1456], Calculated Weight = 8
  Path to node 1457: [1398, 1131, 1457], Calculated Weight = 8
  Path to node 1458: [1398, 1131, 1458], Calculated Weight = 8
  Path to node 1459: [1398, 1131, 1459], Calculated Weight = 8
  Path to node 1460: [1398, 1131, 1460], Calculated Weight = 8
  Path to node 1461: [1398, 1131, 1461], Calculated Weight = 8
  Path to node 1462: [1398, 1131, 1462], Calculated Weight = 8
  Path to node 1463: [1398, 1131, 1463], Calculated Weight = 8
  Path to node 1464: [1398, 1131, 1464], Calculated Weight = 11
  Path to node 1465: [1398, 1131, 1465], Calculated Weight = 8
  Path to node 1466: [1398, 1131, 1466], Calculated Weight = 8
  Path to node 1467: [1398, 1131, 1467], Calculated Weight = 8
  Path to node 1468: [1398, 1131, 1468], Calculated Weight = 8
  Path to node 1469: [1398, 1131, 1469], Calculated Weight = 8
  Path to node 1470: [1398, 1131, 1470], Calculated Weight = 8
  Path to node 1471: [1398, 1131, 1471], Calculated Weight = 8
  Path to node 1472: [1398, 1131, 1472], Calculated Weight = 8
  Path to node 1473: [1398, 1131, 1473], Calculated Weight = 8
  Path to node 1474: [1398, 1131, 1474], Calculated Weight = 8
  Path to node 1475: [1398, 1131, 1475], Calculated Weight = 8
  Path to node 1476: [1398, 1131, 1476], Calculated Weight = 8
  Path to node 1477: [1398, 1131, 1477], Calculated Weight = 8
  Path to node 1478: [1398, 1131, 1478], Calculated Weight = 8
  Path to node 1479: [1398, 1131, 1479], Calculated Weight = 8
  Path to node 1480: [1398, 1131, 1480], Calculated Weight = 8
  Path to node 1482: [1398, 1131, 1482], Calculated Weight = 8
  Path to node 952: [1398, 985, 1003, 952], Calculated Weight = 5
  Path to node 953: [1398, 985, 1003, 953], Calculated Weight = 5
  Path to node 955: [1398, 985, 1003, 955], Calculated Weight = 5
  Path to node 956: [1398, 985, 1003, 956], Calculated Weight = 5
  Path to node 957: [1398, 985, 1003, 957], Calculated Weight = 5
  Path to node 961: [1398, 985, 1003, 961], Calculated Weight = 5
  Path to node 962: [1398, 985, 1003, 962], Calculated Weight = 5
  Path to node 964: [1398, 985, 1003, 964], Calculated Weight = 5
  Path to node 965: [1398, 985, 1003, 965], Calculated Weight = 5
  Path to node 967: [1398, 985, 1003, 967], Calculated Weight = 5
  Path to node 968: [1398, 985, 1003, 968], Calculated Weight = 5
  Path to node 969: [1398, 985, 1003, 969], Calculated Weight = 5
  Path to node 970: [1398, 985, 1003, 970], Calculated Weight = 5
  Path to node 971: [1398, 985, 1003, 971], Calculated Weight = 5
  Path to node 972: [1398, 985, 1003, 972], Calculated Weight = 5
  Path to node 973: [1398, 985, 1003, 973], Calculated Weight = 5
  Path to node 974: [1398, 985, 1003, 974], Calculated Weight = 5
  Path to node 975: [1398, 985, 1003, 975], Calculated Weight = 5
  Path to node 976: [1398, 985, 1003, 976], Calculated Weight = 5
  Path to node 977: [1398, 985, 1003, 977], Calculated Weight = 5
  Path to node 978: [1398, 985, 1003, 978], Calculated Weight = 5
  Path to node 979: [1398, 985, 1003, 979], Calculated Weight = 5
  Path to node 981: [1398, 985, 1003, 981], Calculated Weight = 5
  Path to node 982: [1398, 985, 1003, 982], Calculated Weight = 5
  Path to node 986: [1398, 985, 1003, 986], Calculated Weight = 5
  Path to node 988: [1398, 985, 1003, 988], Calculated Weight = 5
  Path to node 989: [1398, 985, 1003, 989], Calculated Weight = 5
  Path to node 990: [1398, 985, 1003, 990], Calculated Weight = 5
  Path to node 991: [1398, 985, 1003, 991], Calculated Weight = 5
  Path to node 992: [1398, 985, 1003, 992], Calculated Weight = 5
  Path to node 993: [1398, 985, 1003, 993], Calculated Weight = 5
  Path to node 994: [1398, 985, 1003, 994], Calculated Weight = 5
  Path to node 995: [1398, 985, 1003, 995], Calculated Weight = 5
  Path to node 997: [1398, 985, 1003, 997], Calculated Weight = 5

In [47]:
# prompt: from the cell above print out the label from nodes_all instead of the node_id

print(f"\nShortest paths from node {start_node} to all reachable nodes:")
if shortest_paths:
    # Sort by distance for better readability
    sorted_paths = sorted(shortest_paths.items(), key=lambda item: item[1])
    for target_node_id, distance in sorted_paths:
        # Reconstruct the path
        path = []
        current = target_node_id
        # Handle the case where the target is the start node itself
        if current == start_node:
            path = [start_node]
        else:
            while current is not None:
                path.append(current)
                current = path_predecessors.get(current)
            path.reverse()

        # Get labels for the nodes in the path
        path_labels = [nodes_all.loc[nodes_all['node_id'] == node_id, 'label'].iloc[0] for node_id in path if node_id in nodes_all['node_id'].values]

        print(f"  To node {target_node_id} ({nodes_all.loc[nodes_all['node_id'] == target_node_id, 'label'].iloc[0] if target_node_id in nodes_all['node_id'].values else 'Unknown'}): Distance = {distance}, Path = {path_labels}")
else:
    print(f"  No reachable nodes found from node {start_node}.")

# Build the graph as an adjacency list to get edge weights easily
graph_with_weights = {}
for index, row in edges_all.iterrows():
    source = row['source']
    target = row['target']
    weight = row['weight']
    if source not in graph_with_weights:
        graph_with_weights[source] = []
    graph_with_weights[source].append((target, weight))

def calculate_path_weight(path, graph):
    """
    Calculates the total weight of a given path.

    Args:
        path (list): A list of node IDs representing the path.
        graph (dict): Adjacency list representation of the graph with edge weights.

    Returns:
        int or float: The total weight of the path, or 0 if the path is empty or invalid.
    """
    total_weight = 0
    for i in range(len(path) - 1):
        u = path[i]
        v = path[i+1]
        found_edge = False
        if u in graph:
            for neighbor, weight in graph[u]:
                if neighbor == v:
                    total_weight += weight
                    found_edge = True
                    break # Assuming only one edge between two nodes in the given direction
        if not found_edge:
             # This might happen if the path was constructed incorrectly or if there's a disconnect
             print(f"Warning: Edge not found between {u} and {v} in the graph.")
             return -1 # Indicate an invalid path or issue
    return total_weight

# Find the path with the highest total weight among the shortest paths found
highest_weight_path = None
highest_weight = -1 # Initialize with a value lower than any possible path weight

print("\nAnalyzing shortest paths for highest total weight:")
if shortest_paths:
    for target_node_id, distance in sorted_paths:
        path = []
        current = target_node_id
        # Reconstruct the path using the predecessors dictionary
        # Need to handle the start node case specifically as its predecessor is None
        if current == start_node:
            path = [start_node]
        else:
            while current is not None and current in path_predecessors:
                path.append(current)
                current = path_predecessors.get(current)
            path.reverse()

        # Calculate the total weight of the reconstructed path
        current_path_weight = calculate_path_weight(path, graph_with_weights)

        # Get labels for the nodes in the path
        path_labels = [nodes_all.loc[nodes_all['node_id'] == node_id, 'label'].iloc[0] for node_id in path if node_id in nodes_all['node_id'].values]

        print(f"  Path to node {target_node_id} ({nodes_all.loc[nodes_all['node_id'] == target_node_id, 'label'].iloc[0] if target_node_id in nodes_all['node_id'].values else 'Unknown'}): {path_labels}, Calculated Weight = {current_path_weight}")


        # Update the highest weight path if the current one is greater
        if current_path_weight > highest_weight:
            highest_weight = current_path_weight
            highest_weight_path = path # Keep the node IDs for potential further use

    # Get labels for the nodes in the highest weight path
    highest_weight_path_labels = [nodes_all.loc[nodes_all['node_id'] == node_id, 'label'].iloc[0] for node_id in highest_weight_path if node_id in nodes_all['node_id'].values]


    print(f"\nPath with the highest total weight among shortest paths from node {start_node}:")
    print(f"  Path (Labels): {highest_weight_path_labels}")
    print(f"  Total Weight: {highest_weight}")
else:
    print(f"  No shortest paths found from node {start_node} to analyze.")

Shortest paths from node 1398 to all reachable nodes:
  To node 1398 (JD@PHANTOM.CORP): Distance = 0, Path = ['JD@PHANTOM.CORP']
  To node 960 (ENTERPRISE ADMINS@PHANTOM.CORP): Distance = 1, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP']
  To node 963 (DOMAIN USERS@PHANTOM.CORP): Distance = 1, Path = ['JD@PHANTOM.CORP', 'DOMAIN USERS@PHANTOM.CORP']
  To node 985 (DOMAIN ADMINS@PHANTOM.CORP): Distance = 1, Path = ['JD@PHANTOM.CORP', 'DOMAIN ADMINS@PHANTOM.CORP']
  To node 1009 (HELPDESKADMINS@PHANTOM.CORP): Distance = 1, Path = ['JD@PHANTOM.CORP', 'HELPDESKADMINS@PHANTOM.CORP']
  To node 1131 (ADMINISTRATORS@WRAITH.CORP): Distance = 1, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP']
  To node 1003 (ADMINISTRATORS@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'DOMAIN ADMINS@PHANTOM.CORP', 'ADMINISTRATORS@PHANTOM.CORP']
  To node 1034 (AUTHENTICATED USERS@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'DOMAIN USERS@PHANTOM.CORP', 'AUTHENTICATED USERS@PHANTOM.CORP']
  To node 1193 (WRAITH.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'WRAITH.CORP']
  To node 1195 (PHANTOM-DC01-CA@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'PHANTOM-DC01-CA@PHANTOM.CORP']
  To node 1196 (PHANTOM-SRV-SHARPHOUND-CA@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'PHANTOM-SRV-SHARPHOUND-CA@PHANTOM.CORP']
  To node 1244 (SMARTCARDLOGON@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SMARTCARDLOGON@PHANTOM.CORP']
  To node 1245 (SMARTCARDUSER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SMARTCARDUSER@PHANTOM.CORP']
  To node 1246 (ENROLLMENTAGENTOFFLINE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ENROLLMENTAGENTOFFLINE@PHANTOM.CORP']
  To node 1247 (ENROLLMENTAGENT@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ENROLLMENTAGENT@PHANTOM.CORP']
  To node 1248 (MACHINEENROLLMENTAGENT@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'MACHINEENROLLMENTAGENT@PHANTOM.CORP']
  To node 1249 (CTLSIGNING@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CTLSIGNING@PHANTOM.CORP']
  To node 1250 (MACHINE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'MACHINE@PHANTOM.CORP']
  To node 1251 (CLIENTAUTH@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CLIENTAUTH@PHANTOM.CORP']
  To node 1252 (WEBSERVER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'WEBSERVER@PHANTOM.CORP']
  To node 1253 (CA@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CA@PHANTOM.CORP']
  To node 1254 (DOMAINCONTROLLER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DOMAINCONTROLLER@PHANTOM.CORP']
  To node 1255 (IPSECINTERMEDIATEONLINE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'IPSECINTERMEDIATEONLINE@PHANTOM.CORP']
  To node 1256 (SUBCA@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SUBCA@PHANTOM.CORP']
  To node 1257 (OFFLINEROUTER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'OFFLINEROUTER@PHANTOM.CORP']
  To node 1258 (IPSECINTERMEDIATEOFFLINE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'IPSECINTERMEDIATEOFFLINE@PHANTOM.CORP']
  To node 1259 (CEPENCRYPTION@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CEPENCRYPTION@PHANTOM.CORP']
  To node 1260 (EXCHANGEUSERSIGNATURE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'EXCHANGEUSERSIGNATURE@PHANTOM.CORP']
  To node 1261 (EXCHANGEUSER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'EXCHANGEUSER@PHANTOM.CORP']
  To node 1262 (CAEXCHANGE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CAEXCHANGE@PHANTOM.CORP']
  To node 1263 (CROSSCA@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CROSSCA@PHANTOM.CORP']
  To node 1264 (KEYRECOVERYAGENT@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'KEYRECOVERYAGENT@PHANTOM.CORP']
  To node 1265 (RASANDIASSERVER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'RASANDIASSERVER@PHANTOM.CORP']
  To node 1266 (DIRECTORYEMAILREPLICATION@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DIRECTORYEMAILREPLICATION@PHANTOM.CORP']
  To node 1267 (WORKSTATION@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'WORKSTATION@PHANTOM.CORP']
  To node 1268 (DOMAINCONTROLLERAUTHENTICATION@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DOMAINCONTROLLERAUTHENTICATION@PHANTOM.CORP']
  To node 1269 (KERBEROSAUTHENTICATION@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'KERBEROSAUTHENTICATION@PHANTOM.CORP']
  To node 1271 (TESTV2@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'TESTV2@PHANTOM.CORP']
  To node 1272 (TESTV3@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'TESTV3@PHANTOM.CORP']
  To node 1273 (AUTHENTICATION MECHANISM MEDIUM LEVEL ACCESS@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'AUTHENTICATION MECHANISM MEDIUM LEVEL ACCESS@PHANTOM.CORP']
  To node 1274 (ESC9@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC9@PHANTOM.CORP']
  To node 1275 (ESC1@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC1@PHANTOM.CORP']
  To node 1276 (ESC3-SELF@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC3-SELF@PHANTOM.CORP']
  To node 1277 (ESC1SMARTCARD@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC1SMARTCARD@PHANTOM.CORP']
  To node 1278 (CODESIGNING@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CODESIGNING@PHANTOM.CORP']
  To node 1279 (ESC3V2@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC3V2@PHANTOM.CORP']
  To node 1280 (ADMINISTRATOR@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ADMINISTRATOR@PHANTOM.CORP']
  To node 1281 (SPICYTEMP@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SPICYTEMP@PHANTOM.CORP']
  To node 1282 (SPICYTEMP(COPY)@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SPICYTEMP(COPY)@PHANTOM.CORP']
  To node 1283 (SPICYTEMPNAME@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SPICYTEMPNAME@PHANTOM.CORP']
  To node 1284 (OPERATIONSMANAGER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'OPERATIONSMANAGER@PHANTOM.CORP']
  To node 1285 (SPICYTEMP(COPY))@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SPICYTEMP(COPY))@PHANTOM.CORP']
  To node 1286 (CLIENTAUTH2@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CLIENTAUTH2@PHANTOM.CORP']
  To node 1287 (ESC3-SELF2@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC3-SELF2@PHANTOM.CORP']
  To node 1288 (COPYOFOCSPRESPONSESIGNING(LEGACY)@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'COPYOFOCSPRESPONSESIGNING(LEGACY)@PHANTOM.CORP']
  To node 1289 (USERSIGNATURE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'USERSIGNATURE@PHANTOM.CORP']
  To node 1290 (ESC10@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC10@PHANTOM.CORP']
  To node 1291 (ENROLLMENTAGENTV2@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ENROLLMENTAGENTV2@PHANTOM.CORP']
  To node 1293 (CLIENTAUTHV1@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CLIENTAUTHV1@PHANTOM.CORP']
  To node 1295 (CLIENTAUTH3@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'CLIENTAUTH3@PHANTOM.CORP']
  To node 1296 (ESC6A@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC6A@PHANTOM.CORP']
  To node 1297 (MYTEMPLATE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'MYTEMPLATE@PHANTOM.CORP']
  To node 1298 (ABUSABLETEMPLATE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ABUSABLETEMPLATE@PHANTOM.CORP']
  To node 1299 (ESC14@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC14@PHANTOM.CORP']
  To node 1300 (USER@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'USER@PHANTOM.CORP']
  To node 1301 (COPY OF OCSP RESPONSE SIGNING@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'COPY OF OCSP RESPONSE SIGNING@PHANTOM.CORP']
  To node 1302 (OCSPRESPONSESIGNING@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'OCSPRESPONSESIGNING@PHANTOM.CORP']
  To node 1303 (ESC13TEMPLATE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC13TEMPLATE@PHANTOM.CORP']
  To node 1304 (EFS@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'EFS@PHANTOM.CORP']
  To node 1305 (EFSRECOVERY@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'EFSRECOVERY@PHANTOM.CORP']
  To node 1306 (ESC12TEMPLATE@PHANTOM.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ESC12TEMPLATE@PHANTOM.CORP']
  To node 1372 (EXTSRV02.WRAITH.CORP): Distance = 2, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'EXTSRV02.WRAITH.CORP']
  To node 951 (PRINT OPERATORS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'PRINT OPERATORS@PHANTOM.CORP']
  To node 954 (ACCOUNT OPERATORS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ACCOUNT OPERATORS@PHANTOM.CORP']
  To node 958 (DOMAIN CONTROLLERS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DOMAIN CONTROLLERS@PHANTOM.CORP']
  To node 959 (SCHEMA ADMINS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SCHEMA ADMINS@PHANTOM.CORP']
  To node 966 (ENTERPRISE KEY ADMINS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ENTERPRISE KEY ADMINS@PHANTOM.CORP']
  To node 980 (BACKUP OPERATORS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'BACKUP OPERATORS@PHANTOM.CORP']
  To node 983 (REPLICATORS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'REPLICATORS@PHANTOM.CORP']
  To node 984 (SERVER OPERATORS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SERVER OPERATORS@PHANTOM.CORP']
  To node 987 (READ-ONLY DOMAIN CONTROLLERS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'READ-ONLY DOMAIN CONTROLLERS@PHANTOM.CORP']
  To node 996 (SUBDAS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SUBDAS@PHANTOM.CORP']
  To node 1012 (ANOTHER ONE@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ANOTHER ONE@PHANTOM.CORP']
  To node 1019 (T0_ADMINS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'T0_ADMINS@PHANTOM.CORP']
  To node 1023 (DNSUPDATEPROXY@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DNSUPDATEPROXY@PHANTOM.CORP']
  To node 1025 (KEY ADMINS@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'KEY ADMINS@PHANTOM.CORP']
  To node 1033 (EVERYONE@PHANTOM.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'DOMAIN USERS@PHANTOM.CORP', 'AUTHENTICATED USERS@PHANTOM.CORP', 'EVERYONE@PHANTOM.CORP']
  To node 1040 (DOMAIN CONTROLLERS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DOMAIN CONTROLLERS@GHOST.CORP']
  To node 1043 (DOMAIN ADMINS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'DOMAIN ADMINS@GHOST.CORP']
  To node 1050 (PRINT OPERATORS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'PRINT OPERATORS@GHOST.CORP']
  To node 1051 (READ-ONLY DOMAIN CONTROLLERS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'READ-ONLY DOMAIN CONTROLLERS@GHOST.CORP']
  To node 1066 (SERVER OPERATORS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'SERVER OPERATORS@GHOST.CORP']
  To node 1067 (ACCOUNT OPERATORS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ACCOUNT OPERATORS@GHOST.CORP']
  To node 1075 (REPLICATORS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'REPLICATORS@GHOST.CORP']
  To node 1078 (BACKUP OPERATORS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'BACKUP OPERATORS@GHOST.CORP']
  To node 1080 (ADMINISTRATORS@GHOST.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ENTERPRISE ADMINS@PHANTOM.CORP', 'ADMINISTRATORS@GHOST.CORP']
  To node 1086 (DNSADMINS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DNSADMINS@WRAITH.CORP']
  To node 1087 (RAS AND IAS SERVERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'RAS AND IAS SERVERS@WRAITH.CORP']
  To node 1088 (DISTRIBUTED COM USERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DISTRIBUTED COM USERS@WRAITH.CORP']
  To node 1089 (PERFORMANCE LOG USERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'PERFORMANCE LOG USERS@WRAITH.CORP']
  To node 1090 (NETWORK CONFIGURATION OPERATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'NETWORK CONFIGURATION OPERATORS@WRAITH.CORP']
  To node 1091 (ACCOUNT OPERATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'ACCOUNT OPERATORS@WRAITH.CORP']
  To node 1092 (WINDOWS AUTHORIZATION ACCESS GROUP@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'WINDOWS AUTHORIZATION ACCESS GROUP@WRAITH.CORP']
  To node 1093 (STORAGE REPLICA ADMINISTRATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'STORAGE REPLICA ADMINISTRATORS@WRAITH.CORP']
  To node 1094 (RDS MANAGEMENT SERVERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'RDS MANAGEMENT SERVERS@WRAITH.CORP']
  To node 1095 (SERVER OPERATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'SERVER OPERATORS@WRAITH.CORP']
  To node 1096 (T0_ADMINS_DOMAIN@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'T0_ADMINS_DOMAIN@WRAITH.CORP']
  To node 1097 (TERMINAL SERVER LICENSE SERVERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'TERMINAL SERVER LICENSE SERVERS@WRAITH.CORP']
  To node 1098 (INCOMING FOREST TRUST BUILDERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'INCOMING FOREST TRUST BUILDERS@WRAITH.CORP']
  To node 1099 (REMOTE MANAGEMENT USERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'REMOTE MANAGEMENT USERS@WRAITH.CORP']
  To node 1100 (REPLICATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'REPLICATORS@WRAITH.CORP']
  To node 1101 (ACCESS CONTROL ASSISTANCE OPERATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'ACCESS CONTROL ASSISTANCE OPERATORS@WRAITH.CORP']
  To node 1102 (DENIED RODC PASSWORD REPLICATION GROUP@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DENIED RODC PASSWORD REPLICATION GROUP@WRAITH.CORP']
  To node 1103 (CERT PUBLISHERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'CERT PUBLISHERS@WRAITH.CORP']
  To node 1104 (HYPER-V ADMINISTRATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'HYPER-V ADMINISTRATORS@WRAITH.CORP']
  To node 1105 (CRYPTOGRAPHIC OPERATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'CRYPTOGRAPHIC OPERATORS@WRAITH.CORP']
  To node 1106 (ALLOWED RODC PASSWORD REPLICATION GROUP@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'ALLOWED RODC PASSWORD REPLICATION GROUP@WRAITH.CORP']
  To node 1107 (SCHEMA ADMINS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'SCHEMA ADMINS@WRAITH.CORP']
  To node 1108 (ENTERPRISE ADMINS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'ENTERPRISE ADMINS@WRAITH.CORP']
  To node 1109 (DOMAIN ADMINS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DOMAIN ADMINS@WRAITH.CORP']
  To node 1110 (GUESTS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'GUESTS@WRAITH.CORP']
  To node 1111 (GROUP POLICY CREATOR OWNERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'GROUP POLICY CREATOR OWNERS@WRAITH.CORP']
  To node 1112 (DOMAIN COMPUTERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DOMAIN COMPUTERS@WRAITH.CORP']
  To node 1113 (DOMAIN CONTROLLERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DOMAIN CONTROLLERS@WRAITH.CORP']
  To node 1114 (BACKUP OPERATORS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'BACKUP OPERATORS@WRAITH.CORP']
  To node 1115 (PROTECTED USERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'PROTECTED USERS@WRAITH.CORP']
  To node 1116 (ENTERPRISE KEY ADMINS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'ENTERPRISE KEY ADMINS@WRAITH.CORP']
  To node 1117 (ENTERPRISE READ-ONLY DOMAIN CONTROLLERS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'ENTERPRISE READ-ONLY DOMAIN CONTROLLERS@WRAITH.CORP']
  To node 1118 (KEY ADMINS@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'KEY ADMINS@WRAITH.CORP']
  To node 1119 (T0_ADMINS_UNIVERSAL@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'T0_ADMINS_UNIVERSAL@WRAITH.CORP']
  To node 1120 (DNSUPDATEPROXY@WRAITH.CORP): Distance = 3, Path = ['JD@PHANTOM.CORP', 'ADMINISTRATORS@WRAITH.CORP', 'DNSUPDATEPROXY@WRAITH.CORP']

In [45]:
# prompt: get the label from node_all where the node_id match

import pandas as pd
def get_node_label(node_id, nodes_df):
    """
    Gets the label for a given node ID from the nodes DataFrame.

    Args:
        node_id (int): The ID of the node.
        nodes_df (pd.DataFrame): DataFrame containing node information with 'node_id' and 'label' columns.

    Returns:
        str or None: The label of the node, or None if the node_id is not found.
    """
    node_info = nodes_df[nodes_df['node_id'] == node_id]
    if not node_info.empty:
        # Assuming there's only one entry per node_id, get the first one
        return node_info.iloc[0]['label']
    else:
        return None

# Example usage: Get the label for a specific node_id
example_node_id = 100  # Replace with a node_id you want to check
node_label = get_node_label(example_node_id, nodes_all)

if node_label:
    print(f"\nThe label for node ID {example_node_id} is: {node_label}")
else:
    print(f"\nNode ID {example_node_id} not found in the nodes DataFrame.")

# You can also do this directly using pandas indexing/filtering
example_node_id_direct = 200 # Replace with another node_id
node_info_direct = nodes_all[nodes_all['node_id'] == example_node_id_direct]

if not node_info_direct.empty:
    node_label_direct = node_info_direct.iloc[0]['label']
    print(f"The label for node ID {example_node_id_direct} is (direct method): {node_label_direct}")
else:
     print(f"Node ID {example_node_id_direct} not found using direct method.")

The label for node ID 100 is: 94F238BB-831C-11D6-977B-00C04F613221@PHANTOM.CORP
The label for node ID 200 is (direct method): 232E831F-F988-4444-8E3E-8A352E2FD411@PHANTOM.CORP