<a href="https://colab.research.google.com/github/markajbell/BH/blob/main/ProcessData.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [1]:
import pandas as pd
import json
import os
import glob

Set the Path to the Data location (imported form SharpHound)

# Set the Path
to the Data location (imported from SharpHound) and Read json files in folder and create a dictionary with the entire data.

In [2]:
#@title Download lab files
from IPython.display import clear_output
if not os.path.exists("/content/mylab"):
  print("Downloading lab files...")
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_computers.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_containers.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_domains.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_gpos.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_groups.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_ous.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_users.json
  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab.zip
  !unzip mylab.zip -d mylab
  clear_output()
  print("Done")
else:
  print("Lab files already downloaded")

path = "/content/mylab"
data = {}
json_files = glob.glob(os.path.join(path, "*.json"))
for file in json_files:
    filename = os.path.basename(file).replace(".json", "")
    suf = filename.split("_")[-1]

    with open(file, 'r', encoding='utf-8') as f:
        content = json.load(f)

    if "data" in content:
        if suf in data:
            data[f"{suf}"].extend(content["data"])
            #print(f" The key 'data' was found in {f}.")
        else:
            data[f"{suf}"] = content["data"]
            #print(f" The key 'data' was found in {f}.")
    else:
        print(f"Warning: The key 'data' was not found in {f}.")

Done

Show the "content"

In [ ]:
content

{'data': [{'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'SOM@PHANTOM.CORP',
    'distinguishedname': 'CN=SOM,CN=WMIPOLICY,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': True},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False}],
   'ObjectIdentifier': '23631FBB-E0CB-47D0-8B72-A3AD167EAEF6',
   'IsDeleted': False,
   'IsACLProtected': True,
   'ContainedBy': {'ObjectIdentifier': '04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'ADMINSDHOLDER@PHANTOM.CORP',
    'distinguishedname': 'CN=ADMINSDHOLDER,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': True},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False}],
   'ObjectIdentifier': 'E92F8F06-89FF-4658-9F6D-9611D43790C1',
   'IsDeleted': False,
   'IsACLProtected': True,
   'ContainedBy': {'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'WMIGPO@PHANTOM.CORP',
    'distinguishedname': 'CN=WMIGPO,CN=WMIPOLICY,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True}],
   'ObjectIdentifier': '2089520C-EA98-4F51-9266-17DB870EB226',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'WMIPOLICY@PHANTOM.CORP',
    'distinguishedname': 'CN=WMIPOLICY,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': True},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False}],
   'ObjectIdentifier': '04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0',
   'IsDeleted': False,
   'IsACLProtected': True,
   'ContainedBy': {'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'POLICYTEMPLATE@PHANTOM.CORP',
    'distinguishedname': 'CN=POLICYTEMPLATE,CN=WMIPOLICY,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True}],
   'ObjectIdentifier': '6BC18B1C-3EA1-45BE-B7E1-B001627E90B8',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'POLICYTYPE@PHANTOM.CORP',
    'distinguishedname': 'CN=POLICYTYPE,CN=WMIPOLICY,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True}],
   'ObjectIdentifier': '7089E478-DB66-4FAF-B705-917737D4990D',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '04F9AEFD-BFC5-4B9F-887C-FFC7F72B74F0',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'KEYS@PHANTOM.CORP',
    'distinguishedname': 'CN=KEYS,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': True},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-9',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-516',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-526',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-527',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False}],
   'ObjectIdentifier': '20A295DB-7AC5-4C38-8A2B-AACA4DC56E68',
   'IsDeleted': False,
   'IsACLProtected': True,
   'ContainedBy': {'ObjectIdentifier': 'S-1-5-21-2697957641-2271029196-387917394',
    'ObjectType': 'Domain'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'RPCSERVICES@PHANTOM.CORP',
    'distinguishedname': 'CN=RPCSERVICES,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': 'F7C4CB4E-4FF9-418A-A576-F05FFA92E730',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'USERS@PHANTOM.CORP',
    'distinguishedname': 'CN=USERS,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': '06DDAA96-A710-4023-A26A-C522B2A87AB4',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': 'S-1-5-21-2697957641-2271029196-387917394',
    'ObjectType': 'Domain'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'PROGRAM DATA@PHANTOM.CORP',
    'distinguishedname': 'CN=PROGRAM DATA,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': '7ECD8E4E-DC0E-49D5-9379-A6E0E1BBBFDE',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': 'S-1-5-21-2697957641-2271029196-387917394',
    'ObjectType': 'Domain'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'MICROSOFT@PHANTOM.CORP',
    'distinguishedname': 'CN=MICROSOFT,CN=PROGRAM DATA,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': '89A59FA1-EBC4-44D1-9F33-F7E033B227ED',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '7ECD8E4E-DC0E-49D5-9379-A6E0E1BBBFDE',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'MEETINGS@PHANTOM.CORP',
    'distinguishedname': 'CN=MEETINGS,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': 'C41BB32F-AB5A-4E73-8ECE-F6E65240BF84',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'RAS AND IAS SERVERS ACCESS CHECK@PHANTOM.CORP',
    'distinguishedname': 'CN=RAS AND IAS SERVERS ACCESS CHECK,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-553',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-553',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': 'E87CC94F-2114-4B3B-8899-8964AFCBE6F9',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
    'ObjectType': 'Container'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'SYSTEM@PHANTOM.CORP',
    'distinguishedname': 'CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': 'S-1-5-21-2697957641-2271029196-387917394',
    'ObjectType': 'Domain'}},
  {'Properties': {'domain': 'PHANTOM.CORP',
    'name': 'POLICIES@PHANTOM.CORP',
    'distinguishedname': 'CN=POLICIES,CN=SYSTEM,DC=PHANTOM,DC=CORP',
    'domainsid': 'S-1-5-21-2697957641-2271029196-387917394',
    'isaclprotected': False},
   'ChildObjects': [],
   'Aces': [{'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'Owns',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-512',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': False},
    {'PrincipalSID': 'S-1-5-21-2697957641-2271029196-387917394-519',
     'PrincipalType': 'Group',
     'RightName': 'GenericAll',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteDacl',
     'IsInherited': True},
    {'PrincipalSID': 'PHANTOM.CORP-S-1-5-32-544',
     'PrincipalType': 'Group',
     'RightName': 'WriteOwner',
     'IsInherited': True}],
   'ObjectIdentifier': '12B683AA-8B3D-4FE5-B3BF-58326CDC237B',
   'IsDeleted': False,
   'IsACLProtected': False,
   'ContainedBy': {'ObjectIdentifier': '55D64C55-CA9D-42B2-AFB8-FE1C4E2D1BFC',

In [3]:
data.keys()

dict_keys(['domains', 'containers', 'gpos', 'computers', 'users', 'groups', 'ous'])

In [4]:
print("Groups")
pd.DataFrame.from_dict(data["groups"]).columns

Groups

Index(['Properties', 'Members', 'Aces', 'ObjectIdentifier', 'IsDeleted',
       'IsACLProtected', 'ContainedBy'],
      dtype='object')

In [5]:
print("Users")
pd.DataFrame.from_dict(data["users"]).columns

Users

Index(['Properties', 'AllowedToDelegate', 'PrimaryGroupSID', 'HasSIDHistory',
       'SPNTargets', 'UnconstrainedDelegation', 'DomainSID', 'Aces',
       'ObjectIdentifier', 'IsDeleted', 'IsACLProtected', 'ContainedBy'],
      dtype='object')

Expand "Properties" column in new columns.

In [6]:
print("Computers")
pd.DataFrame.from_dict(data["computers"]).columns

Computers

Index(['Properties', 'PrimaryGroupSID', 'AllowedToDelegate', 'AllowedToAct',
       'HasSIDHistory', 'DumpSMSAPassword', 'Sessions', 'PrivilegedSessions',
       'RegistrySessions', 'LocalGroups', 'UserRights', 'DCRegistryData',
       'Status', 'IsDC', 'UnconstrainedDelegation', 'DomainSID',
       'IsWebClientRunning', 'SmbInfo', 'NtlmSessions', 'NTLMRegistryData',
       'Aces', 'ObjectIdentifier', 'IsDeleted', 'IsACLProtected',
       'ContainedBy'],
      dtype='object')

In [7]:
print("GPOs")
pd.DataFrame.from_dict(data["gpos"]).columns

GPOs

Index(['Properties', 'Aces', 'ObjectIdentifier', 'IsDeleted', 'IsACLProtected',
       'ContainedBy'],
      dtype='object')

In [8]:
print("OUs")
pd.DataFrame.from_dict(data["ous"]).columns

OUs

Index(['GPOChanges', 'Properties', 'Links', 'ChildObjects',
       'InheritanceHashes', 'Aces', 'ObjectIdentifier', 'IsDeleted',
       'IsACLProtected', 'ContainedBy'],
      dtype='object')

Convert to Dict

In [9]:
JSONdata = data

In [10]:
users_init = []
result = {"users_names": {}, "groups_names": {}, "computers_names": {}, "ous_names": {}, "gpos_names": {}, "domain_names": {}}
for users in JSONdata["users"]:
    result["users_names"][users['ObjectIdentifier']] = users['Properties']['name']
    properties = users.get('Properties', {})

    row = {}
    for key in users:
        if key not in ['Properties']:
            row[key] = users[key]

    for key in properties:
        row[key] = properties[key]

    users_init.append(row)

df_users_init = pd.DataFrame.from_records(users_init)

groups_init = []
for group in JSONdata["groups"]:
    result["groups_names"][group['ObjectIdentifier']] = group['Properties']['name']
    properties = group.get('Properties', {})

    row = {}
    for key in group:
        if key not in ['Properties']:
            row[key] = group[key]

    for key in properties:
        row[key] = properties[key]

    groups_init.append(row)

df_groups_init = pd.DataFrame.from_records(groups_init)

computers_init = []


for computers in JSONdata["computers"]:
    # The key was incorrect and causing the error; it should be 'ObjectIdentifier'
    result["computers_names"][computers['ObjectIdentifier']] = computers['Properties']['name']
    properties = computers.get('Properties', {})

    row = {}
    # Iterate over the keys of the current computers object
    for key in computers:
        if key not in ['Properties']:
            row[key] = computers[key]

    for key in properties:
        row[key] = properties[key]

    computers_init.append(row)

df_computers_init = pd.DataFrame.from_records(computers_init)

domains_init = []
for domains in JSONdata["domains"]:
    # The key was incorrect and causing the error; it should be 'ObjectIdentifier'
    result["domain_names"][domains['ObjectIdentifier']] = domains['Properties']['name']
    properties = domains.get('Properties', {})

    row = {}
    # Iterate over the keys of the current computers object
    for key in domains:
        if key not in ['Properties']:
            row[key] = domains[key]

    for key in properties:
        row[key] = properties[key]

    domains_init.append(row)

df_computers_init = pd.DataFrame.from_records(domains_init)

#result = {"users_names": {}, "groups_names": {}, "computers_names": {}, "ous_names": {}, "gpos_names": {}, "domain_names": {}}

ous_init = []

for ous in JSONdata["ous"]:
    result["ous_names"][ous['ContainedBy']['ObjectIdentifier']] = ous['Properties']['name']
    properties = ous.get('Properties', {})

    row = {}
    for key in ous:
        if key not in ['Properties']:
            row[key] = ous[key]

    for key in properties:
        row[key] = properties[key]

    ous_init.append(row)
    df_ous_init = pd.DataFrame.from_records(ous_init)

In [11]:
df_groups=pd.DataFrame.from_dict(groups_init)
df_users=pd.DataFrame.from_dict(users_init)
df_computers=pd.DataFrame.from_dict(computers_init)
df_domains=pd.DataFrame.from_dict(domains_init)

df_ous=pd.DataFrame.from_dict(ous_init)

In [12]:
df_groups.columns

Index(['Members', 'Aces', 'ObjectIdentifier', 'IsDeleted', 'IsACLProtected',
       'ContainedBy', 'domain', 'name', 'distinguishedname', 'domainsid',
       'samaccountname', 'doesanyacegrantownerrights',
       'doesanyinheritedacegrantownerrights', 'isaclprotected', 'description',
       'whencreated', 'admincount', 'reconcile'],
      dtype='object')

In [109]:
df_groups.head(5)

,Members,Aces,ObjectIdentifier,IsDeleted,IsACLProtected,ContainedBy,domain,name,distinguishedname,domainsid,samaccountname,doesanyacegrantownerrights,doesanyinheritedacegrantownerrights,isaclprotected,description,whencreated,admincount,reconcile
0,[{'ObjectIdentifier': 'S-1-5-21-1333368235-828...,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-515,False,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN COMPUTERS@MYLAB.LOCAL,"CN=DOMAIN COMPUTERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Computers,False,False,False,All workstations and servers joined to the domain,1.742158e+09,False,NaN
1,[{'ObjectIdentifier': 'S-1-5-21-1333368235-828...,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-516,False,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN CONTROLLERS@MYLAB.LOCAL,"CN=DOMAIN CONTROLLERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Controllers,False,False,True,All domain controllers in the domain,1.742158e+09,True,NaN
2,[{'ObjectIdentifier': 'S-1-5-21-1333368235-828...,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-518,False,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,SCHEMA ADMINS@MYLAB.LOCAL,"CN=SCHEMA ADMINS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Schema Admins,False,False,True,Designated administrators of the schema,1.742158e+09,True,NaN
3,[{'ObjectIdentifier': 'S-1-5-21-1333368235-828...,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-519,False,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,ENTERPRISE ADMINS@MYLAB.LOCAL,"CN=ENTERPRISE ADMINS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Enterprise Admins,False,False,True,Designated administrators of the enterprise,1.742158e+09,True,NaN
4,[{'ObjectIdentifier': 'S-1-5-21-1333368235-828...,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-512,False,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN ADMINS@MYLAB.LOCAL,"CN=DOMAIN ADMINS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Admins,False,False,True,Designated administrators of the domain,1.742158e+09,True,NaN

In [15]:
df_ous.columns

Index(['GPOChanges', 'Links', 'ChildObjects', 'InheritanceHashes', 'Aces',
       'ObjectIdentifier', 'IsDeleted', 'IsACLProtected', 'ContainedBy',
       'domain', 'name', 'distinguishedname', 'domainsid',
       'doesanyacegrantownerrights', 'doesanyinheritedacegrantownerrights',
       'isaclprotected', 'description', 'whencreated', 'blocksinheritance'],
      dtype='object')

In [16]:
df_ous.head(5)

,GPOChanges,Links,ChildObjects,InheritanceHashes,Aces,ObjectIdentifier,IsDeleted,IsACLProtected,ContainedBy,domain,name,distinguishedname,domainsid,doesanyacegrantownerrights,doesanyinheritedacegrantownerrights,isaclprotected,description,whencreated,blocksinheritance
0,"{'LocalAdmins': [], 'RemoteDesktopUsers': [], ...","[{'IsEnforced': False, 'GUID': 'F39BE162-0FF0-...",[],"[66A3BB5610138D9E64C55D7C3D9EA8298F2AFF65, E88...",[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,1AFCEA60-7A76-4602-BC16-0386AB6D5A2C,False,False,{'ObjectIdentifier': 'S-1-5-21-1333368235-8284...,MYLAB.LOCAL,DOMAIN CONTROLLERS@MYLAB.LOCAL,"OU=DOMAIN CONTROLLERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,False,False,False,Default container for domain controllers,1742158051,False
1,"{'LocalAdmins': [], 'RemoteDesktopUsers': [], ...",[],[],"[A199BE7239461E6B9DD7D17E3B4F6828B5617A22, F25...",[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,90CFC892-BAC1-415D-9184-162AF19259DB,False,False,{'ObjectIdentifier': 'S-1-5-21-1333368235-8284...,MYLAB.LOCAL,ADMIN@MYLAB.LOCAL,"OU=ADMIN,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,False,False,False,NaN,1742158747,False
2,"{'LocalAdmins': [], 'RemoteDesktopUsers': [], ...",[],[],[5D34FB42F507FB785CEBAD18A235737CD100E4C5],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,E7DCAE11-F5DB-4745-9BE3-25F56B5D2FA6,False,False,{'ObjectIdentifier': '90CFC892-BAC1-415D-9184-...,MYLAB.LOCAL,TIER 0@MYLAB.LOCAL,"OU=TIER 0,OU=ADMIN,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,False,False,False,NaN,1742158747,False
3,"{'LocalAdmins': [], 'RemoteDesktopUsers': [], ...",[],[],[],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,C1D91B67-BF6D-4C72-AEB9-FDD0FBEC5F92,False,False,{'ObjectIdentifier': 'E7DCAE11-F5DB-4745-9BE3-...,MYLAB.LOCAL,T0-ACCOUNTS@MYLAB.LOCAL,"OU=T0-ACCOUNTS,OU=TIER 0,OU=ADMIN,DC=MYLAB,DC=...",S-1-5-21-1333368235-828418111-1849936505,False,False,False,NaN,1742158747,False
4,"{'LocalAdmins': [], 'RemoteDesktopUsers': [], ...",[],[],"[2FDB61A11EFAB40B87C1D9C50DB6360B6DED1801, 9E8...",[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,0A640252-AC1A-4B31-AB8B-DE8496831036,False,False,{'ObjectIdentifier': 'E7DCAE11-F5DB-4745-9BE3-...,MYLAB.LOCAL,T0-SERVERS@MYLAB.LOCAL,"OU=T0-SERVERS,OU=TIER 0,OU=ADMIN,DC=MYLAB,DC=L...",S-1-5-21-1333368235-828418111-1849936505,False,False,False,NaN,1742158747,False

In [17]:
df_domains.columns

Index(['GPOChanges', 'ChildObjects', 'Trusts', 'Links', 'InheritanceHashes',
       'ForestRootIdentifier', 'Aces', 'ObjectIdentifier', 'IsDeleted',
       'IsACLProtected', 'ContainedBy', 'domain', 'name', 'distinguishedname',
       'domainsid', 'doesanyacegrantownerrights',
       'doesanyinheritedacegrantownerrights', 'isaclprotected', 'whencreated',
       'expirepasswordsonsmartcardonlyaccounts', 'machineaccountquota',
       'minpwdlength', 'pwdproperties', 'pwdhistorylength', 'lockoutthreshold',
       'minpwdage', 'maxpwdage', 'lockoutduration', 'lockoutobservationwindow',
       'functionallevel', 'dsheuristics', 'collected'],
      dtype='object')

In [18]:
df_domains.head(5)

,GPOChanges,ChildObjects,Trusts,Links,InheritanceHashes,ForestRootIdentifier,Aces,ObjectIdentifier,IsDeleted,IsACLProtected,...,pwdproperties,pwdhistorylength,lockoutthreshold,minpwdage,maxpwdage,lockoutduration,lockoutobservationwindow,functionallevel,dsheuristics,collected
0,"{'LocalAdmins': [], 'RemoteDesktopUsers': [], ...",[],[],"[{'IsEnforced': False, 'GUID': 'CD3A9B14-C932-...","[62C26D4FB3FF64505B03CDD35D648DFBC6C157CC, 8A7...",S-1-5-21-1333368235-828418111-1849936505,"[{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', ...",S-1-5-21-1333368235-828418111-1849936505,False,False,...,1,24,0,1 day,42 days,10 minutes,-6000000000,2016,None,True

In [19]:
df_users

,AllowedToDelegate,PrimaryGroupSID,HasSIDHistory,SPNTargets,UnconstrainedDelegation,DomainSID,Aces,ObjectIdentifier,IsDeleted,IsACLProtected,...,unixpassword,unicodepassword,sfupassword,logonscript,useraccountcontrol,profilepath,admincount,supportedencryptiontypes,sidhistory,reconcile
0,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-500,False,True,...,NaN,NaN,NaN,NaN,512.0,NaN,True,None,[],NaN
1,[],S-1-5-21-1333368235-828418111-1849936505-514,[],[],False,S-1-5-21-1333368235-828418111-1849936505,"[{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', ...",S-1-5-21-1333368235-828418111-1849936505-501,False,False,...,NaN,NaN,NaN,NaN,66082.0,NaN,False,None,[],NaN
2,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-502,False,True,...,NaN,NaN,NaN,NaN,514.0,NaN,True,[Not defined],[],NaN
3,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1103,False,True,...,NaN,NaN,NaN,NaN,66048.0,NaN,True,None,[],NaN
4,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1104,False,False,...,NaN,NaN,NaN,NaN,512.0,NaN,False,None,[],NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-3592,False,False,...,NaN,NaN,NaN,NaN,512.0,NaN,False,None,[],NaN
2492,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-3593,False,False,...,NaN,NaN,NaN,NaN,4194816.0,NaN,False,None,[],NaN
2493,[],S-1-5-21-1333368235-828418111-1849936505-513,[],[],False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-3366,False,False,...,NaN,NaN,NaN,NaN,4194816.0,NaN,False,None,[],NaN
2494,[],None,[],[],False,None,[],MYLAB.LOCAL-S-1-5-20,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2495,[],None,[],[],False,None,[],MYLAB.LOCAL-S-1-5-17,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [14]:
df_groups.shape

(578, 18)

In [13]:
df_users.shape

(2496, 55)

In [15]:
df_computers.shape

(100, 57)

In [16]:
df_ous.shape

(223, 19)

In [17]:
df_domains.shape

(1, 32)

In [ ]:
import pandas as pd
# Merge dataframes to find relationships
# The 'primaryGroupSID' and 'PrimaryGroup' may contain information about group membership.
# Replace 'memberOf' with 'primaryGroupSID' or 'PrimaryGroup' depending on your data
merged_df = pd.merge(df_users, df_groups, left_on='PrimaryGroupSID', right_on='ObjectIdentifier', how='inner')
# If 'primaryGroupSID' doesn't work, try 'PrimaryGroup' or any other group-related column

# Display the merged dataframe
print(merged_df)

# Analyze the merged dataframe to understand the relationships
# For example, you can group by group name and count the number of users in each group
group_counts = merged_df.groupby('name_y')['name_x'].count()
group_counts
#group_counts.describe([HasSIDHistory])

In [ ]:
import pandas as pd
# Merge dataframes to find relationships
# The 'primaryGroupSID' and 'PrimaryGroup' may contain information about group membership.
# Replace 'memberOf' with 'primaryGroupSID' or 'PrimaryGroup' depending on your data
merged_df = pd.merge(df_users, df_groups, left_on='PrimaryGroupSID', right_on='ObjectIdentifier', how='inner')
# If 'primaryGroupSID' doesn't work, try 'PrimaryGroup' or any other group-related column

# Display the merged dataframe
print(merged_df)

# Analyze the merged dataframe to understand the relationships
# For example, you can group by group name and count the number of users in each group
group_counts = merged_df.groupby('name_y')['name_x'].count()
group_counts

# Assuming 'HasSIDHistory' is a column in your DataFrame:
# If it's not a column, you need to define it or use a different approach
if 'HasSIDHistory' in merged_df.columns:
  # Filter the merged DataFrame for users with SID history
  users_with_sid_history = merged_df[merged_df['HasSIDHistory'] == True]

  # Group by group name and count users with SID history
  group_counts_sid_history = users_with_sid_history.groupby('name_y')['name_x'].count()

  # Display the results
  print("Group Counts for Users with SID History:")
  print(group_counts_sid_history)

  # You can use describe() on the group_counts_sid_history if needed
  print(group_counts_sid_history.describe())
else:
  print("Column 'HasSIDHistory' not found in DataFrame.")

#group_counts.describe([HasSIDHistory]) #This line is causing error, because HasSIDHistory is not defined

In [21]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

df = merged_df.drop(['AllowedToDelegate', 'IsDeleted_x', 'HasSIDHistory', 'SPNTargets', 'reconcile_y', 'doesanyinheritedacegrantownerrights_x'], axis=1)

In [22]:

df.head(5)

,PrimaryGroupSID,UnconstrainedDelegation,DomainSID,Aces_x,ObjectIdentifier_x,IsACLProtected_x,ContainedBy_x,domain_x,name_x,distinguishedname_x,domainsid_x,samaccountname_x,doesanyacegrantownerrights_x,isaclprotected_x,description_x,whencreated_x,sensitive,dontreqpreauth,passwordnotreqd,unconstraineddelegation,pwdneverexpires,enabled,trustedtoauth,smartcardrequired,encryptedtextpwdallowed,usedeskeyonly,logonscriptenabled,lockedout,passwordcantchange,passwordexpired,lastlogon,lastlogontimestamp,pwdlastset,serviceprincipalnames,hasspn,displayname,email,title,homedirectory,userpassword,unixpassword,unicodepassword,sfupassword,logonscript,useraccountcontrol,profilepath,admincount_x,supportedencryptiontypes,sidhistory,reconcile_x,Members,Aces_y,ObjectIdentifier_y,IsDeleted_y,IsACLProtected_y,ContainedBy_y,domain_y,name_y,distinguishedname_y,domainsid_y,samaccountname_y,doesanyacegrantownerrights_y,doesanyinheritedacegrantownerrights_y,isaclprotected_y,description_y,whencreated_y,admincount_y
0,S-1-5-21-1333368235-828418111-1849936505-513,False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-500,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,LUIS@MYLAB.LOCAL,"CN=LUIS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,luis,False,True,Built-in account for administering the compute...,1.742158e+09,False,False,False,False,False,True,False,False,False,False,False,False,False,False,1.742158e+09,1.742158e+09,1.742132e+09,[],False,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0,NaN,True,None,[],NaN,[],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,False,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,False,All domain users,1.742158e+09,False
1,S-1-5-21-1333368235-828418111-1849936505-514,False,S-1-5-21-1333368235-828418111-1849936505,"[{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', ...",S-1-5-21-1333368235-828418111-1849936505-501,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,GUEST@MYLAB.LOCAL,"CN=GUEST,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Guest,False,False,Built-in account for guest access to the compu...,1.742158e+09,False,False,True,False,True,False,False,False,False,False,False,False,False,False,0.000000e+00,-1.000000e+00,0.000000e+00,[],False,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66082.0,NaN,False,None,[],NaN,[],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-514,False,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN GUESTS@MYLAB.LOCAL,"CN=DOMAIN GUESTS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Guests,False,False,False,All domain guests,1.742158e+09,False
2,S-1-5-21-1333368235-828418111-1849936505-513,False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-502,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,KRBTGT@MYLAB.LOCAL,"CN=KRBTGT,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,krbtgt,False,True,Key Distribution Center Service Account,1.742158e+09,False,False,False,False,False,False,False,False,False,False,False,False,False,False,0.000000e+00,-1.000000e+00,1.742158e+09,[kadmin/changepw],True,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,514.0,NaN,True,[Not defined],[],NaN,[],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,False,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,False,All domain users,1.742158e+09,False
3,S-1-5-21-1333368235-828418111-1849936505-513,False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1103,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,MARIA@MYLAB.LOCAL,"CN=MARIA,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,maria,False,True,NaN,1.742159e+09,False,False,False,False,True,True,False,False,False,False,False,False,False,False,0.000000e+00,-1.000000e+00,1.742159e+09,[],False,Maria,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66048.0,NaN,True,None,[],NaN,[],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,False,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,False,All domain users,1.742158e+09,False
4,S-1-5-21-1333368235-828418111-1849936505-513,False,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1104,False,{'ObjectIdentifier': '21410F29-9A46-4A56-BC92-...,MYLAB.LOCAL,LEONOR_BUTLER@MYLAB.LOCAL,"CN=LEONOR_BUTLER,OU=SERVICEACCOUNTS,OU=FSR,OU=...",S-1-5-21-1333368235-828418111-1849936505,LEONOR_BUTLER,False,False,Created with secframe.com/badblood.,1.742159e+09,False,False,False,False,False,True,False,False,False,False,False,False,False,False,0.000000e+00,-1.000000e+00,1.742159e+09,[POP3/SECWLPT1000001],True,LEONOR_BUTLER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,512.0,NaN,False,None,[],NaN,[],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,False,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MYLAB.LOCAL,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,False,All domain users,1.742158e+09,False

In [23]:
df['samaccountname_y'].describe()

count             2494
unique               2
top       Domain Users
freq              2493
Name: samaccountname_y, dtype: object

In [119]:
df.columns

AttributeError: 'NoneType' object has no attribute 'columns'

In [24]:
df.drop(['email', 'title', 'homedirectory', 'userpassword',
       'unixpassword', 'unicodepassword', 'sfupassword', 'logonscript', 'profilepath', 'sidhistory', 'reconcile_x','UnconstrainedDelegation', 'domain_x', 'doesanyacegrantownerrights_x'], axis=1, inplace=True)

In [25]:
df['dontreqpreauth'].describe()

count      2494
unique        2
top       False
freq       2326
Name: dontreqpreauth, dtype: object

In [26]:
df.drop([ 'smartcardrequired', 'encryptedtextpwdallowed', 'usedeskeyonly', 'logonscriptenabled', 'lockedout', 'passwordcantchange', 'passwordexpired', 'Members', 'IsDeleted_y', 'IsACLProtected_y', 'domain_y', 'doesanyinheritedacegrantownerrights_y', 'admincount_y' , 'whencreated_y'], axis=1, inplace=True)

In [27]:
df.columns

Index(['PrimaryGroupSID', 'DomainSID', 'Aces_x', 'ObjectIdentifier_x',
       'IsACLProtected_x', 'ContainedBy_x', 'name_x', 'distinguishedname_x',
       'domainsid_x', 'samaccountname_x', 'isaclprotected_x', 'description_x',
       'whencreated_x', 'sensitive', 'dontreqpreauth', 'passwordnotreqd',
       'unconstraineddelegation', 'pwdneverexpires', 'enabled',
       'trustedtoauth', 'lastlogon', 'lastlogontimestamp', 'pwdlastset',
       'serviceprincipalnames', 'hasspn', 'displayname', 'useraccountcontrol',
       'admincount_x', 'supportedencryptiontypes', 'Aces_y',
       'ObjectIdentifier_y', 'ContainedBy_y', 'name_y', 'distinguishedname_y',
       'domainsid_y', 'samaccountname_y', 'doesanyacegrantownerrights_y',
       'isaclprotected_y', 'description_y'],
      dtype='object')

In [28]:
df.head(5)

,PrimaryGroupSID,DomainSID,Aces_x,ObjectIdentifier_x,IsACLProtected_x,ContainedBy_x,name_x,distinguishedname_x,domainsid_x,samaccountname_x,isaclprotected_x,description_x,whencreated_x,sensitive,dontreqpreauth,passwordnotreqd,unconstraineddelegation,pwdneverexpires,enabled,trustedtoauth,lastlogon,lastlogontimestamp,pwdlastset,serviceprincipalnames,hasspn,displayname,useraccountcontrol,admincount_x,supportedencryptiontypes,Aces_y,ObjectIdentifier_y,ContainedBy_y,name_y,distinguishedname_y,domainsid_y,samaccountname_y,doesanyacegrantownerrights_y,isaclprotected_y,description_y
0,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-500,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,LUIS@MYLAB.LOCAL,"CN=LUIS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,luis,True,Built-in account for administering the compute...,1.742158e+09,False,False,False,False,False,True,False,1.742158e+09,1.742158e+09,1.742132e+09,[],False,None,512.0,True,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users
1,S-1-5-21-1333368235-828418111-1849936505-514,S-1-5-21-1333368235-828418111-1849936505,"[{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', ...",S-1-5-21-1333368235-828418111-1849936505-501,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,GUEST@MYLAB.LOCAL,"CN=GUEST,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Guest,False,Built-in account for guest access to the compu...,1.742158e+09,False,False,True,False,True,False,False,0.000000e+00,-1.000000e+00,0.000000e+00,[],False,None,66082.0,False,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-514,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN GUESTS@MYLAB.LOCAL,"CN=DOMAIN GUESTS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Guests,False,False,All domain guests
2,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-502,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,KRBTGT@MYLAB.LOCAL,"CN=KRBTGT,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,krbtgt,True,Key Distribution Center Service Account,1.742158e+09,False,False,False,False,False,False,False,0.000000e+00,-1.000000e+00,1.742158e+09,[kadmin/changepw],True,None,514.0,True,[Not defined],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users
3,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1103,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MARIA@MYLAB.LOCAL,"CN=MARIA,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,maria,True,NaN,1.742159e+09,False,False,False,False,True,True,False,0.000000e+00,-1.000000e+00,1.742159e+09,[],False,Maria,66048.0,True,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users
4,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1104,False,{'ObjectIdentifier': '21410F29-9A46-4A56-BC92-...,LEONOR_BUTLER@MYLAB.LOCAL,"CN=LEONOR_BUTLER,OU=SERVICEACCOUNTS,OU=FSR,OU=...",S-1-5-21-1333368235-828418111-1849936505,LEONOR_BUTLER,False,Created with secframe.com/badblood.,1.742159e+09,False,False,False,False,False,True,False,0.000000e+00,-1.000000e+00,1.742159e+09,[POP3/SECWLPT1000001],True,LEONOR_BUTLER,512.0,False,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users

In [29]:
# prompt: add a "weight" column to  df with a value of 1

df['Weight'] = 1

In [ ]:
for column in df.columns:
    unique_values = df[column].unique()
    print(f"Unique values in column '{column}': {unique_values}")

In [30]:
df.head(5)

,PrimaryGroupSID,DomainSID,Aces_x,ObjectIdentifier_x,IsACLProtected_x,ContainedBy_x,name_x,distinguishedname_x,domainsid_x,samaccountname_x,isaclprotected_x,description_x,whencreated_x,sensitive,dontreqpreauth,passwordnotreqd,unconstraineddelegation,pwdneverexpires,enabled,trustedtoauth,lastlogon,lastlogontimestamp,pwdlastset,serviceprincipalnames,hasspn,displayname,useraccountcontrol,admincount_x,supportedencryptiontypes,Aces_y,ObjectIdentifier_y,ContainedBy_y,name_y,distinguishedname_y,domainsid_y,samaccountname_y,doesanyacegrantownerrights_y,isaclprotected_y,description_y,Weight
0,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-500,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,LUIS@MYLAB.LOCAL,"CN=LUIS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,luis,True,Built-in account for administering the compute...,1.742158e+09,False,False,False,False,False,True,False,1.742158e+09,1.742158e+09,1.742132e+09,[],False,None,512.0,True,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users,1
1,S-1-5-21-1333368235-828418111-1849936505-514,S-1-5-21-1333368235-828418111-1849936505,"[{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', ...",S-1-5-21-1333368235-828418111-1849936505-501,False,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,GUEST@MYLAB.LOCAL,"CN=GUEST,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Guest,False,Built-in account for guest access to the compu...,1.742158e+09,False,False,True,False,True,False,False,0.000000e+00,-1.000000e+00,0.000000e+00,[],False,None,66082.0,False,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-514,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN GUESTS@MYLAB.LOCAL,"CN=DOMAIN GUESTS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Guests,False,False,All domain guests,1
2,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-502,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,KRBTGT@MYLAB.LOCAL,"CN=KRBTGT,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,krbtgt,True,Key Distribution Center Service Account,1.742158e+09,False,False,False,False,False,False,False,0.000000e+00,-1.000000e+00,1.742158e+09,[kadmin/changepw],True,None,514.0,True,[Not defined],[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users,1
3,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1103,True,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,MARIA@MYLAB.LOCAL,"CN=MARIA,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,maria,True,NaN,1.742159e+09,False,False,False,False,True,True,False,0.000000e+00,-1.000000e+00,1.742159e+09,[],False,Maria,66048.0,True,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users,1
4,S-1-5-21-1333368235-828418111-1849936505-513,S-1-5-21-1333368235-828418111-1849936505,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-1104,False,{'ObjectIdentifier': '21410F29-9A46-4A56-BC92-...,LEONOR_BUTLER@MYLAB.LOCAL,"CN=LEONOR_BUTLER,OU=SERVICEACCOUNTS,OU=FSR,OU=...",S-1-5-21-1333368235-828418111-1849936505,LEONOR_BUTLER,False,Created with secframe.com/badblood.,1.742159e+09,False,False,False,False,False,True,False,0.000000e+00,-1.000000e+00,1.742159e+09,[POP3/SECWLPT1000001],True,LEONOR_BUTLER,512.0,False,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-513,{'ObjectIdentifier': '643CE9DD-6D50-4B82-8DA1-...,DOMAIN USERS@MYLAB.LOCAL,"CN=DOMAIN USERS,CN=USERS,DC=MYLAB,DC=LOCAL",S-1-5-21-1333368235-828418111-1849936505,Domain Users,False,False,All domain users,1

In [72]:
df_computers['ldapsigning'].describe()

count         1
unique        1
top       False
freq          1
Name: ldapsigning, dtype: object

In [49]:
df_computers.head(3)

,PrimaryGroupSID,AllowedToDelegate,AllowedToAct,HasSIDHistory,DumpSMSAPassword,Sessions,PrivilegedSessions,RegistrySessions,LocalGroups,UserRights,DCRegistryData,Status,IsDC,UnconstrainedDelegation,DomainSID,IsWebClientRunning,SmbInfo,NtlmSessions,NTLMRegistryData,Aces,ObjectIdentifier,IsDeleted,IsACLProtected,ContainedBy,domain,name,distinguishedname,domainsid,samaccountname,haslaps,doesanyacegrantownerrights,doesanyinheritedacegrantownerrights,isaclprotected,description,whencreated,enabled,unconstraineddelegation,trustedtoauth,isdc,encryptedtextpwdallowed,usedeskeyonly,logonscriptenabled,lockedout,passwordexpired,supportedencryptiontypes,lastlogon,lastlogontimestamp,pwdlastset,serviceprincipalnames,email,useraccountcontrol,operatingsystem,sidhistory,ldapavailable,ldapsavailable,ldapsepa,ldapsigning
0,S-1-5-21-1333368235-828418111-1849936505-515,[],[],[],[],"{'Results': [], 'Collected': False, 'FailureRe...","{'Results': [], 'Collected': False, 'FailureRe...","{'Results': [], 'Collected': False, 'FailureRe...",[],[],"{'CertificateMappingMethods': None, 'StrongCer...","{'Connectable': False, 'Error': 'PortNotOpen'}",False,False,S-1-5-21-1333368235-828418111-1849936505,None,None,None,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-4092,False,False,{'ObjectIdentifier': 'D14BA82A-433E-438F-96D3-...,MYLAB.LOCAL,BDEWAPPS1000000.MYLAB.LOCAL,"CN=BDEWAPPS1000000,OU=GROUPS,OU=BDE,OU=TIER 2,...",S-1-5-21-1333368235-828418111-1849936505,BDEWAPPS1000000$,False,False,False,False,Created with secframe.com/badblood.,1742159285,True,False,False,False,False,False,False,False,False,None,0,-1,1742159285,[],None,4096,None,[],NaN,NaN,NaN,NaN
1,S-1-5-21-1333368235-828418111-1849936505-515,[],[],[],[],"{'Results': [], 'Collected': False, 'FailureRe...","{'Results': [], 'Collected': False, 'FailureRe...","{'Results': [], 'Collected': False, 'FailureRe...",[],[],"{'CertificateMappingMethods': None, 'StrongCer...","{'Connectable': False, 'Error': 'PortNotOpen'}",False,False,S-1-5-21-1333368235-828418111-1849936505,None,None,None,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-4093,False,False,{'ObjectIdentifier': '3CA7FFAE-BFEC-4FA8-A93A-...,MYLAB.LOCAL,OGCWLPT1000000.MYLAB.LOCAL,"CN=OGCWLPT1000000,OU=SERVICEACCOUNTS,OU=ESM,OU...",S-1-5-21-1333368235-828418111-1849936505,OGCWLPT1000000$,False,False,False,False,Created with secframe.com/badblood.,1742159286,True,False,False,False,False,False,False,False,False,None,0,-1,1742159286,[],None,4096,None,[],NaN,NaN,NaN,NaN
2,S-1-5-21-1333368235-828418111-1849936505-515,[],[],[],[],"{'Results': [], 'Collected': False, 'FailureRe...","{'Results': [], 'Collected': False, 'FailureRe...","{'Results': [], 'Collected': False, 'FailureRe...",[],[],"{'CertificateMappingMethods': None, 'StrongCer...","{'Connectable': False, 'Error': 'PortNotOpen'}",False,False,S-1-5-21-1333368235-828418111-1849936505,None,None,None,None,[{'PrincipalSID': 'S-1-5-21-1333368235-8284181...,S-1-5-21-1333368235-828418111-1849936505-4094,False,False,{'ObjectIdentifier': '74A73F2B-F020-4843-89B4-...,MYLAB.LOCAL,BDEWLPT1000000.MYLAB.LOCAL,"CN=BDEWLPT1000000,OU=SERVICEACCOUNTS,OU=FIN,OU...",S-1-5-21-1333368235-828418111-1849936505,BDEWLPT1000000$,False,False,False,False,Created with secframe.com/badblood.,1742159286,True,False,False,False,False,False,False,False,False,None,0,-1,1742159286,[],None,4096,None,[],NaN,NaN,NaN,NaN

In [74]:
df_computers.drop([ 'AllowedToDelegate', 'AllowedToAct', 'HasSIDHistory', 'DumpSMSAPassword', 'UserRights', 'DCRegistryData', 'Status', 'IsDC', 'DomainSID', 'IsDeleted', 'IsACLProtected', 'doesanyacegrantownerrights', 'UserRights', 'enabled', 'encryptedtextpwdallowed', 'usedeskeyonly', 'logonscriptenabled', 'lockedout', 'passwordexpired', 'email', 'sidhistory'], axis=1, inplace=True)

In [75]:
df_computers.columns

Index(['PrimaryGroupSID', 'Sessions', 'PrivilegedSessions', 'RegistrySessions',
       'LocalGroups', 'UnconstrainedDelegation', 'IsWebClientRunning',
       'SmbInfo', 'NtlmSessions', 'NTLMRegistryData', 'Aces',
       'ObjectIdentifier', 'ContainedBy', 'domain', 'name',
       'distinguishedname', 'domainsid', 'samaccountname', 'haslaps',
       'doesanyinheritedacegrantownerrights', 'isaclprotected', 'description',
       'whencreated', 'unconstraineddelegation', 'trustedtoauth', 'isdc',
       'supportedencryptiontypes', 'lastlogon', 'lastlogontimestamp',
       'pwdlastset', 'serviceprincipalnames', 'useraccountcontrol',
       'operatingsystem', 'ldapavailable', 'ldapsavailable', 'ldapsepa',
       'ldapsigning'],
      dtype='object')

In [76]:
dict = df_computers['Aces']

In [79]:

#dict.show(10, truncate=True)
dict.describe

<bound method NDFrame.describe of 0     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
1     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
2     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
3     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
4     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
5     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
6     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
7     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
8     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
9     [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
10    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
11    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
12    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
13    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
14    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
15    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
16    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
17    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
18    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
19    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
20    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
21    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
22    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
23    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
24    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
25    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
26    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
27    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
28    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
29    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
30    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
31    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
32    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
33    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
34    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
35    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
36    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
37    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
38    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
39    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
40    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
41    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
42    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
43    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
44    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
45    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
46    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
47    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
48    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
49    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
50    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
51    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
52    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
53    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
54    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
55    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
56    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
57    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
58    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
59    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
60    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
61    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
62    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
63    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
64    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
65    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
66    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
67    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
68    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
69    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
70    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
71    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
72    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
73    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
74    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
75    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
76    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
77    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
78    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
79    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
80    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
81    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
82    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
83    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
84    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
85    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
86    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
87    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
88    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
89    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
90    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
91    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
92    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
93    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
94    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
95    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
96    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
97    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
98    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
99    [{'PrincipalSID': 'S-1-5-21-1333368235-8284181...
Name: Aces, dtype: object>

In [81]:
# prompt: show me the contants of 'dict' without truncating, that didn't work. only showing the 1st 50 characters

import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

dict

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteAccountRestrictions', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3022', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '7A7131FAC4956E4EF34FF39BC7F0A2B8BD71044D'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3769', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53F21117DAED7A85F768663DE6BE35B3B9A62039'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2571', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F42C65357510DD280974B81C50F9E28EEC1B81BD'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-4186', 'PrincipalType': 'Computer', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '7B2B44411944F26D8DD15971427B2E07E320202D'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '9CEAE3A7CE96082F102326F4F621051F3494E681'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EFD612D2FDDBD09C9B50499A333DF166E98516E3'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '249B74BB71A514FA64267D87B4F6A777E301AF04'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F0A68415F9DB3629EE891DB15746B1ACE04ADAE8'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'A8271C611A640CBFAE0E791B9219651437841D4D'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteAccountRestrictions', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '9CEAE3A7CE96082F102326F4F621051F3494E681'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3940', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'DB059EA66E77513649B83715D95A28ECA94164BA'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3310', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '141C86F79B6DD045A368EF00694556F7673996C7'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EFD612D2FDDBD09C9B50499A333DF166E98516E3'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '249B74BB71A514FA64267D87B4F6A777E301AF04'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F0A68415F9DB3629EE891DB15746B1ACE04ADAE8'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'A8271C611A640CBFAE0E791B9219651437841D4D'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}]
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteAccountRestrictions', 'IsInherited': False, 'InheritanceHash': ''}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2624', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EB29650D3F9DA5CB6CE62428EBD27B433048F10A'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1425', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'FD26E9B0CCE3D973F1B708576E16D8BC5857ECC1'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3710', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F8BF75715A4D3EA4BDAB388DC820D022F80F1460'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1963', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '74298907990C3446304B447D32D9755D488897A3'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '9CEAE3A7CE96082F102326F4F621051F3494E681'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EFD612D2FDDBD09C9B50499A333DF166E98516E3'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '249B74BB71A514FA64267D87B4F6A777E301AF04'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F0A68415F9DB3629EE891DB15746B1ACE04ADAE8'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'A8271C611A640CBFAE0E791B9219651437841D4D'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9'}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC'}]

In [93]:
# prompt: how do i add a column to each instance of 'PrincipalSID' within 'dict' called 'weight' and assign different values depending on the contents of 'RightName'

# Assuming 'dict' is your pandas Series containing the 'Aces' data from df_computers
# and you want to modify the dictionary within each element of the Series.

def add_weight(aces_list):
    # Iterate through each dictionary in the aces_list
    for ace_dict in aces_list:
        if 'RightName' in ace_dict and 'PrincipalSID' in ace_dict:
            if ace_dict['RightName'] == 'GenericAll':
                ace_dict['weight'] = 8
            elif ace_dict['RightName'] == 'GenericWrite':
                ace_dict['weight'] = 5
            elif ace_dict['RightName'] == 'WriteOwner':
                ace_dict['weight'] = 9
            elif ace_dict['RightName'] == 'Owns':
                ace_dict['weight'] = 10
            elif ace_dict['RightName'] == 'WriteDacl':
                ace_dict['weight'] = 10
            elif ace_dict['RightName'] == 'GenericRead':
                ace_dict['weight'] = 1
            elif ace_dict['RightName'] == 'AddKeyCredentialLink':
                ace_dict['weight'] = 5
            elif ace_dict['RightName'] == 'WriteAccountRestrictions':
                ace_dict['weight'] = 7
            elif ace_dict['RightName'] == 'GenericExecute':
                ace_dict['weight'] = 1
            else:
                ace_dict['weight'] = 0  # Default weight
    return aces_list


# Apply the function to each element of the 'Aces' Series
# The below line assumes df_computers['Aces'] is a column which contains list of dictionary
# If Aces is not a column with list of dictionary, change this line according to the structure
# of your df_computers['Aces'].

df_computers['Aces'] = df_computers['Aces'].apply(add_weight)

#print(df_computers.head())
pd.set_option("display.max_colwidth", None)

In [96]:
# prompt: show me the weight column for all 'PricipleSID' within df_computers['Aces']

# Assuming 'df_computers' and its 'Aces' column are defined as in your provided code.

import pandas as pd

# Access the 'Aces' column, which presumably contains a list of dictionaries
aces_data = df_computers['Aces']

# Iterate through each row of the DataFrame
for index, row in df_computers.iterrows():
  # Assuming each row's 'Aces' entry is a list of dictionaries
  if isinstance(row['Aces'], list):
    for ace in row['Aces']:
      if 'PrincipalSID' in ace and 'PricipleSID' in ace: # Check for both keys as mentioned in your instructions
          print(f"PrincipalSID: {ace['PrincipalSID'], ace['RightName']}, Weight: {ace.get('weight', 'N/A')}")
      elif 'PrincipalSID' in ace: # Check for 'PrincipalSID'
        print(f"PrincipalSID: {ace['PrincipalSID'], ace['RightName']}, Weight: {ace.get('weight', 'N/A')}")
  else:
      print(f"Row {index} does not have a valid 'Aces' list")

PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3022', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3769', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2571', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-4186', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3940', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3310', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2624', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1425', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3710', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1963', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3310', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3310', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3310', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2605', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1308', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2790', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3710', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1963', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1283', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3654', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2571', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-4186', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3310', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3393', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1605', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-500', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1425', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3710', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1963', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-527', 'AddKeyCredentialLink'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2167', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1723', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1471', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-519', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3600', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3890', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3635', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3476', 'GenericAll'), Weight: 8
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteDacl'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'WriteOwner'), Weight: 9
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-544', 'GenericWrite'), Weight: 5
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'Owns'), Weight: 10
PrincipalSID: ('MYLAB.LOCAL-S-1-5-32-548', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-512', 'WriteAccountRestrictions'), Weight: 7
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-4186', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1308', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1539', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-2790', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-3710', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-1963', 'GenericAll'), Weight: 8
PrincipalSID: ('S-1-5-21-1333368235-828418111-1849936505-526', 'AddKeyCredentialLink'), Weight: 5

In [98]:
# prompt: get me a list of all 'RightName' within the df_computers['Aces'] and make it unique

right_names_computers = set()
for index, row in df_computers.iterrows():
    if isinstance(row['Aces'], list):
        for ace in row['Aces']:
            if 'RightName' in ace:
                right_names_computers.add(ace['RightName'])

print(list(right_names_computers))

['WriteOwner', 'Owns', 'GenericAll', 'WriteDacl', 'GenericWrite', 'AddKeyCredentialLink', 'WriteAccountRestrictions']

In [99]:
# prompt: get me a list of all 'RightName' within the df_computers['Aces'] and make it unique

right_names_groups = set()
for index, row in df_groups.iterrows():
    if isinstance(row['Aces'], list):
        for ace in row['Aces']:
            if 'RightName' in ace:
                right_names_groups.add(ace['RightName'])

print(list(right_names_groups))

['WriteOwner', 'Owns', 'GenericAll', 'WriteDacl', 'GenericWrite']

In [100]:
# prompt: get me a list of all 'RightName' within the df_computers['Aces'] and make it unique

right_names_users = set()
for index, row in df_users.iterrows():
    if isinstance(row['Aces'], list):
        for ace in row['Aces']:
            if 'RightName' in ace:
                right_names_users.add(ace['RightName'])

print(list(right_names_users))

['WriteOwner', 'AllExtendedRights', 'Owns', 'GenericAll', 'WriteDacl', 'GenericWrite', 'AddKeyCredentialLink']

In [103]:
# prompt: get me a list of all 'RightName' within the df_computers['Aces'] and make it unique

right_names_ous = set()
for index, row in df_ous.iterrows():
    if isinstance(row['Aces'], list):
        for ace in row['Aces']:
            if 'RightName' in ace:
                right_names_gpos.add(ace['RightName'])

print(list(right_names_ous))

[]

In [105]:
# prompt: get me a list of all 'RightName' within the df_computers['Aces'] and make it unique

right_names_domains = set()
for index, row in df_domains.iterrows():
    if isinstance(row['Aces'], list):
        for ace in row['Aces']:
            if 'RightName' in ace:
                right_names_domains.add(ace['RightName'])

print(list(right_names_domains))

['WriteOwner', 'AllExtendedRights', 'GetChangesAll', 'Owns', 'GenericAll', 'GetChanges', 'WriteDacl', 'GenericWrite', 'GetChangesInFilteredSet']

In [118]:
# prompt: find a complete unique list from right_names_domains, right_names_users, right_names_groups, right_names_computers and right_names_ous

# Combine all sets into one
all_right_names = right_names_domains.union(right_names_users, right_names_groups, right_names_computers, right_names_ous)

# Convert the combined set back to a list for easier viewing
unique_right_names_list = list(all_right_names)

unique_right_names_list

['WriteOwner',
 'AllExtendedRights',
 'GetChangesAll',
 'Owns',
 'GenericAll',
 'GetChanges',
 'WriteDacl',
 'GenericWrite',
 'GetChangesInFilteredSet',
 'AddKeyCredentialLink',
 'WriteAccountRestrictions']

In [119]:
# prompt: how do i add a weight value to the unique_right_names_list

# Create a dictionary to store weights for each right name
weight_dict = {
    'WriteOwner': 10,
    'AllExtendedRights': 10,
    'GetChangesAll': 2,
    'Owns': 10,
    'GenericAll': 10,
    'GetChanges': 2,
    'WriteDacl': 10,
    'GenericWrite':8,
    'GetChangesInFilteredSet': 5,
    'AddKeyCredentialLink': 5,
    'WriteAccountRestrictions': 5

    # Add more right names and their corresponding weights as needed
}

# Add a 'Weight' column to the unique_right_names_list
weighted_right_names = []
for right_name in unique_right_names_list:
    weight = weight_dict.get(right_name, 0) # Default weight is 0 if not found in the dictionary
    weighted_right_names.append({'RightName': right_name, 'Weight': weight})

weighted_right_names

[{'RightName': 'WriteOwner', 'Weight': 10},
 {'RightName': 'AllExtendedRights', 'Weight': 10},
 {'RightName': 'GetChangesAll', 'Weight': 2},
 {'RightName': 'Owns', 'Weight': 10},
 {'RightName': 'GenericAll', 'Weight': 10},
 {'RightName': 'GetChanges', 'Weight': 2},
 {'RightName': 'WriteDacl', 'Weight': 10},
 {'RightName': 'GenericWrite', 'Weight': 8},
 {'RightName': 'GetChangesInFilteredSet', 'Weight': 5},
 {'RightName': 'AddKeyCredentialLink', 'Weight': 5},
 {'RightName': 'WriteAccountRestrictions', 'Weight': 5}]

In [121]:
# prompt: i now want to add a weight column to the Aces in each df_groups, df_users, df_ous, df_domains with the values in weighted_right_names

def add_weight_column(df, weighted_right_names):
    """Adds a 'Weight' column to the 'Aces' entries in a DataFrame based on weighted_right_names."""

    def assign_weight(aces_list):
        weight_mapping = {item['RightName']: item['Weight'] for item in weighted_right_names}
        for ace_dict in aces_list:
            ace_dict['Weight'] = weight_mapping.get(ace_dict.get('RightName'), 0)
        return aces_list

    if 'Aces' in df.columns:
        df['Aces'] = df['Aces'].apply(assign_weight)
    return df

# Example usage (assuming you have df_groups, df_users, df_ous, df_domains defined):
df_groups = add_weight_column(df_groups, weighted_right_names)
df_users = add_weight_column(df_users, weighted_right_names)
df_ous = add_weight_column(df_ous, weighted_right_names)
df_domains = add_weight_column(df_domains, weighted_right_names)
df_computers = add_weight_column(df_computers, weighted_right_names)

In [124]:
pd.set_option("display.max_colwidth", None)
df_groups['Aces'].head(5)

0    [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-4186', 'PrincipalType': 'Computer', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '392C4A7E0D8B7EC4B23FD5BDE1D092960F530B21', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3962', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1BD7F69D2DFAE3A61C3C143E10ED151506F261F5', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '16FF7EF99D5872999C3CECD6866A2CBD16F2FD72', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3745', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'DDBBDF8654F2B8211312734E18CCBC44EDBF8CC3', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-4003', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '4DF93C1C09EEC67F28261E84EC01FB6392442487', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]
Name: Aces, dtype: object

In [125]:
pd.set_option("display.max_colwidth", None)
df_users['Aces'].head(5)

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05', 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636', 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-4111', 'PrincipalType': 'Computer', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1F8DAFA385A8ABF0E8219284874F4F1BB014028E', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2337', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'B06E43F451E2DD08AEF151837CD59C66B7458ED9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1632', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F096D3004C3AD04F643D5D44271E33B473197D96', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3782', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2D9EF6BA0BE9DE6436094FC958AF962D9F5D5BC7', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1757', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'E082BB29AF57AA93B8BA76177EBC2E458547707D', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}]

In [126]:
pd.set_option("display.max_colwidth", None)
df_ous['Aces'].head(5)

0    [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
1                                                                                                                                                                                                                                                                                                                                                                        [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
2                                                                                                                                                                                                                                                                                                                                                                        [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
3                                                                                                                                                                                                                                                                                                                                                                        [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
4                                                                                                                                                                                                                                                                                                                                                                        [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'Weight': 8}]
Name: Aces, dtype: object

In [127]:
pd.set_option("display.max_colwidth", None)
df_domains['Aces'].head(5)

0    [{'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'AllExtendedRights', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 8}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-9', 'PrincipalType': 'Group', 'RightName': 'GetChangesInFilteredSet', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 5}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-9', 'PrincipalType': 'Group', 'RightName': 'GetChanges', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 2}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GetChangesAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 2}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GetChangesInFilteredSet', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 5}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GetChanges', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 2}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-498', 'PrincipalType': 'Group', 'RightName': 'GetChanges', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 2}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-516', 'PrincipalType': 'Group', 'RightName': 'GetChangesAll', 'IsInherited': False, 'InheritanceHash': '', 'Weight': 2}]
Name: Aces, dtype: object

In [128]:
pd.set_option("display.max_colwidth", None)
df_computers['Aces'].head(5)

0    [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'weight': 10, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteAccountRestrictions', 'IsInherited': False, 'InheritanceHash': '', 'weight': 7, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3022', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '7A7131FAC4956E4EF34FF39BC7F0A2B8BD71044D', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3769', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53F21117DAED7A85F768663DE6BE35B3B9A62039', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2571', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F42C65357510DD280974B81C50F9E28EEC1B81BD', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-4186', 'PrincipalType': 'Computer', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '7B2B44411944F26D8DD15971427B2E07E320202D', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05', 'weight': 5, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636', 'weight': 5, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '9CEAE3A7CE96082F102326F4F621051F3494E681', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EFD612D2FDDBD09C9B50499A333DF166E98516E3', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '249B74BB71A514FA64267D87B4F6A777E301AF04', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F0A68415F9DB3629EE891DB15746B1ACE04ADAE8', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'A8271C611A640CBFAE0E791B9219651437841D4D', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 10, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 9, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 5, 'Weight': 8}]
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'weight': 10, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteAccountRestrictions', 'IsInherited': False, 'InheritanceHash': '', 'weight': 7, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '9CEAE3A7CE96082F102326F4F621051F3494E681', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3940', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'DB059EA66E77513649B83715D95A28ECA94164BA', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3310', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '141C86F79B6DD045A368EF00694556F7673996C7', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05', 'weight': 5, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636', 'weight': 5, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EFD612D2FDDBD09C9B50499A333DF166E98516E3', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '249B74BB71A514FA64267D87B4F6A777E301AF04', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F0A68415F9DB3629EE891DB15746B1ACE04ADAE8', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'A8271C611A640CBFAE0E791B9219651437841D4D', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 10, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 9, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 5, 'Weight': 8}]
2        [{'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'Owns', 'IsInherited': False, 'InheritanceHash': '', 'weight': 10, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-548', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': False, 'InheritanceHash': '', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-512', 'PrincipalType': 'Group', 'RightName': 'WriteAccountRestrictions', 'IsInherited': False, 'InheritanceHash': '', 'weight': 7, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2624', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EB29650D3F9DA5CB6CE62428EBD27B433048F10A', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1425', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'FD26E9B0CCE3D973F1B708576E16D8BC5857ECC1', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3710', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F8BF75715A4D3EA4BDAB388DC820D022F80F1460', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1963', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '74298907990C3446304B447D32D9755D488897A3', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-526', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': 'D94A9B0FCD0C866F6DF0AF15267D5F8B30540C05', 'weight': 5, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-527', 'PrincipalType': 'Group', 'RightName': 'AddKeyCredentialLink', 'IsInherited': True, 'InheritanceHash': '211865054F5764B5BF635446923A438F220E8636', 'weight': 5, 'Weight': 5}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1539', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '9CEAE3A7CE96082F102326F4F621051F3494E681', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'EFD612D2FDDBD09C9B50499A333DF166E98516E3', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-2167', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '249B74BB71A514FA64267D87B4F6A777E301AF04', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1723', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'F0A68415F9DB3629EE891DB15746B1ACE04ADAE8', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-1471', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': 'A8271C611A640CBFAE0E791B9219651437841D4D', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-519', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '2F0A9A0646E6604C2B6894926F09E51DBA3F5583', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3600', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '53D3D840937EF1063F743F1D7C43F642B95F1D41', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3890', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '6AAAE7B1A84D5B966BCE19190377A48DBB4CFD78', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3635', 'PrincipalType': 'Group', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '20671B850928AD1D86E5C695CBFB97E5895572E9', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'S-1-5-21-1333368235-828418111-1849936505-3476', 'PrincipalType': 'User', 'RightName': 'GenericAll', 'IsInherited': True, 'InheritanceHash': '1948CC71A78F62D58398E26A062EF44E559C2437', 'weight': 8, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteDacl', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 10, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'WriteOwner', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 9, 'Weight': 10}, {'PrincipalSID': 'MYLAB.LOCAL-S-1-5-32-544', 'PrincipalType': 'Group', 'RightName': 'GenericWrite', 'IsInherited': True, 'InheritanceHash': '62C26D4FB3FF64505B03CDD35D648DFBC6C157CC', 'weight': 5, 'Weight': 8}]