<a href="https://colab.research.google.com/github/markajbell/BH/blob/main/Stats.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Imports

In [1]:
import pandas as pd
import json
import os
import glob

Set the Path to the Data location (imported form SharpHound)

# Set the Path
to the Data location (imported from SharpHound) and Read json files in folder and create a dictionary with the entire data.

In [2]:
#@title Download lab files
# from IPython.display import clear_output
# if not os.path.exists("/content/mylab"):
#   print("Downloading lab files...")
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_computers.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_containers.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_domains.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_gpos.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_groups.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_ous.json
#  !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab/20250316212118_users.json
#   !wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/mylab.zip
#   !unzip mylab.zip -d mylab
#   clear_output()
#   print("Done")
!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/adsync/secure.json
#!wget https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/adsync/secure10k.json
# else:
#   print("Lab files already downloaded")
!mkdir = "/content/adsync"
!mv secure.json /content/adsync
#!mv secure10k.json /content/adsync

path = "/content/adsync"
data = {}
json_files = glob.glob(os.path.join(path, "*.json"))
for file in json_files:
    filename = os.path.basename(file).replace(".json", "")
    suf = filename.split("_")[-1]

    with open(file, 'r', encoding='utf-8') as f:
        content = json.load(f)

    if "data" in content:
        if suf in data:
            data[f"{suf}"].extend(content["data"])
            #print(f" The key 'data' was found in {f}.")
        else:
            data[f"{suf}"] = content["data"]
            #print(f" The key 'data' was found in {f}.")
    else:
        print(f"Warning: The key 'data' was not found in {f}.")

--2025-07-13 12:35:45--  https://raw.githubusercontent.com/markajbell/BH/refs/heads/main/adsync/secure.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1314149 (1.3M) [text/plain]
Saving to: ‘secure.json’

secure.json         100%[===================>]   1.25M  --.-KB/s    in 0.08s

2025-07-13 12:35:46 (15.2 MB/s) - ‘secure.json’ saved [1314149/1314149]

Show the "content"

In [3]:
content

{'data': [{'id': '0',
   'labels': ['Base', 'Domain'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'MARK.LOCAL',
    'highvalue': True,
    'objectid': 'S-1-5-21-883232822-274137685-4173207997',
    'distinguishedname': 'DC=MARK,DC=LOCAL',
    'functionallevel': '2012',
    'owned': False},
   'type': 'node'},
  {'id': '1',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'Admin@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-cdca22b1-d164-4ec1-8233-45c0ea9044ac',
    'distinguishedname': 'OU=ADMIN,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '2',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'Tier 1 Servers@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d49f51-1ea3-4d9c-93a1-0b591b59c7e9',
    'distinguishedname': 'OU=TIER 1 SERVERS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '3',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'Tier 2@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-5de20ac8-e7ff-4f05-b597-268af392400e',
    'distinguishedname': 'OU=TIER 2,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '4',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T0 Admin@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-f249f685-d5e0-4dad-b5b5-7f723c41ca1e',
    'distinguishedname': 'OU=T0 ADMIN,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '5',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T1 Admin@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-8355af01-1b4e-48c8-8977-a53870b2770b',
    'distinguishedname': 'OU=T1 ADMIN,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '6',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Admin@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-e4602f9d-12bf-4f9e-b667-f6ccd27fae90',
    'distinguishedname': 'OU=T2 ADMIN,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '7',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T0 Admin Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-c0fb853d-9b96-449b-b25c-4d20a1c02e5f',
    'distinguishedname': 'OU=T0 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '8',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T0 Admin Devices@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-b9fd1aed-b3e6-4d53-9242-b85ff389822f',
    'distinguishedname': 'OU=T0 ADMIN DEVICES,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '9',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T0 Admin Groups@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-cd13b9d6-76ca-4b5c-82bd-2d86bef8a375',
    'distinguishedname': 'OU=T0 ADMIN GROUPS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '10',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T0 Admin Service Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-58cd5b4f-82db-4cd1-a3f4-08661c9c53d2',
    'distinguishedname': 'OU=T0 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '11',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T1 Admin Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-73c7c626-6665-4f12-9cdf-c42ab0282573',
    'distinguishedname': 'OU=T1 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '12',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T1 Admin Devices@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-5c1f7a53-4d89-45c5-a182-d42f7a3bd15c',
    'distinguishedname': 'OU=T1 ADMIN DEVICES,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '13',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T1 Admin Groups@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-dc73f46b-2d1b-416f-87d1-783e91a30bfe',
    'distinguishedname': 'OU=T1 ADMIN GROUPS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '14',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T1 Admin Service Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-c703aa33-871c-4893-a8db-437a731598e9',
    'distinguishedname': 'OU=T1 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '15',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Admin Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-61c17d81-4eb2-4829-94e7-c7ddd6ecd193',
    'distinguishedname': 'OU=T2 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '16',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Admin Devices@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-5305b84a-5f72-4ee8-9726-81485bc11905',
    'distinguishedname': 'OU=T2 ADMIN DEVICES,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '17',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Admin Groups@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-508809b7-63d4-4f53-8376-b31aa66c0af6',
    'distinguishedname': 'OU=T2 ADMIN GROUPS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '18',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Admin Service Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-e7679546-c753-4556-889a-67fd84f9d165',
    'distinguishedname': 'OU=T2 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '19',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'Application@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-c8fbc840-cc56-4337-aa2c-31984398cf7f',
    'distinguishedname': 'OU=APPLICATION,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '20',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'Print@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-70355ec3-a132-4ec7-b4c7-f7cdfb011b59',
    'distinguishedname': 'OU=PRINT,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '21',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'Database@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-bee8279d-bcc2-427c-827c-510159969430',
    'distinguishedname': 'OU=DATABASE,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '22',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Groups@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d13355-d2f9-45cf-9ee6-fdc8230ae4e5',
    'distinguishedname': 'OU=T2 GROUPS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '23',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Workstations@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-66aadca5-ccbc-46d4-91e7-f74f2527bdb5',
    'distinguishedname': 'OU=T2 WORKSTATIONS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '24',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 User Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-d4c0667d-16e8-4afd-8cf3-5f6a900f6913',
    'distinguishedname': 'OU=T2 USER ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '25',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Servers@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-3f1588f2-5124-4111-8d63-caf4b57a87ca',
    'distinguishedname': 'OU=T2 SERVERS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '26',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Enabled User Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-dd1b08e8-140d-49e3-ab56-1551c008827a',
    'distinguishedname': 'OU=T2 ENABLED USER ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '27',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Disabled User Accounts@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-9c9959e1-1718-4648-9aa1-e0eb9920d50c',
    'distinguishedname': 'OU=T2 DISABLED USER ACCOUNTS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '28',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Workstations AL@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-5bde0576-c8a8-4759-9b5b-2aad73322f0f',
    'distinguishedname': 'OU=T2 WORKSTATIONS AL,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '29',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Workstations AK@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-ce3180b3-27c3-47a5-882f-6f19301ba3a4',
    'distinguishedname': 'OU=T2 WORKSTATIONS AK,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '30',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Workstations AZ@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-7045f1c8-5a9f-4e7c-8021-a02856b9f945',
    'distinguishedname': 'OU=T2 WORKSTATIONS AZ,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '31',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Distribution Groups@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-c0859a15-e2ab-4416-b2cc-b5b6847ed589',
    'distinguishedname': 'OU=T2 DISTRIBUTION GROUPS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '32',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Security Groups@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-6b597066-2149-4c6f-ac8a-d1c0bf893550',
    'distinguishedname': 'OU=T2 SECURITY GROUPS,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '33',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Servers AL@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-c781d32b-68c2-434f-ac00-3fa1a6d24059',
    'distinguishedname': 'OU=T2 SERVERS AL,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '34',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Servers AK@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-fa615a1f-deb6-4b6d-8bde-89f22e88b725',
    'distinguishedname': 'OU=T2 SERVERS AK,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '35',
   'labels': ['Base', 'OU'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'T2 Servers AZ@MARK.LOCAL',
    'objectid': 'S-1-5-21-883232822-274137685-4173207997-6a528ecf-4ea6-43f4-8285-b77fc0dfc004',
    'distinguishedname': 'OU=T2 SERVERS AZ,DC=MARK,DC=LOCAL',
    'description': None,
    'highvalue': False,
    'blocksInheritance': False,
    'owned': False},
   'type': 'node'},
  {'id': '36',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'ADMINISTRATORS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-544',
    'highvalue': True,
    'distinguishedname': 'CN=Administrators,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Administrators have complete and unrestricted access to the computer/domain',
    'admincount': True,
    'owned': False},
   'type': 'node'},
  {'id': '37',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'REMOTE DESKTOP USERS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-555',
    'highvalue': False,
    'distinguishedname': 'CN=Remote Desktop Users,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members in this group are granted the right to logon remotely',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '38',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'PRINT OPERATORS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-550',
    'highvalue': True,
    'distinguishedname': 'CN=Print Operators,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members can administer printers installed on domain controllers',
    'admincount': True,
    'owned': False},
   'type': 'node'},
  {'id': '39',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'IIS_IUSRS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-568',
    'highvalue': False,
    'distinguishedname': 'CN=IIS_IUSRS,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Built-in group used by Internet Information Services.',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '40',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'BACKUP OPERATORS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-551',
    'highvalue': True,
    'distinguishedname': 'CN=Backup Operators,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Backup Operators can override security restrictions for the sole purpose of backing up or restoring files',
    'admincount': True,
    'owned': False},
   'type': 'node'},
  {'id': '41',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'NETWORK CONFIGURATION OPERATORS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-556',
    'highvalue': False,
    'distinguishedname': 'CN=Network Configuration Operators,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members in this group can have some administrative privileges to manage configuration of networking features',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '42',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'PERFORMANCE MONITOR USERS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-558',
    'highvalue': False,
    'distinguishedname': 'CN=Performance Monitor Users,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members of this group can access performance counter data locally and remotely',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '43',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'REPLICATORS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-552',
    'highvalue': False,
    'distinguishedname': 'CN=Replicator,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Supports file replication in a domain',
    'admincount': True,
    'owned': False},
   'type': 'node'},
  {'id': '44',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'DISTRIBUTED COM USERS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-562',
    'highvalue': False,
    'distinguishedname': 'CN=Distributed COM Users,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members are allowed to launch, activate and use Distributed COM objects on this machine.',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '45',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'PERFORMANCE LOG USERS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-559',
    'highvalue': False,
    'distinguishedname': 'CN=Performance Log Users,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members of this group may schedule logging of performance counters, enable trace providers, and collect event traces both locally and via remote access to this computer',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '46',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'CRYPTOGRAPHIC OPERATORS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-569',
    'highvalue': False,
    'distinguishedname': 'CN=Cryptographic Operators,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members are authorized to perform cryptographic operations.',
    'admincount': False,
    'owned': False},
   'type': 'node'},
  {'id': '47',
   'labels': ['Base', 'Group'],
   'properties': {'domain': 'MARK.LOCAL',
    'name': 'EVENT LOG READERS@MARK.LOCAL',
    'objectid': 'MARK.LOCAL-S-1-5-32-573',
    'highvalue': False,
    'distinguishedname': 'CN=Event Log Readers,CN=Builtin,DC=MARK,DC=LOCAL',
    'description': 'Members of this group can read event logs from local machine',
    'admincount': False,

In [4]:
# prompt: from data['secure'] get the type column

# try:
#   secure_types = [item['type'] for item in data[suf]]
#   print(secure_types)
# except KeyError:
#   print("The key 'secure' was not found in the data dictionary.")
# except TypeError:
#   print("The value for 'secure' is not a list of dictionaries.")

In [5]:
# prompt: if the type column = "node" save that record into a pandas dataframe called nodes, if the type = "relationship' then save to a pandas dataframe called edges

import pandas as pd
df = pd.DataFrame(data[suf])
nodes = df[df['type'] == 'node'].copy()
edges = df[df['type'] == 'relationship'].copy()

In [6]:
# prompt: convert id in nodes to int

nodes['id'] = nodes['id'].astype(int)
#nodes.head()

In [7]:
nodes['id'].dtype

dtype('int64')

In [8]:
# prompt: show all rows

import pandas as pd
pd.set_option('display.max_rows', None)

In [9]:
# prompt: for every record in "nodes" create a l1, l2 and l3 column for the values in "nodes.labels" eg. for record 1 l1=Base, l2=OU and l3 would be null

import pandas as pd
def extract_labels(labels):
    # Ensure labels is a list
    if not isinstance(labels, list):
        return [None, None, None]

    l1 = labels[0] if len(labels) > 0 else None
    l2 = labels[1] if len(labels) > 1 else None
    l3 = labels[2] if len(labels) > 2 else None
    return [l1, l2, l3]

# Apply the function to create the new columns
nodes[['l1', 'l2', 'l3']] = nodes['labels'].apply(lambda x: pd.Series(extract_labels(x)))

#nodes.head()

In [10]:
# prompt: show me records where l3 ne "None"

nodes[nodes['l3'].notna()]

,id,labels,properties,type,start,end,label,l1,l2,l3
71,71,"[Base, Group, User]","{'domain': 'MARK.LOCAL', 'name': 'DMAPLE00091@...",node,NaN,NaN,NaN,Base,Group,User
83,83,"[Base, Group, User]","{'domain': 'MARK.LOCAL', 'name': 'MHONNETTE000...",node,NaN,NaN,NaN,Base,Group,User
396,396,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised
425,425,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised
428,428,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised
450,450,"[Base, User, Compromised]","{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,NaN,NaN,NaN,Base,User,Compromised

In [11]:
# prompt: remove the following columns from nodes:
# start, end, label

nodes = nodes.drop(columns=['start', 'end', 'label', 'labels'])
#nodes.head()

In [12]:
#edges.tail()

In [13]:
# prompt: remove the "labels" column from edges

edges = edges.drop(columns=['labels'])
#edges.head()

Expand "Properties" column in new columns.

Convert to Dict

In [14]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

#nodes

In [15]:
#edges = edges.drop(columns=['id'])
import numpy as np
edges['id'] = np.arange(len(edges)).astype('int64')
edges.head()
edges['id'].dtype

dtype('int64')

In [16]:
# prompt: save the df_compuers as json to content

import json

# Assuming df_computers is already defined as in your provided code.

# Convert the DataFrame to a JSON string.
nodes_json = nodes.to_json(orient='records')

# Save the JSON string to a file named 'content.json'.
with open('nodes.json', 'w') as f:
  f.write(nodes_json)

In [17]:
# prompt: save the df_compuers as json to content

import json

# Assuming df_computers is already defined as in your provided code.

# Convert the DataFrame to a JSON string.
edges_json = edges.to_json(orient='records')

# Save the JSON string to a file named 'content.json'.
with open('edges.json', 'w') as f:
  f.write(edges_json)

In [18]:
# prompt: create a new column in nodes called weight

nodes['weight'] = 1

In [19]:
# prompt: create a list of all id from nodes where "highvalue" = true

# Before accessing 'Properties', check if the column exists in the DataFrame.
if 'properties' in nodes.columns:
    # Use .loc to avoid SettingWithCopyWarning and access the nested 'highvalue' key
    # We use a lambda function with .apply to safely access nested dictionary keys.
    high_value_node_ids = nodes[nodes['properties'].apply(lambda x: x.get('highvalue', False) == True)]['id'].tolist()
    print(high_value_node_ids)
else:
    print("Error: The 'Properties' column was not found in the nodes DataFrame.")

[0, 36, 38, 40, 59, 60, 65, 66, 72, 75, 90, 91, 92, 93, 94, 95, 96, 97, 98, 288, 289, 291, 293, 294, 295, 296, 297, 299, 301, 302, 303, 304, 305, 306, 307, 308, 309, 311, 312, 313, 314, 315, 318, 319, 320, 321, 322, 323, 324, 491, 501, 507, 508, 509, 511, 512, 514, 521, 523, 527, 530, 531, 532, 533, 534, 539, 544, 548, 550, 553, 557, 561, 562, 563, 564, 565, 567, 573, 575, 577, 585, 590, 597, 599, 600, 603, 607, 609, 610, 620, 623, 624, 625, 626, 631, 632, 637, 638, 639, 640, 645, 648, 649, 650, 651, 653, 654, 655, 656, 660, 661, 663, 665, 666, 668, 672, 673, 676, 677, 681, 684, 692, 693, 694]

In [20]:
len(high_value_node_ids)

124

In [21]:
# prompt: if node[id] = value in high_value_nodes_ids assign a weight of 20

for value in high_value_node_ids:
    nodes.loc[nodes['id'] == value, 'weight'] = 20

In [22]:
# prompt: show me nodes records where weight = 20

nodes[nodes['weight'] == 20]

,id,properties,type,l1,l2,l3,weight
0,0,"{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL',...",node,Base,Domain,None,20
36,36,"{'domain': 'MARK.LOCAL', 'name': 'ADMINISTRATO...",node,Base,Group,None,20
38,38,"{'domain': 'MARK.LOCAL', 'name': 'PRINT OPERAT...",node,Base,Group,None,20
40,40,"{'domain': 'MARK.LOCAL', 'name': 'BACKUP OPERA...",node,Base,Group,None,20
59,59,"{'domain': 'MARK.LOCAL', 'name': 'SERVER OPERA...",node,Base,Group,None,20
60,60,"{'domain': 'MARK.LOCAL', 'name': 'ACCOUNT OPER...",node,Base,Group,None,20
65,65,"{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE A...",node,Base,Group,None,20
66,66,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN ADMIN...",node,Base,Group,None,20
72,72,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN CONTR...",node,Base,Group,None,20
75,75,"{'domain': 'MARK.LOCAL', 'name': 'GROUP POLICY...",node,Base,Group,None,20
90,90,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Acc...",node,Base,Group,None,20
91,91,"{'domain': 'MARK.LOCAL', 'name': 'T1 PAW Maint...",node,Base,Group,None,20
92,92,"{'domain': 'MARK.LOCAL', 'name': 'T1 Server Ma...",node,Base,Group,None,20
93,93,"{'domain': 'MARK.LOCAL', 'name': 'T1 Service A...",node,Base,Group,None,20
94,94,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Acc...",node,Base,Group,None,20
95,95,"{'domain': 'MARK.LOCAL', 'name': 'T2 PAW Maint...",node,Base,Group,None,20
96,96,"{'domain': 'MARK.LOCAL', 'name': 'T2 Server Ma...",node,Base,Group,None,20
97,97,"{'domain': 'MARK.LOCAL', 'name': 'T2 Service A...",node,Base,Group,None,20
98,98,"{'domain': 'MARK.LOCAL', 'name': 'Group Policy...",node,Base,Container,None,20
288,288,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
289,289,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
291,291,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
293,293,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
294,294,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
295,295,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
296,296,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
297,297,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
299,299,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
301,301,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
302,302,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
303,303,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
304,304,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
305,305,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
306,306,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
307,307,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
308,308,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
309,309,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
311,311,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
312,312,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
313,313,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
314,314,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
315,315,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
318,318,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
319,319,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
320,320,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
321,321,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
322,322,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
323,323,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
324,324,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...",node,Base,User,None,20
491,491,"{'name': 'S-00000@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
501,501,"{'name': 'S-00001@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
507,507,"{'name': 'S-00002@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
508,508,"{'name': 'PAW-00000@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
509,509,"{'name': 'S-00003@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
511,511,"{'name': 'S-00004@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
512,512,"{'name': 'S-00005@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
514,514,"{'name': 'S-00006@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
521,521,"{'name': 'S-00007@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
523,523,"{'name': 'S-00008@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
527,527,"{'name': 'PAW-00001@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
530,530,"{'name': 'PAW-00002@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
531,531,"{'name': 'PAW-00003@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
532,532,"{'name': 'PAW-00004@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
533,533,"{'name': 'S-00009@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
534,534,"{'name': 'S-00010@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
539,539,"{'name': 'PAW-00005@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
544,544,"{'name': 'S-00011@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
548,548,"{'name': 'S-00012@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
550,550,"{'name': 'PAW-00006@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
553,553,"{'name': 'PAW-00007@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
557,557,"{'name': 'S-00013@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
561,561,"{'name': 'PAW-00008@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
562,562,"{'name': 'S-00014@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
563,563,"{'name': 'S-00015@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
564,564,"{'name': 'S-00016@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
565,565,"{'name': 'S-00017@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
567,567,"{'name': 'PAW-00009@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
573,573,"{'name': 'S-00018@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
575,575,"{'name': 'S-00019@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
577,577,"{'name': 'S-00020@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
585,585,"{'name': 'S-00021@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
590,590,"{'name': 'S-00022@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
597,597,"{'name': 'PAW-00010@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
599,599,"{'name': 'S-00023@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
600,600,"{'name': 'S-00024@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
603,603,"{'name': 'S-00025@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
607,607,"{'name': 'PAW-00011@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
609,609,"{'name': 'PAW-00012@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
610,610,"{'name': 'PAW-00013@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
620,620,"{'name': 'S-00026@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
623,623,"{'name': 'S-00027@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
624,624,"{'name': 'PAW-00014@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
625,625,"{'name': 'PAW-00015@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
626,626,"{'name': 'S-00028@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
631,631,"{'name': 'PAW-00016@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
632,632,"{'name': 'PAW-00017@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
637,637,"{'name': 'PAW-00018@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
638,638,"{'name': 'S-00029@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
639,639,"{'name': 'S-00030@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
640,640,"{'name': 'PAW-00019@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
645,645,"{'name': 'PAW-00020@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
648,648,"{'name': 'S-00031@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
649,649,"{'name': 'S-00032@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
650,650,"{'name': 'S-00033@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
651,651,"{'name': 'S-00034@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
653,653,"{'name': 'PAW-00021@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
654,654,"{'name': 'S-00035@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
655,655,"{'name': 'PAW-00022@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
656,656,"{'name': 'S-00036@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
660,660,"{'name': 'PAW-00023@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
661,661,"{'name': 'PAW-00024@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
663,663,"{'name': 'PAW-00025@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
665,665,"{'name': 'S-00037@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
666,666,"{'name': 'S-00038@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
668,668,"{'name': 'S-00039@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
672,672,"{'name': 'S-00040@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
673,673,"{'name': 'S-00041@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
676,676,"{'name': 'PAW-00026@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
677,677,"{'name': 'S-00042@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
681,681,"{'name': 'PAW-00027@MARK.LOCAL', 'operatingsys...",node,Base,Computer,None,20
684,684,"{'name': 'S-00043@MARK.LOCAL', 'operatingsyste...",node,Base,Computer,None,20
692,692,"{'domain': 'MARK.LOCAL', 'name': 'T0 DEFAULT A...",node,Base,User,None,20
693,693,"{'domain': 'MARK.LOCAL', 'name': 'T1 DEFAULT A...",node,Base,User,None,20
694,694,"{'domain': 'MARK.LOCAL', 'name': 'T2 DEFAULT A...",node,Base,User,None,20

In [23]:
len(nodes[nodes['weight'] == 20])

124

In [24]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
pd.set_option('display.max_colwidth', None)

#nodes.tail(50)

In [25]:
# prompt: print all nodes where weight==20

#print(nodes[nodes['weight'] == 20])

In [26]:
len(nodes)

1297

In [27]:
# prompt: show me records where nodes['properties']['distinguishedname']  does not contain "T2", "T1" or "T0"

# Filter nodes where 'distinguishedname' in 'properties' does not contain "T2", "T1", or "T0"
filtered_nodes = nodes[
    nodes['properties'].apply(
        lambda x: 'distinguishedname' in x and
                  'T2' not in x['distinguishedname'] and
                  'T1' not in x['distinguishedname'] and
                  'T0' not in x['distinguishedname'] and
                  'Tier 0' not in x['distinguishedname'] and
                  'Tier 1' not in x['distinguishedname'] and
                  'Tier 2' not in x['distinguishedname'] and
                  'TIER 0' not in x['distinguishedname'] and
                  'TIER 1' not in x['distinguishedname'] and
                  'TIER 2' not in x['distinguishedname']
    )
]

filtered_nodes

,id,properties,type,l1,l2,l3,weight
0,0,"{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL', 'highvalue': True, 'objectid': 'S-1-5-21-883232822-274137685-4173207997', 'distinguishedname': 'DC=MARK,DC=LOCAL', 'functionallevel': '2012', 'owned': False}",node,Base,Domain,None,20
1,1,"{'domain': 'MARK.LOCAL', 'name': 'Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-cdca22b1-d164-4ec1-8233-45c0ea9044ac', 'distinguishedname': 'OU=ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
19,19,"{'domain': 'MARK.LOCAL', 'name': 'Application@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c8fbc840-cc56-4337-aa2c-31984398cf7f', 'distinguishedname': 'OU=APPLICATION,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
20,20,"{'domain': 'MARK.LOCAL', 'name': 'Print@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-70355ec3-a132-4ec7-b4c7-f7cdfb011b59', 'distinguishedname': 'OU=PRINT,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
21,21,"{'domain': 'MARK.LOCAL', 'name': 'Database@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-bee8279d-bcc2-427c-827c-510159969430', 'distinguishedname': 'OU=DATABASE,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
36,36,"{'domain': 'MARK.LOCAL', 'name': 'ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-544', 'highvalue': True, 'distinguishedname': 'CN=Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Administrators have complete and unrestricted access to the computer/domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
37,37,"{'domain': 'MARK.LOCAL', 'name': 'REMOTE DESKTOP USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-555', 'highvalue': False, 'distinguishedname': 'CN=Remote Desktop Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members in this group are granted the right to logon remotely', 'admincount': False, 'owned': False}",node,Base,Group,None,1
38,38,"{'domain': 'MARK.LOCAL', 'name': 'PRINT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-550', 'highvalue': True, 'distinguishedname': 'CN=Print Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer printers installed on domain controllers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
39,39,"{'domain': 'MARK.LOCAL', 'name': 'IIS_IUSRS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-568', 'highvalue': False, 'distinguishedname': 'CN=IIS_IUSRS,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Built-in group used by Internet Information Services.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
40,40,"{'domain': 'MARK.LOCAL', 'name': 'BACKUP OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-551', 'highvalue': True, 'distinguishedname': 'CN=Backup Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Backup Operators can override security restrictions for the sole purpose of backing up or restoring files', 'admincount': True, 'owned': False}",node,Base,Group,None,20
41,41,"{'domain': 'MARK.LOCAL', 'name': 'NETWORK CONFIGURATION OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-556', 'highvalue': False, 'distinguishedname': 'CN=Network Configuration Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members in this group can have some administrative privileges to manage configuration of networking features', 'admincount': False, 'owned': False}",node,Base,Group,None,1
42,42,"{'domain': 'MARK.LOCAL', 'name': 'PERFORMANCE MONITOR USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-558', 'highvalue': False, 'distinguishedname': 'CN=Performance Monitor Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can access performance counter data locally and remotely', 'admincount': False, 'owned': False}",node,Base,Group,None,1
43,43,"{'domain': 'MARK.LOCAL', 'name': 'REPLICATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-552', 'highvalue': False, 'distinguishedname': 'CN=Replicator,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Supports file replication in a domain', 'admincount': True, 'owned': False}",node,Base,Group,None,1
44,44,"{'domain': 'MARK.LOCAL', 'name': 'DISTRIBUTED COM USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-562', 'highvalue': False, 'distinguishedname': 'CN=Distributed COM Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members are allowed to launch, activate and use Distributed COM objects on this machine.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
45,45,"{'domain': 'MARK.LOCAL', 'name': 'PERFORMANCE LOG USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-559', 'highvalue': False, 'distinguishedname': 'CN=Performance Log Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group may schedule logging of performance counters, enable trace providers, and collect event traces both locally and via remote access to this computer', 'admincount': False, 'owned': False}",node,Base,Group,None,1
46,46,"{'domain': 'MARK.LOCAL', 'name': 'CRYPTOGRAPHIC OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-569', 'highvalue': False, 'distinguishedname': 'CN=Cryptographic Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members are authorized to perform cryptographic operations.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
47,47,"{'domain': 'MARK.LOCAL', 'name': 'EVENT LOG READERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-573', 'highvalue': False, 'distinguishedname': 'CN=Event Log Readers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can read event logs from local machine', 'admincount': False, 'owned': False}",node,Base,Group,None,1
48,48,"{'domain': 'MARK.LOCAL', 'name': 'GUESTS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-546', 'highvalue': False, 'distinguishedname': 'CN=Guests,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Guests have the same access as members of the Users group by default, except for the Guest account which is further restricted', 'admincount': False, 'owned': False}",node,Base,Group,None,1
49,49,"{'domain': 'MARK.LOCAL', 'name': 'SYSTEM MANAGED ACCOUNTS GROUP@MARK.LOCAL', 'objectid': 'S-1-5-32-581', 'highvalue': False, 'distinguishedname': 'CN=System Managed Accounts Group,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group are managed by the system.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
50,50,"{'domain': 'MARK.LOCAL', 'name': 'USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-545', 'highvalue': 'null', 'distinguishedname': 'null', 'description': 'null', 'admincount': 'null', 'owned': False}",node,Base,Group,None,1
51,51,"{'domain': 'MARK.LOCAL', 'name': 'CERTIFICATE SERVICE DCOM ACCESS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-574', 'highvalue': False, 'distinguishedname': 'CN=Certificate Service DCOM Access,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group are allowed to connect to Certification Authorities in the enterprise', 'admincount': False, 'owned': False}",node,Base,Group,None,1
52,52,"{'domain': 'MARK.LOCAL', 'name': 'RDS REMOTE ACCESS SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-575', 'highvalue': False, 'distinguishedname': 'CN=RDS Remote Access Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Servers in this group enable users of RemoteApp programs and personal virtual desktops access to these resources. In Internet-facing deployments, these servers are typically deployed in an edge network. This group needs to be populated on servers running RD Connection Broker. RD Gateway servers and RD Web Access servers used in the deployment need to be in this group.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
53,53,"{'domain': 'MARK.LOCAL', 'name': 'RDS ENDPOINT SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-576', 'highvalue': False, 'distinguishedname': 'CN=RDS Endpoint Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Servers in this group run virtual machines and host sessions where users RemoteApp programs and personal virtual desktops run. This group needs to be populated on servers running RD Connection Broker. RD Session Host servers and RD Virtualization Host servers used in the deployment need to be in this group.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
54,54,"{'domain': 'MARK.LOCAL', 'name': 'RDS MANAGEMENT SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-577', 'highvalue': False, 'distinguishedname': 'CN=RDS Management Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Servers in this group can perform routine administrative actions on servers running Remote Desktop Services. This group needs to be populated on all servers in a Remote Desktop Services deployment. The servers running the RDS Central Management service must be included in this group.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
55,55,"{'domain': 'MARK.LOCAL', 'name': 'HYPER-V ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-578', 'highvalue': False, 'distinguishedname': 'CN=Hyper-V Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group have complete and unrestricted access to all features of Hyper-V.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
56,56,"{'domain': 'MARK.LOCAL', 'name': 'ACCESS CONTROL ASSISTANCE OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-579', 'highvalue': False, 'distinguishedname': 'CN=Access Control Assistance Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can remotely query authorization attributes and permissions for resources on this computer.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
57,57,"{'domain': 'MARK.LOCAL', 'name': 'REMOTE MANAGEMENT USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-580', 'highvalue': False, 'distinguishedname': 'CN=Remote Management Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can access WMI resources over management protocols (such as WS-Management via the Windows Remote Management service). This applies only to WMI namespaces that grant access to the user.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
58,58,"{'domain': 'MARK.LOCAL', 'name': 'CERT PUBLISHERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-517', 'highvalue': False, 'distinguishedname': 'CN=Cert Publishers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are permitted to publish certificates to the directory', 'admincount': False, 'owned': False}",node,Base,Group,None,1
59,59,"{'domain': 'MARK.LOCAL', 'name': 'SERVER OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-549', 'highvalue': True, 'distinguishedname': 'CN=Server Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain servers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
60,60,"{'domain': 'MARK.LOCAL', 'name': 'ACCOUNT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-548', 'highvalue': True, 'distinguishedname': 'CN=Account Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain user and group accounts', 'admincount': True, 'owned': False}",node,Base,Group,None,20
61,61,"{'domain': 'MARK.LOCAL', 'name': 'PRE-WINDOWS 2000 COMPATIBLE ACCESS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-554', 'highvalue': False, 'distinguishedname': 'CN=Pre-Windows 2000 Compatible Access,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'A backward compatibility group which allows read access on all users and groups in the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
62,62,"{'domain': 'MARK.LOCAL', 'name': 'WINDOWS AUTHORIZATION ACCESS GROUP@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-560', 'highvalue': False, 'distinguishedname': 'CN=Windows Authorization Access Group,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group have access to the computed tokenGroupsGlobalAndUniversal attribute on User objects', 'admincount': False, 'owned': False}",node,Base,Group,None,1
63,63,"{'domain': 'MARK.LOCAL', 'name': 'DENIED RODC PASSWORD REPLICATION GROUP@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-572', 'highvalue': False, 'distinguishedname': 'CN=Denied RODC Password Replication Group,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group cannot have their passwords replicated to any read-only domain controllers in the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
64,64,"{'domain': 'MARK.LOCAL', 'name': 'SCHEMA ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-518', 'highvalue': False, 'distinguishedname': 'CN=Schema Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the schema', 'admincount': True, 'owned': False}",node,Base,Group,None,1
65,65,"{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-519', 'highvalue': True, 'distinguishedname': 'CN=Enterprise Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the enterprise', 'admincount': True, 'owned': False}",node,Base,Group,None,20
66,66,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-512', 'highvalue': True, 'distinguishedname': 'CN=Domain Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
67,67,"{'domain': 'MARK.LOCAL', 'name': 'RAS AND IAS SERVERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-553', 'highvalue': False, 'distinguishedname': 'CN=RAS and IAS Servers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Servers in this group can access remote access properties of users', 'admincount': False, 'owned': False}",node,Base,Group,None,1
68,68,"{'domain': 'MARK.LOCAL', 'name': 'INCOMING FOREST TRUST BUILDERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-557', 'highvalue': False, 'distinguishedname': 'CN=Incoming Forest Trust Builders,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can create incoming, one-way trusts to this forest', 'admincount': False, 'owned': False}",node,Base,Group,None,1
69,69,"{'domain': 'MARK.LOCAL', 'name': 'TERMINAL SERVER LICENSE SERVERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-561', 'highvalue': False, 'distinguishedname': 'CN=Terminal Server License Servers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can update user accounts in Active Directory with information about license issuance, for the purpose of tracking and reporting TS Per User CAL usage', 'admincount': False, 'owned': False}",node,Base,Group,None,1
70,70,"{'domain': 'MARK.LOCAL', 'name': 'ALLOWED RODC PASSWORD REPLICATION GROUP@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-571', 'highvalue': False, 'distinguishedname': 'CN=Allowed RODC Password Replication Group,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group can have their passwords replicated to all read-only domain controllers in the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
72,72,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-516', 'highvalue': True, 'distinguishedname': 'CN=Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain controllers in the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
73,73,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN COMPUTERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-515', 'highvalue': False, 'distinguishedname': 'CN=Domain Computers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All workstations and servers joined to the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,1
74,74,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN USERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-513', 'highvalue': False, 'distinguishedname': 'CN=Domain Users,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain users', 'admincount': False, 'owned': False}",node,Base,Group,None,1
75,75,"{'domain': 'MARK.LOCAL', 'name': 'GROUP POLICY CREATOR OWNERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-520', 'highvalue': True, 'distinguishedname': 'CN=Group Policy Creator Owners,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group can modify group policy for the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,20
76,76,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN GUESTS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-514', 'highvalue': False, 'distinguishedname': 'CN=Domain Guests,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain guests', 'admincount': False, 'owned': False}",node,Base,Group,None,1
77,77,"{'domain': 'MARK.LOCAL', 'name': 'READ-ONLY DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-521', 'highvalue': False, 'distinguishedname': 'CN=Read-only Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are Read-Only Domain Controllers in the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,1
78,78,"{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE READ-ONLY DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-498', 'highvalue': False, 'distinguishedname': 'CN=Enterprise Read-only Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are Read-Only Domain Controllers in the enterprise', 'admincount': False, 'owned': False}",node,Base,Group,None,1
79,79,"{'domain': 'MARK.LOCAL', 'name': 'CLONEABLE DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-522', 'highvalue': False, 'distinguishedname': 'CN=Cloneable Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group that are domain controllers may be cloned.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
80,80,"{'domain': 'MARK.LOCAL', 'name': 'PROTECTED USERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-525', 'highvalue': False, 'distinguishedname': 'CN=Protected Users,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group are afforded additional protections against authentication security threats. See http://go.microsoft.com/fwlink/?LinkId=298939 for more information.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
81,81,"{'domain': 'MARK.LOCAL', 'name': 'KEY ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-526', 'highvalue': False, 'distinguishedname': 'CN=Key Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group can perform administrative actions on key objects within the domain.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
82,82,"{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE KEY ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-527', 'highvalue': False, 'distinguishedname': 'CN=Enterprise Key Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members of this group can perform administrative actions on key objects within the forest.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
84,84,"{'domain': 'MARK.LOCAL', 'name': 'STORAGE REPLICA ADMINISTRATORS@MARK.LOCAL', 'objectid': 'S-1-5-32-582', 'highvalue': False, 'distinguishedname': 'CN=Storage Replica Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group have complete and unrestricted access to all features of Storage Replica.', 'admincount': False, 'owned': False}",node,Base,Group,None,1

In [28]:
len(filtered_nodes)

68

In [29]:
# prompt: show all column contents for nodes do not truncate columns

import pandas as pd
pd.set_option('display.max_colwidth', None)
#nodes

In [30]:
# prompt: compile a list of all id's from nodes where distinguishedname contains 'Tier 0' or T0. distinguishedname is a key within the properties column

# tier_0_t0_ids = []
# for index, row in nodes.iterrows():
#     properties = row.get('properties')
#     if properties and isinstance(properties, dict):
#         distinguishedname = properties.get('distinguishedname')
#         if distinguishedname and ('Tier 0' in distinguishedname or 'T0' in distinguishedname or 'TIER 0' in distinguishedname):
#             tier_0_t0_ids.append(row['id'])

# print("tier 0: ", tier_0_t0_ids)
# len_tier0=len(tier_0_t0_ids)
# print(len_tier0)

# tier_1_t0_ids = []
# for index, row in nodes.iterrows():
#     properties = row.get('properties')
#     if properties and isinstance(properties, dict):
#         distinguishedname = properties.get('distinguishedname')
#         if distinguishedname and ('Tier 1' in distinguishedname or 'T1' in distinguishedname or 'TIER 1' in distinguishedname):
#             tier_1_t0_ids.append(row['id'])

# print("tier 1: ",tier_1_t0_ids)
# len_tier1=len(tier_1_t0_ids)
# print(len_tier1)

# tier_2_t0_ids = []
# for index, row in nodes.iterrows():
#     properties = row.get('properties')
#     if properties and isinstance(properties, dict):
#         distinguishedname = properties.get('distinguishedname')
#         if distinguishedname and ('Tier 2' in distinguishedname or 'T2' in distinguishedname or 'TIER 2' in distinguishedname):
#             tier_2_t0_ids.append(row['id'])

# print("tier 2: ",tier_2_t0_ids)
# len_tier2= len(tier_2_t0_ids)
# print(len_tier2)
# total = len_tier0 + len_tier1 + len_tier2
# print("total: ",total)

In [31]:
# prompt: if tier_0_t0_ids isnot high_value_node_ids then append nodeid in a new dataframe called total_tier0

# total_tier0 = []
# for nodeid in tier_0_t0_ids:
#   if nodeid not in high_value_node_ids:
#     total_tier0.append(nodeid)

# print("Nodes in tier_0_t0_ids that are not in high_value_node_ids:", total_tier0)

In [32]:
# prompt: total_tier0 = total_tier0 and appended high_value_node_ids

# total_tier0.extend(high_value_node_ids)
# print("total_tier0:", total_tier0)

In [33]:
#len(total_tier0)

In [34]:
len(nodes)

1297

In [35]:
# prompt: how do i rewrite the following code to check for "TIER 0", "Tier 0" and "T0":
# tier0_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 0' in x.get('distinguishedname', ''))]['id'].tolist()

# tier0_node_ids = nodes[
#     nodes['properties'].apply(
#         lambda x: any(
#             term in x.get('distinguishedname', '')
#             for term in ['TIER 0', 'Tier 0', 'T0']
#         )
#     )
# ]['id'].tolist()

In [36]:
#tier2_node_ids

In [37]:
# 1/0
# tier0_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 0' in x.get('distinguishedname', ''))]['id'].tolist()
# tier0_node_ids

tier0_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 0', 'Tier 0', 'T0']
        )
    )
]['id'].tolist()


tier1_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 1', 'Tier 1', 'T1']
        )
    )
]['id'].tolist()

tier2_node_ids = nodes[
    nodes['properties'].apply(
        lambda x: any(
            term in x.get('distinguishedname', '')
            for term in ['TIER 2', 'Tier 2', 'T2']
        )
    )
]['id'].tolist()

print(f"tier 0 ",len(tier0_node_ids))
# tier1_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 1' in x.get('distinguishedname', ''))]['id'].tolist()
print(f"tier 1 ",len(tier1_node_ids))

# tier2_node_ids = nodes[nodes['properties'].apply(lambda x: 'Tier 2' in x.get('distinguishedname', ''))]['id'].tolist()
print(f"tier 2 ",len(tier2_node_ids))

tier 0  42
tier 1  58
tier 2  949

In [38]:
len(nodes)

1297

In [39]:
# T0="T0"
# T1="T1"
# T2="T2"

In [40]:
# # prompt: produce a list of id's from nodes when nodes[properties][name] contains T0

# ids_with_T0 = nodes[nodes['properties'].apply(lambda x: T0 in x.get('name', ''))]['id'].tolist()
# #ids_with_T0
# ids_with_T1 = nodes[nodes['properties'].apply(lambda x: T1 in x.get('name', ''))]['id'].tolist()
# #ids_with_T1
# ids_with_T2 = nodes[nodes['properties'].apply(lambda x: T2 in x.get('name', ''))]['id'].tolist()
# #ids_with_T2

In [41]:
# print(ids_with_T0)
# print(ids_with_T1)
# print(ids_with_T2)

# print(len(ids_with_T0))
# print(len(ids_with_T1))
# print(len(ids_with_T2))

In [42]:

for value in tier0_node_ids:
    nodes.loc[nodes['id'] == value, 'weight'] = 20

for value in tier1_node_ids:
    nodes.loc[nodes['id'] == value, 'weight'] = 10

for value in tier2_node_ids:
    nodes.loc[nodes['id'] == value, 'weight'] = 5

nodes.head(50)

,id,properties,type,l1,l2,l3,weight
0,0,"{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL', 'highvalue': True, 'objectid': 'S-1-5-21-883232822-274137685-4173207997', 'distinguishedname': 'DC=MARK,DC=LOCAL', 'functionallevel': '2012', 'owned': False}",node,Base,Domain,None,20
1,1,"{'domain': 'MARK.LOCAL', 'name': 'Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-cdca22b1-d164-4ec1-8233-45c0ea9044ac', 'distinguishedname': 'OU=ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
2,2,"{'domain': 'MARK.LOCAL', 'name': 'Tier 1 Servers@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d49f51-1ea3-4d9c-93a1-0b591b59c7e9', 'distinguishedname': 'OU=TIER 1 SERVERS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,10
3,3,"{'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5de20ac8-e7ff-4f05-b597-268af392400e', 'distinguishedname': 'OU=TIER 2,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
4,4,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f249f685-d5e0-4dad-b5b5-7f723c41ca1e', 'distinguishedname': 'OU=T0 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
5,5,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-8355af01-1b4e-48c8-8977-a53870b2770b', 'distinguishedname': 'OU=T1 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,10
6,6,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e4602f9d-12bf-4f9e-b667-f6ccd27fae90', 'distinguishedname': 'OU=T2 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
7,7,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c0fb853d-9b96-449b-b25c-4d20a1c02e5f', 'distinguishedname': 'OU=T0 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
8,8,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-b9fd1aed-b3e6-4d53-9242-b85ff389822f', 'distinguishedname': 'OU=T0 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
9,9,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-cd13b9d6-76ca-4b5c-82bd-2d86bef8a375', 'distinguishedname': 'OU=T0 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
10,10,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-58cd5b4f-82db-4cd1-a3f4-08661c9c53d2', 'distinguishedname': 'OU=T0 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
11,11,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-73c7c626-6665-4f12-9cdf-c42ab0282573', 'distinguishedname': 'OU=T1 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,10
12,12,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5c1f7a53-4d89-45c5-a182-d42f7a3bd15c', 'distinguishedname': 'OU=T1 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,10
13,13,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-dc73f46b-2d1b-416f-87d1-783e91a30bfe', 'distinguishedname': 'OU=T1 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,10
14,14,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c703aa33-871c-4893-a8db-437a731598e9', 'distinguishedname': 'OU=T1 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,10
15,15,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-61c17d81-4eb2-4829-94e7-c7ddd6ecd193', 'distinguishedname': 'OU=T2 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
16,16,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5305b84a-5f72-4ee8-9726-81485bc11905', 'distinguishedname': 'OU=T2 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
17,17,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-508809b7-63d4-4f53-8376-b31aa66c0af6', 'distinguishedname': 'OU=T2 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
18,18,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e7679546-c753-4556-889a-67fd84f9d165', 'distinguishedname': 'OU=T2 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
19,19,"{'domain': 'MARK.LOCAL', 'name': 'Application@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c8fbc840-cc56-4337-aa2c-31984398cf7f', 'distinguishedname': 'OU=APPLICATION,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
20,20,"{'domain': 'MARK.LOCAL', 'name': 'Print@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-70355ec3-a132-4ec7-b4c7-f7cdfb011b59', 'distinguishedname': 'OU=PRINT,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
21,21,"{'domain': 'MARK.LOCAL', 'name': 'Database@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-bee8279d-bcc2-427c-827c-510159969430', 'distinguishedname': 'OU=DATABASE,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,1
22,22,"{'domain': 'MARK.LOCAL', 'name': 'T2 Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d13355-d2f9-45cf-9ee6-fdc8230ae4e5', 'distinguishedname': 'OU=T2 GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
23,23,"{'domain': 'MARK.LOCAL', 'name': 'T2 Workstations@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-66aadca5-ccbc-46d4-91e7-f74f2527bdb5', 'distinguishedname': 'OU=T2 WORKSTATIONS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
24,24,"{'domain': 'MARK.LOCAL', 'name': 'T2 User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-d4c0667d-16e8-4afd-8cf3-5f6a900f6913', 'distinguishedname': 'OU=T2 USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
25,25,"{'domain': 'MARK.LOCAL', 'name': 'T2 Servers@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-3f1588f2-5124-4111-8d63-caf4b57a87ca', 'distinguishedname': 'OU=T2 SERVERS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
26,26,"{'domain': 'MARK.LOCAL', 'name': 'T2 Enabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-dd1b08e8-140d-49e3-ab56-1551c008827a', 'distinguishedname': 'OU=T2 ENABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
27,27,"{'domain': 'MARK.LOCAL', 'name': 'T2 Disabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-9c9959e1-1718-4648-9aa1-e0eb9920d50c', 'distinguishedname': 'OU=T2 DISABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
28,28,"{'domain': 'MARK.LOCAL', 'name': 'T2 Workstations AL@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5bde0576-c8a8-4759-9b5b-2aad73322f0f', 'distinguishedname': 'OU=T2 WORKSTATIONS AL,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
29,29,"{'domain': 'MARK.LOCAL', 'name': 'T2 Workstations AK@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-ce3180b3-27c3-47a5-882f-6f19301ba3a4', 'distinguishedname': 'OU=T2 WORKSTATIONS AK,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
30,30,"{'domain': 'MARK.LOCAL', 'name': 'T2 Workstations AZ@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-7045f1c8-5a9f-4e7c-8021-a02856b9f945', 'distinguishedname': 'OU=T2 WORKSTATIONS AZ,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
31,31,"{'domain': 'MARK.LOCAL', 'name': 'T2 Distribution Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c0859a15-e2ab-4416-b2cc-b5b6847ed589', 'distinguishedname': 'OU=T2 DISTRIBUTION GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
32,32,"{'domain': 'MARK.LOCAL', 'name': 'T2 Security Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-6b597066-2149-4c6f-ac8a-d1c0bf893550', 'distinguishedname': 'OU=T2 SECURITY GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
33,33,"{'domain': 'MARK.LOCAL', 'name': 'T2 Servers AL@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c781d32b-68c2-434f-ac00-3fa1a6d24059', 'distinguishedname': 'OU=T2 SERVERS AL,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
34,34,"{'domain': 'MARK.LOCAL', 'name': 'T2 Servers AK@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-fa615a1f-deb6-4b6d-8bde-89f22e88b725', 'distinguishedname': 'OU=T2 SERVERS AK,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
35,35,"{'domain': 'MARK.LOCAL', 'name': 'T2 Servers AZ@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-6a528ecf-4ea6-43f4-8285-b77fc0dfc004', 'distinguishedname': 'OU=T2 SERVERS AZ,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,5
36,36,"{'domain': 'MARK.LOCAL', 'name': 'ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-544', 'highvalue': True, 'distinguishedname': 'CN=Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Administrators have complete and unrestricted access to the computer/domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
37,37,"{'domain': 'MARK.LOCAL', 'name': 'REMOTE DESKTOP USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-555', 'highvalue': False, 'distinguishedname': 'CN=Remote Desktop Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members in this group are granted the right to logon remotely', 'admincount': False, 'owned': False}",node,Base,Group,None,1
38,38,"{'domain': 'MARK.LOCAL', 'name': 'PRINT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-550', 'highvalue': True, 'distinguishedname': 'CN=Print Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer printers installed on domain controllers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
39,39,"{'domain': 'MARK.LOCAL', 'name': 'IIS_IUSRS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-568', 'highvalue': False, 'distinguishedname': 'CN=IIS_IUSRS,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Built-in group used by Internet Information Services.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
40,40,"{'domain': 'MARK.LOCAL', 'name': 'BACKUP OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-551', 'highvalue': True, 'distinguishedname': 'CN=Backup Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Backup Operators can override security restrictions for the sole purpose of backing up or restoring files', 'admincount': True, 'owned': False}",node,Base,Group,None,20
41,41,"{'domain': 'MARK.LOCAL', 'name': 'NETWORK CONFIGURATION OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-556', 'highvalue': False, 'distinguishedname': 'CN=Network Configuration Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members in this group can have some administrative privileges to manage configuration of networking features', 'admincount': False, 'owned': False}",node,Base,Group,None,1
42,42,"{'domain': 'MARK.LOCAL', 'name': 'PERFORMANCE MONITOR USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-558', 'highvalue': False, 'distinguishedname': 'CN=Performance Monitor Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can access performance counter data locally and remotely', 'admincount': False, 'owned': False}",node,Base,Group,None,1
43,43,"{'domain': 'MARK.LOCAL', 'name': 'REPLICATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-552', 'highvalue': False, 'distinguishedname': 'CN=Replicator,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Supports file replication in a domain', 'admincount': True, 'owned': False}",node,Base,Group,None,1
44,44,"{'domain': 'MARK.LOCAL', 'name': 'DISTRIBUTED COM USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-562', 'highvalue': False, 'distinguishedname': 'CN=Distributed COM Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members are allowed to launch, activate and use Distributed COM objects on this machine.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
45,45,"{'domain': 'MARK.LOCAL', 'name': 'PERFORMANCE LOG USERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-559', 'highvalue': False, 'distinguishedname': 'CN=Performance Log Users,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group may schedule logging of performance counters, enable trace providers, and collect event traces both locally and via remote access to this computer', 'admincount': False, 'owned': False}",node,Base,Group,None,1
46,46,"{'domain': 'MARK.LOCAL', 'name': 'CRYPTOGRAPHIC OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-569', 'highvalue': False, 'distinguishedname': 'CN=Cryptographic Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members are authorized to perform cryptographic operations.', 'admincount': False, 'owned': False}",node,Base,Group,None,1
47,47,"{'domain': 'MARK.LOCAL', 'name': 'EVENT LOG READERS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-573', 'highvalue': False, 'distinguishedname': 'CN=Event Log Readers,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group can read event logs from local machine', 'admincount': False, 'owned': False}",node,Base,Group,None,1
48,48,"{'domain': 'MARK.LOCAL', 'name': 'GUESTS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-546', 'highvalue': False, 'distinguishedname': 'CN=Guests,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Guests have the same access as members of the Users group by default, except for the Guest account which is further restricted', 'admincount': False, 'owned': False}",node,Base,Group,None,1
49,49,"{'domain': 'MARK.LOCAL', 'name': 'SYSTEM MANAGED ACCOUNTS GROUP@MARK.LOCAL', 'objectid': 'S-1-5-32-581', 'highvalue': False, 'distinguishedname': 'CN=System Managed Accounts Group,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members of this group are managed by the system.', 'admincount': False, 'owned': False}",node,Base,Group,None,1

In [43]:
# prompt: get a unique list of label from edges and save it to list called edges_labels

edges_labels = edges['label'].unique().tolist()
edges_labels

['Contains',
 'GpLink',
 'GenericAll',
 'MemberOf',
 'GenericWrite',
 'WriteDacl',
 'Owns',
 'WriteOwner',
 'GetChanges',
 'GetChangesAll',
 'AllExtendedRights',
 'AdminTo',
 'HasSession',
 'ReadLAPSPassword',
 'CanRDP',
 'ExecuteDCOM',
 'AddSelf',
 'ForceChangePassword',
 'AddMember']

In [44]:
# Apply the weights based on the 'label' column

def assign_weight(label):
    if label == "GenericAll":
        return 9
    elif label == "Owns":
        return 10
    elif label == "GenericWrite":
        return 2
    elif label == "AllExtendedRights":
        return 6
    elif label == "CanRDP":
        return 2
    elif label == "Contains":
        return 2
    elif label == "DCSync":
        return 8
    elif label == "WriteDacl":
        return 5
    elif label == "WriteOwner":
        return 7
    elif label == "AddKeyCredentialLink":
        return 6
    elif label == "AdminTo":
        return 8
    elif label == "MemberOf":
        return 1
    elif label == "CanPSRemote":
        return 2
    elif label == "ExecuteDCOM":
        return 2
    elif label == "GPLink":
        return 3
    elif label == "HasSession":
        return 9
    elif label == "ReadLAPSPassword":
        return 2
    elif label == "GetChanges":
        return 3
    elif label == "GetChangesAll":
        return 3
    elif label == "AddSelf":
        return 3
    elif label == "ForceChangePassword":
        return 3
    elif label == "AddMember":
        return 5
    elif label == "tier0":
        return 20
    else:
        return 1 # Default weight for other labels

edges['weight'] = edges['label'].apply(assign_weight)

# Display the updated edges_all DataFrame with the 'weight' column
print("\nEdges_all DataFrame with weight column:")
#edges.head(50)
#clear_output()

Edges_all DataFrame with weight column:

In [45]:
# prompt: from edges['start'] get 'id' and from edges['end] get 'id'
# replace start with edges['start'][id'] and  end with edges['end']['id']

edges['start'] = edges['start'].apply(lambda x: x.get('id') if isinstance(x, dict) else x)
edges['end'] = edges['end'].apply(lambda x: x.get('id') if isinstance(x, dict) else x)
#edges.head(30)

In [46]:
len(edges)

3974

In [47]:
print("\nEdges_all DataFrame with weight column:")
#edges.tail(50)

Edges_all DataFrame with weight column:

In [48]:
# prompt: create a new dataframe called adj with the values of start['id'] and end['id'] from each record

# adj = edges[['start', 'end']].copy()
# adj['start'] = adj['start'].apply(lambda x: x['id']).astype(int)
# adj['end'] = adj['end'].apply(lambda x: x['id']).astype(int)
# adj.head()

In [49]:
# len(edges)
# edges.head(20)

In [50]:
# prompt: from edges, convert start[id] into an integer

# edges['start'] = edges['start'].apply(lambda x: x['id']).astype(int)

In [51]:
# edges['end'] = edges['end'].apply(lambda x: x['id']).astype(int)
# edges['start'] = edges['start'].apply(lambda x: x['id']).astype(int)

In [52]:

edges = edges.drop(columns=['properties', 'id'])

In [53]:
# prompt: create a unique id for each row, make sure it is of type int64
#edges = edges.drop(columns=['id'])
import numpy as np
edges['id'] = np.arange(len(edges)).astype('int64')
edges.head()
edges['id'].dtype

dtype('int64')

In [54]:

edges.keys()

Index(['type', 'start', 'end', 'label', 'weight', 'id'], dtype='object')

In [55]:
# prompt: show me the 1st record in the tier2_node_ids

type(tier2_node_ids[0])

int

In [56]:
# prompt: delete the last record in edges

# edges = edges[:-1]
# edges.tail()

In [57]:
# prompt: add the following record to edges:
# id=9999, properties={}, type="relationship", start=3, end=4,label="WriteDACL", weight=20

# import pandas as pd
# import numpy as np
# new_record = pd.DataFrame([{
#     'id': 9999,
#     'properties': {},
#     'type': 'relationship',
#     'start':  3,
#     'end': 4,
#     'label': 'WriteDacl',  # Corrected the typo to 'WriteDacl'
#     'weight': 20
# }])

# edges = pd.concat([edges, new_record], ignore_index=True)

# # Re-assign ids after adding a new record to ensure uniqueness and sequential order
# edges['id'] = np.arange(len(edges)).astype('int64')

# edges.tail()

In [58]:
tier2_node_ids[5]

18

In [59]:
## prompt: filter where edges['id'] = tier2_node_ids and call the dataframe selected_ddges

#selected_edges = edges[edges['start'].isin(tier2_node_ids)]

In [60]:
#edges['start'].head()
#edges.keys()

In [61]:
#selected_edges_t1 = edges[edges['start'].isin(tier1_node_ids)]

In [62]:
#selected_edges_t1

In [63]:
#selected_edges_t0 = edges[edges['start'].isin(tier0_node_ids)]
#selected_edges_t0

In [64]:
#tier0_node_ids

In [65]:
# prompt: show me type of columns in edges

edges.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3974 entries, 1297 to 5270
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   type    3974 non-null   object
 1   start   3974 non-null   object
 2   end     3974 non-null   object
 3   label   3974 non-null   object
 4   weight  3974 non-null   int64
 5   id      3974 non-null   int64
dtypes: int64(2), object(4)
memory usage: 346.4+ KB

In [66]:
# prompt: make edges['start'] and edges['end'] int64

edges['start'] = edges['start'].astype('int64')
edges['end'] = edges['end'].astype('int64')

In [67]:
# describe = edges.describe()
# describe

In [68]:
print(edges[edges['start'] == 307])

              type  start  end       label  weight    id
2207  relationship    307   74    MemberOf       1   910
2757  relationship    307   59    MemberOf       1  1460
5034  relationship    307  104  HasSession       9  3737

In [69]:
# selected_edges_t2 = edges[edges['start'].isin(tier2_node_ids)]

In [70]:
# selected_edges

In [71]:
# selected_edges_t0 = edges[edges['start'].isin(tier0_node_ids)]
# selected_edges_t0

In [72]:
# selected_edges_t1 = edges[edges['start'].isin(tier1_node_ids)]
# selected_edges_t1

In [73]:
# tier0_node_ids

In [74]:
# selected_edges.head()

In [75]:
print(nodes[nodes['id'] == 8])

   id  \
8   8

                                                                                                                                                                                                                                                                                                      properties  \
8  {'domain': 'MARK.LOCAL', 'name': 'T0 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-b9fd1aed-b3e6-4d53-9242-b85ff389822f', 'distinguishedname': 'OU=T0 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}

   type    l1  l2    l3  weight
8  node  Base  OU  None      20

In [76]:
selected_nodes = nodes[nodes['id'].isin(tier2_node_ids)]

In [77]:
# prompt: set weight to 20 in selected_nodes

# for value in selected_nodes['id']:
#     selected_nodes.loc[selected_nodes['id'] == value, 'weight'] = 20

In [78]:
# selected_nodes

In [79]:
len(selected_nodes)

949

In [80]:
len(selected_edges_t0)

NameError: name 'selected_edges_t0' is not defined

In [ ]:
# import networkx as nx

# # Create a directed graph
# G = nx.DiGraph()

# # Add nodes with their weights
# for index, row in nodes.iterrows():
#     # Ensure node IDs are integers when adding to the graph
#     G.add_node(int(row['id']), weight=row['weight'])

# # Add edges with their weights
# for index, row in edges.iterrows():
#     # Ensure edge endpoints are integers when adding to the graph
#     G.add_edge(int(row['start']), int(row['end']), weight=row['weight'])

# # Compute shortest paths from each source node to all reachable nodes
# shortest_paths = {}
# for source in G.nodes():
#     # Use single_source_dijkstra_path to find paths from one source to all others
#     shortest_paths[source] = nx.single_source_dijkstra_path(G, source)

# # Filter out paths from a node to itself and store in a new dictionary
# shortest_paths_filtered = {
#     source: {
#         target: path
#         for target, path in paths.items()
#         if source != target
#     }
#     for source, paths in shortest_paths.items()
# }

# # Print the shortest paths (optional)
# # for source, paths in shortest_paths_filtered.items():
# #     print(f"Shortest paths from node {source}:")
# #     for target, path in paths.items():
# #         print(f"  To node {target}: {path}")

In [ ]:
# tier2_node_ids

In [ ]:
# tier0_node_ids

In [81]:
selected_edges = edges[edges['end'].isin(tier0_node_ids)]
len(selected_edges)

136

In [ ]:
# prompt: selected_edges=all edges excluding where edges['start'] is in tier0_node_ids

# selected_edges = edges[~edges['start'].isin(tier0_node_ids)]
# len(selected_edges)

In [ ]:
# selected_edges['end'] = selected_edges['end'].apply(lambda x: x['id']).astype(int)
# selected_edges['start'] = selected_edges['start'].apply(lambda x: x['id']).astype(int)

In [ ]:
#selected_edges_t2

In [82]:
import networkx as nx

# Create a directed graph
G = nx.DiGraph()

# Add nodes with their weights
for index, row in selected_nodes.iterrows():
    # Ensure node IDs are integers when adding to the graph
    G.add_node(int(row['id']), weight=row['weight'])

# Add edges with their weights
for index, row in selected_edges.iterrows():
    # Ensure edge endpoints are integers when adding to the graph
    G.add_edge(row['start'], row['end'], weight=row['weight'])

# Compute shortest paths from each source node to all reachable nodes
shortest_paths = {}
for source in G.nodes():
    # Use single_source_dijkstra_path to find paths from one source to all others
    shortest_paths[source] = nx.single_source_dijkstra_path(G, source)

# Filter out paths from a node to itself and store in a new dictionary
shortest_paths_filtered = {
    source: {
        target: path
        for target, path in paths.items()
        if source != target
        if target in tier0_node_ids
    }
    for source, paths in shortest_paths.items()
}

# Print the shortest paths (optional)
for source, paths in shortest_paths_filtered.items():
  if paths:
    #print(f"Shortest paths from node {source}:")
    for target, path in paths.items():
        #print(f"  To node {target}: {path}")
        ShortestPath = source, target, path
        print(ShortestPath)

(15, 301, [15, 301])
(15, 318, [15, 318])
(26, 331, [26, 331])
(26, 341, [26, 341])
(26, 357, [26, 357])
(26, 405, [26, 405])
(26, 444, [26, 444])
(26, 448, [26, 448])
(27, 392, [27, 392])
(29, 481, [29, 481])
(486, 444, [486, 444])
(490, 331, [490, 331])
(494, 448, [494, 448])
(496, 444, [496, 444])
(498, 357, [498, 357])
(498, 448, [498, 448])
(499, 357, [499, 357])
(503, 444, [503, 444])
(505, 448, [505, 448])
(516, 405, [516, 405])
(517, 357, [517, 357])
(517, 448, [517, 448])
(524, 448, [524, 448])
(526, 405, [526, 405])
(538, 448, [538, 448])
(541, 331, [541, 331])
(542, 357, [542, 357])
(549, 357, [549, 357])
(552, 444, [552, 444])
(571, 341, [571, 341])
(572, 444, [572, 444])
(574, 331, [574, 331])
(581, 331, [581, 331])
(581, 444, [581, 444])
(583, 405, [583, 405])
(584, 448, [584, 448])
(587, 405, [587, 405])
(605, 448, [605, 448])
(608, 444, [608, 444])
(611, 331, [611, 331])
(611, 448, [611, 448])
(612, 405, [612, 405])
(616, 448, [616, 448])
(628, 448, [628, 448])
(629, 357, [629, 357])
(630, 405, [630, 405])
(633, 331, [633, 331])
(637, 301, [637, 301])
(641, 405, [641, 405])
(644, 331, [644, 331])
(647, 405, [647, 405])
(659, 341, [659, 341])
(668, 444, [668, 444])
(869, 8, [869, 8])
(869, 686, [869, 8, 686])
(869, 527, [869, 8, 527])
(869, 530, [869, 8, 530])
(869, 531, [869, 8, 531])
(869, 532, [869, 8, 532])
(869, 553, [869, 8, 553])
(869, 607, [869, 8, 607])
(869, 610, [869, 8, 610])
(869, 625, [869, 8, 625])
(869, 631, [869, 8, 631])
(869, 632, [869, 8, 632])
(869, 640, [869, 8, 640])
(869, 645, [869, 8, 645])
(869, 653, [869, 8, 653])
(869, 663, [869, 8, 663])
(869, 303, [869, 8, 686, 303])
(869, 296, [869, 8, 527, 296])
(869, 305, [869, 8, 607, 305])
(869, 457, [869, 8, 610, 457])
(869, 324, [869, 8, 625, 324])
(869, 307, [869, 8, 631, 307])
(869, 692, [869, 8, 653, 692])
(869, 458, [869, 8, 653, 458])
(871, 8, [871, 8])
(871, 686, [871, 8, 686])
(871, 527, [871, 8, 527])
(871, 530, [871, 8, 530])
(871, 531, [871, 8, 531])
(871, 532, [871, 8, 532])
(871, 553, [871, 8, 553])
(871, 607, [871, 8, 607])
(871, 610, [871, 8, 610])
(871, 625, [871, 8, 625])
(871, 631, [871, 8, 631])
(871, 632, [871, 8, 632])
(871, 640, [871, 8, 640])
(871, 645, [871, 8, 645])
(871, 653, [871, 8, 653])
(871, 663, [871, 8, 663])
(871, 303, [871, 8, 686, 303])
(871, 296, [871, 8, 527, 296])
(871, 305, [871, 8, 607, 305])
(871, 457, [871, 8, 610, 457])
(871, 324, [871, 8, 625, 324])
(871, 307, [871, 8, 631, 307])
(871, 692, [871, 8, 653, 692])
(871, 458, [871, 8, 653, 458])
(1, 4, [1, 4])
(1, 7, [1, 4, 7])
(1, 8, [1, 4, 8])
(1, 9, [1, 4, 9])
(1, 10, [1, 4, 10])
(1, 692, [1, 4, 7, 692])
(1, 295, [1, 4, 7, 295])
(1, 303, [1, 4, 7, 303])
(1, 306, [1, 4, 7, 306])
(1, 307, [1, 4, 7, 307])
(1, 324, [1, 4, 7, 324])
(1, 457, [1, 4, 7, 457])
(1, 458, [1, 4, 7, 458])
(1, 469, [1, 4, 7, 469])
(1, 686, [1, 4, 8, 686])
(1, 527, [1, 4, 8, 527])
(1, 530, [1, 4, 8, 530])
(1, 531, [1, 4, 8, 531])
(1, 532, [1, 4, 8, 532])
(1, 553, [1, 4, 8, 553])
(1, 607, [1, 4, 8, 607])
(1, 610, [1, 4, 8, 610])
(1, 625, [1, 4, 8, 625])
(1, 631, [1, 4, 8, 631])
(1, 632, [1, 4, 8, 632])
(1, 640, [1, 4, 8, 640])
(1, 645, [1, 4, 8, 645])
(1, 653, [1, 4, 8, 653])
(1, 663, [1, 4, 8, 663])
(1, 296, [1, 4, 10, 296])
(1, 305, [1, 4, 10, 305])
(4, 7, [4, 7])
(4, 8, [4, 8])
(4, 9, [4, 9])
(4, 10, [4, 10])
(4, 692, [4, 7, 692])
(4, 295, [4, 7, 295])
(4, 303, [4, 7, 303])
(4, 306, [4, 7, 306])
(4, 307, [4, 7, 307])
(4, 324, [4, 7, 324])
(4, 457, [4, 7, 457])
(4, 458, [4, 7, 458])
(4, 469, [4, 7, 469])
(4, 686, [4, 8, 686])
(4, 527, [4, 8, 527])
(4, 530, [4, 8, 530])
(4, 531, [4, 8, 531])
(4, 532, [4, 8, 532])
(4, 553, [4, 8, 553])
(4, 607, [4, 8, 607])
(4, 610, [4, 8, 610])
(4, 625, [4, 8, 625])
(4, 631, [4, 8, 631])
(4, 632, [4, 8, 632])
(4, 640, [4, 8, 640])
(4, 645, [4, 8, 645])
(4, 653, [4, 8, 653])
(4, 663, [4, 8, 663])
(4, 296, [4, 10, 296])
(4, 305, [4, 10, 305])
(7, 692, [7, 692])
(7, 295, [7, 295])
(7, 303, [7, 303])
(7, 306, [7, 306])
(7, 307, [7, 307])
(7, 324, [7, 324])
(7, 457, [7, 457])
(7, 458, [7, 458])
(7, 469, [7, 469])
(8, 686, [8, 686])
(8, 527, [8, 527])
(8, 530, [8, 530])
(8, 531, [8, 531])
(8, 532, [8, 532])
(8, 553, [8, 553])
(8, 607, [8, 607])
(8, 610, [8, 610])
(8, 625, [8, 625])
(8, 631, [8, 631])
(8, 632, [8, 632])
(8, 640, [8, 640])
(8, 645, [8, 645])
(8, 653, [8, 653])
(8, 663, [8, 663])
(8, 303, [8, 686, 303])
(8, 296, [8, 527, 296])
(8, 305, [8, 607, 305])
(8, 457, [8, 610, 457])
(8, 324, [8, 625, 324])
(8, 307, [8, 631, 307])
(8, 692, [8, 653, 692])
(8, 458, [8, 653, 458])
(10, 296, [10, 296])
(10, 305, [10, 305])
(110, 8, [110, 8])
(110, 686, [110, 8, 686])
(110, 527, [110, 8, 527])
(110, 530, [110, 8, 530])
(110, 531, [110, 8, 531])
(110, 532, [110, 8, 532])
(110, 553, [110, 8, 553])
(110, 607, [110, 8, 607])
(110, 610, [110, 8, 610])
(110, 625, [110, 8, 625])
(110, 631, [110, 8, 631])
(110, 632, [110, 8, 632])
(110, 640, [110, 8, 640])
(110, 645, [110, 8, 645])
(110, 653, [110, 8, 653])
(110, 663, [110, 8, 663])
(110, 303, [110, 8, 686, 303])
(110, 296, [110, 8, 527, 296])
(110, 305, [110, 8, 607, 305])
(110, 457, [110, 8, 610, 457])
(110, 324, [110, 8, 625, 324])
(110, 307, [110, 8, 631, 307])
(110, 692, [110, 8, 653, 692])
(110, 458, [110, 8, 653, 458])
(111, 8, [111, 8])
(111, 686, [111, 8, 686])
(111, 527, [111, 8, 527])
(111, 530, [111, 8, 530])
(111, 531, [111, 8, 531])
(111, 532, [111, 8, 532])
(111, 553, [111, 8, 553])
(111, 607, [111, 8, 607])
(111, 610, [111, 8, 610])
(111, 625, [111, 8, 625])
(111, 631, [111, 8, 631])
(111, 632, [111, 8, 632])
(111, 640, [111, 8, 640])
(111, 645, [111, 8, 645])
(111, 653, [111, 8, 653])
(111, 663, [111, 8, 663])
(111, 303, [111, 8, 686, 303])
(111, 296, [111, 8, 527, 296])
(111, 305, [111, 8, 607, 305])
(111, 457, [111, 8, 610, 457])
(111, 324, [111, 8, 625, 324])
(111, 307, [111, 8, 631, 307])
(111, 692, [111, 8, 653, 692])
(111, 458, [111, 8, 653, 458])
(135, 9, [135, 9])
(137, 4, [137, 4])
(137, 7, [137, 4, 7])
(137, 8, [137, 4, 8])
(137, 9, [137, 4, 9])
(137, 10, [137, 4, 10])
(137, 692, [137, 4, 7, 692])
(137, 295, [137, 4, 7, 295])
(137, 303, [137, 4, 7, 303])
(137, 306, [137, 4, 7, 306])
(137, 307, [137, 4, 7, 307])
(137, 324, [137, 4, 7, 324])
(137, 457, [137, 4, 7, 457])
(137, 458, [137, 4, 7, 458])
(137, 469, [137, 4, 7, 469])
(137, 686, [137, 4, 8, 686])
(137, 527, [137, 4, 8, 527])
(137, 530, [137, 4, 8, 530])
(137, 531, [137, 4, 8, 531])
(137, 532, [137, 4, 8, 532])
(137, 553, [137, 4, 8, 553])
(137, 607, [137, 4, 8, 607])
(137, 610, [137, 4, 8, 610])
(137, 625, [137, 4, 8, 625])
(137, 631, [137, 4, 8, 631])
(137, 632, [137, 4, 8, 632])
(137, 640, [137, 4, 8, 640])
(137, 645, [137, 4, 8, 645])
(137, 653, [137, 4, 8, 653])
(137, 663, [137, 4, 8, 663])
(137, 296, [137, 4, 10, 296])
(137, 305, [137, 4, 10, 305])
(139, 9, [139, 9])
(141, 10, [141, 10])
(141, 296, [141, 10, 296])
(141, 305, [141, 10, 305])
(147, 4, [147, 4])
(147, 7, [147, 4, 7])
(147, 8, [147, 4, 8])
(147, 9, [147, 4, 9])
(147, 10, [147, 4, 10])
(147, 692, [147, 4, 7, 692])
(147, 295, [147, 4, 7, 295])
(147, 303, [147, 4, 7, 303])
(147, 306, [147, 4, 7, 306])
(147, 307, [147, 4, 7, 307])
(147, 324, [147, 4, 7, 324])
(147, 457, [147, 4, 7, 457])
(147, 458, [147, 4, 7, 458])
(147, 469, [147, 4, 7, 469])
(147, 686, [147, 4, 8, 686])
(147, 527, [147, 4, 8, 527])
(147, 530, [147, 4, 8, 530])
(147, 531, [147, 4, 8, 531])
(147, 532, [147, 4, 8, 532])
(147, 553, [147, 4, 8, 553])
(147, 607, [147, 4, 8, 607])
(147, 610, [147, 4, 8, 610])
(147, 625, [147, 4, 8, 625])
(147, 631, [147, 4, 8, 631])
(147, 632, [147, 4, 8, 632])
(147, 640, [147, 4, 8, 640])
(147, 645, [147, 4, 8, 645])
(147, 653, [147, 4, 8, 653])
(147, 663, [147, 4, 8, 663])
(147, 296, [147, 4, 10, 296])
(147, 305, [147, 4, 10, 305])
(160, 9, [160, 9])
(172, 4, [172, 4])
(172, 7, [172, 4, 7])
(172, 8, [172, 4, 8])
(172, 9, [172, 4, 9])
(172, 10, [172, 4, 10])
(172, 692, [172, 4, 7, 692])
(172, 295, [172, 4, 7, 295])
(172, 303, [172, 4, 7, 303])
(172, 306, [172, 4, 7, 306])
(172, 307, [172, 4, 7, 307])
(172, 324, [172, 4, 7, 324])
(172, 457, [172, 4, 7, 457])
(172, 458, [172, 4, 7, 458])
(172, 469, [172, 4, 7, 469])
(172, 686, [172, 4, 8, 686])
(172, 527, [172, 4, 8, 527])
(172, 530, [172, 4, 8, 530])
(172, 531, [172, 4, 8, 531])
(172, 532, [172, 4, 8, 532])
(172, 553, [172, 4, 8, 553])
(172, 607, [172, 4, 8, 607])
(172, 610, [172, 4, 8, 610])
(172, 625, [172, 4, 8, 625])
(172, 631, [172, 4, 8, 631])
(172, 632, [172, 4, 8, 632])
(172, 640, [172, 4, 8, 640])
(172, 645, [172, 4, 8, 645])
(172, 653, [172, 4, 8, 653])
(172, 663, [172, 4, 8, 663])
(172, 296, [172, 4, 10, 296])
(172, 305, [172, 4, 10, 305])
(179, 10, [179, 10])
(179, 296, [179, 10, 296])
(179, 305, [179, 10, 305])
(184, 10, [184, 10])
(184, 296, [184, 10, 296])
(184, 305, [184, 10, 305])
(186, 10, [186, 10])
(186, 296, [186, 10, 296])
(186, 305, [186, 10, 305])
(187, 10, [187, 10])
(187, 296, [187, 10, 296])
(187, 305, [187, 10, 305])
(188, 10, [188, 10])
(188, 296, [188, 10, 296])
(188, 305, [188, 10, 305])
(200, 7, [200, 7])
(200, 692, [200, 7, 692])
(200, 295, [200, 7, 295])
(200, 303, [200, 7, 303])
(200, 306, [200, 7, 306])
(200, 307, [200, 7, 307])
(200, 324, [200, 7, 324])
(200, 457, [200, 7, 457])
(200, 458, [200, 7, 458])
(200, 469, [200, 7, 469])
(208, 4, [208, 4])
(208, 7, [208, 4, 7])
(208, 8, [208, 4, 8])
(208, 9, [208, 4, 9])
(208, 10, [208, 4, 10])
(208, 692, [208, 4, 7, 692])
(208, 295, [208, 4, 7, 295])
(208, 303, [208, 4, 7, 303])
(208, 306, [208, 4, 7, 306])
(208, 307, [208, 4, 7, 307])
(208, 324, [208, 4, 7, 324])
(208, 457, [208, 4, 7, 457])
(208, 458, [208, 4, 7, 458])
(208, 469, [208, 4, 7, 469])
(208, 686, [208, 4, 8, 686])
(208, 527, [208, 4, 8, 527])
(208, 530, [208, 4, 8, 530])
(208, 531, [208, 4, 8, 531])
(208, 532, [208, 4, 8, 532])
(208, 553, [208, 4, 8, 553])
(208, 607, [208, 4, 8, 607])
(208, 610, [208, 4, 8, 610])
(208, 625, [208, 4, 8, 625])
(208, 631, [208, 4, 8, 631])
(208, 632, [208, 4, 8, 632])
(208, 640, [208, 4, 8, 640])
(208, 645, [208, 4, 8, 645])
(208, 653, [208, 4, 8, 653])
(208, 663, [208, 4, 8, 663])
(208, 296, [208, 4, 10, 296])
(208, 305, [208, 4, 10, 305])
(219, 10, [219, 10])
(219, 296, [219, 10, 296])
(219, 305, [219, 10, 305])
(237, 10, [237, 10])
(237, 296, [237, 10, 296])
(237, 305, [237, 10, 305])
(258, 10, [258, 10])
(258, 296, [258, 10, 296])
(258, 305, [258, 10, 305])
(262, 9, [262, 9])
(272, 7, [272, 7])
(272, 692, [272, 7, 692])
(272, 295, [272, 7, 295])
(272, 303, [272, 7, 303])
(272, 306, [272, 7, 306])
(272, 307, [272, 7, 307])
(272, 324, [272, 7, 324])
(272, 457, [272, 7, 457])
(272, 458, [272, 7, 458])
(272, 469, [272, 7, 469])
(686, 303, [686, 303])
(527, 296, [527, 296])
(607, 305, [607, 305])
(610, 457, [610, 457])
(625, 324, [625, 324])
(631, 307, [631, 307])
(653, 692, [653, 692])
(653, 458, [653, 458])
(11, 467, [11, 467])
(523, 469, [523, 469])
(66, 8, [66, 8])
(66, 7, [66, 7])
(66, 10, [66, 10])
(66, 692, [66, 7, 692])
(66, 295, [66, 7, 295])
(66, 303, [66, 7, 303])
(66, 306, [66, 7, 306])
(66, 307, [66, 7, 307])
(66, 324, [66, 7, 324])
(66, 457, [66, 7, 457])
(66, 458, [66, 7, 458])
(66, 469, [66, 7, 469])
(66, 296, [66, 10, 296])
(66, 305, [66, 10, 305])
(66, 686, [66, 8, 686])
(66, 527, [66, 8, 527])
(66, 530, [66, 8, 530])
(66, 531, [66, 8, 531])
(66, 532, [66, 8, 532])
(66, 553, [66, 8, 553])
(66, 607, [66, 8, 607])
(66, 610, [66, 8, 610])
(66, 625, [66, 8, 625])
(66, 631, [66, 8, 631])
(66, 632, [66, 8, 632])
(66, 640, [66, 8, 640])
(66, 645, [66, 8, 645])
(66, 653, [66, 8, 653])
(66, 663, [66, 8, 663])
(65, 7, [65, 7])
(65, 10, [65, 10])
(65, 8, [65, 8])
(65, 692, [65, 7, 692])
(65, 295, [65, 7, 295])
(65, 303, [65, 7, 303])
(65, 306, [65, 7, 306])
(65, 307, [65, 7, 307])
(65, 324, [65, 7, 324])
(65, 457, [65, 7, 457])
(65, 458, [65, 7, 458])
(65, 469, [65, 7, 469])
(65, 296, [65, 10, 296])
(65, 305, [65, 10, 305])
(65, 686, [65, 8, 686])
(65, 527, [65, 8, 527])
(65, 530, [65, 8, 530])
(65, 531, [65, 8, 531])
(65, 532, [65, 8, 532])
(65, 553, [65, 8, 553])
(65, 607, [65, 8, 607])
(65, 610, [65, 8, 610])
(65, 625, [65, 8, 625])
(65, 631, [65, 8, 631])
(65, 632, [65, 8, 632])
(65, 640, [65, 8, 640])
(65, 645, [65, 8, 645])
(65, 653, [65, 8, 653])
(65, 663, [65, 8, 663])
(36, 7, [36, 7])
(36, 10, [36, 10])
(36, 8, [36, 8])
(36, 692, [36, 7, 692])
(36, 295, [36, 7, 295])
(36, 303, [36, 7, 303])
(36, 306, [36, 7, 306])
(36, 307, [36, 7, 307])
(36, 324, [36, 7, 324])
(36, 457, [36, 7, 457])
(36, 458, [36, 7, 458])
(36, 469, [36, 7, 469])
(36, 296, [36, 10, 296])
(36, 305, [36, 10, 305])
(36, 686, [36, 8, 686])
(36, 527, [36, 8, 527])
(36, 530, [36, 8, 530])
(36, 531, [36, 8, 531])
(36, 532, [36, 8, 532])
(36, 553, [36, 8, 553])
(36, 607, [36, 8, 607])
(36, 610, [36, 8, 610])
(36, 625, [36, 8, 625])
(36, 631, [36, 8, 631])
(36, 632, [36, 8, 632])
(36, 640, [36, 8, 640])
(36, 645, [36, 8, 645])
(36, 653, [36, 8, 653])
(36, 663, [36, 8, 663])
(60, 8, [60, 8])
(60, 686, [60, 8, 686])
(60, 527, [60, 8, 527])
(60, 530, [60, 8, 530])
(60, 531, [60, 8, 531])
(60, 532, [60, 8, 532])
(60, 553, [60, 8, 553])
(60, 607, [60, 8, 607])
(60, 610, [60, 8, 610])
(60, 625, [60, 8, 625])
(60, 631, [60, 8, 631])
(60, 632, [60, 8, 632])
(60, 640, [60, 8, 640])
(60, 645, [60, 8, 645])
(60, 653, [60, 8, 653])
(60, 663, [60, 8, 663])
(60, 303, [60, 8, 686, 303])
(60, 296, [60, 8, 527, 296])
(60, 305, [60, 8, 607, 305])
(60, 457, [60, 8, 610, 457])
(60, 324, [60, 8, 625, 324])
(60, 307, [60, 8, 631, 307])
(60, 692, [60, 8, 653, 692])
(60, 458, [60, 8, 653, 458])

In [83]:
# prompt: using the above code, save all ShortestPath to a json file

shortest_paths_list = []
for source, paths in shortest_paths_filtered.items():
    if paths:
        for target, path in paths.items():
            shortest_paths_list.append({
                'source': source,
                'target': target,
                'path': path,
            })

with open('shortest_paths.json', 'w') as f:
    json.dump(shortest_paths_list, f, indent=4)

print("Shortest paths saved to shortest_paths.json")

Shortest paths saved to shortest_paths.json

In [84]:
# # prompt: save the df_compuers as json to content

# import json

# # Assuming df_computers is already defined as in your provided code.

# # Convert the DataFrame to a JSON string.
# selected_edges_json = selected_edges_t2.to_json(orient='records')

# # Save the JSON string to a file named 'content.json'.
# with open('selected_edges_t2.json', 'w') as f:
#   f.write(selected_edges_json)

In [ ]:
# prompt: save the df_compuers as json to content

# import json

# # Assuming df_computers is already defined as in your provided code.

# # Convert the DataFrame to a JSON string.
# selected_nodes_json = selected_nodes.to_json(orient='records')

# # Save the JSON string to a file named 'content.json'.
# with open('selected_nodes.json', 'w') as f:
#   f.write(selected_nodes_json)

In [ ]:
# prompt: export shortest_paths_filtered to json and save as shortest_paths_filtered_json

# shortest_paths_filtered_json = json.dumps(ShortestPath, indent=2)

# # Optionally, save the JSON string to a file
# with open('ShortestPath.json', 'w') as f:
#   f.write(shortest_paths_filtered_json)

In [85]:
# prompt: find the corresponding record in edges where (edges['start']=shortest_paths_list['source']) and (edges['end']=shortest_paths_list['target'] and then add up the weight

# Calculate the total weight for each shortest path
shortest_paths_with_weight = []
for path_info in shortest_paths_list:
    total_weight = 0
    # The path is a list of node IDs
    path = path_info['path']
    # Iterate through the path to get the edges
    for i in range(len(path) - 1):
        start_node = path[i]
        end_node = path[i+1]
        # Find the corresponding edge in the 'edges' DataFrame
        # There might be multiple edges between two nodes, so we sum up weights if needed
        # For shortest path, we typically consider the direct edge weight
        edge = edges[(edges['start'] == start_node) & (edges['end'] == end_node)]
        if not edge.empty:
            # Assuming there is only one edge with this start and end for simplicity in path finding
            # If multiple edges exist, you might need to adjust based on which edge is part of the shortest path calculation
            total_weight += edge.iloc[0]['weight']
    path_info['total_weight'] = total_weight
    shortest_paths_with_weight.append(path_info)

# Print or use the shortest_paths_with_weight list
for path_info in shortest_paths_with_weight:
    print(f"Path from {path_info['source']} to {path_info['target']}: {path_info['path']} - Total Weight: {path_info['total_weight']}")

Path from 15 to 301: [15, 301] - Total Weight: 2
Path from 15 to 318: [15, 318] - Total Weight: 2
Path from 26 to 331: [26, 331] - Total Weight: 2
Path from 26 to 341: [26, 341] - Total Weight: 2
Path from 26 to 357: [26, 357] - Total Weight: 2
Path from 26 to 405: [26, 405] - Total Weight: 2
Path from 26 to 444: [26, 444] - Total Weight: 2
Path from 26 to 448: [26, 448] - Total Weight: 2
Path from 27 to 392: [27, 392] - Total Weight: 2
Path from 29 to 481: [29, 481] - Total Weight: 2
Path from 486 to 444: [486, 444] - Total Weight: 9
Path from 490 to 331: [490, 331] - Total Weight: 9
Path from 494 to 448: [494, 448] - Total Weight: 9
Path from 496 to 444: [496, 444] - Total Weight: 9
Path from 498 to 357: [498, 357] - Total Weight: 9
Path from 498 to 448: [498, 448] - Total Weight: 9
Path from 499 to 357: [499, 357] - Total Weight: 9
Path from 503 to 444: [503, 444] - Total Weight: 9
Path from 505 to 448: [505, 448] - Total Weight: 9
Path from 516 to 405: [516, 405] - Total Weight: 9
Path from 517 to 357: [517, 357] - Total Weight: 9
Path from 517 to 448: [517, 448] - Total Weight: 9
Path from 524 to 448: [524, 448] - Total Weight: 9
Path from 526 to 405: [526, 405] - Total Weight: 9
Path from 538 to 448: [538, 448] - Total Weight: 9
Path from 541 to 331: [541, 331] - Total Weight: 9
Path from 542 to 357: [542, 357] - Total Weight: 9
Path from 549 to 357: [549, 357] - Total Weight: 9
Path from 552 to 444: [552, 444] - Total Weight: 9
Path from 571 to 341: [571, 341] - Total Weight: 9
Path from 572 to 444: [572, 444] - Total Weight: 9
Path from 574 to 331: [574, 331] - Total Weight: 9
Path from 581 to 331: [581, 331] - Total Weight: 9
Path from 581 to 444: [581, 444] - Total Weight: 9
Path from 583 to 405: [583, 405] - Total Weight: 9
Path from 584 to 448: [584, 448] - Total Weight: 9
Path from 587 to 405: [587, 405] - Total Weight: 9
Path from 605 to 448: [605, 448] - Total Weight: 9
Path from 608 to 444: [608, 444] - Total Weight: 9
Path from 611 to 331: [611, 331] - Total Weight: 9
Path from 611 to 448: [611, 448] - Total Weight: 9
Path from 612 to 405: [612, 405] - Total Weight: 9
Path from 616 to 448: [616, 448] - Total Weight: 9
Path from 628 to 448: [628, 448] - Total Weight: 9
Path from 629 to 357: [629, 357] - Total Weight: 9
Path from 630 to 405: [630, 405] - Total Weight: 9
Path from 633 to 331: [633, 331] - Total Weight: 9
Path from 637 to 301: [637, 301] - Total Weight: 9
Path from 641 to 405: [641, 405] - Total Weight: 9
Path from 644 to 331: [644, 331] - Total Weight: 9
Path from 647 to 405: [647, 405] - Total Weight: 9
Path from 659 to 341: [659, 341] - Total Weight: 9
Path from 668 to 444: [668, 444] - Total Weight: 9
Path from 869 to 8: [869, 8] - Total Weight: 2
Path from 869 to 686: [869, 8, 686] - Total Weight: 4
Path from 869 to 527: [869, 8, 527] - Total Weight: 4
Path from 869 to 530: [869, 8, 530] - Total Weight: 4
Path from 869 to 531: [869, 8, 531] - Total Weight: 4
Path from 869 to 532: [869, 8, 532] - Total Weight: 4
Path from 869 to 553: [869, 8, 553] - Total Weight: 4
Path from 869 to 607: [869, 8, 607] - Total Weight: 4
Path from 869 to 610: [869, 8, 610] - Total Weight: 4
Path from 869 to 625: [869, 8, 625] - Total Weight: 4
Path from 869 to 631: [869, 8, 631] - Total Weight: 4
Path from 869 to 632: [869, 8, 632] - Total Weight: 4
Path from 869 to 640: [869, 8, 640] - Total Weight: 4
Path from 869 to 645: [869, 8, 645] - Total Weight: 4
Path from 869 to 653: [869, 8, 653] - Total Weight: 4
Path from 869 to 663: [869, 8, 663] - Total Weight: 4
Path from 869 to 303: [869, 8, 686, 303] - Total Weight: 13
Path from 869 to 296: [869, 8, 527, 296] - Total Weight: 13
Path from 869 to 305: [869, 8, 607, 305] - Total Weight: 13
Path from 869 to 457: [869, 8, 610, 457] - Total Weight: 13
Path from 869 to 324: [869, 8, 625, 324] - Total Weight: 13
Path from 869 to 307: [869, 8, 631, 307] - Total Weight: 13
Path from 869 to 692: [869, 8, 653, 692] - Total Weight: 13
Path from 869 to 458: [869, 8, 653, 458] - Total Weight: 13
Path from 871 to 8: [871, 8] - Total Weight: 2
Path from 871 to 686: [871, 8, 686] - Total Weight: 4
Path from 871 to 527: [871, 8, 527] - Total Weight: 4
Path from 871 to 530: [871, 8, 530] - Total Weight: 4
Path from 871 to 531: [871, 8, 531] - Total Weight: 4
Path from 871 to 532: [871, 8, 532] - Total Weight: 4
Path from 871 to 553: [871, 8, 553] - Total Weight: 4
Path from 871 to 607: [871, 8, 607] - Total Weight: 4
Path from 871 to 610: [871, 8, 610] - Total Weight: 4
Path from 871 to 625: [871, 8, 625] - Total Weight: 4
Path from 871 to 631: [871, 8, 631] - Total Weight: 4
Path from 871 to 632: [871, 8, 632] - Total Weight: 4
Path from 871 to 640: [871, 8, 640] - Total Weight: 4
Path from 871 to 645: [871, 8, 645] - Total Weight: 4
Path from 871 to 653: [871, 8, 653] - Total Weight: 4
Path from 871 to 663: [871, 8, 663] - Total Weight: 4
Path from 871 to 303: [871, 8, 686, 303] - Total Weight: 13
Path from 871 to 296: [871, 8, 527, 296] - Total Weight: 13
Path from 871 to 305: [871, 8, 607, 305] - Total Weight: 13
Path from 871 to 457: [871, 8, 610, 457] - Total Weight: 13
Path from 871 to 324: [871, 8, 625, 324] - Total Weight: 13
Path from 871 to 307: [871, 8, 631, 307] - Total Weight: 13
Path from 871 to 692: [871, 8, 653, 692] - Total Weight: 13
Path from 871 to 458: [871, 8, 653, 458] - Total Weight: 13
Path from 1 to 4: [1, 4] - Total Weight: 2
Path from 1 to 7: [1, 4, 7] - Total Weight: 4
Path from 1 to 8: [1, 4, 8] - Total Weight: 4
Path from 1 to 9: [1, 4, 9] - Total Weight: 4
Path from 1 to 10: [1, 4, 10] - Total Weight: 4
Path from 1 to 692: [1, 4, 7, 692] - Total Weight: 6
Path from 1 to 295: [1, 4, 7, 295] - Total Weight: 6
Path from 1 to 303: [1, 4, 7, 303] - Total Weight: 6
Path from 1 to 306: [1, 4, 7, 306] - Total Weight: 6
Path from 1 to 307: [1, 4, 7, 307] - Total Weight: 6
Path from 1 to 324: [1, 4, 7, 324] - Total Weight: 6
Path from 1 to 457: [1, 4, 7, 457] - Total Weight: 6
Path from 1 to 458: [1, 4, 7, 458] - Total Weight: 6
Path from 1 to 469: [1, 4, 7, 469] - Total Weight: 6
Path from 1 to 686: [1, 4, 8, 686] - Total Weight: 6
Path from 1 to 527: [1, 4, 8, 527] - Total Weight: 6
Path from 1 to 530: [1, 4, 8, 530] - Total Weight: 6
Path from 1 to 531: [1, 4, 8, 531] - Total Weight: 6
Path from 1 to 532: [1, 4, 8, 532] - Total Weight: 6
Path from 1 to 553: [1, 4, 8, 553] - Total Weight: 6
Path from 1 to 607: [1, 4, 8, 607] - Total Weight: 6
Path from 1 to 610: [1, 4, 8, 610] - Total Weight: 6
Path from 1 to 625: [1, 4, 8, 625] - Total Weight: 6
Path from 1 to 631: [1, 4, 8, 631] - Total Weight: 6
Path from 1 to 632: [1, 4, 8, 632] - Total Weight: 6
Path from 1 to 640: [1, 4, 8, 640] - Total Weight: 6
Path from 1 to 645: [1, 4, 8, 645] - Total Weight: 6
Path from 1 to 653: [1, 4, 8, 653] - Total Weight: 6
Path from 1 to 663: [1, 4, 8, 663] - Total Weight: 6
Path from 1 to 296: [1, 4, 10, 296] - Total Weight: 6
Path from 1 to 305: [1, 4, 10, 305] - Total Weight: 6
Path from 4 to 7: [4, 7] - Total Weight: 2
Path from 4 to 8: [4, 8] - Total Weight: 2
Path from 4 to 9: [4, 9] - Total Weight: 2
Path from 4 to 10: [4, 10] - Total Weight: 2
Path from 4 to 692: [4, 7, 692] - Total Weight: 4
Path from 4 to 295: [4, 7, 295] - Total Weight: 4
Path from 4 to 303: [4, 7, 303] - Total Weight: 4
Path from 4 to 306: [4, 7, 306] - Total Weight: 4
Path from 4 to 307: [4, 7, 307] - Total Weight: 4
Path from 4 to 324: [4, 7, 324] - Total Weight: 4
Path from 4 to 457: [4, 7, 457] - Total Weight: 4
Path from 4 to 458: [4, 7, 458] - Total Weight: 4
Path from 4 to 469: [4, 7, 469] - Total Weight: 4
Path from 4 to 686: [4, 8, 686] - Total Weight: 4
Path from 4 to 527: [4, 8, 527] - Total Weight: 4
Path from 4 to 530: [4, 8, 530] - Total Weight: 4
Path from 4 to 531: [4, 8, 531] - Total Weight: 4
Path from 4 to 532: [4, 8, 532] - Total Weight: 4
Path from 4 to 553: [4, 8, 553] - Total Weight: 4
Path from 4 to 607: [4, 8, 607] - Total Weight: 4
Path from 4 to 610: [4, 8, 610] - Total Weight: 4
Path from 4 to 625: [4, 8, 625] - Total Weight: 4
Path from 4 to 631: [4, 8, 631] - Total Weight: 4
Path from 4 to 632: [4, 8, 632] - Total Weight: 4
Path from 4 to 640: [4, 8, 640] - Total Weight: 4
Path from 4 to 645: [4, 8, 645] - Total Weight: 4
Path from 4 to 653: [4, 8, 653] - Total Weight: 4
Path from 4 to 663: [4, 8, 663] - Total Weight: 4
Path from 4 to 296: [4, 10, 296] - Total Weight: 4
Path from 4 to 305: [4, 10, 305] - Total Weight: 4
Path from 7 to 692: [7, 692] - Total Weight: 2
Path from 7 to 295: [7, 295] - Total Weight: 2
Path from 7 to 303: [7, 303] - Total Weight: 2
Path from 7 to 306: [7, 306] - Total Weight: 2
Path from 7 to 307: [7, 307] - Total Weight: 2
Path from 7 to 324: [7, 324] - Total Weight: 2
Path from 7 to 457: [7, 457] - Total Weight: 2
Path from 7 to 458: [7, 458] - Total Weight: 2
Path from 7 to 469: [7, 469] - Total Weight: 2
Path from 8 to 686: [8, 686] - Total Weight: 2
Path from 8 to 527: [8, 527] - Total Weight: 2
Path from 8 to 530: [8, 530] - Total Weight: 2
Path from 8 to 531: [8, 531] - Total Weight: 2
Path from 8 to 532: [8, 532] - Total Weight: 2
Path from 8 to 553: [8, 553] - Total Weight: 2
Path from 8 to 607: [8, 607] - Total Weight: 2
Path from 8 to 610: [8, 610] - Total Weight: 2
Path from 8 to 625: [8, 625] - Total Weight: 2
Path from 8 to 631: [8, 631] - Total Weight: 2
Path from 8 to 632: [8, 632] - Total Weight: 2
Path from 8 to 640: [8, 640] - Total Weight: 2
Path from 8 to 645: [8, 645] - Total Weight: 2
Path from 8 to 653: [8, 653] - Total Weight: 2
Path from 8 to 663: [8, 663] - Total Weight: 2
Path from 8 to 303: [8, 686, 303] - Total Weight: 11
Path from 8 to 296: [8, 527, 296] - Total Weight: 11
Path from 8 to 305: [8, 607, 305] - Total Weight: 11
Path from 8 to 457: [8, 610, 457] - Total Weight: 11
Path from 8 to 324: [8, 625, 324] - Total Weight: 11
Path from 8 to 307: [8, 631, 307] - Total Weight: 11
Path from 8 to 692: [8, 653, 692] - Total Weight: 11
Path from 8 to 458: [8, 653, 458] - Total Weight: 11
Path from 10 to 296: [10, 296] - Total Weight: 2
Path from 10 to 305: [10, 305] - Total Weight: 2
Path from 110 to 8: [110, 8] - Total Weight: 1
Path from 110 to 686: [110, 8, 686] - Total Weight: 3
Path from 110 to 527: [110, 8, 527] - Total Weight: 3
Path from 110 to 530: [110, 8, 530] - Total Weight: 3
Path from 110 to 531: [110, 8, 531] - Total Weight: 3
Path from 110 to 532: [110, 8, 532] - Total Weight: 3
Path from 110 to 553: [110, 8, 553] - Total Weight: 3
Path from 110 to 607: [110, 8, 607] - Total Weight: 3
Path from 110 to 610: [110, 8, 610] - Total Weight: 3
Path from 110 to 625: [110, 8, 625] - Total Weight: 3
Path from 110 to 631: [110, 8, 631] - Total Weight: 3
Path from 110 to 632: [110, 8, 632] - Total Weight: 3
Path from 110 to 640: [110, 8, 640] - Total Weight: 3
Path from 110 to 645: [110, 8, 645] - Total Weight: 3
Path from 110 to 653: [110, 8, 653] - Total Weight: 3
Path from 110 to 663: [110, 8, 663] - Total Weight: 3
Path from 110 to 303: [110, 8, 686, 303] - Total Weight: 12
Path from 110 to 296: [110, 8, 527, 296] - Total Weight: 12
Path from 110 to 305: [110, 8, 607, 305] - Total Weight: 12
Path from 110 to 457: [110, 8, 610, 457] - Total Weight: 12
Path from 110 to 324: [110, 8, 625, 324] - Total Weight: 12
Path from 110 to 307: [110, 8, 631, 307] - Total Weight: 12
Path from 110 to 692: [110, 8, 653, 692] - Total Weight: 12
Path from 110 to 458: [110, 8, 653, 458] - Total Weight: 12
Path from 111 to 8: [111, 8] - Total Weight: 1
Path from 111 to 686: [111, 8, 686] - Total Weight: 3
Path from 111 to 527: [111, 8, 527] - Total Weight: 3
Path from 111 to 530: [111, 8, 530] - Total Weight: 3
Path from 111 to 531: [111, 8, 531] - Total Weight: 3
Path from 111 to 532: [111, 8, 532] - Total Weight: 3
Path from 111 to 553: [111, 8, 553] - Total Weight: 3
Path from 111 to 607: [111, 8, 607] - Total Weight: 3
Path from 111 to 610: [111, 8, 610] - Total Weight: 3
Path from 111 to 625: [111, 8, 625] - Total Weight: 3
Path from 111 to 631: [111, 8, 631] - Total Weight: 3
Path from 111 to 632: [111, 8, 632] - Total Weight: 3
Path from 111 to 640: [111, 8, 640] - Total Weight: 3
Path from 111 to 645: [111, 8, 645] - Total Weight: 3
Path from 111 to 653: [111, 8, 653] - Total Weight: 3
Path from 111 to 663: [111, 8, 663] - Total Weight: 3
Path from 111 to 303: [111, 8, 686, 303] - Total Weight: 12
Path from 111 to 296: [111, 8, 527, 296] - Total Weight: 12
Path from 111 to 305: [111, 8, 607, 305] - Total Weight: 12
Path from 111 to 457: [111, 8, 610, 457] - Total Weight: 12
Path from 111 to 324: [111, 8, 625, 324] - Total Weight: 12
Path from 111 to 307: [111, 8, 631, 307] - Total Weight: 12
Path from 111 to 692: [111, 8, 653, 692] - Total Weight: 12
Path from 111 to 458: [111, 8, 653, 458] - Total Weight: 12
Path from 135 to 9: [135, 9] - Total Weight: 1
Path from 137 to 4: [137, 4] - Total Weight: 1
Path from 137 to 7: [137, 4, 7] - Total Weight: 3
Path from 137 to 8: [137, 4, 8] - Total Weight: 3
Path from 137 to 9: [137, 4, 9] - Total Weight: 3
Path from 137 to 10: [137, 4, 10] - Total Weight: 3
Path from 137 to 692: [137, 4, 7, 692] - Total Weight: 5
Path from 137 to 295: [137, 4, 7, 295] - Total Weight: 5
Path from 137 to 303: [137, 4, 7, 303] - Total Weight: 5
Path from 137 to 306: [137, 4, 7, 306] - Total Weight: 5
Path from 137 to 307: [137, 4, 7, 307] - Total Weight: 5
Path from 137 to 324: [137, 4, 7, 324] - Total Weight: 5
Path from 137 to 457: [137, 4, 7, 457] - Total Weight: 5
Path from 137 to 458: [137, 4, 7, 458] - Total Weight: 5
Path from 137 to 469: [137, 4, 7, 469] - Total Weight: 5
Path from 137 to 686: [137, 4, 8, 686] - Total Weight: 5
Path from 137 to 527: [137, 4, 8, 527] - Total Weight: 5
Path from 137 to 530: [137, 4, 8, 530] - Total Weight: 5
Path from 137 to 531: [137, 4, 8, 531] - Total Weight: 5
Path from 137 to 532: [137, 4, 8, 532] - Total Weight: 5
Path from 137 to 553: [137, 4, 8, 553] - Total Weight: 5
Path from 137 to 607: [137, 4, 8, 607] - Total Weight: 5
Path from 137 to 610: [137, 4, 8, 610] - Total Weight: 5
Path from 137 to 625: [137, 4, 8, 625] - Total Weight: 5
Path from 137 to 631: [137, 4, 8, 631] - Total Weight: 5
Path from 137 to 632: [137, 4, 8, 632] - Total Weight: 5
Path from 137 to 640: [137, 4, 8, 640] - Total Weight: 5
Path from 137 to 645: [137, 4, 8, 645] - Total Weight: 5
Path from 137 to 653: [137, 4, 8, 653] - Total Weight: 5
Path from 137 to 663: [137, 4, 8, 663] - Total Weight: 5
Path from 137 to 296: [137, 4, 10, 296] - Total Weight: 5
Path from 137 to 305: [137, 4, 10, 305] - Total Weight: 5
Path from 139 to 9: [139, 9] - Total Weight: 1
Path from 141 to 10: [141, 10] - Total Weight: 1
Path from 141 to 296: [141, 10, 296] - Total Weight: 3
Path from 141 to 305: [141, 10, 305] - Total Weight: 3
Path from 147 to 4: [147, 4] - Total Weight: 1
Path from 147 to 7: [147, 4, 7] - Total Weight: 3
Path from 147 to 8: [147, 4, 8] - Total Weight: 3
Path from 147 to 9: [147, 4, 9] - Total Weight: 3
Path from 147 to 10: [147, 4, 10] - Total Weight: 3
Path from 147 to 692: [147, 4, 7, 692] - Total Weight: 5
Path from 147 to 295: [147, 4, 7, 295] - Total Weight: 5
Path from 147 to 303: [147, 4, 7, 303] - Total Weight: 5
Path from 147 to 306: [147, 4, 7, 306] - Total Weight: 5
Path from 147 to 307: [147, 4, 7, 307] - Total Weight: 5
Path from 147 to 324: [147, 4, 7, 324] - Total Weight: 5
Path from 147 to 457: [147, 4, 7, 457] - Total Weight: 5
Path from 147 to 458: [147, 4, 7, 458] - Total Weight: 5
Path from 147 to 469: [147, 4, 7, 469] - Total Weight: 5
Path from 147 to 686: [147, 4, 8, 686] - Total Weight: 5
Path from 147 to 527: [147, 4, 8, 527] - Total Weight: 5
Path from 147 to 530: [147, 4, 8, 530] - Total Weight: 5
Path from 147 to 531: [147, 4, 8, 531] - Total Weight: 5
Path from 147 to 532: [147, 4, 8, 532] - Total Weight: 5
Path from 147 to 553: [147, 4, 8, 553] - Total Weight: 5
Path from 147 to 607: [147, 4, 8, 607] - Total Weight: 5
Path from 147 to 610: [147, 4, 8, 610] - Total Weight: 5
Path from 147 to 625: [147, 4, 8, 625] - Total Weight: 5
Path from 147 to 631: [147, 4, 8, 631] - Total Weight: 5
Path from 147 to 632: [147, 4, 8, 632] - Total Weight: 5
Path from 147 to 640: [147, 4, 8, 640] - Total Weight: 5
Path from 147 to 645: [147, 4, 8, 645] - Total Weight: 5
Path from 147 to 653: [147, 4, 8, 653] - Total Weight: 5
Path from 147 to 663: [147, 4, 8, 663] - Total Weight: 5
Path from 147 to 296: [147, 4, 10, 296] - Total Weight: 5
Path from 147 to 305: [147, 4, 10, 305] - Total Weight: 5
Path from 160 to 9: [160, 9] - Total Weight: 1
Path from 172 to 4: [172, 4] - Total Weight: 1
Path from 172 to 7: [172, 4, 7] - Total Weight: 3
Path from 172 to 8: [172, 4, 8] - Total Weight: 3
Path from 172 to 9: [172, 4, 9] - Total Weight: 3
Path from 172 to 10: [172, 4, 10] - Total Weight: 3
Path from 172 to 692: [172, 4, 7, 692] - Total Weight: 5
Path from 172 to 295: [172, 4, 7, 295] - Total Weight: 5
Path from 172 to 303: [172, 4, 7, 303] - Total Weight: 5
Path from 172 to 306: [172, 4, 7, 306] - Total Weight: 5
Path from 172 to 307: [172, 4, 7, 307] - Total Weight: 5
Path from 172 to 324: [172, 4, 7, 324] - Total Weight: 5
Path from 172 to 457: [172, 4, 7, 457] - Total Weight: 5
Path from 172 to 458: [172, 4, 7, 458] - Total Weight: 5
Path from 172 to 469: [172, 4, 7, 469] - Total Weight: 5
Path from 172 to 686: [172, 4, 8, 686] - Total Weight: 5
Path from 172 to 527: [172, 4, 8, 527] - Total Weight: 5
Path from 172 to 530: [172, 4, 8, 530] - Total Weight: 5
Path from 172 to 531: [172, 4, 8, 531] - Total Weight: 5
Path from 172 to 532: [172, 4, 8, 532] - Total Weight: 5
Path from 172 to 553: [172, 4, 8, 553] - Total Weight: 5
Path from 172 to 607: [172, 4, 8, 607] - Total Weight: 5
Path from 172 to 610: [172, 4, 8, 610] - Total Weight: 5
Path from 172 to 625: [172, 4, 8, 625] - Total Weight: 5
Path from 172 to 631: [172, 4, 8, 631] - Total Weight: 5
Path from 172 to 632: [172, 4, 8, 632] - Total Weight: 5
Path from 172 to 640: [172, 4, 8, 640] - Total Weight: 5
Path from 172 to 645: [172, 4, 8, 645] - Total Weight: 5
Path from 172 to 653: [172, 4, 8, 653] - Total Weight: 5
Path from 172 to 663: [172, 4, 8, 663] - Total Weight: 5
Path from 172 to 296: [172, 4, 10, 296] - Total Weight: 5
Path from 172 to 305: [172, 4, 10, 305] - Total Weight: 5
Path from 179 to 10: [179, 10] - Total Weight: 1
Path from 179 to 296: [179, 10, 296] - Total Weight: 3
Path from 179 to 305: [179, 10, 305] - Total Weight: 3
Path from 184 to 10: [184, 10] - Total Weight: 1
Path from 184 to 296: [184, 10, 296] - Total Weight: 3
Path from 184 to 305: [184, 10, 305] - Total Weight: 3
Path from 186 to 10: [186, 10] - Total Weight: 1
Path from 186 to 296: [186, 10, 296] - Total Weight: 3
Path from 186 to 305: [186, 10, 305] - Total Weight: 3
Path from 187 to 10: [187, 10] - Total Weight: 1
Path from 187 to 296: [187, 10, 296] - Total Weight: 3
Path from 187 to 305: [187, 10, 305] - Total Weight: 3
Path from 188 to 10: [188, 10] - Total Weight: 1
Path from 188 to 296: [188, 10, 296] - Total Weight: 3
Path from 188 to 305: [188, 10, 305] - Total Weight: 3
Path from 200 to 7: [200, 7] - Total Weight: 1
Path from 200 to 692: [200, 7, 692] - Total Weight: 3
Path from 200 to 295: [200, 7, 295] - Total Weight: 3
Path from 200 to 303: [200, 7, 303] - Total Weight: 3
Path from 200 to 306: [200, 7, 306] - Total Weight: 3
Path from 200 to 307: [200, 7, 307] - Total Weight: 3
Path from 200 to 324: [200, 7, 324] - Total Weight: 3
Path from 200 to 457: [200, 7, 457] - Total Weight: 3
Path from 200 to 458: [200, 7, 458] - Total Weight: 3
Path from 200 to 469: [200, 7, 469] - Total Weight: 3
Path from 208 to 4: [208, 4] - Total Weight: 1
Path from 208 to 7: [208, 4, 7] - Total Weight: 3
Path from 208 to 8: [208, 4, 8] - Total Weight: 3
Path from 208 to 9: [208, 4, 9] - Total Weight: 3
Path from 208 to 10: [208, 4, 10] - Total Weight: 3
Path from 208 to 692: [208, 4, 7, 692] - Total Weight: 5
Path from 208 to 295: [208, 4, 7, 295] - Total Weight: 5

In [86]:
# prompt: show me the top 10 weights from path_info['total_weight']

# Sort the paths by total weight in descending order
sorted_paths_by_weight = sorted(shortest_paths_with_weight, key=lambda x: x['total_weight'], reverse=True)

# Get the top 10 paths
top_10_paths = sorted_paths_by_weight[:10]

# Print the top 10 paths and their weights
print("\nTop 10 Paths by Total Weight:")
for path_info in top_10_paths:
    print(f"Path from {path_info['source']} to {path_info['target']}: {path_info['path']} - Total Weight: {path_info['total_weight']}")

Top 10 Paths by Total Weight:
Path from 60 to 303: [60, 8, 686, 303] - Total Weight: 20
Path from 60 to 296: [60, 8, 527, 296] - Total Weight: 20
Path from 60 to 305: [60, 8, 607, 305] - Total Weight: 20
Path from 60 to 457: [60, 8, 610, 457] - Total Weight: 20
Path from 60 to 324: [60, 8, 625, 324] - Total Weight: 20
Path from 60 to 307: [60, 8, 631, 307] - Total Weight: 20
Path from 60 to 692: [60, 8, 653, 692] - Total Weight: 20
Path from 60 to 458: [60, 8, 653, 458] - Total Weight: 20
Path from 869 to 303: [869, 8, 686, 303] - Total Weight: 13
Path from 869 to 296: [869, 8, 527, 296] - Total Weight: 13

In [87]:
# prompt:  show me the top 10 minimum  weights from path_info['total_weight']

# Sort the paths by total weight in ascending order
sorted_paths_by_weight_min = sorted(shortest_paths_with_weight, key=lambda x: x['total_weight'], reverse=False)

# Get the top 10 paths with minimum weights
top_10_min_paths = sorted_paths_by_weight_min[:10]

# Print the top 10 minimum paths and their weights
print("\nTop 10 Paths by Minimum Total Weight:")
for path_info in top_10_min_paths:
    print(f"Path from {path_info['source']} to {path_info['target']}: {path_info['path']} - Total Weight: {path_info['total_weight']}")

Top 10 Paths by Minimum Total Weight:
Path from 110 to 8: [110, 8] - Total Weight: 1
Path from 111 to 8: [111, 8] - Total Weight: 1
Path from 135 to 9: [135, 9] - Total Weight: 1
Path from 137 to 4: [137, 4] - Total Weight: 1
Path from 139 to 9: [139, 9] - Total Weight: 1
Path from 141 to 10: [141, 10] - Total Weight: 1
Path from 147 to 4: [147, 4] - Total Weight: 1
Path from 160 to 9: [160, 9] - Total Weight: 1
Path from 172 to 4: [172, 4] - Total Weight: 1
Path from 179 to 10: [179, 10] - Total Weight: 1

In [88]:
# prompt: show me the top 10 numbers that appears most in path_info['path']

from collections import Counter

# Extract all numbers from the 'path' lists
all_numbers_in_paths = [number for path_info in shortest_paths_list for number in path_info['path']]

# Count the occurrences of each number
number_counts = Counter(all_numbers_in_paths)

# Get the top 10 most common numbers and their counts
top_10_numbers = number_counts.most_common(10)

# Print the top 10 numbers and their counts
print("Top 10 numbers appearing most in path_info['path']:")
for number, count in top_10_numbers:
    print(f"Number: {number}, Count: {count}")

Top 10 numbers appearing most in path_info['path']:
Number: 8, Count: 287
Number: 4, Count: 185
Number: 7, Count: 119
Number: 10, Count: 56
Number: 1, Count: 31
Number: 137, Count: 31
Number: 147, Count: 31
Number: 172, Count: 31
Number: 208, Count: 31
Number: 653, Count: 29

In [120]:
# prompt: find paths from path_info['path'] that include the 1st entry in top_10_numbers with the highest and lowest weight

# Get the first number from the top 10 list
if top_10_numbers:
    target_number = top_10_numbers[1][0]
    print(f"\nSearching for paths containing the number: {target_number}")

    # Filter paths that include the target number
    paths_with_target = [
        path_info for path_info in shortest_paths_with_weight
        if target_number in path_info['path']
    ]

    if paths_with_target:
        print(f"\nPaths containing the number {target_number}:")
        print(nodes[nodes['id'] == target_number]['properties'].iloc[0]['distinguishedname'])

        # Sort the filtered paths by total weight in descending order
        paths_with_target_sorted_desc = sorted(paths_with_target, key=lambda x: x['total_weight'], reverse=True)

        # Get the path with the highest weight that includes the target number
        highest_weight_path_with_target = paths_with_target_sorted_desc[0]

        print(f"\nPath with the HIGHEST weight containing {target_number}:")
        print(f"Path from {highest_weight_path_with_target['source']} to {highest_weight_path_with_target['target']}: {highest_weight_path_with_target['path']} - Total Weight: {highest_weight_path_with_target['total_weight']}")

        # Sort the filtered paths by total weight in ascending order
        paths_with_target_sorted_asc = sorted(paths_with_target, key=lambda x: x['total_weight'], reverse=False)

        # Get the path with the lowest weight that includes the target number
        lowest_weight_path_with_target = paths_with_target_sorted_asc[0]

        print(f"\nPath with the LOWEST weight containing {target_number}:")
        print(f"Path from {lowest_weight_path_with_target['source']} to {lowest_weight_path_with_target['target']}: {lowest_weight_path_with_target['path']} - Total Weight: {lowest_weight_path_with_target['total_weight']}")


    else:
        print(f"No paths found containing the number {target_number}.")
else:
    print("The top_10_numbers list is empty.")

Searching for paths containing the number: 4

Paths containing the number 4:
OU=T0 ADMIN,DC=MARK,DC=LOCAL

Path with the HIGHEST weight containing 4:
Path from 1 to 692: [1, 4, 7, 692] - Total Weight: 6

Path with the LOWEST weight containing 4:
Path from 137 to 4: [137, 4] - Total Weight: 1

In [118]:
# prompt: for each value pair in highest_weight_path_with_target print out the corresponding edge record, eg if path contains 60,8,686,303, then pick out the 1st two values 60 and 8 and find the corresponding record in edges start and end

print("\nEdge records for the highest weight path containing the target number:")
path = highest_weight_path_with_target['path']
for i in range(len(path) - 1):
    start_node = path[i]
    end_node = path[i+1]
    # Find the corresponding edge record
    edge_record = edges[(edges['start'] == start_node) & (edges['end'] == end_node)]
    if not edge_record.empty:
        print(edge_record.iloc[0].to_dict())
        print(f"Start Node: ", start_node )
        print(nodes[nodes['id'] == start_node]['properties'].iloc[0]['distinguishedname'])
        print(f"End Node: ", end_node )
        print(nodes[nodes['id'] == end_node]['properties'].iloc[0]['distinguishedname'])
        print("-------------------------------------------")
    else:
        print(f"No edge found between nodes {start_node} and {end_node}")

Edge records for the highest weight path containing the target number:
{'type': 'relationship', 'start': 1, 'end': 4, 'label': 'Contains', 'weight': 2, 'id': 3}
Start Node:  1
OU=ADMIN,DC=MARK,DC=LOCAL
End Node:  4
OU=T0 ADMIN,DC=MARK,DC=LOCAL
-------------------------------------------
{'type': 'relationship', 'start': 4, 'end': 7, 'label': 'Contains', 'weight': 2, 'id': 6}
Start Node:  4
OU=T0 ADMIN,DC=MARK,DC=LOCAL
End Node:  7
OU=T0 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL
-------------------------------------------
{'type': 'relationship', 'start': 7, 'end': 692, 'label': 'Contains', 'weight': 2, 'id': 1425}
Start Node:  7
OU=T0 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL
End Node:  692
CN=T0 DEFAULT ADMIN USER,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL
-------------------------------------------

In [117]:
# prompt: how would i print out nodes['distinguishedname'] and nodes['start] when nodes[nodes['id'] == start_node]

# Access the row where the 'id' column matches start_node
node_row = nodes[nodes['id'] == start_node]

# Check if a matching row was found
if not node_row.empty:
    # Access the 'properties' dictionary within that row and then the 'distinguishedname' key
    distinguished_name = node_row['properties'].iloc[0].get('distinguishedname')
    start_value = node_row['start'].iloc[0] # Access the 'start' column directly

    # Print the values
    print(f"Distinguished Name: {distinguished_name}")
    print(f"Start: {start_value}")
else:
    print(f"Node with ID {start_node} not found.")

KeyError: 'start'

In [111]:

print("\nEdge records for the lowest weight path containing the target number:")
path = lowest_weight_path_with_target['path']
for i in range(len(path) - 1):
    start_node = path[i]
    end_node = path[i+1]
    # Find the corresponding edge record
    edge_record = edges[(edges['start'] == start_node) & (edges['end'] == end_node)]
    if not edge_record.empty:
        print(edge_record.iloc[0].to_dict())
        print(nodes[nodes['id'] == start_node])
        print(nodes[nodes['id'] == end_node])
    else:
        print(f"No edge found between nodes {start_node} and {end_node}")

Edge records for the lowest weight path containing the target number:
{'type': 'relationship', 'start': 137, 'end': 4, 'label': 'GpLink', 'weight': 1, 'id': 139}
      id  \
137  137

                                                                                                                                                                                                  properties  \
137  {'domain': 'MARK.LOCAL', 'name': 'Network_Restriction_23@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-366cbb81-f13b-490d-9207-67a0ff5d207d', 'exploitable': False, 'owned': False}

     type    l1   l2    l3  weight
137  node  Base  GPO  None       1
   id  \
4   4

                                                                                                                                                                                                                                                                                      properties  \
4  {'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f249f685-d5e0-4dad-b5b5-7f723c41ca1e', 'distinguishedname': 'OU=T0 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}

   type    l1  l2    l3  weight
4  node  Base  OU  None      20

In [95]:
print(nodes[nodes['id'] == 110])

      id  \
110  110

                                                                                                                                                                       properties  \
110  {'domain': 'MARK.LOCAL', 'name': 'PAW Configuration@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-d37c9c32-7ad3-4495-862c-b8c9734a1860', 'owned': False}

     type    l1   l2    l3  weight
110  node  Base  GPO  None       1

In [ ]:
# prompt: convert shortest_paths_with_weight to dataframe called df_shortest_paths_with_weight

import pandas as pd
df_shortest_paths_with_weight = pd.DataFrame(shortest_paths_with_weight)

In [ ]:
df_shortest_paths_with_weight

,source,target,path,weight,total_weight
0,3,481,"[3, 23, 29, 481]",NaN,6
1,3,331,"[3, 24, 26, 331]",NaN,6
2,3,341,"[3, 24, 26, 341]",NaN,6
3,3,357,"[3, 24, 26, 357]",NaN,6
4,3,405,"[3, 24, 26, 405]",NaN,6
...,...,...,...,...,...
979,873,405,"[873, 28, 516, 405]",NaN,19
980,873,341,"[873, 28, 571, 341]",NaN,19
981,873,331,"[873, 28, 581, 331]",NaN,19
982,873,8,"[873, 28, 492, 386, 705, 97, 711, 869, 8]",NaN,30
983,873,481,"[873, 28, 492, 386, 705, 97, 711, 869, 29, 481]",NaN,38

In [ ]:
# prompt: for each source find minimum weight and target. if weight is the same print out all instances

import pandas as pd
# Group by source and find the minimum weight
min_weights = df_shortest_paths_with_weight.groupby('source')['total_weight'].min().reset_index()

# Merge with the original DataFrame to get rows with the minimum weight
result_min = pd.merge(df_shortest_paths_with_weight, min_weights, on=['source', 'total_weight'])

# Print the results
# for index, row in result.iterrows():
#   print(f"Source: {row['source']}, Target: {row['target']}, Minimum Weight: {row['total_weight']}, Path: {row['path']}")

In [ ]:
# prompt: for each source find minimum weight and target. if weight is the same print out all instances

import pandas as pd
# Group by source and find the minimum weight
max_weights = df_shortest_paths_with_weight.groupby('source')['total_weight'].max().reset_index()

# Merge with the original DataFrame to get rows with the minimum weight
result_max = pd.merge(df_shortest_paths_with_weight, max_weights, on=['source', 'total_weight'])

# Print the results
# for index, row in result.iterrows():
#   print(f"Source: {row['source']}, Target: {row['target']}, Max Weight: {row['total_weight']}, Path: {row['path']}")
# df_shortest_paths_with_weight = pd.DataFrame(shortest_paths_with_weight)
# df_shortest_paths_with_weight

In [ ]:
result_min

     source  target                 path  weight  total_weight
0         3     481     [3, 23, 29, 481]     NaN             6
1         3     331     [3, 24, 26, 331]     NaN             6
2         3     341     [3, 24, 26, 341]     NaN             6
3         3     357     [3, 24, 26, 357]     NaN             6
4         3     405     [3, 24, 26, 405]     NaN             6
..      ...     ...                  ...     ...           ...
449     873     357  [873, 28, 498, 357]     NaN            19
450     873     448  [873, 28, 498, 448]     NaN            19
451     873     405  [873, 28, 516, 405]     NaN            19
452     873     341  [873, 28, 571, 341]     NaN            19
453     873     331  [873, 28, 581, 331]     NaN            19

[454 rows x 5 columns]

In [ ]:
result_max

,source,target,path,weight,total_weight
0,3,8,"[3, 22, 32, 711, 869, 8]",NaN,10
1,6,444,"[6, 17, 97, 26, 444]",NaN,13
2,6,448,"[6, 17, 97, 26, 448]",NaN,13
3,6,357,"[6, 17, 97, 26, 357]",NaN,13
4,6,405,"[6, 17, 97, 26, 405]",NaN,13
...,...,...,...,...,...
250,870,8,"[870, 30, 495, 377, 705, 97, 711, 869, 8]",NaN,30
251,871,481,"[871, 30, 495, 377, 705, 97, 711, 869, 29, 481]",NaN,38
252,872,341,"[872, 30, 495, 377, 705, 97, 26, 341]",NaN,30
253,872,8,"[872, 30, 495, 377, 705, 97, 711, 869, 8]",NaN,30
254,873,481,"[873, 28, 492, 386, 705, 97, 711, 869, 29, 481]",NaN,38

In [ ]:
# prompt: show me where source appears the most within the results_max dataframe. is ther one source that appears most

source_counts = result_max['source'].value_counts()

print("Count of each source in result_max:")
print(source_counts)

most_frequent_source = source_counts.index[0]
most_frequent_count = source_counts.iloc[0]

print(f"\nThe source that appears most frequently is: {most_frequent_source} with a count of {most_frequent_count}")

if most_frequent_count > 1:
  print("Yes, there is one source that appears most.")
else:
  print("No single source appears most frequently (or all sources appear only once).")

Count of each source in result_max:
source
6      7
22     7
16     7
321    7
313    7
      ..
705    1
868    1
870    1
871    1
873    1
Name: count, Length: 137, dtype: int64

The source that appears most frequently is: 6 with a count of 7
Yes, there is one source that appears most.

In [ ]:
# prompt: convert result into a DataFrame

import pandas as pd
df_shortest_paths_with_weight = pd.DataFrame(shortest_paths_with_weight)
df_shortest_paths_with_weight

,source,target,path,weight,total_weight
0,3,481,"[3, 23, 29, 481]",NaN,6
1,3,331,"[3, 24, 26, 331]",NaN,6
2,3,341,"[3, 24, 26, 341]",NaN,6
3,3,357,"[3, 24, 26, 357]",NaN,6
4,3,405,"[3, 24, 26, 405]",NaN,6
...,...,...,...,...,...
979,873,405,"[873, 28, 516, 405]",NaN,19
980,873,341,"[873, 28, 571, 341]",NaN,19
981,873,331,"[873, 28, 581, 331]",NaN,19
982,873,8,"[873, 28, 492, 386, 705, 97, 711, 869, 8]",NaN,30
983,873,481,"[873, 28, 492, 386, 705, 97, 711, 869, 29, 481]",NaN,38

In [ ]:
print(edges[edges['end'] == 301])

        id properties          type  start  end       label  weight
1448  1448         {}  relationship     15  301    Contains       2
3099  3099         {}  relationship    637  301  HasSession       9

In [ ]:
shortest_paths_with_weight

[{'source': 3,
  'target': 481,
  'path': [3, 23, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 331,
  'path': [3, 24, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 341,
  'path': [3, 24, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 357,
  'path': [3, 24, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 405,
  'path': [3, 24, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 444,
  'path': [3, 24, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 448,
  'path': [3, 24, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 392,
  'path': [3, 24, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 3,
  'target': 8,
  'path': [3, 22, 32, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(10)},
 {'source': 6,
  'target': 301,
  'path': [6, 15, 301],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 6,
  'target': 318,
  'path': [6, 15, 318],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 6,
  'target': 392,
  'path': [6, 17, 96, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(8)},
 {'source': 6,
  'target': 481,
  'path': [6, 17, 96, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(9)},
 {'source': 6,
  'target': 444,
  'path': [6, 17, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 6,
  'target': 448,
  'path': [6, 17, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 6,
  'target': 357,
  'path': [6, 17, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 6,
  'target': 405,
  'path': [6, 17, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 6,
  'target': 341,
  'path': [6, 17, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 6,
  'target': 331,
  'path': [6, 17, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 6,
  'target': 8,
  'path': [6, 17, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 15,
  'target': 301,
  'path': [15, 301],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 15,
  'target': 318,
  'path': [15, 318],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 15,
  'target': 392,
  'path': [15, 694, 96, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(7)},
 {'source': 15,
  'target': 481,
  'path': [15, 694, 96, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(8)},
 {'source': 15,
  'target': 444,
  'path': [15, 293, 95, 30, 486, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 15,
  'target': 448,
  'path': [15, 293, 95, 30, 494, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 15,
  'target': 357,
  'path': [15, 293, 95, 30, 499, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 15,
  'target': 405,
  'path': [15, 293, 95, 30, 630, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 15,
  'target': 331,
  'path': [15, 694, 96, 29, 490, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(17)},
 {'source': 15,
  'target': 8,
  'path': [15, 694, 96, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 15,
  'target': 341,
  'path': [15, 293, 95, 697, 705, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(18)},
 {'source': 16,
  'target': 301,
  'path': [16, 637, 301],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 16,
  'target': 392,
  'path': [16, 688, 320, 96, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 16,
  'target': 481,
  'path': [16, 688, 320, 96, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(17)},
 {'source': 16,
  'target': 444,
  'path': [16, 688, 322, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 16,
  'target': 357,
  'path': [16, 688, 322, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 16,
  'target': 448,
  'path': [16, 688, 322, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 16,
  'target': 405,
  'path': [16, 688, 322, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 16,
  'target': 341,
  'path': [16, 688, 322, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 16,
  'target': 331,
  'path': [16, 688, 322, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 16,
  'target': 8,
  'path': [16, 688, 322, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 17,
  'target': 392,
  'path': [17, 96, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 17,
  'target': 481,
  'path': [17, 96, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(7)},
 {'source': 17,
  'target': 444,
  'path': [17, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 448,
  'path': [17, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 357,
  'path': [17, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 405,
  'path': [17, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 341,
  'path': [17, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 331,
  'path': [17, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 8,
  'path': [17, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 17,
  'target': 301,
  'path': [17, 94, 16, 637, 301],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 18,
  'target': 444,
  'path': [18, 311, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 357,
  'path': [18, 311, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 448,
  'path': [18, 311, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 405,
  'path': [18, 311, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 341,
  'path': [18, 311, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 331,
  'path': [18, 311, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 8,
  'path': [18, 311, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(12)},
 {'source': 18,
  'target': 481,
  'path': [18, 311, 97, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(20)},
 {'source': 22,
  'target': 8,
  'path': [22, 32, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(8)},
 {'source': 22,
  'target': 444,
  'path': [22, 31, 697, 705, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 22,
  'target': 357,
  'path': [22, 31, 697, 705, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 22,
  'target': 448,
  'path': [22, 31, 697, 705, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 22,
  'target': 405,
  'path': [22, 31, 697, 705, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 22,
  'target': 341,
  'path': [22, 31, 697, 705, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 22,
  'target': 331,
  'path': [22, 31, 697, 705, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 22,
  'target': 481,
  'path': [22, 32, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(16)},
 {'source': 23,
  'target': 481,
  'path': [23, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 23,
  'target': 444,
  'path': [23, 28, 496, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 23,
  'target': 357,
  'path': [23, 28, 498, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 23,
  'target': 448,
  'path': [23, 28, 498, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 23,
  'target': 405,
  'path': [23, 28, 516, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 23,
  'target': 341,
  'path': [23, 28, 571, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 23,
  'target': 331,
  'path': [23, 28, 581, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 23,
  'target': 8,
  'path': [23, 28, 492, 386, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(24)},
 {'source': 24,
  'target': 331,
  'path': [24, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 341,
  'path': [24, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 357,
  'path': [24, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 405,
  'path': [24, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 444,
  'path': [24, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 448,
  'path': [24, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 392,
  'path': [24, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 24,
  'target': 8,
  'path': [24, 26, 331, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(15)},
 {'source': 24,
  'target': 481,
  'path': [24, 26, 331, 705, 97, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 25,
  'target': 444,
  'path': [25, 35, 668, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 26,
  'target': 331,
  'path': [26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 26,
  'target': 341,
  'path': [26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 26,
  'target': 357,
  'path': [26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 26,
  'target': 405,
  'path': [26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 26,
  'target': 444,
  'path': [26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 26,
  'target': 448,
  'path': [26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 26,
  'target': 8,
  'path': [26, 331, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 26,
  'target': 481,
  'path': [26, 331, 705, 97, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(21)},
 {'source': 27,
  'target': 392,
  'path': [27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 28,
  'target': 444,
  'path': [28, 496, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 28,
  'target': 357,
  'path': [28, 498, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 28,
  'target': 448,
  'path': [28, 498, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 28,
  'target': 405,
  'path': [28, 516, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 28,
  'target': 341,
  'path': [28, 571, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 28,
  'target': 331,
  'path': [28, 581, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 28,
  'target': 8,
  'path': [28, 492, 386, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 28,
  'target': 481,
  'path': [28, 492, 386, 705, 97, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(30)},
 {'source': 29,
  'target': 481,
  'path': [29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(2)},
 {'source': 29,
  'target': 331,
  'path': [29, 490, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 29,
  'target': 357,
  'path': [29, 517, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 29,
  'target': 448,
  'path': [29, 517, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 29,
  'target': 444,
  'path': [29, 490, 331, 705, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 29,
  'target': 405,
  'path': [29, 490, 331, 705, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 29,
  'target': 341,
  'path': [29, 490, 331, 705, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 29,
  'target': 8,
  'path': [29, 490, 331, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 30,
  'target': 444,
  'path': [30, 486, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 30,
  'target': 448,
  'path': [30, 494, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 30,
  'target': 357,
  'path': [30, 499, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 30,
  'target': 405,
  'path': [30, 630, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 30,
  'target': 341,
  'path': [30, 495, 377, 705, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 30,
  'target': 331,
  'path': [30, 495, 377, 705, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 30,
  'target': 8,
  'path': [30, 495, 377, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 30,
  'target': 481,
  'path': [30, 495, 377, 705, 97, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(30)},
 {'source': 31,
  'target': 444,
  'path': [31, 697, 705, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 357,
  'path': [31, 697, 705, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 448,
  'path': [31, 697, 705, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 405,
  'path': [31, 697, 705, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 341,
  'path': [31, 697, 705, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 331,
  'path': [31, 697, 705, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 8,
  'path': [31, 697, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 31,
  'target': 481,
  'path': [31, 697, 705, 97, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(22)},
 {'source': 32,
  'target': 8,
  'path': [32, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(6)},
 {'source': 32,
  'target': 481,
  'path': [32, 711, 869, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(14)},
 {'source': 32,
  'target': 444,
  'path': [32, 711, 868, 28, 496, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 32,
  'target': 357,
  'path': [32, 711, 868, 28, 498, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 32,
  'target': 448,
  'path': [32, 711, 868, 28, 498, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 32,
  'target': 405,
  'path': [32, 711, 868, 28, 516, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 32,
  'target': 341,
  'path': [32, 711, 868, 28, 571, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 32,
  'target': 331,
  'path': [32, 711, 868, 28, 581, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(23)},
 {'source': 35,
  'target': 444,
  'path': [35, 668, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(11)},
 {'source': 94,
  'target': 301,
  'path': [94, 16, 637, 301],
  'weight': np.float64(59.0),
  'total_weight': np.int64(19)},
 {'source': 94,
  'target': 392,
  'path': [94, 16, 688, 320, 96, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(24)},
 {'source': 94,
  'target': 481,
  'path': [94, 16, 688, 320, 96, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(25)},
 {'source': 94,
  'target': 444,
  'path': [94, 16, 688, 322, 97, 26, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 94,
  'target': 357,
  'path': [94, 16, 688, 322, 97, 26, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 94,
  'target': 448,
  'path': [94, 16, 688, 322, 97, 26, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 94,
  'target': 405,
  'path': [94, 16, 688, 322, 97, 26, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 94,
  'target': 341,
  'path': [94, 16, 688, 322, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 94,
  'target': 331,
  'path': [94, 16, 688, 322, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 94,
  'target': 8,
  'path': [94, 16, 688, 322, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(29)},
 {'source': 95,
  'target': 444,
  'path': [95, 30, 486, 444],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 95,
  'target': 448,
  'path': [95, 30, 494, 448],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 95,
  'target': 357,
  'path': [95, 30, 499, 357],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 95,
  'target': 405,
  'path': [95, 30, 630, 405],
  'weight': np.float64(nan),
  'total_weight': np.int64(13)},
 {'source': 95,
  'target': 481,
  'path': [95, 29, 481],
  'weight': np.float64(nan),
  'total_weight': np.int64(8)},
 {'source': 95,
  'target': 392,
  'path': [95, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(9)},
 {'source': 95,
  'target': 331,
  'path': [95, 697, 705, 97, 26, 331],
  'weight': np.float64(nan),
  'total_weight': np.int64(15)},
 {'source': 95,
  'target': 341,
  'path': [95, 697, 705, 97, 26, 341],
  'weight': np.float64(nan),
  'total_weight': np.int64(15)},
 {'source': 95,
  'target': 8,
  'path': [95, 697, 705, 97, 711, 869, 8],
  'weight': np.float64(nan),
  'total_weight': np.int64(15)},
 {'source': 96,
  'target': 392,
  'path': [96, 27, 392],
  'weight': np.float64(nan),
  'total_weight': np.int64(4)},
 {'source': 96,
  'target': 481,

In [ ]:
# prompt: for each node in shortest_paths_with_weight, find the minimum total_weight and the maxium total_weight, save it to a DataFrame

import pandas as pd
# Initialize a dictionary to store min and max weights for each target node
target_node_weights = {}

# Iterate through the shortest paths
for path_info in shortest_paths_with_weight:
    target_node = path_info['target']
    total_weight = path_info['total_weight']

    if target_node not in target_node_weights:
        target_node_weights[target_node] = {'min_weight': float('inf'), 'max_weight': float('-inf')}

    # Update min and max weights
    target_node_weights[target_node]['min_weight'] = min(target_node_weights[target_node]['min_weight'], total_weight)
    target_node_weights[target_node]['max_weight'] = max(target_node_weights[target_node]['max_weight'], total_weight)

# Convert the dictionary to a DataFrame
min_max_weights_df = pd.DataFrame.from_dict(target_node_weights, orient='index')
min_max_weights_df.index.name = 'target_node'
min_max_weights_df = min_max_weights_df.reset_index()

# Display the resulting DataFrame
print("\nMin and Max Total Weights for Each Target Node:")
min_max_weights_df

Min and Max Total Weights for Each Target Node:

    target_node  min_weight  max_weight
0           481           2          38
1           331           2          39
2           341           2          39
3           357           2          39
4           405           2          39
5           444           2          39
6           448           2          39
7           392           2          34
8             8           2          39
9           301           2          29
10          318           2           4

In [ ]:
# prompt: for each record in "shortest_paths_filtered" add up the weights and find the smallest and largest combined weights and the path for the largest weight

# Function to calculate the total weight of a path
def calculate_path_weight(graph, path):
    total_weight = 0
    for i in range(len(path) - 1):
        # Add node weight
        total_weight += graph.nodes[path[i]].get('weight', 0)
        # Add edge weight
        total_weight += graph[path[i]][path[i+1]].get('weight', 0)
    # Add the weight of the last node in the path
    if path:
        total_weight += graph.nodes[path[-1]].get('weight', 0)
    return total_weight

all_path_weights = {}

# Iterate through each source and its paths in shortest_paths_filtered
for source, paths_from_source in shortest_paths_list.items():
    all_path_weights[source] = {}
    # Iterate through each target and its path
    for target, path in paths_from_source.items():
        # Calculate the weight of the path using the original graph G
        weight = calculate_path_weight(G, path)
        all_path_weights[source][target] = weight

# Find the smallest and largest combined weights
min_weight = float('inf')
max_weight = float('-inf')
largest_weight_path = None
largest_weight_source = None
largest_weight_target = None

for source, paths_from_source in all_path_weights.items():
    for target, weight in paths_from_source.items():
        if weight < min_weight:
            min_weight_source = source
            min_weight_target = target
            min_weight_path = shortest_paths_filtered[source][target]
            min_weight = weight
        if weight > max_weight:
            max_weight = weight
            largest_weight_source = source
            largest_weight_target = target
            largest_weight_path = shortest_paths_filtered[source][target]

print(f"Smallest combined weight: {min_weight}")
print(f"Path for the smallest weight: {min_weight_path}")
print(f"Source for the smallest weight path: {min_weight_source}")
print(f"Target for the smallest weight path: {min_weight_target}")
print(f"Largest combined weight: {max_weight}")
print(f"Path for the largest weight: {largest_weight_path}")
print(f"Source for the largest weight path: {largest_weight_source}")
print(f"Target for the largest weight path: {largest_weight_target}")

AttributeError: 'list' object has no attribute 'items'

In [ ]:

print(nodes[nodes['id'] == 637])
print(nodes[nodes['id'] == 301])
# print(nodes[nodes['id'] == 94])
# print(nodes[nodes['id'] == 698])
# print(nodes[nodes['id'] == 710])
# print(nodes[nodes['id'] == 91])

      id                                         properties  type    l1  \
637  637  {'name': 'PAW-00018@MARK.LOCAL', 'operatingsys...  node  Base

           l2    l3  weight
637  Computer  None    20.0
      id                                         properties  type    l1    l2  \
301  301  {'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21...  node  Base  User

       l3  weight
301  None    20.0

In [ ]:
selected_nodes

        id  \
3        3
6        6
15      15
16      16
17      17
18      18
22      22
23      23
24      24
25      25
26      26
27      27
28      28
29      29
30      30
31      31
32      32
33      33
34      34
35      35
71      71
83      83
94      94
95      95
96      96
97      97
289    289
290    290
292    292
293    293
294    294
298    298
299    299
300    300
301    301
304    304
308    308
310    310
311    311
312    312
313    313
314    314
316    316
317    317
318    318
320    320
321    321
322    322
325    325
326    326
327    327
328    328
329    329
330    330
331    331
332    332
333    333
334    334
335    335
336    336
337    337
338    338
339    339
340    340
341    341
342    342
343    343
344    344
345    345
346    346
347    347
348    348
349    349
350    350
351    351
352    352
353    353
354    354
355    355
356    356
357    357
358    358
359    359
360    360
361    361
362    362
363    363
364    364
365    365
366    366
367    367
368    368
369    369
370    370
371    371
372    372
373    373
374    374
375    375
376    376
377    377
378    378
379    379
380    380
381    381
382    382
383    383
384    384
385    385
386    386
387    387
388    388
389    389
390    390
391    391
392    392
393    393
394    394
395    395
396    396
397    397
398    398
399    399
400    400
401    401
402    402
403    403
404    404
405    405
406    406
407    407
408    408
409    409
410    410
411    411
412    412
413    413
414    414
415    415
416    416
417    417
418    418
419    419
420    420
421    421
422    422
423    423
424    424
425    425
426    426
427    427
428    428
429    429
430    430
431    431
432    432
433    433
434    434
435    435
436    436
437    437
438    438
439    439
440    440
441    441
442    442
443    443
444    444
445    445
446    446
447    447
448    448
449    449
450    450
451    451
452    452
453    453
454    454
455    455
456    456
462    462
463    463
464    464
465    465
466    466
468    468
470    470
471    471
472    472
473    473
474    474
475    475
476    476
477    477
478    478
479    479
480    480
481    481
482    482
483    483
484    484
485    485
486    486
487    487
488    488
489    489
490    490
492    492
493    493
494    494
495    495
496    496
497    497
498    498
499    499
500    500
501    501
502    502
503    503
504    504
505    505
506    506
507    507
509    509
510    510
511    511
513    513
515    515
516    516
517    517
518    518
519    519
520    520
521    521
522    522
524    524
525    525
526    526
528    528
529    529
533    533
535    535
536    536
537    537
538    538
539    539
540    540
541    541
542    542
543    543
545    545
546    546
547    547
548    548
549    549
551    551
552    552
554    554
555    555
556    556
557    557
558    558
559    559
560    560
562    562
565    565
566    566
567    567
568    568
569    569
570    570
571    571
572    572
573    573
574    574
576    576
578    578
579    579
580    580
581    581
582    582
583    583
584    584
586    586
587    587
588    588
589    589
591    591
592    592
593    593
594    594
595    595
596    596
598    598
601    601
602    602
603    603
604    604
605    605
606    606
608    608
609    609
611    611
612    612
613    613
614    614
615    615
616    616
617    617
618    618
619    619
621    621
622    622
627    627
628    628
629    629
630    630
633    633
634    634
635    635
636    636
637    637
638    638
641    641
642    642
643    643
644    644
646    646
647    647
649    649
652    652
655    655
656    656
657    657
658    658
659    659
660    660
661    661
662    662
664    664
666    666
668    668
672    672
673    673
676    676
688    688
694    694
695    695
696    696
697    697
698    698
699    699
700    700
701    701
702    702
703    703
704    704
705    705
706    706
707    707
708    708
709    709
710    710
711    711
712    712
713    713
714    714
715    715
716    716
717    717
718    718
719    719
720    720
721    721
722    722
723    723
724    724
725    725
726    726
727    727
728    728
729    729
730    730
731    731
732    732
733    733
734    734
735    735
736    736
737    737
738    738
739    739
740    740
741    741
742    742
743    743
744    744
745    745
746    746
747    747
748    748
749    749
750    750
751    751
752    752
753    753
754    754
755    755
756    756
757    757
758    758
759    759
760    760
761    761
762    762
763    763
764    764
765    765
766    766
767    767
768    768
769    769
770    770
771    771
772    772
773    773
774    774
775    775
776    776
777    777
778    778
779    779
780    780
781    781
782    782
783    783
784    784
785    785
786    786
787    787
788    788
789    789
790    790
791    791
792    792
793    793
794    794
795    795
796    796
797    797
798    798
799    799
800    800
801    801
802    802
803    803
804    804
805    805
806    806
807    807
808    808
809    809
810    810
811    811
812    812
813    813
814    814
815    815
816    816
817    817
818    818
819    819
820    820
821    821
822    822
823    823
824    824
825    825
826    826
827    827
828    828
829    829
830    830
831    831
832    832
833    833
834    834
835    835
836    836
837    837
838    838
839    839
840    840
841    841
842    842
843    843
844    844
845    845
846    846
847    847
848    848
849    849
850    850
851    851
852    852
853    853
854    854
855    855
856    856
857    857
858    858
859    859
860    860
861    861
862    862
863    863
864    864
865    865
866    866
867    867
868    868
869    869
870    870
871    871
872    872
873    873
874    874
875    875
876    876
877    877
878    878
879    879
880    880
881    881
882    882
883    883
884    884
885    885
886    886
887    887
888    888
889    889
890    890
891    891
892    892
893    893
894    894
895    895
896    896
897    897
898    898
899    899
900    900
901    901
902    902
903    903
904    904
905    905
906    906
907    907
908    908
909    909
910    910
911    911
912    912
913    913
914    914
915    915
916    916
917    917
918    918
919    919
920    920
921    921
922    922
923    923
924    924
925    925
926    926
927    927
928    928
929    929
930    930
931    931
932    932
933    933
934    934
935    935
936    936
937    937
938    938
939    939
940    940
941    941
942    942
943    943
944    944
945    945
946    946
947    947
948    948
949    949
950    950
951    951
952    952
953    953
954    954
955    955
956    956
957    957
958    958
959    959
960    960
961    961
962    962
963    963
964    964
965    965
966    966
967    967
968    968
969    969
970    970
971    971
972    972
973    973
974    974
975    975
976    976
977    977
978    978
979    979
980    980
981    981
982    982
983    983
984    984
985    985
986    986
987    987
988    988
989    989
990    990
991    991
992    992
993    993
994    994
995    995
996    996
997    997
998    998
999    999
1000  1000
1001  1001
1002  1002
1003  1003
1004  1004
1005  1005
1006  1006
1007  1007
1008  1008
1009  1009
1010  1010
1011  1011
1012  1012
1013  1013
1014  1014
1015  1015
1016  1016
1017  1017
1018  1018
1019  1019
1020  1020
1021  1021
1022  1022
1023  1023
1024  1024
1025  1025
1026  1026
1027  1027
1028  1028
1029  1029
1030  1030
1031  1031
1032  1032
1033  1033
1034  1034
1035  1035
1036  1036
1037  1037
1038  1038
1039  1039
1040  1040
1041  1041
1042  1042
1043  1043
1044  1044
1045  1045
1046  1046
1047  1047
1048  1048
1049  1049
1050  1050
1051  1051
1052  1052
1053  1053
1054  1054
1055  1055
1056  1056
1057  1057
1058  1058
1059  1059
1060  1060
1061  1061
1062  1062
1063  1063
1064  1064
1065  1065
1066  1066
1067  1067
1068  1068
1069  1069
1070  1070
1071  1071
1072  1072
1073  1073
1074  1074
1075  1075
1076  1076
1077  1077
1078  1078
1079  1079
1080  1080
1081  1081
1082  1082
1083  1083
1084  1084
1085  1085
1086  1086
1087  1087
1088  1088
1089  1089
1090  1090
1091  1091
1092  1092
1093  1093
1094  1094
1095  1095
1096  1096
1097  1097
1098  1098
1099  1099
1100  1100
1101  1101
1102  1102
1103  1103
1104  1104
1105  1105
1106  1106
1107  1107
1108  1108
1109  1109
1110  1110
1111  1111
1112  1112
1113  1113
1114  1114
1115  1115
1116  1116
1117  1117
1118  1118
1119  1119
1120  1120
1121  1121
1122  1122
1123  1123
1124  1124
1125  1125
1126  1126
1127  1127
1128  1128
1129  1129
1130  1130
1131  1131
1132  1132
1133  1133
1134  1134
1135  1135
1136  1136
1137  1137
1138  1138
1139  1139
1140  1140
1141  1141
1142  1142
1143  1143
1144  1144
1145  1145
1146  1146
1147  1147
1148  1148
1149  1149
1150  1150
1151  1151
1152  1152
1153  1153
1154  1154
1155  1155
1156  1156
1157  1157
1158  1158
1159  1159
1160  1160
1161  1161
1162  1162
1163  1163
1164  1164
1165  1165
1166  1166
1167  1167
1168  1168
1169  1169
1170  1170
1171  1171
1172  1172
1173  1173
1174  1174
1175  1175
1176  1176
1177  1177
1178  1178
1179  1179
1180  1180
1181  1181
1182  1182
1183  1183
1184  1184
1185  1185
1186  1186
1187  1187
1188  1188
1189  1189
1190  1190
1191  1191
1192  1192
1193  1193
1194  1194
1195  1195
1196  1196
1197  1197
1198  1198
1199  1199
1200  1200
1201  1201
1202  1202
1203  1203
1204  1204
1205  1205
1206  1206
1207  1207
1208  1208
1209  1209
1210  1210
1211  1211
1212  1212
1213  1213
1214  1214
1215  1215
1216  1216
1217  1217
1218  1218
1219  1219
1220  1220
1221  1221
1222  1222
1223  1223
1224  1224
1225  1225
1226  1226
1227  1227
1228  1228
1229  1229
1230  1230
1231  1231
1232  1232
1233  1233
1234  1234
1235  1235
1236  1236
1237  1237
1238  1238
1239  1239
1240  1240
1241  1241
1242  1242
1243  1243
1244  1244
1245  1245
1246  1246
1247  1247
1248  1248
1249  1249
1250  1250
1251  1251
1252  1252
1253  1253
1254  1254
1255  1255
1256  1256
1257  1257
1258  1258
1259  1259
1260  1260
1261  1261
1262  1262
1263  1263
1264  1264
1265  1265
1266  1266
1267  1267
1268  1268
1269  1269
1270  1270
1271  1271
1272  1272
1273  1273
1274  1274
1275  1275
1276  1276
1277  1277
1278  1278
1279  1279
1280  1280
1281  1281
1282  1282
1283  1283
1284  1284
1285  1285
1286  1286
1287  1287
1288  1288
1289  1289
1290  1290
1291  1291
1292  1292
1293  1293
1294  1294
1295  1295
1296  1296

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               properties  \
3                                                                                                                                                                                                                                                                                                                                                                                                                                                               {'domain': 'MARK.LOCAL', 'name': 'Tier 2@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5de20ac8-e7ff-4f05-b597-268af392400e', 'distinguishedname': 'OU=TIER 2,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
6                                                                                                                                                                                                                                                                                                                                                                                                                                                           {'domain': 'MARK.LOCAL', 'name': 'T2 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e4602f9d-12bf-4f9e-b667-f6ccd27fae90', 'distinguishedname': 'OU=T2 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
15                                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-61c17d81-4eb2-4829-94e7-c7ddd6ecd193', 'distinguishedname': 'OU=T2 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
16                                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-5305b84a-5f72-4ee8-9726-81485bc11905', 'distinguishedname': 'OU=T2 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
17                                                                                                                                                                                                                                                                                                                                                                                                                                            {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-508809b7-63d4-4f53-8376-b31aa66c0af6', 'distinguishedname': 'OU=T2 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
18                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-e7679546-c753-4556-889a-67fd84f9d165', 'distinguishedname': 'OU=T2 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
22                                                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f6d13355-d2f9-45cf-9ee6-fdc8230ae4e5', 'distinguishedname': 'OU=T2 GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
23                                                                                                                                                                                                                                                                                                                                                                                                                                            {'domain': 'MARK.LOCAL', 'name': 'T2 Workstations@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-66aadca5-ccbc-46d4-91e7-f74f2527bdb5', 'distinguishedname': 'OU=T2 WORKSTATIONS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
24                                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-d4c0667d-16e8-4afd-8cf3-5f6a900f6913', 'distinguishedname': 'OU=T2 USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
25                                                                                                                                                                                                                                                                                                                                                                                                                                                      {'domain': 'MARK.LOCAL', 'name': 'T2 Servers@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-3f1588f2-5124-4111-8d63-caf4b57a87ca', 'distinguishedname': 'OU=T2 SERVERS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
26                                                                                                                                                                                                                                                                                                                                                                                                                          {'domain': 'MARK.LOCAL', 'name': 'T2 Enabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-dd1b08e8-140d-49e3-ab56-1551c008827a', 'distinguishedname': 'OU=T2 ENABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}
27                                                                                                                                                                                                                                                                                                                                                                                                                        {'domain': 'MARK.LOCAL', 'name': 'T2 Disabled User Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-9c9959e1-1718-4648-9aa1-e0eb9920d50c', 'distinguishedname': 'OU=T2 DISABLED USER ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}

In [ ]:
selected_nodes

,id,properties,type,l1,l2,l3,weight
0,0,"{'domain': 'MARK.LOCAL', 'name': 'MARK.LOCAL', 'highvalue': True, 'objectid': 'S-1-5-21-883232822-274137685-4173207997', 'distinguishedname': 'DC=MARK,DC=LOCAL', 'functionallevel': '2012', 'owned': False}",node,Base,Domain,None,20
4,4,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-f249f685-d5e0-4dad-b5b5-7f723c41ca1e', 'distinguishedname': 'OU=T0 ADMIN,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
7,7,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-c0fb853d-9b96-449b-b25c-4d20a1c02e5f', 'distinguishedname': 'OU=T0 ADMIN ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
8,8,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Devices@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-b9fd1aed-b3e6-4d53-9242-b85ff389822f', 'distinguishedname': 'OU=T0 ADMIN DEVICES,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
9,9,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Groups@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-cd13b9d6-76ca-4b5c-82bd-2d86bef8a375', 'distinguishedname': 'OU=T0 ADMIN GROUPS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
10,10,"{'domain': 'MARK.LOCAL', 'name': 'T0 Admin Service Accounts@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-58cd5b4f-82db-4cd1-a3f4-08661c9c53d2', 'distinguishedname': 'OU=T0 ADMIN SERVICE ACCOUNTS,DC=MARK,DC=LOCAL', 'description': None, 'highvalue': False, 'blocksInheritance': False, 'owned': False}",node,Base,OU,None,20
36,36,"{'domain': 'MARK.LOCAL', 'name': 'ADMINISTRATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-544', 'highvalue': True, 'distinguishedname': 'CN=Administrators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Administrators have complete and unrestricted access to the computer/domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
38,38,"{'domain': 'MARK.LOCAL', 'name': 'PRINT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-550', 'highvalue': True, 'distinguishedname': 'CN=Print Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer printers installed on domain controllers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
40,40,"{'domain': 'MARK.LOCAL', 'name': 'BACKUP OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-551', 'highvalue': True, 'distinguishedname': 'CN=Backup Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Backup Operators can override security restrictions for the sole purpose of backing up or restoring files', 'admincount': True, 'owned': False}",node,Base,Group,None,20
59,59,"{'domain': 'MARK.LOCAL', 'name': 'SERVER OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-549', 'highvalue': True, 'distinguishedname': 'CN=Server Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain servers', 'admincount': True, 'owned': False}",node,Base,Group,None,20
60,60,"{'domain': 'MARK.LOCAL', 'name': 'ACCOUNT OPERATORS@MARK.LOCAL', 'objectid': 'MARK.LOCAL-S-1-5-32-548', 'highvalue': True, 'distinguishedname': 'CN=Account Operators,CN=Builtin,DC=MARK,DC=LOCAL', 'description': 'Members can administer domain user and group accounts', 'admincount': True, 'owned': False}",node,Base,Group,None,20
65,65,"{'domain': 'MARK.LOCAL', 'name': 'ENTERPRISE ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-519', 'highvalue': True, 'distinguishedname': 'CN=Enterprise Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the enterprise', 'admincount': True, 'owned': False}",node,Base,Group,None,20
66,66,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN ADMINS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-512', 'highvalue': True, 'distinguishedname': 'CN=Domain Admins,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Designated administrators of the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
72,72,"{'domain': 'MARK.LOCAL', 'name': 'DOMAIN CONTROLLERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-516', 'highvalue': True, 'distinguishedname': 'CN=Domain Controllers,CN=Users,DC=MARK,DC=LOCAL', 'description': 'All domain controllers in the domain', 'admincount': True, 'owned': False}",node,Base,Group,None,20
75,75,"{'domain': 'MARK.LOCAL', 'name': 'GROUP POLICY CREATOR OWNERS@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-520', 'highvalue': True, 'distinguishedname': 'CN=Group Policy Creator Owners,CN=Users,DC=MARK,DC=LOCAL', 'description': 'Members in this group can modify group policy for the domain', 'admincount': False, 'owned': False}",node,Base,Group,None,20
90,90,"{'domain': 'MARK.LOCAL', 'name': 'T1 Admin Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1000', 'distinguishedname': 'CN=T1 ADMIN ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
91,91,"{'domain': 'MARK.LOCAL', 'name': 'T1 PAW Maintenance@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1001', 'distinguishedname': 'CN=T1 PAW MAINTENANCE,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
92,92,"{'domain': 'MARK.LOCAL', 'name': 'T1 Server Management@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1002', 'distinguishedname': 'CN=T1 SERVER MANAGEMENT,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
93,93,"{'domain': 'MARK.LOCAL', 'name': 'T1 Service Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1003', 'distinguishedname': 'CN=T1 SERVICE ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
94,94,"{'domain': 'MARK.LOCAL', 'name': 'T2 Admin Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1004', 'distinguishedname': 'CN=T2 ADMIN ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
95,95,"{'domain': 'MARK.LOCAL', 'name': 'T2 PAW Maintenance@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1005', 'distinguishedname': 'CN=T2 PAW MAINTENANCE,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
96,96,"{'domain': 'MARK.LOCAL', 'name': 'T2 Server Management@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1006', 'distinguishedname': 'CN=T2 SERVER MANAGEMENT,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
97,97,"{'domain': 'MARK.LOCAL', 'name': 'T2 Service Accounts Group@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1007', 'distinguishedname': 'CN=T2 SERVICE ACCOUNTS GROUP,DC=MARK,DC=LOCAL', 'description': 'This is a security group', 'highvalue': True, 'admincount': True, 'owned': False}",node,Base,Group,None,20
98,98,"{'domain': 'MARK.LOCAL', 'name': 'Group Policy Objects Container@MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-167D14BB-ED5C-438D-89A0-8E2173C713FB', 'highvalue': True, 'distinguishedname': 'CN=Policies,CN=System,DC=MARK,DC=LOCAL', 'owned': False}",node,Base,Container,None,20
288,288,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1011', 'displayname': 'Lore Domebo', 'name': 'LDOMEBO00001@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1735793646, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=LDOMEBO00001,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
289,289,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1012', 'displayname': 'Ora Swinney', 'name': 'OSWINNEY00002@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=OSWINNEY00002,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
291,291,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1014', 'displayname': 'Leandra Marucci', 'name': 'LMARUCCI00004@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 1744872398, 'lastlogontimestamp': 1744872398, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=LMARUCCI00004,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
293,293,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1016', 'displayname': 'Lynette Nette', 'name': 'LNETTE00006@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=LNETTE00006,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
294,294,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1017', 'displayname': 'Venessa Schaumberg', 'name': 'VSCHAUMBERG00007@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1729493472, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=VSCHAUMBERG00007,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
295,295,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1018', 'displayname': 'Shanel Nori', 'name': 'SNORI00008@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': True, 'hasspn': True, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=SNORI00008,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
296,296,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1019', 'displayname': 'Devon Scotti', 'name': 'DSCOTTI00009@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=DSCOTTI00009,OU=T0 ADMIN SERVICE ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
297,297,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1020', 'displayname': 'Leta Radoslovich', 'name': 'LRADOSLOVICH00010@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=LRADOSLOVICH00010,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
299,299,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1022', 'displayname': 'Deane Broaddus', 'name': 'DBROADDUS00012@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 1737401792, 'lastlogontimestamp': 1737401792, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=DBROADDUS00012,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
301,301,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1024', 'displayname': 'Teisha Ralat', 'name': 'TRALAT00014@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1728191894, 'lastlogon': 1718679255, 'lastlogontimestamp': 1718679255, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': 'S-1-5-21-883822822-279636685-4182209497-1384', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=TRALAT00014,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
302,302,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1025', 'displayname': 'Roxanna Florido', 'name': 'RFLORIDO00015@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1742548203, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=RFLORIDO00015,OU=T1 ADMIN ACCOUNTS,OU=T1 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
303,303,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1026', 'displayname': 'Shaquita Flanegan', 'name': 'SFLANEGAN00016@MARK.LOCAL', 'enabled': True, 'pwdlastset': 0, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': True, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=SFLANEGAN00016,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
304,304,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1027', 'displayname': 'Tomasa Boyarski', 'name': 'TBOYARSKI00017@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=TBOYARSKI00017,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
305,305,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1028', 'displayname': 'Zoila Dinucci', 'name': 'ZDINUCCI00018@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1747923112, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': 'S-1-5-21-883822822-279636685-4182209497-1934', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': True, 'owned': False, 'distinguishedname': 'CN=ZDINUCCI00018,OU=T0 ADMIN SERVICE ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
306,306,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1029', 'displayname': 'Maryanne Sedtal', 'name': 'MSEDTAL00019@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1746739983, 'lastlogon': 0, 'lastlogontimestamp': 0, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=MSEDTAL00019,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
307,307,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1030', 'displayname': 'Chelsea Sullivan', 'name': 'CSULLIVAN00020@MARK.LOCAL', 'enabled': True, 'pwdlastset': 1724431118, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': False, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': 'S-1-5-21-883822822-279636685-4182209497-1268', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=CSULLIVAN00020,OU=T0 ADMIN ACCOUNTS,OU=T0 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20
308,308,"{'domain': 'MARK.LOCAL', 'objectid': 'S-1-5-21-883232822-274137685-4173207997-1031', 'displayname': 'Chanda Meiggs', 'name': 'CMEIGGS00021@MARK.LOCAL', 'enabled': True, 'pwdlastset': -1, 'lastlogon': -1, 'lastlogontimestamp': -1, 'highvalue': True, 'dontreqpreauth': False, 'hasspn': False, 'passwordnotreqd': False, 'pwdneverexpires': True, 'sensitive': False, 'serviceprincipalnames': '', 'sidhistory': '', 'unconstraineddelegation': False, 'description': 'null', 'admincount': True, 'savedcredentials': False, 'owned': False, 'distinguishedname': 'CN=CMEIGGS00021,OU=T2 ADMIN ACCOUNTS,OU=T2 Admin,OU=Admin,DC=MARK,DC=LOCAL'}",node,Base,User,None,20

In [ ]:
pd.set_option("display.max_rows", None, "display.max_columns", None)
shortest_paths

{0: {0: [0],
  285: [0, 285],
  287: [0, 287],
  49: [0, 285, 49],
  74: [0, 285, 74],
  63: [0, 287, 63],
  86: [0, 285, 74, 86],
  87: [0, 285, 74, 87],
  50: [0, 285, 74, 87, 50]},
 4: {4: [4], 7: [4, 7]},
 7: {7: [7]},
 8: {8: [8],
  686: [8, 686],
  527: [8, 527],
  530: [8, 530],
  531: [8, 531],
  532: [8, 532],
  553: [8, 553],
  607: [8, 607],
  610: [8, 610],
  625: [8, 625],
  631: [8, 631],
  632: [8, 632],
  640: [8, 640],
  645: [8, 645],
  653: [8, 653],
  663: [8, 663]},
 9: {9: [9],
  65: [9, 65],
  284: [9, 65, 36, 284],
  285: [9, 65, 36, 285],
  286: [9, 65, 286],
  287: [9, 65, 36, 287],
  63: [9, 65, 64, 63],
  36: [9, 65, 36],
  37: [9, 65, 37],
  38: [9, 65, 286, 38],
  39: [9, 65, 39],
  40: [9, 65, 40],
  41: [9, 65, 36, 41],
  42: [9, 65, 36, 42],
  43: [9, 65, 43],
  45: [9, 65, 45],
  48: [9, 65, 36, 48],
  50: [9, 65, 36, 50],
  51: [9, 65, 36, 51],
  52: [9, 65, 52],
  53: [9, 65, 36, 53],
  56: [9, 65, 36, 56],
  57: [9, 65, 36, 57],
  58: [9, 65, 36, 58],
  59: [9, 65, 286, 59],
  60: [9, 65, 60],
  61: [9, 65, 36, 61],
  62: [9, 65, 36, 62],
  64: [9, 65, 64],
  66: [9, 65, 286, 66],
  67: [9, 65, 36, 67],
  68: [9, 65, 36, 68],
  69: [9, 65, 36, 69],
  70: [9, 65, 36, 70],
  71: [9, 65, 36, 71],
  72: [9, 65, 286, 72],
  73: [9, 65, 36, 73],
  74: [9, 65, 286, 74],
  75: [9, 65, 286, 75],
  76: [9, 65, 36, 76],
  77: [9, 65, 77],
  78: [9, 65, 36, 78],
  79: [9, 65, 36, 79],
  80: [9, 65, 36, 80],
  81: [9, 65, 36, 81],
  82: [9, 65, 36, 82],
  83: [9, 65, 36, 83],
  84: [9, 65, 36, 84],
  0: [9, 65, 36, 0],
  44: [9, 65, 36, 44],
  46: [9, 65, 36, 46],
  47: [9, 65, 36, 47],
  49: [9, 65, 36, 285, 49],
  55: [9, 65, 36, 55],
  102: [9, 65, 286, 66, 102],
  86: [9, 65, 286, 74, 86],
  87: [9, 65, 286, 74, 87],
  85: [9, 65, 286, 66, 102, 85]},
 10: {10: [10]},
 36: {36: [36],
  0: [36, 0],
  284: [36, 284],
  285: [36, 285],
  286: [36, 65, 286],
  287: [36, 287],
  37: [36, 37],
  39: [36, 39],
  40: [36, 40],
  41: [36, 41],
  42: [36, 42],
  43: [36, 65, 43],
  44: [36, 44],
  45: [36, 45],
  46: [36, 46],
  47: [36, 47],
  48: [36, 48],
  49: [36, 285, 49],
  50: [36, 50],
  51: [36, 51],
  52: [36, 52],
  53: [36, 53],
  55: [36, 55],
  56: [36, 56],
  57: [36, 57],
  58: [36, 58],
  59: [36, 65, 286, 59],
  60: [36, 60],
  61: [36, 61],
  62: [36, 62],
  63: [36, 63],
  64: [36, 64],
  65: [36, 65],
  66: [36, 66],
  67: [36, 67],
  68: [36, 68],
  69: [36, 69],
  70: [36, 70],
  71: [36, 71],
  72: [36, 65, 286, 72],
  73: [36, 73],
  74: [36, 74],
  75: [36, 75],
  76: [36, 76],
  77: [36, 77],
  78: [36, 78],
  79: [36, 79],
  80: [36, 80],
  81: [36, 81],
  82: [36, 82],
  83: [36, 83],
  84: [36, 84],
  38: [36, 65, 286, 38],
  102: [36, 66, 102],
  86: [36, 73, 86],
  87: [36, 73, 87],
  85: [36, 66, 102, 85]},
 38: {38: [38]},
 40: {40: [40]},
 59: {59: [59]},
 60: {60: [60],
  284: [60, 284],
  285: [60, 285],
  37: [60, 37],
  39: [60, 39],
  41: [60, 41],
  42: [60, 42],
  44: [60, 44],
  45: [60, 45],
  46: [60, 46],
  47: [60, 47],
  48: [60, 48],
  49: [60, 49],
  51: [60, 51],
  52: [60, 52],
  57: [60, 57],
  58: [60, 58],
  61: [60, 61],
  62: [60, 62],
  63: [60, 63],
  67: [60, 67],
  68: [60, 68],
  69: [60, 69],
  70: [60, 70],
  71: [60, 71],
  73: [60, 73],
  74: [60, 74],
  75: [60, 75],
  76: [60, 76],
  78: [60, 78],
  79: [60, 79],
  80: [60, 80],
  81: [60, 81],
  82: [60, 82],
  83: [60, 83],
  84: [60, 84],
  86: [60, 73, 86],
  87: [60, 73, 87],
  50: [60, 73, 87, 50]},
 65: {65: [65],
  284: [65, 36, 284],
  285: [65, 36, 285],
  286: [65, 286],
  287: [65, 36, 287],
  63: [65, 64, 63],
  36: [65, 36],
  37: [65, 37],
  38: [65, 286, 38],
  39: [65, 39],
  40: [65, 40],
  41: [65, 36, 41],
  42: [65, 36, 42],
  43: [65, 43],
  45: [65, 45],
  48: [65, 36, 48],
  50: [65, 36, 50],
  51: [65, 36, 51],
  52: [65, 52],
  53: [65, 36, 53],
  56: [65, 36, 56],
  57: [65, 36, 57],
  58: [65, 36, 58],
  59: [65, 286, 59],
  60: [65, 60],
  61: [65, 36, 61],
  62: [65, 36, 62],
  64: [65, 64],
  66: [65, 286, 66],
  67: [65, 36, 67],
  68: [65, 36, 68],
  69: [65, 36, 69],
  70: [65, 36, 70],
  71: [65, 36, 71],
  72: [65, 286, 72],
  73: [65, 36, 73],
  74: [65, 286, 74],
  75: [65, 286, 75],
  76: [65, 36, 76],
  77: [65, 77],
  78: [65, 36, 78],
  79: [65, 36, 79],
  80: [65, 36, 80],
  81: [65, 36, 81],
  82: [65, 36, 82],
  83: [65, 36, 83],
  84: [65, 36, 84],
  0: [65, 36, 0],
  44: [65, 36, 44],
  46: [65, 36, 46],
  47: [65, 36, 47],
  49: [65, 36, 285, 49],
  55: [65, 36, 55],
  102: [65, 286, 66, 102],
  86: [65, 286, 74, 86],
  87: [65, 286, 74, 87],
  85: [65, 286, 66, 102, 85]},
 66: {66: [66],
  0: [66, 36, 0],
  102: [66, 102],
  284: [66, 36, 284],
  285: [66, 36, 285],
  286: [66, 286],
  287: [66, 36, 287],
  36: [66, 36],
  37: [66, 37],
  38: [66, 286, 38],
  39: [66, 39],
  40: [66, 40],
  42: [66, 36, 42],
  43: [66, 43],
  44: [66, 36, 44],
  45: [66, 45],
  47: [66, 36, 47],
  48: [66, 36, 48],
  49: [66, 36, 285, 49],
  51: [66, 36, 51],
  53: [66, 36, 53],
  57: [66, 36, 57],
  58: [66, 36, 58],
  59: [66, 286, 59],
  60: [66, 60],
  61: [66, 36, 61],
  62: [66, 36, 62],
  63: [66, 64, 63],
  64: [66, 64],
  65: [66, 65],
  67: [66, 36, 67],
  68: [66, 36, 68],
  69: [66, 36, 69],
  70: [66, 36, 70],
  71: [66, 36, 71],
  72: [66, 286, 72],
  73: [66, 36, 73],
  74: [66, 286, 74],
  75: [66, 286, 75],
  76: [66, 36, 76],
  77: [66, 77],
  78: [66, 36, 78],
  79: [66, 36, 79],
  80: [66, 36, 80],
  81: [66, 36, 81],
  82: [66, 36, 82],
  83: [66, 36, 83],
  84: [66, 36, 84],
  41: [66, 36, 41],
  46: [66, 36, 46],
  50: [66, 36, 50],
  52: [66, 36, 52],
  55: [66, 36, 55],
  56: [66, 36, 56],
  86: [66, 286, 74, 86],
  87: [66, 286, 74, 87],
  85: [66, 102, 85]},
 72: {72: [72], 63: [72, 63]},
 75: {75: [75], 63: [75, 63]},
 90: {90: [90], 85: [90, 85]},
 91: {91: [91]},
 92: {92: [92]},
 93: {93: [93]},
 94: {94: [94]},
 95: {95: [95]},
 96: {96: [96]},
 97: {97: [97]},
 98: {98: [98],
  106: [98, 106],
  107: [98, 107],
  109: [98, 109],
  110: [98, 110],
  111: [98, 111],
  115: [98, 115],
  116: [98, 116],
  117: [98, 117],
  118: [98, 118],
  121: [98, 121],
  125: [98, 125],
  127: [98, 127],
  128: [98, 128],
  129: [98, 129],
  130: [98, 130],
  131: [98, 131],
  133: [98, 133],
  134: [98, 134],
  135: [98, 135],
  137: [98, 137],
  138: [98, 138],
  139: [98, 139],
  142: [98, 142],
  143: [98, 143],
  144: [98, 144],
  145: [98, 145],
  146: [98, 146],
  147: [98, 147],
  148: [98, 148],
  149: [98, 149],
  150: [98, 150],
  151: [98, 151],
  152: [98, 152],
  153: [98, 153],
  154: [98, 154],
  155: [98, 155],
  156: [98, 156],
  157: [98, 157],
  158: [98, 158],
  159: [98, 159],
  160: [98, 160],
  161: [98, 161],
  162: [98, 162],
  163: [98, 163],
  164: [98, 164],
  165: [98, 165],
  166: [98, 166],
  167: [98, 167],
  168: [98, 168],
  169: [98, 169],
  170: [98, 170],
  171: [98, 171],
  172: [98, 172],
  173: [98, 173],
  174: [98, 174],
  175: [98, 175],
  176: [98, 176],
  177: [98, 177],
  178: [98, 178],
  179: [98, 179],
  180: [98, 180],
  181: [98, 181],
  182: [98, 182],
  183: [98, 183],
  184: [98, 184],
  185: [98, 185],
  186: [98, 186],
  187: [98, 187],
  188: [98, 188],
  189: [98, 189],
  190: [98, 190],
  191: [98, 191],
  192: [98, 192],
  193: [98, 193],
  194: [98, 194],
  195: [98, 195],
  196: [98, 196],
  197: [98, 197],
  198: [98, 198],
  199: [98, 199],
  200: [98, 200],
  201: [98, 201],
  202: [98, 202],
  203: [98, 203],
  204: [98, 204],
  205: [98, 205],
  206: [98, 206],
  207: [98, 207],
  208: [98, 208],
  209: [98, 209],
  210: [98, 210],
  211: [98, 211],
  212: [98, 212],
  213: [98, 213],
  214: [98, 214],
  215: [98, 215],
  216: [98, 216],
  217: [98, 217],
  218: [98, 218],
  219: [98, 219],
  220: [98, 220],
  221: [98, 221],
  222: [98, 222],
  223: [98, 223],
  224: [98, 224],
  225: [98, 225],
  226: [98, 226],
  227: [98, 227],
  228: [98, 228],
  229: [98, 229],
  230: [98, 230],
  231: [98, 231],
  232: [98, 232],
  233: [98, 233],
  234: [98, 234],
  235: [98, 235],
  236: [98, 236],
  237: [98, 237],
  238: [98, 238],
  239: [98, 239],
  240: [98, 240],
  241: [98, 241],
  242: [98, 242],
  243: [98, 243],
  244: [98, 244],
  245: [98, 245],
  246: [98, 246],
  247: [98, 247],
  248: [98, 248],
  249: [98, 249],
  250: [98, 250],
  251: [98, 251],
  252: [98, 252],
  253: [98, 253],
  254: [98, 254],
  255: [98, 255],
  256: [98, 256],
  257: [98, 257],
  258: [98, 258],
  259: [98, 259],
  260: [98, 260],
  261: [98, 261],
  262: [98, 262],
  263: [98, 263],
  264: [98, 264],
  265: [98, 265],
  266: [98, 266],
  267: [98, 267],
  268: [98, 268],
  269: [98, 269],
  270: [98, 270],
  271: [98, 271],
  272: [98, 272],
  273: [98, 273],
  279: [98, 279],
  280: [98, 280],
  281: [98, 281],
  282: [98, 282],
  283: [98, 283]},
 288: {288: [288],
  74: [288, 74],
  86: [288, 74, 86],
  87: [288, 74, 87],
  50: [288, 74, 87, 50]},
 289: {289: [289],
  74: [289, 74],
  86: [289, 74, 86],
  87: [289, 74, 87],
  50: [289, 74, 87, 50]},
 291: {291: [291],
  74: [291, 74],
  86: [291, 74, 86],
  87: [291, 74, 87],
  50: [291, 74, 87, 50]},
 293: {293: [293],
  74: [293, 74],
  86: [293, 74, 86],
  87: [293, 74, 87],
  50: [293, 74, 87, 50]},
 294: {294: [294],
  74: [294, 74],
  86: [294, 74, 86],
  87: [294, 74, 87],
  50: [294, 74, 87, 50]},
 295: {295: [295],
  74: [295, 74],
  86: [295, 74, 86],
  87: [295, 74, 87],
  50: [295, 74, 87, 50]},
 296: {296: [296],
  74: [296, 74],
  86: [296, 74, 86],
  87: [296, 74, 87],
  50: [296, 74, 87, 50]},
 297: {297: [297],
  74: [297, 74],
  86: [297, 74, 86],
  87: [297, 74, 87],
  50: [297, 74, 87, 50]},
 299: {299: [299],
  74: [299, 74],
  86: [299, 74, 86],
  87: [299, 74, 87],
  50: [299, 74, 87, 50]},
 301: {301: [301],
  74: [301, 74],
  86: [301, 74, 86],
  87: [301, 74, 87],
  50: [301, 74, 87, 50]},
 302: {302: [302],
  74: [302, 74],
  86: [302, 74, 86],
  87: [302, 74, 87],
  50: [302, 74, 87, 50]},
 303: {303: [303],
  74: [303, 74],
  86: [303, 74, 86],
  87: [303, 74, 87],
  50: [303, 74, 87, 50]},
 304: {304: [304],
  74: [304, 74],
  86: [304, 74, 86],
  87: [304, 74, 87],
  50: [304, 74, 87, 50]},
 305: {305: [305],
  74: [305, 74],
  86: [305, 74, 86],
  87: [305, 74, 87],
  50: [305, 74, 87, 50]},
 306: {306: [306],
  74: [306, 74],
  86: [306, 74, 86],
  87: [306, 74, 87],
  50: [306, 74, 87, 50]},
 307: {307: [307],
  74: [307, 74],
  86: [307, 74, 86],
  87: [307, 74, 87],
  50: [307, 74, 87, 50]},
 308: {308: [308],
  74: [308, 74],
  86: [308, 74, 86],
  87: [308, 74, 87],
  50: [308, 74, 87, 50]},
 309: {309: [309],
  74: [309, 74],
  86: [309, 74, 86],
  87: [309, 74, 87],
  50: [309, 74, 87, 50]},
 311: {311: [311],
  74: [311, 74],
  86: [311, 74, 86],
  87: [311, 74, 87],
  50: [311, 74, 87, 50]},
 312: {312: [312],
  74: [312, 74],
  86: [312, 74, 86],
  87: [312, 74, 87],
  50: [312, 74, 87, 50]},
 313: {313: [313],
  74: [313, 74],
  86: [313, 74, 86],
  87: [313, 74, 87],
  50: [313, 74, 87, 50]},
 314: {314: [314],
  74: [314, 74],
  86: [314, 74, 86],
  87: [314, 74, 87],
  50: [314, 74, 87, 50]},
 315: {315: [315],
  74: [315, 74],
  86: [315, 74, 86],
  87: [315, 74, 87],
  50: [315, 74, 87, 50]},
 318: {318: [318],
  74: [318, 74],
  86: [318, 74, 86],
  87: [318, 74, 87],
  50: [318, 74, 87, 50]},
 319: {319: [319],
  74: [319, 74],
  86: [319, 74, 86],
  87: [319, 74, 87],
  50: [319, 74, 87, 50]},
 320: {320: [320],
  74: [320, 74],
  86: [320, 74, 86],
  87: [320, 74, 87],
  50: [320, 74, 87, 50]},
 321: {321: [321],
  74: [321, 74],
  86: [321, 74, 86],
  87: [321, 74, 87],
  50: [321, 74, 87, 50]},
 322: {322: [322],
  74: [322, 74],
  86: [322, 74, 86],
  87: [322, 74, 87],
  50: [322, 74, 87, 50]},
 323: {323: [323],
  74: [323, 74],
  86: [323, 74, 86],
  87: [323, 74, 87],
  50: [323, 74, 87, 50]},
 324: {324: [324],
  74: [324, 74],
  86: [324, 74, 86],
  87: [324, 74, 87],
  50: [324, 74, 87, 50]},
 331: {331: [331],
  74: [331, 74],
  86: [331, 74, 86],
  87: [331, 74, 87],
  50: [331, 74, 87, 50]},
 341: {341: [341],
  74: [341, 74],
  86: [341, 74, 86],
  87: [341, 74, 87],
  50: [341, 74, 87, 50]},
 357: {357: [357],
  74: [357, 74],
  86: [357, 74, 86],
  87: [357, 74, 87],
  50: [357, 74, 87, 50]},
 392: {392: [392],
  74: [392, 74],
  86: [392, 74, 86],
  87: [392, 74, 87],
  50: [392, 74, 87, 50]},
 405: {405: [405],
  74: [405, 74],
  86: [405, 74, 86],
  87: [405, 74, 87],
  50: [405, 74, 87, 50]},
 444: {444: [444],
  74: [444, 74],
  86: [444, 74, 86],
  87: [444, 74, 87],
  50: [444, 74, 87, 50]},
 448: {448: [448],
  74: [448, 74],
  86: [448, 74, 86],
  87: [448, 74, 87],
  50: [448, 74, 87, 50]},
 457: {457: [457],
  74: [457, 74],
  86: [457, 74, 86],
  87: [457, 74, 87],
  50: [457, 74, 87, 50]},
 458: {458: [458],
  74: [458, 74],
  86: [458, 74, 86],
  87: [458, 74, 87],
  50: [458, 74, 87, 50]},
 467: {467: [467],
  74: [467, 74],
  86: [467, 74, 86],
  87: [467, 74, 87],
  50: [467, 74, 87, 50]},
 469: {469: [469],
  74: [469, 74],
  86: [469, 74, 86],
  87: [469, 74, 87],
  50: [469, 74, 87, 50]},
 481: {481: [481],
  74: [481, 74],
  86: [481, 74, 86],
  87: [481, 74, 87],
  50: [481, 74, 87, 50]},
 491: {491: [491]},
 501: {501: [501]},
 507: {507: [507]},
 508: {508: [508]},
 509: {509: [509]},
 511: {511: [511]},
 512: {512: [512]},
 514: {514: [514]},
 521: {521: [521]},
 523: {523: [523]},
 527: {527: [527]},
 530: {530: [530]},
 531: {531: [531]},
 532: {532: [532]},
 533: {533: [533]},
 534: {534: [534]},
 539: {539: [539]},
 544: {544: [544]},
 548: {548: [548]},
 550: {550: [550]},
 553: {553: [553]},
 557: {557: [557]},
 561: {561: [561]},
 562: {562: [562]},
 563: {563: [563]},
 564: {564: [564]},
 565: {565: [565]},
 567: {567: [567]},
 573: {573: [573]},
 575: {575: [575]},
 577: {577: [577]},
 585: {585: [585]},
 590: {590: [590]},
 597: {597: [597]},
 599: {599: [599]},
 600: {600: [600]},
 603: {603: [603]},
 607: {607: [607]},
 609: {609: [609]},
 610: {610: [610]},
 620: {620: [620]},
 623: {623: [623]},
 624: {624: [624]},
 625: {625: [625]},
 626: {626: [626]},
 631: {631: [631]},
 632: {632: [632]},
 637: {637: [637]},
 638: {638: [638]},
 639: {639: [639]},
 640: {640: [640]},
 645: {645: [645]},
 648: {648: [648]},
 649: {649: [649]},
 650: {650: [650]},
 651: {651: [651]},
 653: {653: [653]},
 654: {654: [654]},
 655: {655: [655]},
 656: {656: [656]},
 660: {660: [660]},
 661: {661: [661]},
 663: {663: [663]},
 665: {665: [665]},
 666: {666: [666]},
 668: {668: [668]},
 672: {672: [672]},
 673: {673: [673]},
 676: {676: [676]},
 677: {677: [677]},
 681: {681: [681]},
 684: {684: [684]},
 686: {686: [686]},
 692: {692: [692]},
 693: {693: [693]},
 694: {694: [694]},
 1: {1: [1], 4: [1, 4], 7: [1, 4, 7]},
 6: {6: [6],
  16: [6, 16],
  17: [6, 17],
  18: [6, 18],
  688: [6, 16, 688],
  539: [6, 16, 539],
  567: [6, 16, 567],
  609: [6, 16, 609],
  637: [6, 16, 637],
  655: [6, 16, 655],
  660: [6, 16, 660],
  661: [6, 16, 661],
  676: [6, 16, 676]},
 16: {16: [16],
  688: [16, 688],
  539: [16, 539],
  567: [16, 567],
  609: [16, 609],
  637: [16, 637],
  655: [16, 655],
  660: [16, 660],
  661: [16, 661],
  676: [16, 676]},
 17: {17: [17]},
 18: {18: [18]},
 2: {2: [2],
  19: [2, 19],
  689: [2, 19, 689],
  512: [2, 19, 512],
  534: [2, 19, 534],
  575: [2, 19, 575],
  651: [2, 19, 651]},
 19: {19: [19],
  689: [19, 689],
  512: [19, 512],
  534: [19, 534],
  575: [19, 575],
  651: [19, 651]},
 3: {3: [3],
  23: [3, 23],
  24: [3, 24],
  25: [3, 25],
  28: [3, 23, 28],
  29: [3, 23, 29],
  30: [3, 23, 30],
  26: [3, 24, 26],
  27: [3, 24, 27],
  33: [3, 25, 33],
  34: [3, 25, 34],
  35: [3, 25, 35],
  501: [3, 25, 33, 501],
  509: [3, 25, 33, 509],
  548: [3, 25, 33, 548],
  656: [3, 25, 33, 656],
  672: [3, 25, 33, 672],
  511: [3, 25, 34, 511],
  521: [3, 25, 34, 521],
  533: [3, 25, 34, 533],
  562: [3, 25, 34, 562],
  603: [3, 25, 34, 603],
  649: [3, 25, 34, 649],
  666: [3, 25, 34, 666],
  673: [3, 25, 34, 673],
  507: [3, 25, 35, 507],
  557: [3, 25, 35, 557],
  565: [3, 25, 35, 565],
  573: [3, 25, 35, 573],
  638: [3, 25, 35, 638],
  668: [3, 25, 35, 668]},
 23: {23: [23], 28: [23, 28], 29: [23, 29], 30: [23, 30]},
 24: {24: [24], 26: [24, 26], 27: [24, 27]},
 25: {25: [25],
  33: [25, 33],
  34: [25, 34],
  35: [25, 35],
  501: [25, 33, 501],
  509: [25, 33, 509],
  548: [25, 33, 548],
  656: [25, 33, 656],
  672: [25, 33, 672],
  511: [25, 34, 511],
  521: [25, 34, 521],
  533: [25, 34, 533],
  562: [25, 34, 562],
  603: [25, 34, 603],
  649: [25, 34, 649],
  666: [25, 34, 666],
  673: [25, 34, 673],
  507: [25, 35, 507],
  557: [25, 35, 557],
  565: [25, 35, 565],
  573: [25, 35, 573],
  638: [25, 35, 638],
  668: [25, 35, 668]},
 26: {26: [26]},
 27: {27: [27]},
 28: {28: [28]},
 29: {29: [29]},
 30: {30: [30]},
 22: {22: [22], 31: [22, 31], 32: [22, 32]},
 31: {31: [31]},
 32: {32: [32]},
 33: {33: [33],
  501: [33, 501],
  509: [33, 509],
  548: [33, 548],
  656: [33, 656],
  672: [33, 672]},
 34: {34: [34],
  511: [34, 511],
  521: [34, 521],
  533: [34, 533],
  562: [34, 562],
  603: [34, 603],
  649: [34, 649],
  666: [34, 666],
  673: [34, 673]},
 35: {35: [35],
  507: [35, 507],
  557: [35, 557],
  565: [35, 565],
  573: [35, 573],
  638: [35, 638],
  668: [35, 668]},
 102: {102: [102], 72: [102, 72], 85: [102, 85], 63: [102, 72, 63]},
 101: {101: [101],
  102: [101, 102],
  72: [101, 102, 72],
  85: [101, 102, 85],
  63: [101, 102, 72, 63]},
 85: {85: [85]},
 106: {106: [106]},
 107: {107: [107]},
 109: {109: [109]},
 110: {110: [110]},
 111: {111: [111]},
 115: {115: [115]},
 116: {116: [116]},
 117: {117: [117]},
 118: {118: [118]},
 121: {121: [121]},
 125: {125: [125]},
 127: {127: [127]},
 128: {128: [128]},
 129: {129: [129]},
 130: {130: [130]},
 131: {131: [131]},
 133: {133: [133]},
 134: {134: [134]},
 135: {135: [135]},
 137: {137: [137]},
 138: {138: [138]},
 139: {139: [139]},
 142: {142: [142]},
 143: {143: [143]},
 144: {144: [144]},
 145: {145: [145]},
 146: {146: [146]},
 147: {147: [147]},
 148: {148: [148]},
 149: {149: [149]},
 150: {150: [150]},
 151: {151: [151]},
 152: {152: [152]},
 153: {153: [153]},
 154: {154: [154]},
 155: {155: [155]},
 156: {156: [156]},
 157: {157: [157]},
 158: {158: [158]},
 159: {159: [159]},
 160: {160: [160]},
 161: {161: [161]},
 162: {162: [162]},
 163: {163: [163]},
 164: {164: [164]},
 165: {165: [165]},
 166: {166: [166]},
 167: {167: [167]},
 168: {168: [168]},
 169: {169: [169]},
 170: {170: [170]},
 171: {171: [171]},
 172: {172: [172]},
 173: {173: [173]},
 174: {174: [174]},
 175: {175: [175]},
 176: {176: [176]},
 177: {177: [177]},
 178: {178: [178]},
 179: {179: [179]},
 180: {180: [180]},
 181: {181: [181]},
 182: {182: [182]},
 183: {183: [183]},
 184: {184: [184]},
 185: {185: [185]},
 186: {186: [186]},
 187: {187: [187]},
 188: {188: [188]},
 189: {189: [189]},
 190: {190: [190]},
 191: {191: [191]},
 192: {192: [192]},
 193: {193: [193]},
 194: {194: [194]},
 195: {195: [195]},
 196: {196: [196]},
 197: {197: [197]},
 198: {198: [198]},
 199: {199: [199]},
 200: {200: [200]},
 201: {201: [201]},
 202: {202: [202]},
 203: {203: [203]},
 204: {204: [204]},
 205: {205: [205]},
 206: {206: [206]},
 207: {207: [207]},
 208: {208: [208]},
 209: {209: [209]},
 210: {210: [210]},
 211: {211: [211]},
 212: {212: [212]},
 213: {213: [213]},
 214: {214: [214]},
 215: {215: [215]},
 216: {216: [216]},
 217: {217: [217]},
 218: {218: [218]},
 219: {219: [219]},
 220: {220: [220]},
 221: {221: [221]},
 222: {222: [222]},
 223: {223: [223]},
 224: {224: [224]},
 225: {225: [225]},
 226: {226: [226]},
 227: {227: [227]},
 228: {228: [228]},
 229: {229: [229]},
 230: {230: [230]},
 231: {231: [231]},
 232: {232: [232]},
 233: {233: [233]},
 234: {234: [234]},
 235: {235: [235]},
 236: {236: [236]},
 237: {237: [237]},
 238: {238: [238]},
 239: {239: [239]},
 240: {240: [240]},
 241: {241: [241]},
 242: {242: [242]},
 243: {243: [243]},

In [ ]:
shortest_paths_filtered

{0: {285: [0, 285],
  287: [0, 287],
  49: [0, 285, 49],
  74: [0, 285, 74],
  63: [0, 287, 63],
  86: [0, 285, 74, 86],
  87: [0, 285, 74, 87],
  50: [0, 285, 74, 87, 50]},
 4: {7: [4, 7]},
 7: {},
 8: {686: [8, 686],
  527: [8, 527],
  530: [8, 530],
  531: [8, 531],
  532: [8, 532],
  553: [8, 553],
  607: [8, 607],
  610: [8, 610],
  625: [8, 625],
  631: [8, 631],
  632: [8, 632],
  640: [8, 640],
  645: [8, 645],
  653: [8, 653],
  663: [8, 663]},
 9: {65: [9, 65],
  284: [9, 65, 36, 284],
  285: [9, 65, 36, 285],
  286: [9, 65, 286],
  287: [9, 65, 36, 287],
  63: [9, 65, 64, 63],
  36: [9, 65, 36],
  37: [9, 65, 37],
  38: [9, 65, 286, 38],
  39: [9, 65, 39],
  40: [9, 65, 40],
  41: [9, 65, 36, 41],
  42: [9, 65, 36, 42],
  43: [9, 65, 43],
  45: [9, 65, 45],
  48: [9, 65, 36, 48],
  50: [9, 65, 36, 50],
  51: [9, 65, 36, 51],
  52: [9, 65, 52],
  53: [9, 65, 36, 53],
  56: [9, 65, 36, 56],
  57: [9, 65, 36, 57],
  58: [9, 65, 36, 58],
  59: [9, 65, 286, 59],
  60: [9, 65, 60],
  61: [9, 65, 36, 61],
  62: [9, 65, 36, 62],
  64: [9, 65, 64],
  66: [9, 65, 286, 66],
  67: [9, 65, 36, 67],
  68: [9, 65, 36, 68],
  69: [9, 65, 36, 69],
  70: [9, 65, 36, 70],
  71: [9, 65, 36, 71],
  72: [9, 65, 286, 72],
  73: [9, 65, 36, 73],
  74: [9, 65, 286, 74],
  75: [9, 65, 286, 75],
  76: [9, 65, 36, 76],
  77: [9, 65, 77],
  78: [9, 65, 36, 78],
  79: [9, 65, 36, 79],
  80: [9, 65, 36, 80],
  81: [9, 65, 36, 81],
  82: [9, 65, 36, 82],
  83: [9, 65, 36, 83],
  84: [9, 65, 36, 84],
  0: [9, 65, 36, 0],
  44: [9, 65, 36, 44],
  46: [9, 65, 36, 46],
  47: [9, 65, 36, 47],
  49: [9, 65, 36, 285, 49],
  55: [9, 65, 36, 55],
  102: [9, 65, 286, 66, 102],
  86: [9, 65, 286, 74, 86],
  87: [9, 65, 286, 74, 87],
  85: [9, 65, 286, 66, 102, 85]},
 10: {},
 36: {0: [36, 0],
  284: [36, 284],
  285: [36, 285],
  286: [36, 65, 286],
  287: [36, 287],
  37: [36, 37],
  39: [36, 39],
  40: [36, 40],
  41: [36, 41],
  42: [36, 42],
  43: [36, 65, 43],
  44: [36, 44],
  45: [36, 45],
  46: [36, 46],
  47: [36, 47],
  48: [36, 48],
  49: [36, 285, 49],
  50: [36, 50],
  51: [36, 51],
  52: [36, 52],
  53: [36, 53],
  55: [36, 55],
  56: [36, 56],
  57: [36, 57],
  58: [36, 58],
  59: [36, 65, 286, 59],
  60: [36, 60],
  61: [36, 61],
  62: [36, 62],
  63: [36, 63],
  64: [36, 64],
  65: [36, 65],
  66: [36, 66],
  67: [36, 67],
  68: [36, 68],
  69: [36, 69],
  70: [36, 70],
  71: [36, 71],
  72: [36, 65, 286, 72],
  73: [36, 73],
  74: [36, 74],
  75: [36, 75],
  76: [36, 76],
  77: [36, 77],
  78: [36, 78],
  79: [36, 79],
  80: [36, 80],
  81: [36, 81],
  82: [36, 82],
  83: [36, 83],
  84: [36, 84],
  38: [36, 65, 286, 38],
  102: [36, 66, 102],
  86: [36, 73, 86],
  87: [36, 73, 87],
  85: [36, 66, 102, 85]},
 38: {},
 40: {},
 59: {},
 60: {284: [60, 284],
  285: [60, 285],
  37: [60, 37],
  39: [60, 39],
  41: [60, 41],
  42: [60, 42],
  44: [60, 44],
  45: [60, 45],
  46: [60, 46],
  47: [60, 47],
  48: [60, 48],
  49: [60, 49],
  51: [60, 51],
  52: [60, 52],
  57: [60, 57],
  58: [60, 58],
  61: [60, 61],
  62: [60, 62],
  63: [60, 63],
  67: [60, 67],
  68: [60, 68],
  69: [60, 69],
  70: [60, 70],
  71: [60, 71],
  73: [60, 73],
  74: [60, 74],
  75: [60, 75],
  76: [60, 76],
  78: [60, 78],
  79: [60, 79],
  80: [60, 80],
  81: [60, 81],
  82: [60, 82],
  83: [60, 83],
  84: [60, 84],
  86: [60, 73, 86],
  87: [60, 73, 87],
  50: [60, 73, 87, 50]},
 65: {284: [65, 36, 284],
  285: [65, 36, 285],
  286: [65, 286],
  287: [65, 36, 287],
  63: [65, 64, 63],
  36: [65, 36],
  37: [65, 37],
  38: [65, 286, 38],
  39: [65, 39],
  40: [65, 40],
  41: [65, 36, 41],
  42: [65, 36, 42],
  43: [65, 43],
  45: [65, 45],
  48: [65, 36, 48],
  50: [65, 36, 50],
  51: [65, 36, 51],
  52: [65, 52],
  53: [65, 36, 53],
  56: [65, 36, 56],
  57: [65, 36, 57],
  58: [65, 36, 58],
  59: [65, 286, 59],
  60: [65, 60],
  61: [65, 36, 61],
  62: [65, 36, 62],
  64: [65, 64],
  66: [65, 286, 66],
  67: [65, 36, 67],
  68: [65, 36, 68],
  69: [65, 36, 69],
  70: [65, 36, 70],
  71: [65, 36, 71],
  72: [65, 286, 72],
  73: [65, 36, 73],
  74: [65, 286, 74],
  75: [65, 286, 75],
  76: [65, 36, 76],
  77: [65, 77],
  78: [65, 36, 78],
  79: [65, 36, 79],
  80: [65, 36, 80],
  81: [65, 36, 81],
  82: [65, 36, 82],
  83: [65, 36, 83],
  84: [65, 36, 84],
  0: [65, 36, 0],
  44: [65, 36, 44],
  46: [65, 36, 46],
  47: [65, 36, 47],
  49: [65, 36, 285, 49],
  55: [65, 36, 55],
  102: [65, 286, 66, 102],
  86: [65, 286, 74, 86],
  87: [65, 286, 74, 87],
  85: [65, 286, 66, 102, 85]},
 66: {0: [66, 36, 0],
  102: [66, 102],
  284: [66, 36, 284],
  285: [66, 36, 285],
  286: [66, 286],
  287: [66, 36, 287],
  36: [66, 36],
  37: [66, 37],
  38: [66, 286, 38],
  39: [66, 39],
  40: [66, 40],
  42: [66, 36, 42],
  43: [66, 43],
  44: [66, 36, 44],
  45: [66, 45],
  47: [66, 36, 47],
  48: [66, 36, 48],
  49: [66, 36, 285, 49],
  51: [66, 36, 51],
  53: [66, 36, 53],
  57: [66, 36, 57],
  58: [66, 36, 58],
  59: [66, 286, 59],
  60: [66, 60],
  61: [66, 36, 61],
  62: [66, 36, 62],
  63: [66, 64, 63],
  64: [66, 64],
  65: [66, 65],
  67: [66, 36, 67],
  68: [66, 36, 68],
  69: [66, 36, 69],
  70: [66, 36, 70],
  71: [66, 36, 71],
  72: [66, 286, 72],
  73: [66, 36, 73],
  74: [66, 286, 74],
  75: [66, 286, 75],
  76: [66, 36, 76],
  77: [66, 77],
  78: [66, 36, 78],
  79: [66, 36, 79],
  80: [66, 36, 80],
  81: [66, 36, 81],
  82: [66, 36, 82],
  83: [66, 36, 83],
  84: [66, 36, 84],
  41: [66, 36, 41],
  46: [66, 36, 46],
  50: [66, 36, 50],
  52: [66, 36, 52],
  55: [66, 36, 55],
  56: [66, 36, 56],
  86: [66, 286, 74, 86],
  87: [66, 286, 74, 87],
  85: [66, 102, 85]},
 72: {63: [72, 63]},
 75: {63: [75, 63]},
 90: {85: [90, 85]},
 91: {},
 92: {},
 93: {},
 94: {},
 95: {},
 96: {},
 97: {},
 98: {106: [98, 106],
  107: [98, 107],
  109: [98, 109],
  110: [98, 110],
  111: [98, 111],
  115: [98, 115],
  116: [98, 116],
  117: [98, 117],
  118: [98, 118],
  121: [98, 121],
  125: [98, 125],
  127: [98, 127],
  128: [98, 128],
  129: [98, 129],
  130: [98, 130],
  131: [98, 131],
  133: [98, 133],
  134: [98, 134],
  135: [98, 135],
  137: [98, 137],
  138: [98, 138],
  139: [98, 139],
  142: [98, 142],
  143: [98, 143],
  144: [98, 144],
  145: [98, 145],
  146: [98, 146],
  147: [98, 147],
  148: [98, 148],
  149: [98, 149],
  150: [98, 150],
  151: [98, 151],
  152: [98, 152],
  153: [98, 153],
  154: [98, 154],
  155: [98, 155],
  156: [98, 156],
  157: [98, 157],
  158: [98, 158],
  159: [98, 159],
  160: [98, 160],
  161: [98, 161],
  162: [98, 162],
  163: [98, 163],
  164: [98, 164],
  165: [98, 165],
  166: [98, 166],
  167: [98, 167],
  168: [98, 168],
  169: [98, 169],
  170: [98, 170],
  171: [98, 171],
  172: [98, 172],
  173: [98, 173],
  174: [98, 174],
  175: [98, 175],
  176: [98, 176],
  177: [98, 177],
  178: [98, 178],
  179: [98, 179],
  180: [98, 180],
  181: [98, 181],
  182: [98, 182],
  183: [98, 183],
  184: [98, 184],
  185: [98, 185],
  186: [98, 186],
  187: [98, 187],
  188: [98, 188],
  189: [98, 189],
  190: [98, 190],
  191: [98, 191],
  192: [98, 192],
  193: [98, 193],
  194: [98, 194],
  195: [98, 195],
  196: [98, 196],
  197: [98, 197],
  198: [98, 198],
  199: [98, 199],
  200: [98, 200],
  201: [98, 201],
  202: [98, 202],
  203: [98, 203],
  204: [98, 204],
  205: [98, 205],
  206: [98, 206],
  207: [98, 207],
  208: [98, 208],
  209: [98, 209],
  210: [98, 210],
  211: [98, 211],
  212: [98, 212],
  213: [98, 213],
  214: [98, 214],
  215: [98, 215],
  216: [98, 216],
  217: [98, 217],
  218: [98, 218],
  219: [98, 219],
  220: [98, 220],
  221: [98, 221],
  222: [98, 222],
  223: [98, 223],
  224: [98, 224],
  225: [98, 225],
  226: [98, 226],
  227: [98, 227],
  228: [98, 228],
  229: [98, 229],
  230: [98, 230],
  231: [98, 231],
  232: [98, 232],
  233: [98, 233],
  234: [98, 234],
  235: [98, 235],
  236: [98, 236],
  237: [98, 237],
  238: [98, 238],
  239: [98, 239],
  240: [98, 240],
  241: [98, 241],
  242: [98, 242],
  243: [98, 243],
  244: [98, 244],
  245: [98, 245],
  246: [98, 246],
  247: [98, 247],
  248: [98, 248],
  249: [98, 249],
  250: [98, 250],
  251: [98, 251],
  252: [98, 252],
  253: [98, 253],
  254: [98, 254],
  255: [98, 255],
  256: [98, 256],
  257: [98, 257],
  258: [98, 258],
  259: [98, 259],
  260: [98, 260],
  261: [98, 261],
  262: [98, 262],
  263: [98, 263],
  264: [98, 264],
  265: [98, 265],
  266: [98, 266],
  267: [98, 267],
  268: [98, 268],
  269: [98, 269],
  270: [98, 270],
  271: [98, 271],
  272: [98, 272],
  273: [98, 273],
  279: [98, 279],
  280: [98, 280],
  281: [98, 281],
  282: [98, 282],
  283: [98, 283]},
 288: {74: [288, 74],
  86: [288, 74, 86],
  87: [288, 74, 87],
  50: [288, 74, 87, 50]},
 289: {74: [289, 74],
  86: [289, 74, 86],
  87: [289, 74, 87],
  50: [289, 74, 87, 50]},
 291: {74: [291, 74],
  86: [291, 74, 86],
  87: [291, 74, 87],
  50: [291, 74, 87, 50]},
 293: {74: [293, 74],
  86: [293, 74, 86],
  87: [293, 74, 87],
  50: [293, 74, 87, 50]},
 294: {74: [294, 74],
  86: [294, 74, 86],
  87: [294, 74, 87],
  50: [294, 74, 87, 50]},
 295: {74: [295, 74],
  86: [295, 74, 86],
  87: [295, 74, 87],
  50: [295, 74, 87, 50]},
 296: {74: [296, 74],
  86: [296, 74, 86],
  87: [296, 74, 87],
  50: [296, 74, 87, 50]},
 297: {74: [297, 74],
  86: [297, 74, 86],
  87: [297, 74, 87],
  50: [297, 74, 87, 50]},
 299: {74: [299, 74],
  86: [299, 74, 86],
  87: [299, 74, 87],
  50: [299, 74, 87, 50]},
 301: {74: [301, 74],
  86: [301, 74, 86],
  87: [301, 74, 87],
  50: [301, 74, 87, 50]},
 302: {74: [302, 74],
  86: [302, 74, 86],
  87: [302, 74, 87],
  50: [302, 74, 87, 50]},
 303: {74: [303, 74],
  86: [303, 74, 86],
  87: [303, 74, 87],
  50: [303, 74, 87, 50]},
 304: {74: [304, 74],
  86: [304, 74, 86],
  87: [304, 74, 87],
  50: [304, 74, 87, 50]},
 305: {74: [305, 74],
  86: [305, 74, 86],
  87: [305, 74, 87],
  50: [305, 74, 87, 50]},
 306: {74: [306, 74],
  86: [306, 74, 86],
  87: [306, 74, 87],
  50: [306, 74, 87, 50]},
 307: {74: [307, 74],
  86: [307, 74, 86],
  87: [307, 74, 87],
  50: [307, 74, 87, 50]},
 308: {74: [308, 74],
  86: [308, 74, 86],
  87: [308, 74, 87],
  50: [308, 74, 87, 50]},
 309: {74: [309, 74],
  86: [309, 74, 86],
  87: [309, 74, 87],
  50: [309, 74, 87, 50]},
 311: {74: [311, 74],
  86: [311, 74, 86],
  87: [311, 74, 87],
  50: [311, 74, 87, 50]},
 312: {74: [312, 74],
  86: [312, 74, 86],
  87: [312, 74, 87],
  50: [312, 74, 87, 50]},
 313: {74: [313, 74],
  86: [313, 74, 86],
  87: [313, 74, 87],
  50: [313, 74, 87, 50]},
 314: {74: [314, 74],
  86: [314, 74, 86],
  87: [314, 74, 87],
  50: [314, 74, 87, 50]},
 315: {74: [315, 74],
  86: [315, 74, 86],
  87: [315, 74, 87],
  50: [315, 74, 87, 50]},
 318: {74: [318, 74],
  86: [318, 74, 86],
  87: [318, 74, 87],
  50: [318, 74, 87, 50]},
 319: {74: [319, 74],
  86: [319, 74, 86],
  87: [319, 74, 87],
  50: [319, 74, 87, 50]},
 320: {74: [320, 74],
  86: [320, 74, 86],
  87: [320, 74, 87],
  50: [320, 74, 87, 50]},
 321: {74: [321, 74],
  86: [321, 74, 86],
  87: [321, 74, 87],
  50: [321, 74, 87, 50]},
 322: {74: [322, 74],
  86: [322, 74, 86],
  87: [322, 74, 87],
  50: [322, 74, 87, 50]},
 323: {74: [323, 74],
  86: [323, 74, 86],
  87: [323, 74, 87],
  50: [323, 74, 87, 50]},
 324: {74: [324, 74],
  86: [324, 74, 86],
  87: [324, 74, 87],
  50: [324, 74, 87, 50]},
 331: {74: [331, 74],
  86: [331, 74, 86],
  87: [331, 74, 87],
  50: [331, 74, 87, 50]},
 341: {74: [341, 74],
  86: [341, 74, 86],
  87: [341, 74, 87],
  50: [341, 74, 87, 50]},
 357: {74: [357, 74],
  86: [357, 74, 86],
  87: [357, 74, 87],
  50: [357, 74, 87, 50]},
 392: {74: [392, 74],
  86: [392, 74, 86],
  87: [392, 74, 87],
  50: [392, 74, 87, 50]},
 405: {74: [405, 74],
  86: [405, 74, 86],
  87: [405, 74, 87],
  50: [405, 74, 87, 50]},
 444: {74: [444, 74],
  86: [444, 74, 86],
  87: [444, 74, 87],
  50: [444, 74, 87, 50]},
 448: {74: [448, 74],
  86: [448, 74, 86],
  87: [448, 74, 87],
  50: [448, 74, 87, 50]},
 457: {74: [457, 74],
  86: [457, 74, 86],
  87: [457, 74, 87],
  50: [457, 74, 87, 50]},
 458: {74: [458, 74],
  86: [458, 74, 86],
  87: [458, 74, 87],
  50: [458, 74, 87, 50]},
 467: {74: [467, 74],
  86: [467, 74, 86],
  87: [467, 74, 87],
  50: [467, 74, 87, 50]},
 469: {74: [469, 74],
  86: [469, 74, 86],
  87: [469, 74, 87],
  50: [469, 74, 87, 50]},
 481: {74: [481, 74],
  86: [481, 74, 86],
  87: [481, 74, 87],
  50: [481, 74, 87, 50]},
 491: {},
 501: {},
 507: {},
 508: {},
 509: {},
 511: {},
 512: {},
 514: {},
 521: {},
 523: {},
 527: {},
 530: {},
 531: {},
 532: {},
 533: {},
 534: {},
 539: {},
 544: {},
 548: {},
 550: {},
 553: {},
 557: {},
 561: {},
 562: {},
 563: {},
 564: {},
 565: {},
 567: {},
 573: {},
 575: {},
 577: {},
 585: {},
 590: {},
 597: {},
 599: {},
 600: {},
 603: {},
 607: {},
 609: {},
 610: {},
 620: {},
 623: {},
 624: {},
 625: {},
 626: {},
 631: {},
 632: {},
 637: {},
 638: {},
 639: {},
 640: {},
 645: {},
 648: {},
 649: {},
 650: {},
 651: {},
 653: {},
 654: {},
 655: {},
 656: {},
 660: {},
 661: {},
 663: {},
 665: {},
 666: {},
 668: {},
 672: {},
 673: {},
 676: {},
 677: {},
 681: {},
 684: {},
 686: {},
 692: {},
 693: {},
 694: {},
 1: {4: [1, 4], 7: [1, 4, 7]},
 6: {16: [6, 16],
  17: [6, 17],
  18: [6, 18],
  688: [6, 16, 688],
  539: [6, 16, 539],
  567: [6, 16, 567],
  609: [6, 16, 609],
  637: [6, 16, 637],
  655: [6, 16, 655],
  660: [6, 16, 660],
  661: [6, 16, 661],
  676: [6, 16, 676]},
 16: {688: [16, 688],
  539: [16, 539],
  567: [16, 567],
  609: [16, 609],
  637: [16, 637],
  655: [16, 655],
  660: [16, 660],
  661: [16, 661],
  676: [16, 676]},
 17: {},
 18: {},
 2: {19: [2, 19],
  689: [2, 19, 689],
  512: [2, 19, 512],
  534: [2, 19, 534],
  575: [2, 19, 575],
  651: [2, 19, 651]},
 19: {689: [19, 689],
  512: [19, 512],
  534: [19, 534],
  575: [19, 575],
  651: [19, 651]},
 3: {23: [3, 23],
  24: [3, 24],
  25: [3, 25],
  28: [3, 23, 28],
  29: [3, 23, 29],
  30: [3, 23, 30],
  26: [3, 24, 26],
  27: [3, 24, 27],
  33: [3, 25, 33],
  34: [3, 25, 34],
  35: [3, 25, 35],
  501: [3, 25, 33, 501],
  509: [3, 25, 33, 509],
  548: [3, 25, 33, 548],
  656: [3, 25, 33, 656],
  672: [3, 25, 33, 672],
  511: [3, 25, 34, 511],
  521: [3, 25, 34, 521],
  533: [3, 25, 34, 533],
  562: [3, 25, 34, 562],
  603: [3, 25, 34, 603],
  649: [3, 25, 34, 649],
  666: [3, 25, 34, 666],
  673: [3, 25, 34, 673],
  507: [3, 25, 35, 507],
  557: [3, 25, 35, 557],
  565: [3, 25, 35, 565],
  573: [3, 25, 35, 573],
  638: [3, 25, 35, 638],
  668: [3, 25, 35, 668]},
 23: {28: [23, 28], 29: [23, 29], 30: [23, 30]},
 24: {26: [24, 26], 27: [24, 27]},
 25: {33: [25, 33],
  34: [25, 34],
  35: [25, 35],
  501: [25, 33, 501],
  509: [25, 33, 509],
  548: [25, 33, 548],
  656: [25, 33, 656],
  672: [25, 33, 672],
  511: [25, 34, 511],
  521: [25, 34, 521],
  533: [25, 34, 533],
  562: [25, 34, 562],
  603: [25, 34, 603],
  649: [25, 34, 649],
  666: [25, 34, 666],
  673: [25, 34, 673],
  507: [25, 35, 507],
  557: [25, 35, 557],
  565: [25, 35, 565],
  573: [25, 35, 573],
  638: [25, 35, 638],
  668: [25, 35, 668]},
 26: {},
 27: {},
 28: {},
 29: {},
 30: {},
 22: {31: [22, 31], 32: [22, 32]},
 31: {},
 32: {},
 33: {501: [33, 501],
  509: [33, 509],
  548: [33, 548],
  656: [33, 656],
  672: [33, 672]},
 34: {511: [34, 511],
  521: [34, 521],
  533: [34, 533],
  562: [34, 562],
  603: [34, 603],
  649: [34, 649],
  666: [34, 666],
  673: [34, 673]},
 35: {507: [35, 507],
  557: [35, 557],
  565: [35, 565],
  573: [35, 573],
  638: [35, 638],
  668: [35, 668]},
 102: {72: [102, 72], 85: [102, 85], 63: [102, 72, 63]},
 101: {102: [101, 102],
  72: [101, 102, 72],
  85: [101, 102, 85],
  63: [101, 102, 72, 63]},
 85: {},
 106: {},
 107: {},
 109: {},
 110: {},
 111: {},
 115: {},
 116: {},
 117: {},
 118: {},
 121: {},
 125: {},
 127: {},
 128: {},
 129: {},
 130: {},
 131: {},
 133: {},
 134: {},
 135: {},
 137: {},
 138: {},
 139: {},
 142: {},
 143: {},
 144: {},
 145: {},
 146: {},
 147: {},
 148: {},
 149: {},
 150: {},
 151: {},
 152: {},
 153: {},
 154: {},
 155: {},
 156: {},
 157: {},
 158: {},
 159: {},
 160: {},
 161: {},
 162: {},
 163: {},
 164: {},
 165: {},
 166: {},
 167: {},
 168: {},
 169: {},
 170: {},
 171: {},
 172: {},
 173: {},
 174: {},
 175: {},
 176: {},
 177: {},
 178: {},
 179: {},
 180: {},
 181: {},
 182: {},
 183: {},
 184: {},
 185: {},
 186: {},
 187: {},
 188: {},
 189: {},
 190: {},
 191: {},
 192: {},
 193: {},
 194: {},
 195: {},
 196: {},
 197: {},
 198: {},
 199: {},
 200: {},
 201: {},
 202: {},
 203: {},
 204: {},
 205: {},
 206: {},
 207: {},
 208: {},
 209: {},
 210: {},
 211: {},
 212: {},
 213: {},
 214: {},
 215: {},
 216: {},
 217: {},
 218: {},
 219: {},
 220: {},
 221: {},
 222: {},
 223: {},
 224: {},
 225: {},
 226: {},
 227: {},
 228: {},
 229: {},
 230: {},
 231: {},
 232: {},
 233: {},
 234: {},
 235: {},
 236: {},
 237: {},
 238: {},
 239: {},
 240: {},
 241: {},
 242: {},
 243: {},
 244: {},
 245: {},
 246: {},
 247: {},
 248: {},
 249: {},
 250: {},
 251: {},
 252: {},
 253: {},
 254: {},
 255: {},
 256: {},
 257: {},
 258: {},
 259: {},
 260: {},
 261: {},
 262: {},
 263: {},
 264: {},
 265: {},
 266: {},
 267: {},
 268: {},
 269: {},
 270: {},
 271: {},
 272: {},
 273: {},
 279: {},
 280: {},
 281: {},
 282: {},
 283: {},
 285: {49: [285, 49],
  74: [285, 74],
  86: [285, 74, 86],
  87: [285, 74, 87],
  50: [285, 74, 87, 50]},
 287: {63: [287, 63],
  74: [287, 74],
  86: [287, 74, 86],
  87: [287, 74, 87],
  50: [287, 74, 87, 50]},
 284: {48: [284, 48]},
 286: {38: [286, 38],
  59: [286, 59],
  60: [286, 60],
  65: [286, 65],
  66: [286, 66],
  72: [286, 72],
  75: [286, 75],
  36: [286, 36],
  64: [286, 64],
  74: [286, 74],
  284: [286, 36, 284],
  285: [286, 36, 285],
  37: [286, 36, 37],
  39: [286, 36, 39],
  41: [286, 36, 41],
  42: [286, 36, 42],
  44: [286, 36, 44],
  45: [286, 36, 45],
  46: [286, 36, 46],
  47: [286, 36, 47],
  48: [286, 36, 48],
  49: [286, 36, 285, 49],
  51: [286, 36, 51],
  52: [286, 36, 52],
  57: [286, 36, 57],
  58: [286, 36, 58],
  61: [286, 36, 61],
  62: [286, 36, 62],
  63: [286, 72, 63],
  67: [286, 36, 67],
  68: [286, 36, 68],
  69: [286, 36, 69],
  70: [286, 36, 70],
  71: [286, 36, 71],
  73: [286, 36, 73],
  76: [286, 36, 76],
  78: [286, 36, 78],
  79: [286, 36, 79],
  80: [286, 36, 80],
  81: [286, 36, 81],
  82: [286, 36, 82],
  83: [286, 36, 83],
  84: [286, 36, 84],
  287: [286, 36, 287],
  40: [286, 65, 40],
  43: [286, 65, 43],
  50: [286, 36, 50],
  53: [286, 36, 53],
  56: [286, 36, 56],
  77: [286, 65, 77],
  0: [286, 36, 0],
  102: [286, 66, 102],
  55: [286, 36, 55],
  86: [286, 74, 86],
  87: [286, 74, 87],
  85: [286, 66, 102, 85]},
 76: {48: [76, 48]},
 48: {},
 49: {},
 87: {50: [87, 50]},
 50: {},
 89: {50: [89, 50]},
 63: {},
 58: {63: [58, 63]},
 64: {63: [64, 63]},
 74: {86: [74, 86], 87: [74, 87], 50: [74, 87, 50]},
 73: {86: [73, 86], 87: [73, 87], 50: [73, 87, 50]},
 86: {},
 37: {},
 39: {},
 41: {},
 42: {},
 43: {},
 44: {},
 45: {},
 46: {},
 47: {},
 51: {},
 52: {},
 53: {},
 55: {},
 56: {},
 57: {},
 61: {},
 62: {},
 67: {},
 68: {},
 69: {},
 70: {},
 71: {74: [71, 74], 86: [71, 74, 86], 87: [71, 74, 87], 50: [71, 74, 87, 50]},
 77: {},
 78: {},
 79: {},
 80: {},
 81: {},
 82: {},
 83: {74: [83, 74], 86: [83, 74, 86], 87: [83, 74, 87], 50: [83, 74, 87, 50]},
 84: {},
 290: {74: [290, 74],
  86: [290, 74, 86],
  87: [290, 74, 87],
  50: [290, 74, 87, 50]},
 292: {74: [292, 74],
  86: [292, 74, 86],
  87: [292, 74, 87],
  50: [292, 74, 87, 50]},
 298: {74: [298, 74],
  86: [298, 74, 86],
  87: [298, 74, 87],
  50: [298, 74, 87, 50]},
 300: {74: [300, 74],
  86: [300, 74, 86],
  87: [300, 74, 87],
  50: [300, 74, 87, 50]},
 310: {74: [310, 74],
  86: [310, 74, 86],
  87: [310, 74, 87],
  50: [310, 74, 87, 50]},
 316: {74: [316, 74],
  86: [316, 74, 86],
  87: [316, 74, 87],
  50: [316, 74, 87, 50]},
 317: {74: [317, 74],
  86: [317, 74, 86],
  87: [317, 74, 87],
  50: [317, 74, 87, 50]},
 325: {74: [325, 74],

In [ ]:
# prompt: can you display the combined weight from the shortest_paths and display the path with the max weight

# Function to calculate the total weight of a path
def calculate_path_weight(graph, path):
    total_weight = 0
    # Add the weight of the starting node
    if path:
        total_weight += graph.nodes[path[0]].get('weight', 0) # Get node weight
    # Add the weight of the edges and the weights of subsequent nodes
    for i in range(len(path) - 1):
        u, v = path[i], path[i+1]
        # Add edge weight
        total_weight += graph.edges[u, v].get('weight', 0) # Get edge weight
        # Add weight of the next node
        total_weight += graph.nodes[v].get('weight', 0) # Get node weight
    return total_weight

max_weight = -1
max_path = None

# Iterate through the filtered shortest paths and calculate total weights
for source, paths in shortest_paths_filtered.items():
    for target, path in paths.items():
        current_weight = calculate_path_weight(G, path)
#        print(f"Path from {source} to {target}: {path}, Combined Weight: {current_weight}")
        if current_weight > max_weight:
            max_weight = current_weight
            max_path = path

print(f"\nPath with the maximum combined weight: {max_path}")
print(f"Maximum combined weight: {max_weight}")

Path with the maximum combined weight: [9, 65, 36, 0]
Maximum combined weight: 87.0

In [ ]:
max_path
max_path = pd.DataFrame(max_path)
max_path.head()

    0
0   9
1  65
2  36
3   0

In [ ]:
rename = {0: 'id'}
max_path = max_path.rename(columns=rename)
max_path

   id
0   9
1  65
2  36
3   0

In [ ]:
# prompt: get label from nodes where id=max_path['id']

# Assuming max_path is a DataFrame with an 'id' column representing the node IDs in the max path
# and nodes is a DataFrame with 'id' and 'properties' columns.

# Get the list of node IDs from the max_path DataFrame
max_path_node_ids = max_path['id'].tolist()

# Filter the nodes DataFrame to get only the nodes that are in the max_path
nodes_in_max_path = nodes[nodes['id'].isin(max_path_node_ids)].copy()

# Now, extract the 'name' property from the 'properties' column for these nodes
# Use .loc to avoid SettingWithCopyWarning
# We use a lambda function with .apply to safely access nested dictionary keys.
max_path_node_labels = nodes_in_max_path.loc[:, 'properties'].apply(lambda x: x.get('name', ''))

print("Labels of nodes in the max path:")
print(max_path_node_labels.tolist())

Labels of nodes in the max path:
['MARK.LOCAL', 'T0 Admin Groups@MARK.LOCAL', 'ADMINISTRATORS@MARK.LOCAL', 'ENTERPRISE ADMINS@MARK.LOCAL']

In [ ]:
max_path

   id
0   9
1  65
2  36
3   0

ignore from here

In [ ]:
vertices = nodes['id'].tolist()
vertices

[6221,
 6222,
 6223,
 6224,
 6225,
 6226,
 6227,
 6228,
 6229,
 6230,
 6231,
 6232,
 6233,
 6234,
 6235,
 6236,
 6237,
 6238,
 6239,
 6240,
 6241,
 6242,
 6243,
 6244,
 6245,
 6246,
 6247,
 6248,
 6249,
 6250,
 6251,
 6252,
 6253,
 6254,
 6255,
 6256,
 6257,
 6258,
 6259,
 6260,
 6261,
 6262,
 6263,
 6264,
 6265,
 6266,
 6267,
 6268,
 6269,
 6270,
 6271,
 6272,
 6273,
 6274,
 6275,
 6276,
 6277,
 6278,
 6279,
 6280,
 6281,
 6282,
 6283,
 6284,
 6285,
 6286,
 6287,
 6288,
 6289,
 6290,
 6291,
 6292,
 6293,
 6294,
 6295,
 6296,
 6297,
 6298,
 6299,
 6300,
 6301,
 6302,
 6303,
 6304,
 6305,
 6306,
 6307,
 6308,
 6309,
 6310,
 6311,
 6312,
 6313,
 6314,
 6315,
 6316,
 6317,
 6318,
 6319,
 6320,
 6321,
 6322,
 6323,
 6324,
 6325,
 6326,
 6327,
 6328,
 6329,
 6330,
 6331,
 6332,
 6333,
 6334,
 6335,
 6336,
 6337,
 6338,
 6339,
 6340,
 6341,
 6342,
 6343,
 6344,
 6345,
 6346,
 6347,
 6348,
 6349,
 6350,
 6351,
 6352,
 6353,
 6354,
 6355,
 6356,
 6357,
 6358,
 6359,
 6360,
 6361,
 6362,
 6363,
 6364,
 6365,
 6366,
 6367,
 6368,
 6369,
 6370,
 6371,
 6372,
 6373,
 6374,
 6375,
 6376,
 6377,
 6378,
 6379,
 6380,
 6381,
 6382,
 6383,
 6384,
 6385,
 6386,
 6387,
 6388,
 6389,
 6390,
 6391,
 6392,
 6393,
 6394,
 6395,
 6396,
 6397,
 6398,
 6399,
 6400,
 6401,
 6402,
 6403,
 6404,
 6405,
 6406,
 6407,
 6408,
 6409,
 6410,
 6411,
 6412,
 6413,
 6414,
 6415,
 6416,
 6417,
 6418,
 6419,
 6420,
 6421,
 6422,
 6423,
 6424,
 6425,
 6426,
 6427,
 6428,
 6429,
 6430,
 6431,
 6432,
 6433,
 6434,
 6435,
 6436,
 6437,
 6438,
 6439,
 6440,
 6441,
 6442,
 6443,
 6444,
 6445,
 6446,
 6447,
 6448,
 6449,
 6450,
 6451,
 6452,
 6453,
 6454,
 6455,
 6456,
 6457,
 6458,
 6459,
 6460,
 6461,
 6462,
 6463,
 6464,
 6465,
 6466,
 6467,
 6468,
 6469,
 6470,
 6471,
 6472,
 6473,
 6474,
 6475,
 6476,
 6477,
 6478,
 6479,
 6480,
 6481,
 6482,
 6483,
 6484,
 6485,
 6486,
 6487,
 6488,
 6489,
 6490,
 6491,
 6492,
 6493,
 6494,
 6495,
 6496,
 6497,
 6498,
 6499,
 6500,
 6501,
 6502,
 6503,
 6504,
 6505,
 6506,
 6507,
 6508,
 6509,
 6510,
 6511,
 6512,
 6513,
 6514,
 6515,
 6516,
 6517,
 6518,
 6519,
 6520,
 6521,
 6522,
 6523,
 6524,
 6525,
 6526,
 6527,
 6528,
 6529,
 6530,
 6531,
 6532,
 6533,
 6534,
 6535,
 6536,
 6537,
 6538,
 6539,
 6540,
 6541,
 6542,
 6543,
 6544,
 6545,
 6546,
 6547,
 6548,
 6549,
 6550,
 6551,
 6552,
 6553,
 6554,
 6555,
 6556,
 6557,
 6558,
 6559,
 6560,
 6561,
 6562,
 6563,
 6564,
 6565,
 6566,
 6567,
 6568,
 6569,
 6570,
 6571,
 6572,
 6573,
 6574,
 6575,
 6576,
 6577,
 6578,
 6579,
 6580,
 6581,
 6582,
 6583,
 6584,
 6585,
 6586,
 6587,
 6588,
 6589,
 6590,
 6591,
 6592,
 6593,
 6594,
 6595,
 6596,
 6597,
 6598,
 6599,
 6600,
 6601,
 6602,
 6603,
 6604,
 6605,
 6606,
 6607,
 6608,
 6609,
 6610,
 6611,
 6612,
 6613,
 6614,
 6615,
 6616,
 6617,
 6618,
 6619,
 6620,
 6621,
 6622,
 6623,
 6624,
 6625,
 6626,
 6627,
 6628,
 6629,
 6630,
 6631,
 6632,
 6633,
 6634,
 6635,
 6636,
 6637,
 6638,
 6639,
 6640,
 6641,
 6642,
 6643,
 6644,
 6645,
 6646,
 6647,
 6648,
 6649,
 6650,
 6651,
 6652,
 6653,
 6654,
 6655,
 6656,
 6657,
 6658,
 6659,
 6660,
 6661,
 6662,
 6663,
 6664,
 6665,
 6666,
 6667,
 6668,
 6669,
 6670,
 6671,
 6672,
 6673,
 6674,
 6675,
 6676,
 6677,
 6678,
 6679,
 6680,
 6681,
 6682,
 6683,
 6684,
 6685,
 6686,
 6687,
 6688,
 6689,
 6690,
 6691,
 6692,
 6693,
 6694,
 6695,
 6696,
 6697,
 6698,
 6699,
 6700,
 6701,
 6702,
 6703,
 6704,
 6705,
 6706,
 6707,
 6708,
 6709,
 6710,
 6711,
 6712,
 6713,
 6714,
 6715,
 6716,
 6717,
 6718,
 6719,
 6720,
 6721,
 6722,
 6723,
 6724,
 6725,
 6726,
 6727,
 6728,
 6729,
 6730,
 6731,
 6732,
 6733,
 6734,
 6735,
 6736,
 6737,
 6738,
 6739,
 6740,
 6741,
 6742,
 6743,
 6744,
 6745,
 6746,
 6747,
 6748,
 6749,
 6750,
 6751,
 6752,
 6753,
 6754,
 6755,
 6756,
 6757,
 6758,
 6759,
 6760,
 6761,
 6762,
 6763,
 6764,
 6765,
 6766,
 6767,
 6768,
 6769,
 6770,
 6771,
 6772,
 6773,
 6774,
 6775,
 6776,
 6777,
 6778,
 6779,
 6780,
 6781,
 6782,
 6783,
 6784,
 6785,
 6786,
 6787,
 6788,
 6789,
 6790,
 6791,
 6792,
 6793,
 6794,
 6795,
 6796,
 6797,
 6798,
 6799,
 6800,
 6801,
 6802,
 6803,
 6804,
 6805,
 6806,
 6807,
 6808,
 6809,
 6810,
 6811,
 6812,
 6813,
 6814,
 6815,
 6816,
 6817,
 6818,
 6819,
 6820,
 6821,
 6822,
 6823,
 6824,
 6825,
 6826,
 6827,
 6828,
 6829,
 6830,
 6831,
 6832,
 6833,
 6834,
 6835,
 6836,
 6837,
 6838,
 6839,
 6840,
 6841,
 6842,
 6843,
 6844,
 6845,
 6846,
 6847,
 6848,
 6849,
 6850,
 6851,
 6852,
 6853,
 6854,
 6855,
 6856,
 6857,
 6858,
 6859,
 6860,
 6861,
 6862,
 6863,
 6864,
 6865,
 6866,
 6867,
 6868,
 6869,
 6870,
 6871,
 6872,
 6873,
 6874,
 6875,
 6876,
 6877,
 6878,
 6879,
 6880,
 6881,
 6882,
 6883,
 6884,
 6885,
 6886,
 6887,
 6888,
 6889,
 6890,
 6891,
 6892,
 6893,
 6894,
 6895,
 6896,
 6897,
 6898,
 6899,
 6900,
 6901,
 6902,
 6903,
 6904,
 6905,
 6906,
 6907,
 6908,
 6909,
 6910,
 6911,
 6912,
 6913,
 6914,
 6915,
 6916,
 6917,
 6918,
 6919,
 6920,
 6921,
 6922,
 6923,
 6924,
 6925,
 6926,
 6927,
 6928,
 6929,
 6930,
 6931,
 6932,
 6933,
 6934,
 6935,
 6936,
 6937,
 6938,
 6939,
 6940,
 6941,
 6942,
 6943,
 6944,
 6945,
 6946,
 6947,
 6948,
 6949,
 6950,
 6951,
 6952,
 6953,
 6954,
 6955,
 6956,
 6957,
 6958,
 6959,
 6960,
 6961,
 6962,
 6963,
 6964,
 6965,
 6966,
 6967,
 6968,
 6969,
 6970,
 6971,
 6972,
 6973,
 6974,
 6975,
 6976,
 6977,
 6978,
 6979,
 6980,
 6981,
 6982,
 6983,
 6984,
 6985,
 6986,
 6987,
 6988,
 6989,
 6990,
 6991,
 6992,
 6993,
 6994,
 6995,
 6996,
 6997,
 6998,
 6999,
 7000,
 7001,
 7002,
 7003,
 7004,
 7005,
 7006,
 7007,
 7008,
 7009,
 7010,
 7011,
 7012,
 7013,
 7014,
 7015,
 7016,
 7017,
 7018,
 7019,
 7020,
 7021,
 7022,
 7023,
 7024,
 7025,
 7026,
 7027,
 7028,
 7029,
 7030,
 7031,
 7032,
 7033,
 7034,
 7035,
 7036,
 7037,
 7038,
 7039,
 7040,
 7041,
 7042,
 7043,
 7044,
 7045,
 7046,
 7047,
 7048,
 7049,
 7050,
 7051,
 7052,
 7053,
 7054,
 7055,
 7056,
 7057,
 7058,
 7059,
 7060,
 7061,
 7062,
 7063,
 7064,
 7065,
 7066,
 7067,
 7068,
 7069,
 7070,
 7071,
 7072,
 7073,
 7074,
 7075,
 7076,
 7077,
 7078,
 7079,
 7080,
 7081,
 7082,
 7083,
 7084,
 7085,
 7086,
 7087,
 7088,
 7089,
 7090,
 7091,
 7092,
 7093,
 7094,
 7095,
 7096,
 7097,
 7098,
 7099,
 7100,
 7101,
 7102,
 7103,
 7104,
 7105,
 7106,
 7107,
 7108,
 7109,
 7110,
 7111,
 7112,
 7113,
 7114,
 7115,
 7116,
 7117,
 7118,
 7119,
 7120,
 7121,
 7122,
 7123,
 7124,
 7125,
 7126,
 7127,
 7128,
 7129,
 7130,
 7131,
 7132,
 7133,
 7134,
 7135,
 7136,
 7137,
 7138,
 7139,
 7140,
 7141,
 7142,
 7143,
 7144,
 7145,
 7146,
 7147,
 7148,
 7149,
 7150,
 7151,
 7152,
 7153,
 7154,
 7155,
 7156,
 7157,
 7158,
 7159,
 7160,
 7161,
 7162,
 7163,
 7164,
 7165,
 7166,
 7167,
 7168,
 7169,
 7170,
 7171,
 7172,
 7173,
 7174,
 7175,
 7176,
 7177,
 7178,
 7179,
 7180,
 7181,
 7182,
 7183,
 7184,
 7185,
 7186,
 7187,
 7188,
 7189,
 7190,
 7191,
 7192,
 7193,
 7194,
 7195,
 7196,
 7197,
 7198,
 7199,
 7200,
 7201,
 7202,
 7203,
 7204,
 7205,
 7206,
 7207,
 7208,
 7209,
 7210,
 7211,
 7212,
 7213,
 7214,
 7215,
 7216,
 7217,
 7218,
 7219,
 7220,
 ...]

In [ ]:
adj_list=adj.values.tolist()
len(adj_list)

48321

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt

def createAdjacencyMatrix(vertices,edges):
  noofvertices=len(vertices)
  adjM=[]
  while(len(adjM)<noofvertices):
    temp=[]
    for i in range(noofvertices):
      temp.append(0)
    adjM.append(temp)
  for edge in edges:
    i=edge[0]
    j=edge[1]
    if i>=noofvertices or j>=noofvertices or i<0 or j<0:
      print(f"Not a Proper Input in Edge {i},{j}")
    else:
      adjM[i][j]=1
      adjM[j][i]=1
#  G=nx.Graph()
#  G.add_edges_from(edges)
#  nx.draw_networkx(G)
#  plt.show()
  return adjM
vertices = vertices
edges = adj_list
adjM=createAdjacencyMatrix(vertices,edges)

Not a Proper Input in Edge 10075,6298
Not a Proper Input in Edge 10077,6298
Not a Proper Input in Edge 10078,6298
Not a Proper Input in Edge 10080,6298
Not a Proper Input in Edge 10081,6298
Not a Proper Input in Edge 10082,6298
Not a Proper Input in Edge 10083,6298
Not a Proper Input in Edge 10085,6298
Not a Proper Input in Edge 10087,6298
Not a Proper Input in Edge 10088,6298
Not a Proper Input in Edge 10089,6298
Not a Proper Input in Edge 10090,6298
Not a Proper Input in Edge 10094,6298
Not a Proper Input in Edge 10100,6298
Not a Proper Input in Edge 10101,6298
Not a Proper Input in Edge 10103,6298
Not a Proper Input in Edge 10104,6298
Not a Proper Input in Edge 10105,6298
Not a Proper Input in Edge 10106,6298
Not a Proper Input in Edge 10107,6298
Not a Proper Input in Edge 10108,6298
Not a Proper Input in Edge 10110,6298
Not a Proper Input in Edge 10111,6298
Not a Proper Input in Edge 10114,6298
Not a Proper Input in Edge 10116,6298
Not a Proper Input in Edge 10117,6298
Not a Proper Input in Edge 10118,6298
Not a Proper Input in Edge 10119,6298
Not a Proper Input in Edge 10120,6298
Not a Proper Input in Edge 10123,6298
Not a Proper Input in Edge 10124,6298
Not a Proper Input in Edge 10125,6298
Not a Proper Input in Edge 10127,6298
Not a Proper Input in Edge 10134,6298
Not a Proper Input in Edge 10136,6298
Not a Proper Input in Edge 10137,6298
Not a Proper Input in Edge 10140,6298
Not a Proper Input in Edge 10141,6298
Not a Proper Input in Edge 10142,6298
Not a Proper Input in Edge 10145,6298
Not a Proper Input in Edge 10148,6298
Not a Proper Input in Edge 10150,6298
Not a Proper Input in Edge 10153,6298
Not a Proper Input in Edge 10156,6298
Not a Proper Input in Edge 10161,6298
Not a Proper Input in Edge 10165,6298
Not a Proper Input in Edge 10166,6298
Not a Proper Input in Edge 10167,6298
Not a Proper Input in Edge 10168,6298
Not a Proper Input in Edge 10170,6298
Not a Proper Input in Edge 10171,6298
Not a Proper Input in Edge 10173,6298
Not a Proper Input in Edge 10174,6298
Not a Proper Input in Edge 10178,6298
Not a Proper Input in Edge 10182,6298
Not a Proper Input in Edge 10185,6298
Not a Proper Input in Edge 10189,6298
Not a Proper Input in Edge 10190,6298
Not a Proper Input in Edge 10191,6298
Not a Proper Input in Edge 10192,6298
Not a Proper Input in Edge 10193,6298
Not a Proper Input in Edge 10194,6298
Not a Proper Input in Edge 10196,6298
Not a Proper Input in Edge 10198,6298
Not a Proper Input in Edge 10199,6298
Not a Proper Input in Edge 10201,6298
Not a Proper Input in Edge 10202,6298
Not a Proper Input in Edge 10203,6298
Not a Proper Input in Edge 10204,6298
Not a Proper Input in Edge 10207,6298
Not a Proper Input in Edge 10209,6298
Not a Proper Input in Edge 10210,6298
Not a Proper Input in Edge 10211,6298
Not a Proper Input in Edge 10212,6298
Not a Proper Input in Edge 10214,6298
Not a Proper Input in Edge 10215,6298
Not a Proper Input in Edge 10216,6298
Not a Proper Input in Edge 10218,6298
Not a Proper Input in Edge 10222,6298
Not a Proper Input in Edge 10224,6298
Not a Proper Input in Edge 10225,6298
Not a Proper Input in Edge 10231,6298
Not a Proper Input in Edge 10232,6298
Not a Proper Input in Edge 10234,6298
Not a Proper Input in Edge 10237,6298
Not a Proper Input in Edge 10239,6298
Not a Proper Input in Edge 10240,6298
Not a Proper Input in Edge 10241,6298
Not a Proper Input in Edge 10242,6298
Not a Proper Input in Edge 10243,6298
Not a Proper Input in Edge 10244,6298
Not a Proper Input in Edge 10246,6298
Not a Proper Input in Edge 10247,6298
Not a Proper Input in Edge 10248,6298
Not a Proper Input in Edge 10251,6298
Not a Proper Input in Edge 10252,6298
Not a Proper Input in Edge 10253,6298
Not a Proper Input in Edge 10254,6298
Not a Proper Input in Edge 10258,6298
Not a Proper Input in Edge 10260,6298
Not a Proper Input in Edge 10261,6298
Not a Proper Input in Edge 10263,6298
Not a Proper Input in Edge 10265,6298
Not a Proper Input in Edge 10266,6298
Not a Proper Input in Edge 10267,6298
Not a Proper Input in Edge 10271,6298
Not a Proper Input in Edge 10272,6298
Not a Proper Input in Edge 10273,6298
Not a Proper Input in Edge 10276,6298
Not a Proper Input in Edge 10277,6298
Not a Proper Input in Edge 10278,6298
Not a Proper Input in Edge 10279,6298
Not a Proper Input in Edge 10284,6298
Not a Proper Input in Edge 10286,6298
Not a Proper Input in Edge 10289,6298
Not a Proper Input in Edge 10292,6298
Not a Proper Input in Edge 10294,6298
Not a Proper Input in Edge 10295,6298
Not a Proper Input in Edge 10296,6298
Not a Proper Input in Edge 10297,6298
Not a Proper Input in Edge 10298,6298
Not a Proper Input in Edge 10300,6298
Not a Proper Input in Edge 10301,6298
Not a Proper Input in Edge 10302,6298
Not a Proper Input in Edge 10304,6298
Not a Proper Input in Edge 10305,6298
Not a Proper Input in Edge 10306,6298
Not a Proper Input in Edge 10307,6298
Not a Proper Input in Edge 10309,6298
Not a Proper Input in Edge 10310,6298
Not a Proper Input in Edge 10311,6298
Not a Proper Input in Edge 10312,6298
Not a Proper Input in Edge 10313,6298
Not a Proper Input in Edge 10315,6298
Not a Proper Input in Edge 10316,6298
Not a Proper Input in Edge 10318,6298
Not a Proper Input in Edge 10319,6298
Not a Proper Input in Edge 10320,6298
Not a Proper Input in Edge 10322,6298
Not a Proper Input in Edge 10323,6298
Not a Proper Input in Edge 10324,6298
Not a Proper Input in Edge 10325,6298
Not a Proper Input in Edge 10326,6298
Not a Proper Input in Edge 10328,6298
Not a Proper Input in Edge 10329,6298
Not a Proper Input in Edge 10331,6298
Not a Proper Input in Edge 10333,6298
Not a Proper Input in Edge 10335,6298
Not a Proper Input in Edge 10341,6298
Not a Proper Input in Edge 10342,6298
Not a Proper Input in Edge 10343,6298
Not a Proper Input in Edge 10345,6298
Not a Proper Input in Edge 10349,6298
Not a Proper Input in Edge 10351,6298
Not a Proper Input in Edge 10352,6298
Not a Proper Input in Edge 10353,6298
Not a Proper Input in Edge 10355,6298
Not a Proper Input in Edge 10358,6298
Not a Proper Input in Edge 10359,6298
Not a Proper Input in Edge 10362,6298
Not a Proper Input in Edge 10364,6298
Not a Proper Input in Edge 10366,6298
Not a Proper Input in Edge 10368,6298
Not a Proper Input in Edge 10369,6298
Not a Proper Input in Edge 10371,6298
Not a Proper Input in Edge 10372,6298
Not a Proper Input in Edge 10375,6298
Not a Proper Input in Edge 10377,6298
Not a Proper Input in Edge 10378,6298
Not a Proper Input in Edge 10380,6298
Not a Proper Input in Edge 10381,6298
Not a Proper Input in Edge 10382,6298
Not a Proper Input in Edge 10383,6298
Not a Proper Input in Edge 10390,6298
Not a Proper Input in Edge 10391,6298
Not a Proper Input in Edge 10395,6298
Not a Proper Input in Edge 10396,6298
Not a Proper Input in Edge 10399,6298
Not a Proper Input in Edge 10400,6298
Not a Proper Input in Edge 10407,6298
Not a Proper Input in Edge 10412,6298
Not a Proper Input in Edge 10413,6298
Not a Proper Input in Edge 10415,6298
Not a Proper Input in Edge 10416,6298
Not a Proper Input in Edge 10421,6298
Not a Proper Input in Edge 10424,6298
Not a Proper Input in Edge 10425,6298
Not a Proper Input in Edge 10427,6298
Not a Proper Input in Edge 10428,6298
Not a Proper Input in Edge 10430,6298
Not a Proper Input in Edge 10431,6298
Not a Proper Input in Edge 10433,6298
Not a Proper Input in Edge 10434,6298
Not a Proper Input in Edge 10435,6298
Not a Proper Input in Edge 10438,6298
Not a Proper Input in Edge 10439,6298
Not a Proper Input in Edge 10440,6298
Not a Proper Input in Edge 10442,6298
Not a Proper Input in Edge 10443,6298
Not a Proper Input in Edge 10444,6298
Not a Proper Input in Edge 10445,6298
Not a Proper Input in Edge 10446,6298
Not a Proper Input in Edge 10449,6298
Not a Proper Input in Edge 10450,6298
Not a Proper Input in Edge 10452,6298
Not a Proper Input in Edge 10453,6298
Not a Proper Input in Edge 10454,6298
Not a Proper Input in Edge 10455,6298
Not a Proper Input in Edge 10458,6298
Not a Proper Input in Edge 10460,6298
Not a Proper Input in Edge 10461,6298
Not a Proper Input in Edge 10462,6298
Not a Proper Input in Edge 10463,6298
Not a Proper Input in Edge 10465,6298
Not a Proper Input in Edge 10470,6298
Not a Proper Input in Edge 10472,6298
Not a Proper Input in Edge 10474,6298
Not a Proper Input in Edge 10475,6298
Not a Proper Input in Edge 10476,6298
Not a Proper Input in Edge 10479,6298
Not a Proper Input in Edge 10481,6298
Not a Proper Input in Edge 10482,6298
Not a Proper Input in Edge 10487,6298
Not a Proper Input in Edge 10489,6298
Not a Proper Input in Edge 10490,6298
Not a Proper Input in Edge 10492,6298
Not a Proper Input in Edge 10494,6298
Not a Proper Input in Edge 10495,6298
Not a Proper Input in Edge 10496,6298
Not a Proper Input in Edge 10497,6298
Not a Proper Input in Edge 10498,6298
Not a Proper Input in Edge 10501,6298
Not a Proper Input in Edge 10503,6298
Not a Proper Input in Edge 10504,6298
Not a Proper Input in Edge 10506,6298
Not a Proper Input in Edge 10509,6298
Not a Proper Input in Edge 10511,6298
Not a Proper Input in Edge 10513,6298
Not a Proper Input in Edge 10517,6298
Not a Proper Input in Edge 10519,6298
Not a Proper Input in Edge 10521,6298
Not a Proper Input in Edge 10522,6298
Not a Proper Input in Edge 10523,6298
Not a Proper Input in Edge 10524,6298
Not a Proper Input in Edge 10526,6298
Not a Proper Input in Edge 10527,6298
Not a Proper Input in Edge 10528,6298
Not a Proper Input in Edge 10529,6298
Not a Proper Input in Edge 10531,6298
Not a Proper Input in Edge 10532,6298
Not a Proper Input in Edge 10533,6298
Not a Proper Input in Edge 10534,6298
Not a Proper Input in Edge 10535,6298
Not a Proper Input in Edge 10536,6298
Not a Proper Input in Edge 10538,6298
Not a Proper Input in Edge 10539,6298
Not a Proper Input in Edge 10540,6298
Not a Proper Input in Edge 10541,6298
Not a Proper Input in Edge 10542,6298
Not a Proper Input in Edge 10543,6298
Not a Proper Input in Edge 10545,6298
Not a Proper Input in Edge 10547,6298
Not a Proper Input in Edge 10548,6298
Not a Proper Input in Edge 10550,6298
Not a Proper Input in Edge 10555,6298
Not a Proper Input in Edge 10556,6298
Not a Proper Input in Edge 10558,6298
Not a Proper Input in Edge 10561,6298
Not a Proper Input in Edge 10563,6298
Not a Proper Input in Edge 10566,6298
Not a Proper Input in Edge 10567,6298
Not a Proper Input in Edge 10569,6298
Not a Proper Input in Edge 10571,6298
Not a Proper Input in Edge 10572,6298
Not a Proper Input in Edge 10574,6298
Not a Proper Input in Edge 10575,6298
Not a Proper Input in Edge 10576,6298
Not a Proper Input in Edge 10577,6298
Not a Proper Input in Edge 10580,6298
Not a Proper Input in Edge 10582,6298
Not a Proper Input in Edge 10583,6298
Not a Proper Input in Edge 10584,6298
Not a Proper Input in Edge 10585,6298
Not a Proper Input in Edge 10586,6298
Not a Proper Input in Edge 10588,6298
Not a Proper Input in Edge 10590,6298
Not a Proper Input in Edge 10591,6298
Not a Proper Input in Edge 10594,6298
Not a Proper Input in Edge 10595,6298
Not a Proper Input in Edge 10596,6298
Not a Proper Input in Edge 10598,6298
Not a Proper Input in Edge 10599,6298
Not a Proper Input in Edge 10601,6298
Not a Proper Input in Edge 10603,6298
Not a Proper Input in Edge 10604,6298
Not a Proper Input in Edge 10607,6298
Not a Proper Input in Edge 10609,6298
Not a Proper Input in Edge 10614,6298
Not a Proper Input in Edge 10615,6298
Not a Proper Input in Edge 10616,6298
Not a Proper Input in Edge 10619,6298
Not a Proper Input in Edge 10622,6298
Not a Proper Input in Edge 10625,6298
Not a Proper Input in Edge 10627,6298
Not a Proper Input in Edge 10629,6298
Not a Proper Input in Edge 10630,6298
Not a Proper Input in Edge 10631,6298
Not a Proper Input in Edge 10632,6298
Not a Proper Input in Edge 10633,6298
Not a Proper Input in Edge 10634,6298
Not a Proper Input in Edge 10635,6298
Not a Proper Input in Edge 10636,6298
Not a Proper Input in Edge 10637,6298
Not a Proper Input in Edge 10638,6298
Not a Proper Input in Edge 10639,6298
Not a Proper Input in Edge 10640,6298
Not a Proper Input in Edge 10641,6298
Not a Proper Input in Edge 10642,6298
Not a Proper Input in Edge 10647,6298
Not a Proper Input in Edge 10648,6298
Not a Proper Input in Edge 10649,6298
Not a Proper Input in Edge 10651,6298
Not a Proper Input in Edge 10652,6298
Not a Proper Input in Edge 10653,6298
Not a Proper Input in Edge 10656,6298
Not a Proper Input in Edge 10657,6298
Not a Proper Input in Edge 10659,6298
Not a Proper Input in Edge 10662,6298
Not a Proper Input in Edge 10667,6298
Not a Proper Input in Edge 10668,6298
Not a Proper Input in Edge 10669,6298
Not a Proper Input in Edge 10675,6298
Not a Proper Input in Edge 10676,6298
Not a Proper Input in Edge 10678,6298
Not a Proper Input in Edge 10681,6298
Not a Proper Input in Edge 10682,6298
Not a Proper Input in Edge 10684,6298
Not a Proper Input in Edge 10685,6298
Not a Proper Input in Edge 10686,6298
Not a Proper Input in Edge 10688,6298
Not a Proper Input in Edge 10694,6298
Not a Proper Input in Edge 10695,6298
Not a Proper Input in Edge 10696,6298
Not a Proper Input in Edge 10698,6298
Not a Proper Input in Edge 10699,6298
Not a Proper Input in Edge 10700,6298
Not a Proper Input in Edge 10706,6298
Not a Proper Input in Edge 10707,6298
Not a Proper Input in Edge 10708,6298
Not a Proper Input in Edge 10709,6298
Not a Proper Input in Edge 10710,6298
Not a Proper Input in Edge 10711,6298
Not a Proper Input in Edge 10712,6298
Not a Proper Input in Edge 10713,6298
Not a Proper Input in Edge 10714,6298
Not a Proper Input in Edge 10715,6298
Not a Proper Input in Edge 10716,6298
Not a Proper Input in Edge 10723,6298
Not a Proper Input in Edge 10726,6298
Not a Proper Input in Edge 10727,6298
Not a Proper Input in Edge 10731,6298
Not a Proper Input in Edge 10732,6298
Not a Proper Input in Edge 10733,6298
Not a Proper Input in Edge 10734,6298
Not a Proper Input in Edge 10735,6298
Not a Proper Input in Edge 10736,6298
Not a Proper Input in Edge 10737,6298
Not a Proper Input in Edge 10739,6298
Not a Proper Input in Edge 10741,6298
Not a Proper Input in Edge 10743,6298
Not a Proper Input in Edge 10744,6298
Not a Proper Input in Edge 10745,6298
Not a Proper Input in Edge 10746,6298
Not a Proper Input in Edge 10751,6298
Not a Proper Input in Edge 10752,6298
Not a Proper Input in Edge 10753,6298
Not a Proper Input in Edge 10755,6298
Not a Proper Input in Edge 10756,6298
Not a Proper Input in Edge 10757,6298
Not a Proper Input in Edge 10758,6298
Not a Proper Input in Edge 10759,6298
Not a Proper Input in Edge 10760,6298
Not a Proper Input in Edge 10762,6298
Not a Proper Input in Edge 10764,6298
Not a Proper Input in Edge 10765,6298
Not a Proper Input in Edge 10766,6298
Not a Proper Input in Edge 10767,6298
Not a Proper Input in Edge 10769,6298
Not a Proper Input in Edge 10770,6298
Not a Proper Input in Edge 10771,6298
Not a Proper Input in Edge 10772,6298
Not a Proper Input in Edge 10775,6298
Not a Proper Input in Edge 10776,6298
Not a Proper Input in Edge 10777,6298
Not a Proper Input in Edge 10778,6298
Not a Proper Input in Edge 10779,6298
Not a Proper Input in Edge 10783,6298
Not a Proper Input in Edge 10784,6298
Not a Proper Input in Edge 10785,6298
Not a Proper Input in Edge 10787,6298
Not a Proper Input in Edge 10789,6298
Not a Proper Input in Edge 10790,6298
Not a Proper Input in Edge 10797,6298
Not a Proper Input in Edge 10798,6298
Not a Proper Input in Edge 10799,6298
Not a Proper Input in Edge 10800,6298
Not a Proper Input in Edge 10801,6298
Not a Proper Input in Edge 10802,6298
Not a Proper Input in Edge 10803,6298
Not a Proper Input in Edge 10804,6298
Not a Proper Input in Edge 10805,6298
Not a Proper Input in Edge 10806,6298
Not a Proper Input in Edge 10808,6298
Not a Proper Input in Edge 10810,6298
Not a Proper Input in Edge 10812,6298
Not a Proper Input in Edge 10815,6298
Not a Proper Input in Edge 10816,6298
Not a Proper Input in Edge 10817,6298
Not a Proper Input in Edge 10818,6298
Not a Proper Input in Edge 10819,6298
Not a Proper Input in Edge 10820,6298
Not a Proper Input in Edge 10822,6298
Not a Proper Input in Edge 10824,6298
Not a Proper Input in Edge 10825,6298
Not a Proper Input in Edge 10826,6298
Not a Proper Input in Edge 10827,6298
Not a Proper Input in Edge 10828,6298
Not a Proper Input in Edge 10829,6298
Not a Proper Input in Edge 10830,6298
Not a Proper Input in Edge 10832,6298
Not a Proper Input in Edge 10834,6298
Not a Proper Input in Edge 10835,6298
Not a Proper Input in Edge 10836,6298
Not a Proper Input in Edge 10838,6298
Not a Proper Input in Edge 10840,6298
Not a Proper Input in Edge 10841,6298
Not a Proper Input in Edge 10842,6298
Not a Proper Input in Edge 10844,6298
Not a Proper Input in Edge 10845,6298
Not a Proper Input in Edge 10847,6298
Not a Proper Input in Edge 10850,6298
Not a Proper Input in Edge 10852,6298
Not a Proper Input in Edge 10853,6298
Not a Proper Input in Edge 10855,6298
Not a Proper Input in Edge 10856,6298
Not a Proper Input in Edge 10857,6298
Not a Proper Input in Edge 10858,6298
Not a Proper Input in Edge 10859,6298
Not a Proper Input in Edge 10861,6298
Not a Proper Input in Edge 10862,6298
Not a Proper Input in Edge 10863,6298
Not a Proper Input in Edge 10864,6298
Not a Proper Input in Edge 10865,6298
Not a Proper Input in Edge 10867,6298
Not a Proper Input in Edge 10868,6298
Not a Proper Input in Edge 10869,6298
Not a Proper Input in Edge 10871,6298
Not a Proper Input in Edge 10874,6298
Not a Proper Input in Edge 10875,6298
Not a Proper Input in Edge 10876,6298
Not a Proper Input in Edge 10877,6298
Not a Proper Input in Edge 10878,6298
Not a Proper Input in Edge 10881,6298
Not a Proper Input in Edge 10882,6298
Not a Proper Input in Edge 10883,6298
Not a Proper Input in Edge 10884,6298
Not a Proper Input in Edge 10885,6298
Not a Proper Input in Edge 10886,6298
Not a Proper Input in Edge 10888,6298
Not a Proper Input in Edge 10889,6298
Not a Proper Input in Edge 10890,6298
Not a Proper Input in Edge 10893,6298
Not a Proper Input in Edge 10894,6298
Not a Proper Input in Edge 10897,6298
Not a Proper Input in Edge 10899,6298
Not a Proper Input in Edge 10900,6298
Not a Proper Input in Edge 10901,6298
Not a Proper Input in Edge 10903,6298
Not a Proper Input in Edge 10904,6298
Not a Proper Input in Edge 10906,6298
Not a Proper Input in Edge 10908,6298
Not a Proper Input in Edge 10909,6298
Not a Proper Input in Edge 10911,6298
Not a Proper Input in Edge 10912,6298
Not a Proper Input in Edge 10914,6298
Not a Proper Input in Edge 10915,6298
Not a Proper Input in Edge 10917,6298
Not a Proper Input in Edge 10918,6298
Not a Proper Input in Edge 10919,6298
Not a Proper Input in Edge 10923,6298
Not a Proper Input in Edge 10924,6298
Not a Proper Input in Edge 10925,6298
Not a Proper Input in Edge 10929,6298
Not a Proper Input in Edge 10933,6298
Not a Proper Input in Edge 10935,6298
Not a Proper Input in Edge 10936,6298
Not a Proper Input in Edge 10940,6298
Not a Proper Input in Edge 10942,6298
Not a Proper Input in Edge 10943,6298
Not a Proper Input in Edge 10944,6298
Not a Proper Input in Edge 10945,6298
Not a Proper Input in Edge 10946,6298
Not a Proper Input in Edge 10947,6298
Not a Proper Input in Edge 10949,6298
Not a Proper Input in Edge 10951,6298
Not a Proper Input in Edge 10952,6298
Not a Proper Input in Edge 10955,6298
Not a Proper Input in Edge 10956,6298
Not a Proper Input in Edge 10958,6298
Not a Proper Input in Edge 10959,6298
Not a Proper Input in Edge 10963,6298
Not a Proper Input in Edge 10965,6298
Not a Proper Input in Edge 10967,6298
Not a Proper Input in Edge 10968,6298
Not a Proper Input in Edge 10970,6298
Not a Proper Input in Edge 10972,6298
Not a Proper Input in Edge 10974,6298
Not a Proper Input in Edge 10976,6298
Not a Proper Input in Edge 10979,6298
Not a Proper Input in Edge 10981,6298
Not a Proper Input in Edge 10983,6298
Not a Proper Input in Edge 10984,6298
Not a Proper Input in Edge 10985,6298
Not a Proper Input in Edge 10988,6298
Not a Proper Input in Edge 10989,6298
Not a Proper Input in Edge 10990,6298

In [ ]:
#adjM.shape
import numpy as np
len(adjM)
arr = np.array(adjM)

newarr = arr.reshape(10075, 10075)

print(newarr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [ ]:
def create_adjacency_matrix(V, edges):
    # Initialize an empty V x V matrix with all zeros
    matrix = [[0] * V for _ in range(V)]

    # Populate the matrix based on the edges
    for edge in edges:
        u, v = edge
        matrix[u][v] = 1
#       matrix[v][u] = 1  # Undirected graph

    return matrix
V1 = len(adj)
edges1 = adj[['start', 'end']].values.tolist()
adj_matrix1 = create_adjacency_matrix(V1, edges1)
for row in adj_matrix1:
    print(row)
print()

In [ ]:
type(adj)

pandas.core.frame.DataFrame